### ISSUE TITLE
Rule: Public methods in a junit test should have @Test annotation

### ISSUE THREAD

**Issue by pocmo** [detekt/detekt#1003]
This has happened so often to me that I would like to see this covered by detekt. :)

Rule: If a unit test (detecting this seems to depend on #379) does have a public method then it should have an `@Test` annotation.

**Comment by BraisGabin** [comment]
Related with #379. And we decided to not have framework/library specific rules/configurations in the default rule set. But a custom rule set for JUnit would be *really* helpful.
