### ISSUE TITLE
Suggestion: LongParameterList rule but on method call if named argument is not used

### ISSUE THREAD

**Issue by cyfung** [detekt/detekt#1007]
Can we have a rule which warns method call with long parameter list IF named arguments is not used.

I know the rule LongParameterList exists, but I think it is not a problem if named arguments is used when calling the methods.

**Comment by arturbosch** [comment]
So basically a rule to enforce named arguments when a function call needs > than threshold arguments? 
Sounds like a good rule to me, wdyt?

**Comment by cyfung** [comment]
Yes, that's what I was thinking.

**Comment by sowmyav24** [comment]
Is this issue still valid ? I can see the rule `LongParameterList` already has `ignoreDefaultParameters` configuration to consider defaults for parameters and does not include default parameters in the parameters count.

**Comment by cortinico** [comment]
> Is this issue still valid?

Yes I think so. Do you want to pick it up @sowmyav24?
If not I'll be happy to do it.

Currently the `LongParameterList` is checking function declarations with too many parameters. Ideally we could have a rule that checks function invocation with too many parameters and reports if the parameter list is above a threshold (as @arturbosch suggested).

**Comment by sowmyav24** [comment]
Yes, My query was more around the scenario where the threshhold is 2 and the function declaration is 
`fun foo(val a, val b, val c =1, val d= 1)`

Here the function can be invoked as 
`foo(1,2,3,4)`
or 
`foo(1, 2)`

Currently, `LongParameterList `  will not report this function as we ignore default parameters.
But if we go with the route of function invocation, the result would be, 
`foo(1,2,3,4)` will be reported and `foo(1, 2)` will be not which would be ambiguous.
