### ISSUE TITLE
NestedClassesVisibility fails on internal interfaces

### ISSUE THREAD

**Issue by Litun** [detekt/detekt#1075]
NestedClassesVisibility rule fails on:
`internal interface Interface {
    class InnerClass
}`
But you can't do `internal class InnerClass` because of "Modifier internal is not applicable inside interface". 
Please fix it.

**Comment by arturbosch** [comment]
But you can write `private class InnerClass`. What is your use case for having the inner class be internal visible?

**Comment by schalkms** [comment]
I think this is not really a common use case, but a valid one. Hence, this shouldn't get flagged IMHO.

**Comment by Litun** [comment]
@arturbosch We use these classes as a part of interface contract. But in case of modularisation we decided to hide some interfaces as internal.
