### ISSUE TITLE
Detekt deactivates non activated rules by default which causes confusion for detekt extension authors

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#1103]
## Expected Behavior
Rules from extensions - rule set id !in default rule set ids - should be active by default.
 
## Current Behavior
Custom rules only executed if they are turned on in the yaml configuration.

## Context
Questions from slack.
Any potential rule author.

**Comment by Mishkun** [comment]
Any news about this issue?

**Comment by BraisGabin** [comment]
I think that #4315 should close this issue. The rule author will be able to decide if they rules are enabled or not by default after that.
