### ISSUE TITLE
Improve documentation of composite build setup of the Gradle Plugin

### ISSUE THREAD

**Issue by Mauin** [detekt/detekt#1209]
As mentioned in #1207 it is currently quite hard to understand the dependencies and small, intricate details that affect the Gradle Plugin during a build in the detekt repo.

To improve documentation and also lower the barrier of entry for new contributors looking into the Gradle Plugin and related components it would be good to have some documentation about the setup and how it is/can be affected in the different Gradle modules.

- Explain the composite build (link to Gradle docs)
- Version override in `settings.gradle`
- The completely separate Gradle module for the Plugin
- Overriding the `detekt-cli` via the `detekt` configuration and why we do it

The first step would be creating a `README.md` in the `detekt-gradle-plugin` directory.

**Comment by schalkms** [comment]
@arturbosch should we still improve something here? The gradle plugin setup changed quite a bit since this issue was created.

**Comment by cortinico** [comment]
> @arturbosch should we still improve something here? The gradle plugin setup changed quite a bit since this issue was created.

Imho this can be closed as we don't have a composite build anymore (removed in  https://github.com/detekt/detekt/pull/2493)
