### ISSUE TITLE
Rule: Prefer IntArray instead of Array<Int> to escape boxing

### ISSUE THREAD

**Issue by Mishkun** [detekt/detekt#1245]
### Prerequisites
Since Kotlin has no notion of primitive types, there are speicalized Array instances for each Java primitive:

- `IntArray`
- `DoubleArray`
- `FloatArray`
- `ShortArray`
- `ByteArray`
- `LongArray`
- `CharArray`

_From this point I will refer to the arrays of primitive types as `Array<Primitive>`._

As stated here in [docs](https://kotlinlang.org/docs/reference/basic-types.html#arrays) and [stackoverflow](https://stackoverflow.com/questions/45090808/intarray-vs-arrayint-in-kotlin), using `Array<Primitive>` leads to implicit boxing and perfomance hit.

Thus, I think we should mark `Array<Primitive>` usages to help improve performance and educate non-Java newcomers

### Actual rule

Actual rule should detect these patterns:
- [x] Using `Array<Primitive>` as a parameter of the function
- [x] Using `Array<Primitive>` as an explicit return type
- [ ] Using `arrayOf()` factory with primitive types
- [ ] All references to `Array<Primitive>` types

These can be standalone rules or one rule tweakable from config

**Comment by schalkms** [comment]
@Mishkun Is there any specific reason why this rule should only detect the following cases and not all usages of `Array<Primitive>`.
- Using Array<Primitive> as a parameter of the function
- Using Array<Primitive> as an explicit return type
- Using arrayOf() factory with primitive types

**Comment by schalkms** [comment]
@Mishkun I updated your initial issue post to supply a check list for future features/improvements of this rule.
