### ISSUE TITLE
Gradle plugin should set default value for "baseline" property

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#1260]
## Expected Behavior
Onboarding experience for project with existing issues is:
1. Apply plugin in build.gradle
2. Run `gradlew detekt` to check for issues
2. Run `gradlew detektBaseline` to generate a baseline file

## Current Behavior
Onboarding experience for project with existing issues is:
1. Apply plugin in build.gradle
2. Run `gradlew detekt` to check for issues
2. Figure out how to set "baseline" property
3. Run `gradlew detektBaseline` to generate a baseline file

## Context
Sensible defaults make for a better onboarding experience. A user shouldn't have to explicitly set a configuration for the baseline file path when Gradle conventions could be followed to set a default value instead.

Conventionally this will be one of:
* $rootProject.projectDir/config/detekt/baseline.xml
* $projectDir/config/detekt/baseline.xml

The second makes more sense in this context, since there will be multiple detekt tasks (they'll be created for different modules and sourcesets) and having a single baseline would require either merging files or generating different files for different projects & sourcesets (but project and sourceset names change - if that happened and filenames were based on project name, the baseline would have to be regenerated which would be annoying to manage).

**Comment by arturbosch** [comment]
+1, related to #1262, go for projectDir first, then rootProject?

**Comment by 3flex** [comment]
As mentioned in #1262 I'm not a fan of the search order - a single default path will work best.

**Comment by Tapchicoma** [comment]
If baseline file will be set by default, then I would like to not have empty baseline file for each gradle module in the project - if module doesn't have any issues - baseline file should not be generated.

But, in general, if you are trying to follow android lint approach, baseline config is optional.

**Comment by arturbosch** [comment]
Baseline should be picked up by default on defaullt path if it is present else do not care or generate a baseline, it should stay a manual `createBaseline`.

**Comment by 3flex** [comment]
Generating baselines could get complicated when multiple sourcesets are involved as well, since detekt can find different issues in different sourcesets in the same module. detektBaseline task might have to run detekt on each sourceset then merge all results into a single baseline file.

**Comment by arturbosch** [comment]
Yes, now it will override the baseline everytime when its set to rootProject/bla.
@vanniktech mentioned that our current baseline functionality in the gradle plugin meets the way android lint does baselining ?

**Comment by vanniktech** [comment]
Yes. Unless something changed again.
