### ISSUE TITLE
Make RuleSetProvider easier

### ISSUE THREAD

**Issue by vanniktech** [detekt/detekt#1276]
This is a sample `RuleSetProvider` of Detekt:

```kotlin
class CustomRuleSetProvider : RuleSetProvider {
  override val ruleSetId: String = "detekt-custom-rules"

  override fun instance(config: Config)
      = RuleSet(ruleSetId, listOf(NoInternalImportRule(config)))
}
```

I don't like it since the `ruleSetId` is being used twice. ktlint's `RuleSetProvider` looks like this:

```kotlin
class CustomRuleSetProvider : RuleSetProvider {
  override fun get() = RuleSet("custom-ktlint-rules", NoInternalImportRule())
}
```

Which is much better. Can we also squeeze the ruleSetId together?

**Comment by arturbosch** [comment]
We could change the `list` to a `vararg BaseRule` and remove the explicit `RuleSet(ruleSetId...` by using a SingleAssign-Delegate and set the ID in `buildRuleset` function.
The `ruleSetId` as a property has the benefit of lazily creating a rule set only if it is active in the config.

**Comment by arturbosch** [comment]
Linking to #2680

**Comment by schalkms** [comment]
Closing this issue in favor of #3816
