### ISSUE TITLE
Grouped output

### ISSUE THREAD

**Issue by realdadfish** [detekt/detekt#1355]
Continued from https://github.com/arturbosch/detekt/issues/171 I'd love to see Detekt get some console output formatting options. Right now each executed rule lists all the violations in each file, one by one.

Now, if more than one violation in more than one file occurs, I then have to hop in between to fix all the issues in all files. So it would be super-awesome to have an option to group the output by file, and not only by violation.

**Comment by arturbosch** [comment]
We could provide an additional `ConsoleReport` which sorts the findings by ruleset `and` file :).
See `FindingsReport`.

**Comment by sowmyav24** [comment]
Couple of open questions for this issue is put forth in [#1852](https://github.com/arturbosch/detekt/pull/1852#issue-311662150)

**Comment by sowmyav24** [comment]
We can close this issue . Merged in [#1852 ](https://github.com/arturbosch/detekt/pull/1852)

**Comment by arturbosch** [comment]
Closing, there is a RuleSetBased`FindingsReport` and a `FileBasedFindingsReport`.
