### ISSUE TITLE
Rule namings are inconsistent regarding positive vs. negative logic

### ISSUE THREAD

**Issue by sschuberth** [detekt/detekt#1687]
In general, naming of rules is inconsistent. For example, the "exceptions" ruleset has a rule named "TooGenericExceptionCaught", i.e. the is rule named after the current state of the code, and in what regard it is wrong. On the other hand the "formatting" ruleset has a rule named "NoTrailingSpaces", i.e. it named after how the rule expects the code to be, and how it should change.

It would be nice if this rule naming was consistent, i.e. it should be "NoGenericExceptionCatch" and "NoTrailingSpaces", or "TooGenericExceptionCaught" and "TrailingSpacesPresent" (or so).

**Comment by schalkms** [comment]
Thanks for your feedback!
Since detekt provides a wrapper over ktlint's rules, we wanted to keep the naming.
Therefore, the naming of rules might not be 100 % consistent.

**Comment by sschuberth** [comment]
Ok, that explains it. But how about prefixing or suffixing such rules then, to make it more obvious they come from different sources? Like renaming "NoTrailingSpaces" to "ktlint-NoTrailingSpaces" or "NoTrailingSpaces-ktlint"?

**Comment by arturbosch** [comment]
Hm the rule set groups all ktlint rules to `formatting` so there is clue.
We could rename the rule set to `ktlint` however.
We had #109 for renaming options, well we are still before 1.0 so we can consider further renamings.

**Comment by arturbosch** [comment]
I think I like `NoGenericExceptionCatch` and `NoGenericExceptionThrow` ^^

**Comment by sschuberth** [comment]
> Hm the rule set groups all ktlint rules to `formatting` so there is clue.

Well, only if you know that *detekt* does not implement any of these checks itself...

> We could rename the rule set to `ktlint` however.

...also, *ktlint* does more than plain formatting check, so equating "formatting" with "ktlint" is a bit improper.

**Comment by arturbosch** [comment]
> > Hm the rule set groups all ktlint rules to `formatting` so there is clue.
> 
> Well, only if you _know_ that `detekt` does not implement any of these checks itself...
> 
> > We could rename the rule set to `ktlint` however.
> 
> ...also, `ktlint` does more than plain formatting checks, so equating "formatting" with "ktlint" is a bit improper.

I get your point. I'm fine with renaming `detekt-formatting` to `detekt-ktlint` and the ruleset `ktlint`.
Waiting for feedback.

**Comment by sschuberth** [comment]
I think renaming the ktlint plugin to `detekt-ktlint` makes sense. About the ruleset I'm not sure: Does the ruleset wrap *all* ktlint checks, or only formatting-related checks? If the latter, the ruleset should probably be named `formatting-ktlint` to emphasize that, and to leave room for additional future `formatting-<another-style-checker>` rulesets.

**Comment by schalkms** [comment]
Since there were no efforts to rename the rules as well as no further feedback, I'll close this for now.
If you have contradicting opinions to mine, please feel to reach out or reopen this issue.
