### ISSUE TITLE
Error in processing test sources that use internal classes of main sources

### ISSUE THREAD

**Issue by remal** [detekt/detekt#1750]
* I have an `internal` class in `main` source-set of my Gradle project.
* And I have a test that uses this class.

Kotlin Gradle plugin handles this by using the same Kotlin module name for both `main` and `test` source-sets. But Detekt displays an error like this:

```
/ConfigSpec.kt:21:25: error: cannot access 'EmptyConfig': it is internal in 'io.gitlab.arturbosch.detekt.api'
                println(EmptyConfig.toString())
```

**Comment by remal** [comment]
The issue can be fixed by passing Kotlin module name to Detekt via command-line parameters. To implement it we have to make a slight refactoring of  `detekt-cli` and `detekt-api` and add some functionality to Detekt Gradle plugin.

I can make the fix myself and send PR, if Detekt's maintainers are OK with the solution.

**Comment by schalkms** [comment]
Please go ahead. I will happily review the PR then.

**Comment by schalkms** [comment]
Please also include a code sample in this issue to help everyone understand the problem at hand.

**Comment by arturbosch** [comment]
@remal does this only occur when using type resolution features?

**Comment by BraisGabin** [comment]
Closing in favor of #3067
