### ISSUE TITLE
List rules that should use type and symbol solving

### ISSUE THREAD

**Issue by schalkms** [detekt/detekt#1915]
#### Expected Behavior
Many rules in the detekt codebase should use type and symbol solving in order to make the rules more robust against false-positives.

####  Current Behavior
Currently, only a subset of detekt's rules are using type and symbol solving.

#### Context
Which rules do we need to update?

- [ ] `UnusedPrivateMember`
  - Use type and symbol solving
  - Optional: extend check to public members as well (maybe use the IntelliJ rule here) -> see issue #2229

**Comment by BraisGabin** [comment]
This issue was pinned at 14 Sep 2019. There was 0 comments in this issue since them 11 months. I think it's safe to unpin it.

**Comment by arturbosch** [comment]
Well, lets close this then. 
Most of the time we get feedback based on new issues and someone improves the rule with type solution.

**Comment by gcandrade10** [comment]
Hello! I see that 
https://github.com/detekt/detekt/issues/2229 and 
https://github.com/detekt/detekt/issues/2573
were closed in favor of this issue
Is there any initiative to add a rule to detect dead code that is not private?
Thank you in advance!
