### ISSUE TITLE
Add proper attribution for rules derived from Kotlin/IntelliJ source

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#1917]
A couple of rules are derived or copied entirely from Apache 2.0 licensed Kotlin and its plugin for IntelliJ.

These must be properly attributed by detekt.

**Comment by arturbosch** [comment]
In KDoc which will also appear on the website?

**Comment by schalkms** [comment]
The same holds true for `ktlint's` rules.

**Comment by cortinico** [comment]
I believe this is essentially done as every rule is linked, and we kept on adding references to rules (e.g. compiler ones). Is there anyhting missing here?

**Comment by 3flex** [comment]
Agreed. New issues can be opened if there are rules that were missed or some other licensing or attribution issues need resolving.
