### ISSUE TITLE
Property API for Gradle plugin

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#1931]
## Expected Behavior
Gradle plugin properties are set using a consistent method throughout the plugin.

## Current Behavior
1. Some public properties using Provider API in some tasks but not others (e.g. `parallel` is a `Boolean` in `Detekt` task, but `Property<Boolean>` in `DetektCreateBaselineTask`)
1. Tasks (mostly) use Provider API in the back end while extensions use basic types which is a bit confusing
1. ~~Properties in `IdeaExtension` not using appropriate types, e.g. `path` is a string but should be a file type~~ (no longer relevant, IdeaExtension has been removed)
1. ~~`IdeaExtension` is being used as an extension on the task as well as DetektExtension which doesn't make sense - it should be one or the other. It should be configured via the extension, then the plugin should map extension properties to the task (same as the other tasks).~~ (no longer relevant, IdeaExtension has been removed)

## Context
I would like to use the Provider API (which will be stable in 6.0) wherever possible. This will be a breaking change, but in nearly all cases very easy to fix (e.g. change `parallel = true` to `parallel.set(true)`). The Groovy and Kotlin DSL will be identical.

The compatibility layer that was introduced earlier can be removed - this:
```kotlin
    @get:Internal
    internal val autoCorrectProp: Property<Boolean> = project.objects.property(Boolean::class.javaObjectType)
    var autoCorrect: Boolean
        @Input
        get() = autoCorrectProp.get()
        set(value) = autoCorrectProp.set(value)
```
Would become:
```kotlin
    @get:Input
    val autoCorrect: Property<Boolean> = project.objects.property(Boolean::class.javaObjectType)
```

I can include a brief migration guide and include this in the Gradle 6 migration PR.

**Comment by chao2zhang** [comment]
Is it breaking for groovy consumers and kts consumers alike?

**Comment by cortinico** [comment]
> Is it breaking for groovy consumers and kts consumers alike?

AFAIK It's breaking only for kts consumers. Groovy consumers won't be affected by the `Boolean` -> `Property<Boolean>` transition (there is a note about it here https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_properties)
