### ISSUE TITLE
Support analysis of `buildSrc` folder in Gradle projects

### ISSUE THREAD

**Issue by igorwojda** [detekt/detekt#1950]
I noticed that by default detekt ignores Gradle `buildSrc` folder.

```
    detekt {
        config = files("${project.rootDir}/detekt.yml")
        input = files("${project.rootDir}/buildSrc/src/main/kotlin")
    }
```

The problem is that using `input` config overrides "all paths where detect looks typically for Kotlin files", so now `buildSrc` folder is the only folder that is checked. 

How can I add `buildSrc` and keep existing folders?

**Comment by arturbosch** [comment]
I think we haven't considered `buildSrc` in our gradle plugin.
What you can do it write a custome detekt check just for buildSrc and add `dependsOn Check`.

```
val detektBuildSrc by tasks.registering(Detekt::class) {
    description = "Runs over buildSrc"
    buildUponDefaultConfig = true
    setSource(files([buildSrcDir]))
    ....
}
```

**Comment by igorwojda** [comment]
Thx for code - I will play with it. 
BTW I think plugin should also check `buildSrc` folder by default (or at least have an easy way to add it)

**Comment by BraisGabin** [comment]
I think that this issue could be fixed just by adding the detekt plugin to the buildSrc module, right? Could we close this?

**Comment by cortinico** [comment]
> BTW I think plugin should also check `buildSrc` folder by default (or at least have an easy way to add it)

As @BraisGabin mentioned, you can apply the Detekt Gradle plugin to the `buildSrc` project and it will work out of the box.
