### ISSUE TITLE
Move detekt-formatting to another repository

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2081]
I think that detekt-formatting is kind of strange right know. It's a plugin but it's in the main repository of the project. And it's no so easy to find how to enable it.

I think that moving it to a different repository could help in different ways:

- It reduce the complexity of the core project
- It'll be clearer to everyone that it's not enable by default.
- It'll have it's own documentation. And as soon as you find the plugin you will know how to enable it.
- We can desync the versions of detekt and detekt-formatting. So, if ktlint breaks something, we can just update the plugin.

This is just an idea. Everytime that I see detekt-formatting there it seems a bit strange for me. And the issues related with detekt-formatting are completely different that the other ones.

What do you think?

Bonus: I think that we can make this change without any breaking change.

**Comment by arturbosch** [comment]
Good points!

Some cons I see:
- increases maintainability through multiple repositories (like sonar-kotlin and detekt-intellij-plugin)
- easier to break formatting rules when changing some suppression/baseline features

**Comment by BraisGabin** [comment]
I agree with your first point. The second no that much. If we break detekt-formatting is because we are adding breaking changes. So that change doesn't affect only to formatting but any plugin. On the other hand, those breaking changes are easier to spot if we have a project inside the repo. But we are using production code as our integration tests.

**Comment by schalkms** [comment]
Thanks for bringing this topic up for discussion.

> Some cons I see:
> - increases maintainability through multiple repositories (like sonar-kotlin and detekt-intellij-plugin)
> - easier to break formatting rules when changing some suppression/baseline features

I think the mentioned disadvantages outweigh the benefits.
As I see it the formatting ruleset is an essential detekt feature. The rulesets should in my opinion be in the same repo. One notable exemption are custom ruleset implementions.

@arturbosch me might want to think about grouping all the detekt projects and forks of notable integrations (Maven plugin, vanniktech/gradle-code-quality-tools-plugin ...) together at GitHub by using an organization.

**Comment by arturbosch** [comment]
> @arturbosch me might want to think about grouping all the detekt projects and forks of notable integrations (Maven plugin, vanniktech/gradle-code-quality-tools-plugin ...) together at GitHub by using an organization.

This is a good idea. However the namespace `Detekt` is already taken. Maybe I can ask the GitHub support if that organization is inactive for some years and may be deleted or something ...

**Comment by schalkms** [comment]
Yeah, I am also fine with another name.

**Comment by arturbosch** [comment]
> Yeah, I am also fine with another name.

I wrote GitHub regarding the name.
`detekt-static-analysis` sounds good to me too?

**Comment by BraisGabin** [comment]
> Maybe I can ask the GitHub support if that organization is inactive for some years and may be deleted or something ...

I did that before with other organization name and they gave me it. Maybe we are lucky.

**Comment by arturbosch** [comment]
Woop woop, we got https://github.com/detekt !!!
I've invited you two + @Mauin and @3flex via GitHub :)

**Comment by arturbosch** [comment]
FYI:
I've moved sonar-kotlin and intellij plugin to the organization.
After 1.2.1 I can move detekt to the organization. However this will break the website for our users.
I'm thinking about forking the repo after the migration and update the docs to point to the new domain prominantly on the start page.

**Comment by BraisGabin** [comment]
A realted topic: Right now if you use `java -jar detekt-cli-1.2.2-all.jar --c detekt-config.yml -gc` the generated config has the formatting in it. This is a bit missleading.

**Comment by arturbosch** [comment]
> A realted topic: Right now if you use `java -jar detekt-cli-1.2.2-all.jar --c detekt-config.yml -gc` the generated config has the formatting in it. This is a bit missleading.

True, this is inconvenient.
When we really move the formatting rule set to a new repository (much cooler with an organization), we could introduce a new `ConfigPropertiesProvider` interface which allows plugins to generate additional properties when using `-gc`.

**Comment by schalkms** [comment]
Since there were no efforts to move this to another repository as well as no further feedback, I'll close this for.
If you have contradicting opinions to mine, please feel to reopen this issue.

**Comment by BraisGabin** [comment]
I'm OK about closing this for now. I still think that we should move it to other repository but I think that the first step is to remove formatting from the default configuration. I'm going to open a new issue to do that.
