### ISSUE TITLE
Should curly braces formatting rule fix missing space in function declaration? 

### ISSUE THREAD

**Issue by adrianczuczka** [detekt/detekt#2114]
Detekt/Ktlint has a formatting rule concerning spacing around curly braces, but it doesn't seem like it catches this lack of spacing: 
``` 
fun test(): Unit{
}
```
very simple scenario, but I don't think the rule catches the lack of spacing before the left brace. Am I missing something here?

**Comment by schalkms** [comment]
Can you please try this out in ktlint without the detekt wrapper?
Does it fix the issue in ktlint?

**Comment by adrianczuczka** [comment]
Just tried it with ktlint and it does in fact catch it.

**Comment by arturbosch** [comment]
I couldn't reproduce this with the newest detekt version:

![diff-2114](https://user-images.githubusercontent.com/20924106/82249523-37bd3d80-994a-11ea-93d0-fb7f4539b702.png)


Feel free to reopen the issue if it still occurs for you.
