### ISSUE TITLE
[CI] Test detekt run with formatting plugin and html report

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#2122]
## Expected Behavior
We should have a regressions test combining these common detekt features.

## Current Behavior
A recent formatting change lead to a crash when used together with the html report.
This was only found when testing current master snapshot against our analysis projects before a release.

## Context
CI, prevent bugs.

**Comment by schalkms** [comment]
Good point.
Not only that. We should add regression tests for all common detekt use cases in order to prevent future issues.

**Comment by BraisGabin** [comment]
Agree, #2033 could be detected before the release.

**Comment by schalkms** [comment]
Automated system tests could also help to mitigate these problems in the future.
