### ISSUE TITLE
detekt-gradle-plugin shows autocorrect inconsistency

### ISSUE THREAD

**Issue by wardhapk** [detekt/detekt#2148]
I'm using `detekt-gradle-plugin:1.2.0` with `io.gitlab.arturbosch.detekt:detekt-formatting`. I have `autoCorrect = true` in the `detekt` gradle task. However some of the rules are not getting auto-corrected/auto-formatted.
Eg:- FinalNewline is getting auto-corrected. NoUnusedImports is not getting auto-corrected.

**Comment by 3flex** [comment]
Does it work when running with CLI?

**Comment by wardhapk** [comment]
Same behavior with CLI too, unused imports were not removed.

**Comment by arturbosch** [comment]
@wardhapk please verify if this is still an issue for you in the newest detekt version.
Feel free to reopen this issue than.

**Comment by wardhapk** [comment]
@arturbosch Will update
