### ISSUE TITLE
 File 'C\...\.idea' specified for property 'ideaExtension.path' is not a file.

### ISSUE THREAD

**Issue by chriskn** [detekt/detekt#2172]
## Expected Behavior
Folders should recognized as valid input for ideaExtension.path on Windows

## Observed Behavior
Even if the specified folder is valid, detekt failes. Reason is that it want's a file were a folder is needed. 

## Steps to Reproduce
Configure detekt gradle plugin on a windows machine. 
```
    detekt {
        toolVersion = "1.2.2"
        buildUponDefaultConfig= true
        idea {
            path = "$project.rootDir/.idea"
            codeStyleScheme = "$project.rootDir/config/codestyleConfig.xml"
            inspectionsProfile = "$project.rootDir/config/inspectConfig.xml"
            report = "$project.rootDir/build/detekt/report"
            mask = "*.kt"
        }
}
```
This configuration (plus the usual plugin and dependencies) Will fail with the message described in the title.

## Your Environment
* Version of detekt used: 1.2.2
* Version of Gradle used (if applicable): 6.0.1
* Operating System and version: Windows 10

**Comment by chriskn** [comment]
Suggestion: Use InputDirectory instead InputFile in https://github.com/arturbosch/detekt/blob/ffbd6e119105f6e07d686bc5632f7b531bf91a59/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/extensions/IdeaExtension.kt#L14

See https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/InputDirectory.html

**Comment by Kaelten** [comment]
with this bug you can't run either detektIdeaFormat or detektIdeaInspect

**Comment by JoeGaebel** [comment]
@3flex, I would suggest this as a bug, as opposed to improvement.

**Comment by dotdevru** [comment]
+1 for this issue.

**Comment by afaucogney** [comment]
Is there a workarround, because there are not so many +1. Does people are using this feature ?

**Comment by arturbosch** [comment]
The workaround is to use the `inspect.sh` and `format.sh` scripts from the IntelliJ installation yourself.
detekt just provides Gradle wrapper tasks for them.

 > Does people are using this feature ?

Not many I'm afraid as this feaure must have been broken for a long time now.
I've worked on a fix for this. Just need to find time to commit everything.

**Comment by adamschoenemann** [comment]
+1
