### ISSUE TITLE
Doc: type and symbol solving

### ISSUE THREAD

**Issue by schalkms** [detekt/detekt#2259]
On the homepage there should be a separate chapter regarding rules that use type and symbol solving and how to configure them in Gradle. The existing section are missing some essential information.

- [ ] How to configure and use these rules on Android (code underneath this todo list)
- [ ] Run the `detekt main` -> see https://github.com/detekt/detekt/issues/2038#issuecomment-574347664
- [ ] Mention that this is still experimental and has some peculiarities

From the Slack chat:

```kotlin
dependencies {
    detekt(project(":detekt-cli"))
    detektPlugins(project(":detekt-formatting"))
}
val detektAll by tasks.registering(Detekt::class) {
    description = "Runs over whole code base without the starting overhead for each module."
    parallel = true
    buildUponDefaultConfig = true
    include("**/*.kt")
    exclude("**/resources/**")
    exclude("**/build/**")
    exclude("**/*.kts")
    // baseline.set(file("$rootDir/config/detekt/baseline.xml"))
    classpath.setFrom(project.configurations.getByName("detekt"))
    reports {
        xml.enabled = false
        html.enabled = false
        txt.enabled = false
    }
}
```

**Comment by BraisGabin** [comment]
Is this the same as #1943 ?

**Comment by schalkms** [comment]
@BraisGabin yes, this issue further improves the documentation. I closed the old one, since the work is ongoing here this issue.

**Comment by Whathecode** [comment]
For anyone using Groovy and not Kotlin for Gradle, here is an example similar to the original posted by @schalkms:

```
tasks.register("detektCustom", io.gitlab.arturbosch.detekt.Detekt.class) { detektTask ->
    detektTask.source = files("$projectDir/src/")
    detektTask.config.from("$rootDir/detekt.yml")
    detektTask.buildUponDefaultConfig = true
    detektTask.ignoreFailures = false
    detektTask.classpath.setFrom(project.configurations.getByName("detekt"))
}
```

**Comment by schalkms** [comment]
@Whathecode thanks for posting more helpful content. This will be added to the page as well.

**Comment by Whathecode** [comment]
I just saw that the specific configured `classpath` is not even used in `BindingContext` other than an early out in case none are specified: https://github.com/detekt/detekt/blob/master/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/BindingContext.kt

Instead, to get multi-project analysis, you need to pass all source folders of the project you want to analyze to `source`. Thus, what I tried to do above through `classpath` would look like:

        detektTask.source = files(
            "$rootDir/carp.common/src/",
            "$projectDir/src/"
        )

**Comment by BraisGabin** [comment]
How is the status of this issue? We did some improvements already in our documentation in this regard. Should we update the tasks that should be done so we can close this issue?

**Comment by cortinico** [comment]
> How is the status of this issue? We did some improvements already in our documentation in this regard. Should we update the tasks that should be done so we can close this issue?

I have a draft for this page. I'd love to pick it up and send it out for review in the next days (unless someone else wants to pick it up).

**Comment by BraisGabin** [comment]
Sure, go for it!

**Comment by schalkms** [comment]
Sorry for the inconvenience. This one is on me.
It's a pity, but I haven't had the chance to tackle this issue and write the blog post.
However, I created the initial page in the corresponding homepage section.
Please feel free to go for it. I'll happily review the PR.

https://detekt.github.io/detekt/type-resolution.html

**Comment by cortinico** [comment]
The page is now available here: https://detekt.github.io/detekt/type-resolution.html

Feel free to contribute, open issues & give suggestions 👌

**Comment by arturbosch** [comment]
Great work! I will highlight it in the release notes to get further feedback.

**Comment by karandeep26** [comment]
can we use this approach to run type resolutions? (detektMain?)
