### ISSUE TITLE
Validation on formatting rules incorrect

### ISSUE THREAD

**Issue by zsmoore** [detekt/detekt#2265]
It appears that the validation is based off of the default config in the repo.

The default config contains formatting so any formatting rules placed in a config will not be reported as incorrect config even if you do not have the detekt-formatting plugin enabled.

Similarly to this since the default config contains formatting rules but they don't ship with the detekt gradle plugin it is confusing to not have them enabled or reporting.

**Comment by BraisGabin** [comment]
Related with #2081

**Comment by BraisGabin** [comment]
Closing this in favor of #3242
