### ISSUE TITLE
New rule: function could be private

### ISSUE THREAD

**Issue by RafaO** [detekt/detekt#2300]
## Expected Behavior of the rule
I would like to be able to detect the functions that can have a private modifier and don't have it.

So far I couldn't find a rule for that.

## Context
It would help me keep the visibility as low as possible in the classes.

**Comment by schalkms** [comment]
That's a good idea.
The way to go is to check, which part of the Kotlin compiler reports these cases and then adapt it for this detekt rule via the `BindingContext`.
The following rule gives a good introduction on how it's done
https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/HasPlatformType.kt

Do you have resources to tackle this new feature/rule? @RafaO 
I think it would be a good first issue and a nice addition to detekt.

**Comment by RafaO** [comment]
Thanks for the response @schalkms !

Unfortunately, I haven't worked with the Kotlin compiler that much and wouldn't know where to start to check. I took a look at the sample rule that you mentioned and I think it would be similar, but I am still unsure about how to check that the function is not called from outside the class.

I am sorry I can't take it any further :(

**Comment by cortinico** [comment]
I gave a quick look at this rule. Apparently this inspection is not part of the Kotlin Compiler but of the IDEA inspection for Kotlin:

https://github.com/JetBrains/kotlin/blob/master/idea/src/org/jetbrains/kotlin/idea/inspections/MemberVisibilityCanBePrivateInspection.kt

We would have to write a `MemberVisibilityCanBePrivate` rule by miming the logic of such inspection, similarly to what was done for `UselessCallOnNotNull` or `RedundantExplicitType`.

**Comment by schalkms** [comment]
Sorry, I should have described this clearer.
Yeah, the idea is to either wrap a Kotlin inspection from the Kotlin compiler or as @cortinico mentioned correctly, reuse the logic from an existing IDEA inspection.
This means you can have a look how the inspection is implemented and reimplement it in a detekt rule. I hope we brought some light into this topic. @RafaO 

Examples:
- https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UselessCallOnNotNull.kt
- https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/RedundantExplicitType.kt

**Comment by RajatVaryani** [comment]
Hey @schalkms 👋  

Can I work on this?

I have a question not relevant to this ticket but where do look for Kotlin inspection code from the compiler. Any examples present in detekt codebase?

**Comment by schalkms** [comment]
@RajatVaryani thanks for your help! That's awesome to hear! We can use every helping hand to further improve detekt and its rules. 

Sure, I can give you some examples. The keywords are `BindingContext` and `PsiUtil`. The easiest way is to search for all usages with IntelliJ or grep.
https://github.com/detekt/detekt/blob/6dd27429efc0055aeab94d1e7f28a877555222f3/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/internal/BaseRule.kt#L16

The `Kotlin` main repo and the `Kotlin` compiler slack channel could also be consulted for more information.

**Comment by schalkms** [comment]
I assigned you in order to make it transparent to the community that you work on this.
Please feel free to ask questions, if you topics to clarify.

**Comment by BraisGabin** [comment]
@RajatVaryani I'm unassigning you from this issue. If you are still interested in this issue you can open a PR anyway :)

**Comment by sowmyav24** [comment]
I had a look at the IDEA inspection rule. They also do a `ReferencesSearch` for the function under inspection which we would need to determine the if the function can be private.
I did not find any existing rule, which requires referencing across the files during analysis. Do correct me if there is any such rule is already present.

**Comment by BraisGabin** [comment]
Closing this issue as this rule will be basically the same as #6778. There we have the reasons why we can't implement this right now on detekt. To be honest I would love if detekt could do things like this but probably now is not the time for it.
