### ISSUE TITLE
Hyperlink to error inside Android studio

### ISSUE THREAD

**Issue by ahmadmssm** [detekt/detekt#2340]
I can not find a way to make the reported issues hyperlink that opens the line with the issue inside a class

**Comment by schalkms** [comment]
Do you use the command line report of detekt?
Do you use the command line emulator in Android Studio?
What OS and what terminal do you use?
The links in the command line report are clickable (see #171 for details).

**Comment by 3flex** [comment]
I have the same issue. Running detekt directly from IntelliJ's Gradle integration (on Windows) so it's not specific to Android Studio, but IntelliJ itself.

**Comment by ahmadmssm** [comment]
@schalkms Thanks for the quick reply, 
1. I use this command ` gradle detekt`, and I write it in Android studio's built-in terminal.
2. I use the run green button to launch the Emulator (I think it is something that is not related to the emulator).
3. I Use MAC OSC Catalina 10.15.3 and use the native mac terminal.

**Comment by schalkms** [comment]
Okay, did you try it with zsh in the native Mac terminal or with iTerm? By default Mac OS used the bash, but if I remember it correctly they switched to zsh in one of the recent OS versions.

**Comment by ahmadmssm** [comment]
@schalkms Yes, that's right, MAC OS switched to zsh starting from Catalina, I guess.
I'm using the native terminal and not iTerm or iTerm2.

**Comment by schalkms** [comment]
Does it work in the _native_ terminal?

**Comment by ahmadmssm** [comment]
No

**Comment by arturbosch** [comment]
Can we do something about this in detekt?
I guess the terminal emulator/intellij should find absolute paths and make them clickable?

**Comment by schalkms** [comment]
This was already implemented in #171 but somehow broke with the new path resolving API.
The printed path needs to have a special format, so that the terminal understands and interprets it as a hyperlink.
