### ISSUE TITLE
Build Gradle plugin with oldest supported version

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#2414]
## Expected Behavior
Gradle plugin is built with oldest supported version.

## Observed Behavior
Gradle plugin is built with latest supported version.

## Context

See first paragraph here: https://github.com/gradle/gradle/issues/10953#issuecomment-544012826

This will make it impossible to use our Gradle compat class to support Gradle 5.0, since that class must be compiled with Gradle 5.3 or higher as that version introduced ObjectFactory.fileCollection().

So suggestion is to build Gradle plugin with Gradle 5.3 so the plugin still compiles and is also compatible with all new versions, instead of building with latest Gradle which doesn't have compatibility guarantees when the built plugin is run on an earlier version.

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by arturbosch** [comment]
If I understand this correctly we need to downgradle the Gradle wrapper to 5.3 and I need to publish plugins with the Gradle wrapper only and not my latest version from sdk?

**Comment by 3flex** [comment]
Publishing with latest version should be OK, I believe the plugin should just be built with the older version.

Downgrading the wrapper to 5.3 in detekt-gradle-plugin should be enough, plus changelog/README update with the new earliest supported version.

**Comment by schalkms** [comment]
I think this issue is done, right?

**Comment by 3flex** [comment]
Not exactly, since the detekt Gradle plugin is built with Gradle 6.7 (as is the rest of the project). But since the detekt Gradle plugin supports Gradle 5.4 and up, it should be built with Gradle 5.4, not 6.7.

That said unless the build setup changes back to being a composite build, or the whole project is built with Gradle 5.4, it's not possible to resolve this, so maybe close as won't fix...
