### ISSUE TITLE
Configure default excludes for InvalidPackageDeclaration

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#2539]
## Expected Behavior
We should exclude `*.gradle.kts` files by default. Maybe even `*.kts` files?

## Current Behavior
InvalidPackageDeclaration flags `gradle.kts` for not having a package declaration.

## Context
A failfast configured codeac instance with rule defaults.

**Comment by BraisGabin** [comment]
Do you mean `*.gradle.kts`? Anyway I vote for `*.kts`.
