### ISSUE TITLE
detektGenerateConfig ignores detekt.config paramenter

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2565]
## Expected Behavior
`./gradlew detektGenerateConfig` creates the config file in the defined `config` path defined in the configuration
```kotlin
detekt {
    config = files("$rootProjectDir/detekt-config.yml")
}
```

## Observed Behavior
The `config` is ignored and the task creates it in the default path: `config/detekt/detekt.yml`

## Steps to Reproduce
Configure the plugin like this:
```kotlin
detekt {
    config = files("$rootProjectDir/detekt-config.yml")
}
```
and then run: `./gradlew detektGenerateConfig`

## Your Environment
* Version of detekt used: 1.7.2 (reproducible in 1.6.0 too)
* Version of Gradle used (if applicable): 5.6.1
* Operating System and version: macOS

**Comment by iAmMONK** [comment]
I had some problems with config as well. But this code fixed the issue for me:
`config.from(files("${project.rootDir}/config/quality/detekt/default-config.yml"))`

**Comment by arturbosch** [comment]
Right, the cli respects the config parameter but the gradle plugin not.
So the fix is quite easy in the gradle plugin.
Not sure if this is a bug or feature. I would consider this for a 1.X.0 release as this will need a migration entry.

**Comment by BraisGabin** [comment]
Ok, I was trying to fix this but it's not that easy. We allow to add multiple paths in `config`. So, which one should be used?

**Comment by arturbosch** [comment]
Let's go with the last one as it overwrites the properties of the preceding. E.g.: config1,config2 we would use config2
