### ISSUE TITLE
Include Kotlin multiplatform test folders to default exclude configuration

### ISSUE THREAD

**Issue by Whathecode** [detekt/detekt#2608]
The [default-detekt-config.yml](https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml) has several default 'excludes' configurations to exclude test sources.

`excludes: '**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt'`

However, this does not cover test folders in Kotlin multiplatform projects, which are named `**/<platform-target>Test/**`, e.g., `**/jsTest/**` and `**/commonTest/**`. I reuse the majority of defaults, but using detekt in a multiplatform project requires me [to override all default excludes with my own](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/detekt.yml):

`excludes: '**/commonTest/**,**/jvmTest/**,**/jsTest/**,**/test/**'`

Therefore, it would be nice to either add the default multiplatform test folders to `default-detekt-config.yml`, or alternatively, to override the 'default' excludes in one place.

**Comment by Whathecode** [comment]
Maybe `**/*Test/**`, or would that be too broad?

**Comment by BraisGabin** [comment]
`'**/test/**'` is already too broad... adding `**/*Test/**` doesn't seem like a huge change. This will help to android and it's flavours. Where the tests of a flavour are placed in `**/flavourTest/**`.

Any way, I think that for your use case something like #2581 would be really handy too.

**Comment by schalkms** [comment]
I think adding `**/commonTest/**,**/jvmTest/**,**/jsTest/**,**/iosTest/**` makes more sense, since this is really common in Kotlin multi-platform.
If everyone agrees, I'll submit a PR.

**Comment by Whathecode** [comment]
@schalkms I tried making a PR before but couldn't find the sources to modify. :) I presumed that default file was generated?

**Comment by schalkms** [comment]
One needs to edit 1 file and 1 unit test. The .yml file is auto-generated. I modified the 2 files quickly and submitted the PR.
