### ISSUE TITLE
Detekt 1.8.0 artifacts are not published to Maven Central

### ISSUE THREAD

**Issue by arturdryomov** [detekt/detekt#2630]
## Expected Behavior

Detekt 1.8.0 available at Maven Central.

## Observed Behavior

Detekt 1.8.0 is not available at Maven Central.

## Steps to Reproduce

* Open [Maven Central listing](https://search.maven.org/search?q=g:io.gitlab.arturbosch.detekt).
* Observe the latest version as `1.7.4`.

**Comment by arturbosch** [comment]
Somehow the auto sync feature of bintray had a dropout.
Thanks for reporting, fixed.
