### ISSUE TITLE
Ability to suppress rules at the module level

### ISSUE THREAD

**Issue by btrautmann** [detekt/detekt#2633]
## Expected Behavior
With tools like Android Lint, one can specify a rule or list of rules to be ignored for a given module. Our codebase has a large number of modules and in general we want them all to behave/be checked the same, but there are a few outliers that require exclusions.

With Android Lint, this would be done by either configuring a `lint.xml` file that would then be pointed to in the `build.gradle` within the `lintOptions` block, or by using the `disable "SomeRule"` syntax in the `lintOptions` block.

Having Detekt offer this functionality would be great.
## Current Behavior
Today (based on [this](https://arturbosch.github.io/detekt/suppressing-rules.html) documentation), the most far-reaching suppression appears to be the `@file:` annotation, which is not enough because every file must then contain that annotation.

## Context
In a large, multi-module project, it is not enough to rely on a single configuration for all modules, and it is too much to ask to have a configuration file for every module. The hope here is that you can have a single configuration file for all modules with the ability to easily turn off rules for certain modules without needing to create a different configuration file for each.

**Comment by BraisGabin** [comment]
You can specify a config file per module. Or add a base one and then add one in the module you want and change the rules as you wish.

**Comment by btrautmann** [comment]
Is there documentation on this configuration file inheritance method? I don't see it in the documentation for configuring or suppressing.

**Comment by cortinico** [comment]
@btrautmann You can specify more than one config file when configuring Detekt (comma or semicolon separated). So you can have a global config file with your default configuration and local config files that overrides your specific configuration.

Logic for the parsing of multiple files is here:
https://github.com/detekt/detekt/blob/cff69a96a6e9c3829f9b9da72752fae5526c14d1/detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Configurations.kt#L75-L81

There is no real documentation about the override mechanism, although this page: https://detekt.github.io/detekt/cli.html mentions this for the CLI interface:

```
    --config, -c
      Path to the config file (path/to/config.yml). Multiple configuration
      files can be specified with ',' or ';' as separator.
```

**Comment by btrautmann** [comment]
Thanks for the help! Will give those a shot.
