### ISSUE TITLE
Detekt ClassCastException

### ISSUE THREAD

**Issue by blundell** [detekt/detekt#2648]
## Expected Behaviour

Detekt to run or detektBaseline to run

## Observed Behaviour

Crashes/Fails

## Steps to Reproduce

Run Detekt

## Context

I get this stack trace:

```
Analyzing '/home/blundell/StudioProjects/MyApp/com/foo/SomeClass.kt' led to an exception.
The original exception message was: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
Running detekt '1.7.4' on Java '1.8.0_252-8u252-b09-1~18.04-b09' on OS 'Linux'.
If the exception message does not help, please feel free to create an issue on our GitHub page.
```

The class is super simple:

```
interface NavigationAction

class SomeClass : NavigationAction
```

## Your Environment

Running detekt '1.7.4' on Java '1.8.0_252-8u252-b09-1~18.04-b09' on OS 'Linux'.

**Comment by BraisGabin** [comment]
Is that all the stack trace? Is not any clue about which rule has the problem?

**Comment by blundell** [comment]
So I think the problem was I generated the config using Detekt 1.8.0 then reverted to Detekt 1.7.4 and tried to use that config. Regenerating the default config whilst using 1.7.4 has cleared the issue.


(The stacktrace was 1000's of lines long, repeating itself with the small snippet I sent)

**Comment by blundell** [comment]
(As you can see here, the config has changed)
Thsi is 1.8.0 vs 1.7.4
![image](https://user-images.githubusercontent.com/655860/80798469-57a7df80-8b9c-11ea-82f9-f17957bbdfab.png)
