### ISSUE TITLE
Rule: Mandatory braces for single-line for loop bodies

### ISSUE THREAD

**Issue by daphil19** [detekt/detekt#2652]
I'd like to have the option to enforce braces around for loops with a single statement for the body. This is similar to #365, which added this for `if` statements.

Non-compliant example:
```kotlin
for (i in 0..10)
    println(i)
```

Compliant example:
```kotlin
for (i in 0..10) {
    println(i)
}
````

Compliant example 2:
```kotlin
for (i in 0..10) println(i)
```

**Comment by schalkms** [comment]
Good idea 💡 
The basic logic could be reused from the `MandatoryBracesIfStatemeunts` rule.
Do you have resources to help us out @daphil19 ?

[Source of the rule](https://github.com/detekt/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/optional/MandatoryBracesIfStatements.kt)
