### ISSUE TITLE
Clean the exclusion rule a bit

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2669]
In the exclusion list of tests we have these three regex: `'**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt'`.

Do we really want to support this file names like `Somthing.Test.kt`? I never saw a project that names it's tests like that (and the same for `Spek` and `Spec`). Usually it is `SomthingTest.kt`.

So, if no one ever complained about this is that the previous patterns are doing it's job. So I propose to remove these three patterns.

And I think that these is more important now because we are going to add 4 new elements to that list: #2667

**Comment by schalkms** [comment]
I agree. We should do that.
I’m putting a feedback label on this issue.

**Comment by schalkms** [comment]
I'd say: go for it @BraisGabin
