### ISSUE TITLE
CanBeInternal rule

### ISSUE THREAD

**Issue by danikula** [detekt/detekt#2673]
## Expected Behavior of the rule
`CanBeInternal` should detekt code (classes, interfaces, constants,...) that isn't used outside it's module and can be internal. 

## Context
It's commonly used practice to minimize code visibility and Detekt can help with this.

**Comment by schalkms** [comment]
This is a good idea for a contributed rule. I really like it! Help is highly appreciated in order to get this rule into detekt. Since there are many more high prior topics, it would be cool, if someone had to resources to pick it up. @danikula

**Comment by BraisGabin** [comment]
Related with #2300. Not the same, but similar.

**Comment by atulgpt** [comment]
Hi @BraisGabin shouldn't there be a single issue to address both this issue and [#2300](https://github.com/detekt/detekt/issues/2300)? Rule name can be `VisibilityCanBeReduced`

**Comment by mustafaozhan** [comment]
Ohh this seems a nice love it ❤️

**Comment by BraisGabin** [comment]
They will share a lot of behavior but they are different rules so I think we should keep both.

**Comment by BraisGabin** [comment]
Closing this issue as this rule will be basically the same as #6778. There we have the reasons why we can't implement this right now on detekt. To be honest I would love if detekt could do things like this but probably now is not the time for it.
