### ISSUE TITLE
CLI is too noisy

### ISSUE THREAD

**Issue by ZacSweers** [detekt/detekt#2674]
## Expected Behavior
The CLI should output exactly the relevant information, and hide extra debug/info logging behind a `--verbose` flag or something similar.

## Observed Behavior

Currently, the CLI logs a ton of irrelevant information when running, burying the actual relevant information in the bottom (and often leading it to be truncated if the gui showing it has a limit.

![image](https://user-images.githubusercontent.com/1361086/81597958-85f39f00-9394-11ea-899d-cab0698f64b3.png)

## Steps to Reproduce

N/A

## Context

Explained above.

## Your Environment

* Version of detekt used: 1.8.0
* Version of Gradle used (if applicable): N/A
* Operating System and version: MacOS
* Link to your project (if it's a public repository):

**Comment by arturbosch** [comment]
It seems like you used the `--debug` flag when calling detekt here. As of 1.6.0 - I think - detekt is quiet by default.

**Comment by ZacSweers** [comment]
D'oh, I could have sworn I checked that
