### ISSUE TITLE
New rule: NoPrintStatement

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#2678]
## Expected Behavior of the rule
This rule finds all usages of standard `println()` or `print()` (System.out.println).
A logger or `PrintStream` facility should be used instead.

## Context
Unified logging/piping output of a (command line) program.

**Comment by schalkms** [comment]
This is related to the `PrintStackTrace` rule that detekt already has.

**Comment by cortinico** [comment]
Isn't this something that can be achieved with `ForbiddenMethodCall`?

**Comment by BraisGabin** [comment]
I agree with @cortinico. What do you think about adding `kotlin.io.println()` and `kotlin.io.print()` as default values in `ForbiddenMethodCall`?

**Comment by schalkms** [comment]
@BraisGabin please go ahead
