### ISSUE TITLE
False positive UnderscoresInNumericLiterals in Serializable

### ISSUE THREAD

**Issue by vladimirfx** [detekt/detekt#2686]
## Expected Behavior
This is valid code according to docs:

    class Office(
        val id: Long,
        val address: String,
        val phone: String
    ) : Serializable {
        companion object {
            private const val serialVersionUID = -43857148126114372L
        }
    }

## Observed Behavior
UnderscoresInNumericLiterals reported for `serialVersionUID` field.

## Your Environment
* Version of detekt used: 1.9.0
* Version of Gradle used (if applicable): 6.4

**Comment by schalkms** [comment]
Thanks for reporting this. I have a fix, which will be submitted soon.
