### ISSUE TITLE
Separate task for autocorrection

### ISSUE THREAD

**Issue by tprochazka** [detekt/detekt#2705]
Maybe I miss something bat a current way when `detekt` task does check and autocorrection together (based on setup) is very problematic). Because I want to do autocorrection locally (before push), but definitely not on CI server.

**Comment by schalkms** [comment]
That's a very common use case IMHO. It's always interesting to hear, how users actually use detekt in different scenarios.
There's no need for a separate `detekt` since this can be easily solved with a 2nd configuration file. Depending on the current environment you include the second file, which sets `autoCorrect` to false.

```groovy
config = files("path/to/config.yml", "2ndconfig.yml")
```

**Comment by arturbosch** [comment]
You could also try to add a custom detekt task just for CI:
```kotlin
val detektCI by tasks.registering(Detekt::class) {
  ...
  autoCorrect = false
  ...
}
```

**Comment by tprochazka** [comment]
I understand, but I still think that call `gradlew detekt` on CI and `gradlew detektFix` locally when I want to fix code base is much much better than trying to detect the environment in some hacky way and have two duplicated configuration file. Or at least `-P` switch would help.

**Comment by schalkms** [comment]
>  than trying to detect the environment in some hacky way and have two duplicated configuration file.

This is perfectly normal. There's nothing hacky about that. This repository also has a special GitHub CI configuration for JDK8 that compiles test snippets with the help of the Kotlin compiler.

https://github.com/detekt/detekt/blob/57e0b91b3c57df3988d4d24ba0be411337067adb/.github/workflows/pre-merge.yaml#L22

**Comment by arturbosch** [comment]
Consider 
```kotlin
detekt {
  ...
  autoCorrect = System.getProperty("IS_CI", true)
}
```

**Comment by tprochazka** [comment]
Yes. Thanks!
I know that everything like this is possible, but it is not a general solution, it always depends on some custom CI server-side variable.

**Comment by yitzLefkowitz** [comment]
I know that this is closed, I am genuinely wondering about the pushback to the seemingly reasonable suggestions of @tprochazka. In my case we do not want autocorrect to run, unless the user specifically and intentionally runs it (locally). We can register a custom gradle task, however the custom task doesnt have the detekt extension what makes some of the configurations (for example toolVersion) a pain. Not to mention that means that need to duplicate the rest of the detekt configs.

**Comment by cortinico** [comment]
> We can register a custom gradle task, however the custom task doesnt have the detekt extension what makes some of the configurations (for example toolVersion) a pain. Not to mention that means that need to duplicate the rest of the detekt configs.

The detekt extension exposes the `autoCorrect` property that you could toggle via a Gradle Property or so (environment variable, files, etc.)
https://github.com/detekt/detekt/blob/d627b9018b59161ef593729225d5fede994e708a/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/extensions/DetektExtension.kt#L43

There is no need to create to separate task for this.
