### ISSUE TITLE
How should we match the configuration values?

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2711]
## Expected Behavior
All the matchings with packages, fully qualified names, class names, imports... that we provide in the configuration file follows some kind of rule.

## Observed Behavior
Right now there are a lot of behaviours and they are not documented so it's kind of difficult to know which is the behaviour.

## Context
I saw this problem when I refactor the string list in yaml arrays. In some places we use a "contains" in other places an "endsWith", in other places we use [`glob`](https://en.wikipedia.org/wiki/Glob_(programming)) and in others we use full regex.

In my opinion we can reduce all our needs in two different options:

1. Regex: It's difficult to read and maintain (by the user) but it gives maximum flexibility. Normally we don't need to provide this option, but whe it's needed there is no problem with it. The regex is a well defined language.
2. glob: It's much more easy to read and it gives a lot of flexibility too. It's really good for fully qualified names because you don't need to scape the `.`. I think that these should be the default option.

Options that we don't need:
- Complete match. If you need a complete match you can use `glob`. You just need to scape `*` and `?` and they are not used too much in fully qualified names or similar.
- Partial match (aka contains or endsWith). This cases can be easily archived with `glob` because you just need to add a `*` at the beggining and/or the end. 

An example of this can be found here: #2698

**Comment by schalkms** [comment]
I mentioned in another thread concerning this topic.

> I don't think that a uniform guideline for configuration options can be reached. There are many contributed rules and you can't make sure that everyone adheres to the guidelines. That would make it harder for 3rd party contributors to actually contribute a rule. Furthermore, you change a public API here. As a user of detekt, I'm tired of constantly changing my existing config just for the sake of change. It costs time. I'm not sure regarding the user benefit of having a uniform config. The rules are different and would be hard to achieve a uniform guideline.

All in all, you trade freedom and flexibility for consistency.

**Comment by schalkms** [comment]
> In my opinion we can reduce all our needs in two different options:
> 1. Regex
> 2. glob

I don't think so. With regular expressions you can only describe regular languages according to the [Chomsky hierarchy](https://en.wikipedia.org/wiki/Chomsky_hierarchy#The_hierarchy).
You can't describe context free or context sensitive languages, which might be applicable for a specific rule's config option. In my opinion this has to be handled and evaluated case by case. For some rules you might want to configure the rule with a regular expression. In other cases a simple string list as we have with the exception ruleset might be fine too.

**Comment by cortinico** [comment]
> 2\. glob: It's much more easy to read and it gives a lot of flexibility too. It's really good for fully qualified names because you don't need to scape the `.`. I think that these should be the default option.

I'd be for this as the default.

If a user needs more fine-grained control, they can still create a custom rule that maps the same behavior but uses the full Regex mechanism.

The benefit is that default values are easier to read and to manipulate for the vast majority of our users.

**Comment by cortinico** [comment]
Should this be moved to a "Discussion"?
