### ISSUE TITLE
New Rule: Forbidden Annotation

### ISSUE THREAD

**Issue by gtcompscientist** [detekt/detekt#2719]
**ForbiddenAnnotation**

## Expected Behavior of the rule
- Allows for certain Annotations to be disallowed at the project level. This is slightly different from ForbiddenImports as there are some times when an import might not also match to the Annotation.
- If you don't enumerate ALL imports (ie: allow .* imports)
- If an Annotation doesn't require an import (ie: `@SuppressWarnings`)

## Context
Kotlin code should use Kotlin's `@Suppress` annotation, not Java's `@SuppressWarnings` and there are other annotations that we would like to not have in our code.

**Comment by gtcompscientist** [comment]
Does `visitAnnotation()` guarantee that it visits all Annotations? ie:

- Class
- Property
- Function
- Parameter
- File

**Comment by cortinico** [comment]
> Does `visitAnnotation()` guarantee that it visits all Annotations? ie:

It's hard to say as the PSI api is not really well documented. The general suggestion is to play around with the PSI-Viewer plugin and/or write some tests to validate all the scenarios.

**Comment by arturbosch** [comment]
We have a `ForbiddenImport` rule which can be used to forbid annotations.
Does it make sense to offer an specialized version for annotations?

**Comment by cortinico** [comment]
Context from this slack thread: https://kotlinlang.slack.com/archives/C88E12QH4/p1590074412134700

I'm also not entirely sure we need a `ForbiddenAnnotations` rule.

@gtcompscientist scenario is involving annotations (such as `java.lang.SuppressWarning`) that don't have an explicit import and are impossible to catch with the `ForbiddenImport` rule.

**Comment by BraisGabin** [comment]
I never open an issue but I would like to support the same for classes too. For example, I would like to forbid the use of `java.lang.Math` and `java.lang.Runnable`. And there's other case: if the class is in the same package. So maybe the rule could be called `ForbiddenClass` and check all the cases: Classes, annotations and objects.

I know that I would use a rule like that but I don't know how much value could it bring for the community in general.

**Comment by gtcompscientist** [comment]
@BraisGabin I think that's a really interesting adaptation. Definitely the kind of thing that would be very useful for pushing people towards the Kotlin implementations.

**Comment by cortinico** [comment]
> For example, I would like to forbid the use of `java.lang.Math` and `java.lang.Runnable`

Small side note: there is a `ForbiddenMethodCall` rule that will most likely cover the use case.

**Comment by gtcompscientist** [comment]
@cortinico 

> > For example, I would like to forbid the use of `java.lang.Math` and `java.lang.Runnable`
> 
> Small side note: there is a `ForbiddenMethodCall` rule that will most likely cover the use case.

I think to be practical, the rule would need to allow wildcards in the config. ie: `java.lang.Math.*` Does that make sense?

**Comment by cortinico** [comment]
> I think to be practical, the rule would need to allow wildcards in the config. ie: `java.lang.Math.*` Does that make sense?

Currently it only supports only a list of fully qualified method names. Having wildcards will probably also be beneficial (if there is a valid use case).

Also that's bit off-topic for this issue (ForbiddenAnnotation). I just wanted to mention that detekt has `ForbiddenMethodCall` to cover some related scenarios.

**Comment by schalkms** [comment]
@gtcompscientist Is there any progress on this issue? Do you need further assistance?

**Comment by schalkms** [comment]
This issue went stale. Do we want to continue on this issue? Should we close it?

**Comment by BraisGabin** [comment]
Is this an actionable issue? I mean, if we want help (and we do) it should be clear what's the expected outcome and I see a lot of ideas here but there is nothing specific.

Do we want a ForbiddenAnnotation? A ForbiddenClass that will include the annotations? Both?

**Comment by schalkms** [comment]
@BraisGabin I still don’t see much added value to implement a new rule. Many annotations can be prohibited by using the **ForbiddenImport** rule.

**Comment by BraisGabin** [comment]
I agree, I mean, if no one is willing to take this issue we can close it. I'm not against the rule, but if no one wants it enough to write it we can close it.

**Comment by cortinico** [comment]
Reopening as we'll be adding this rule in https://github.com/detekt/detekt/pull/5515

**Comment by schalkms** [comment]
Closed with [028f69e](https://github.com/detekt/detekt/commit/028f69e5eba6bf72ee76eff3c5c0bae3fee5fa78)

Thanks David!
