### ISSUE TITLE
Plugin version and formatting dependency

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [detekt/detekt#2732]
I am creating a precompiled plugin with all the detekt configuration, the problem I have to define the version variable in two places:

1. In the precompiled plugin file for the formatting dependency:

```
io.gitlab.arturbosch.detekt:detekt-formatting:$version"
```

2. In the `buildSrc/build.gradle.kts`  file where I put the plugin dependency.

**Comment by schalkms** [comment]
Okay.. and what's the issue here?

**Comment by JavierSegoviaCordoba** [comment]
I have to define the version in two places because I can't use the same variable. Should be great if the plugin add the version to a constant to avoid it

**Comment by schalkms** [comment]
This is a 2 separate jars and modules. Is it really so hard to duplicate a number just once?

**Comment by schalkms** [comment]
There are 2 separate jars and modules. Is it really so hard to duplicate a number just once?

**Comment by JavierSegoviaCordoba** [comment]
No, but it is easy to forget update one. AGP has it in a constant for example.

**Comment by arturbosch** [comment]
There is a file `PluginVersion.kt` generated and shipped with the Gradle plugin.
You may just use it:
```kotlin
package io.gitlab.arturbosch.detekt

internal const val DEFAULT_DETEKT_VERSION = "1.9.1"

```
