### ISSUE TITLE
Old documentation idexed by google

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2805]
https://arturbosch.github.io/detekt/changelog.html

This link is still valid and it's indexed by Google (and I image that other search engines too).

We should:
- Or find a way to redirect all those urls to the new web with a `301` so we can keep the indexation and the users are redirected to the correct place.
- Or remove it because this documentation is missleading.

I'm a maintainer so I know that detekt is in version 1.9.0 and it has a RC of 1.10.0. But if a normal user arrives to that page will say "great, detekt 1.8.0 is the last version".

And, right now it's not that bad: it's just one minor away but this gap is growing.

**Comment by cortinico** [comment]
> * Or find a way to redirect all those urls to the new web with a `301` so we can keep the indexation and the users are redirected to the correct place.

If @arturbosch is not using arturbosch/detekt, we could updated the `docs` folder and use https://github.com/jekyll/jekyll-redirect-from

I already used it in the past and it works ok (though it's not a HTTP 301 redirect):
https://github.com/gdgpisa/gdgpisa.github.io/blob/master/feedbackform.md

**Comment by arturbosch** [comment]
I will just update the repo from time to time for some months and delete it after some more months.

**Comment by schalkms** [comment]
After a long time having this issue stale, is the indexing still a problem?

**Comment by cortinico** [comment]
> After a long time having this issue stale, is the indexing still a problem?

The older website is still live. I'm unsure if it's still indexed but I believe so.

> and delete it after some more months.

@arturbosch Could you delete your fork? Or we should setup the `gh-pages` branch of your fork to contain redirect to the production website.

**Comment by arturbosch** [comment]
time is flying ... deleted :)
