### ISSUE TITLE
kotlin mutli platform project with custom detekt rule

### ISSUE THREAD

**Issue by grbe1l** [detekt/detekt#2810]
Hi, looking through the Detekt documents there does not seem too much information on Kotlin DSL with Gradle for multiplatform projects when doing custom rules. Here I am wanting to create a module within my project and call this rather than integrating my own custom rules into the detect code base. 

I have looked into this and have not manged to create a solution. I have tried many different gradle set ups within the sub modules and the top gradle.build.kts. I have attached an example of a test project I have setup for an idea of what I am trying to achieve. 

[example project](https://github.com/grbe1l/testDetekt)

Any help on this would be great!

**Comment by schalkms** [comment]
Do the following how-tos help?
https://diamantidis.github.io/2019/09/01/kotlin-multiplatform-project-code-styling-for-ios-and-android
https://blog.karumi.com/first-steps-into-kotlin-multiplatform/

**Comment by grbe1l** [comment]
I am looking more how to set up the Detekt DSL for custom rules with a multiplatform project rather in how to set up the project.

**Comment by schalkms** [comment]
Sorry, I read over the custom DSL mention.  Is there a reason why you develop your custom detekt rule in a MPP setup?

**Comment by schalkms** [comment]
Okay. What were your problems (stack traces etc.) while configuring the detekt custom rule Gradle script?
Have you tried doing the same in a *standard* JVM project? Does it work in this case?

**Comment by grbe1l** [comment]
I have added my custom rules onto the detekt code base and the rule has worked. I couldn't get the custom rule to run when it was within my MPP via the gradle setup. I was wondering how to do this for this particular setup as it doesn't seem to be documented.

**Comment by schalkms** [comment]
Okay, thanks for the context. We've never considered writing detekt custom rules in a MPP app. So far now one has tried that to my knowledge. @arturbosch what's your opinion on this?

> I couldn't get the custom rule to run when it was within my MPP via the gradle setup.

What went wrong here? Do you have any stacktrace or error message?

**Comment by grbe1l** [comment]
There is no stacktrace/error message to show as I couldn't integrate it within the MPP. I think this would be very useful use of detekt as it could run custom rules specifically designed for this MPP, while keeping my codebase light with only the custom rules I need. This would also make it very easy to update/add new rules within this MPP.

**Comment by schalkms** [comment]
> I think this would be very useful use of detekt as it could run custom rules specifically designed for this MPP, while keeping my codebase light with only the custom rules I need. This would also make it very easy to update/add new rules within this MPP.

I understand the use case, but it's a very seldom one. So far we haven't had a single user report about that. Considering the number of custom detekt rules, this is a strong statement. You can of course create a second JVM app write your rule and integrate the jar in your MPP app. This would be a feasible workaround.

**Comment by grbe1l** [comment]
The separate JVM app is the solution I believe I will have to go with for now. This was more of is there currently a way to do this, as I believe this to be a lightweight/clean solution.

**Comment by schalkms** [comment]
I'm sorry to say this. We have to discuss internally, if we even want to support and maintain this use case.

**Comment by arturbosch** [comment]
@grbe1l in your example I see that you have added formatting but not your custom rule as `detektPlugins`.

I read this discussion as you want to write your custom rules in a gradle module next to your project.
Mozilla does the same here: https://github.com/mozilla-mobile/fenix/blob/master/build.gradle#L167
