### ISSUE TITLE
[gradle-plugin] Support for configuration cache

### ISSUE THREAD

**Issue by ouchadam** [detekt/detekt#2811]
## Expected Behavior
When enabling the gradle configuration cache then detekt works
```
org.gradle.unsafe.configuration-cache=ON
org.gradle.unsafe.configuration-cache-problems=warn
```

## Current Behavior (using 1.10.0-RC1)
gradle fails to configure project

```
field 'project' from type 'io.gitlab.arturbosch.detekt.extensions.DetektReport': cannot deserialize object of type 'org.gradle.api.Project' as these are not supported with the configuration cache.
  See https://docs.gradle.org/6.5/userguide/configuration_cache.html#disallowed_types

field 'project' from type 'io.gitlab.arturbosch.detekt.extensions.DetektReports': cannot deserialize object of type 'org.gradle.api.Project' as these are not supported with the configuration cache.
  See https://docs.gradle.org/6.5/userguide/configuration_cache.html#disallowed_types
```

## Context
Trying out the experimental configuration caching and seeing what breaks!

**Comment by CristianGM** [comment]
That's still not working properly, we have some tests on our projects for configuration-cache compatibility and I see:
task `:detekt` of type `io.gitlab.arturbosch.detekt.Detekt`: invocation of 'Task.project' at execution time is unsupported.

I'm using 1.10.0 but I see in master branch the code is still the same.

The culprit: https://github.com/detekt/detekt/blob/master/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/Detekt.kt#L192
It get's called in line 220 which is execution time.
