### ISSUE TITLE
generateDocumentation does too much work

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2830]
`./gradlew generateDocumentation` executes `:detekt-generator:test` and `:detekt-generator:detekt`. Tasks that we don't need to execut to run generate the documentation.

The reason is because `generateDocumentation` depends on `:detekt-generator:build` instead of `:detekt-generator:assemble`. The problem is that, when I change the dependency the run fails with the message:

```
> Task :detekt-generator:generateDocumentation FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: io/gitlab/arturbosch/detekt/formatting/FormattingRule
        at io.gitlab.arturbosch.detekt.generator.collection.RuleVisitor.<clinit>(RuleVisitor.kt:167)
        at io.gitlab.arturbosch.detekt.generator.collection.RuleCollector.visit(RuleCollector.kt:9)
        at io.gitlab.arturbosch.detekt.generator.collection.DetektCollector.visit(DetektCollector.kt:61)
        at io.gitlab.arturbosch.detekt.generator.Generator.execute(Generator.kt:32)
        at io.gitlab.arturbosch.detekt.generator.Main.main(Main.kt:23)
Caused by: java.lang.ClassNotFoundException: io.gitlab.arturbosch.detekt.formatting.FormattingRule
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more
```
Any idea why?

**Comment by arturbosch** [comment]
Does it also fail after restarting the Gradle daemon? Might be still a problem with caching the classloader for devs ...

I have also thought about removing the dependencies on `detekt-rules` and `detekt-formatting` for the generator.
We use these dependencies to get the rule names:
```kotlin
        private val ruleClasses = listOf(
                io.gitlab.arturbosch.detekt.api.Rule::class.simpleName,
                FormattingRule::class.simpleName,
                ThresholdRule::class.simpleName,
                EmptyRule::class.simpleName
        )
```

**Comment by BraisGabin** [comment]
The `--stop` did the trick! PR incoming!

**Comment by BraisGabin** [comment]
Should we close this issue or should we keep it open to track the dependencies changes that you are talking?

**Comment by arturbosch** [comment]
> Should we close this issue or should we keep it open to track the dependencies changes that you are talking?

We could change the ticket to "general build speed improvements"?

My proposal could improve the average incremental build time but makes the doc generation "unsafer".
It is an unlikely error but it could happen. Then again we could write a custom detekt rule to check this without making our average build slower :).

Another idea I have is to finally split the `detekt-rules` module into a module for each `RuleSetProvider`.
detekt rule contributor are slowed down to the `detekt-rules:test` task which takes 1-1.5 minutes for each change...

![2020-06-29-154639_799x172_scrot](https://user-images.githubusercontent.com/20924106/86013753-c8923900-ba1f-11ea-9ed8-14b7f8e12e4f.png)

**Comment by BraisGabin** [comment]
> My proposal could improve the average incremental build time but makes the doc generation "unsafer".
> It is an unlikely error but it could happen. Then again we could write a custom detekt rule to check this without making our average build slower :).

I think that `generateDocumentation` is not that slow to justify a lose of safety.

> Another idea I have is to finally split the `detekt-rules` module into a module for each `RuleSetProvider`.
> detekt rule contributors are slowed down to the `detekt-rules:test` task which takes 1-1.5 minutes for each change...

Great idea! I like this one a lot! Maybe add these modules inside :detelt-rules so we can keep using `:detekt-rules:test` but it should run the tests in the modules that changed. I always use `./gradlew :detekt-rules:test` when I'm developing so improving this time would be great!

**Comment by cortinico** [comment]
> I think that generateDocumentation is not that slow to justify a lose of safety.

Agree with @BraisGabin. `generateDocumentation` is definitely not the bottleneck (at least not for now).

> detekt rule contributors are slowed down to the detekt-rules:test task which takes 1-1.5 minutes for each change... @schalkms @BraisGabin @cortinico what do you think?

Yeah this would be a great improvement 👍 
Every RuleSet should be already self contained so it shouldn't be that hard plus we can iteratively pull out every set one by one.
