### ISSUE TITLE
Clarify / document processors and console reports in config

### ISSUE THREAD

**Issue by erikhuizinga** [detekt/detekt#2833]
The default detekt config isn't very understandable to me, especially this part:

https://github.com/detekt/detekt/blob/26a78f56e9b295fae7acd6d79638891f343f9aa1/detekt-core/src/main/resources/default-detekt-config.yml#L15-L32

What do these processors do? What does the user gain by enabling/disabling them? I've tried enabling / disabling the processors one by one in a non-trivial project, but I could only find out what `DetektProgressListener` does. The user shouldn't need to config and run detekt to find out what certain config items do.

Also, the console reports aren't documented AFAIK. Some of the names are somewhat (but not entirely) self-explanatory, but not all are unambiguous. Especially for newcomers: what is the difference between a notification and a finding? And what's a file based finding?

### Suggestions

Do any of:

- Add a comment on every config line that explains the config, or links to documentation.
- Expand https://detekt.github.io/detekt/configurations.html#console-and-output-reports and https://detekt.github.io/detekt/configurations.html#processors with descriptions and examples of what these feature flags do.
- Clearly document that a default config exists, that it can be generated and where its features are documented.

---

Furthermore (but this is a different issue), _excluding_ processors / reports sounds like any new future processors/reports are enabled by default, unless explicitly excluded. This might introduce unnecessary processing / reporting after users upgrade detekt, which may negatively affect them (e.g. they might suddenly see reports on CI while they don't want that). It might make more sense to, instead, explicitly enable certain processors / console reports. That way it feels more like you actually configure what detekt does, instead of what it doesn't do. _It's counterintuitive to comment a line to enable it._

Do you want me to make a separate issue for this?

**Comment by cortinico** [comment]
> What do these processors do? What does the user gain by enabling/disabling them? I've tried enabling / disabling the processors one by one in a non-trivial project, but I could only find out what `DetektProgressListener` does

They do enable/disable the processors that runs during the analysis and collect statistics. If you comment/uncomment them you will see that those lines will appear/disappear:

![Screenshot 2020-07-04 at 01 11 42](https://user-images.githubusercontent.com/3001957/86500830-3af27880-bd94-11ea-90e0-2b751a4d8531.png)

> Add a comment on every config line that explains the config, or links to documentation.

Agree that the documentation on this part is lacking. We should probably provide a short doc for every Processor as we do for every Rule.

> Clearly document that a default config exists, that it can be generated and where its features are documented.

That's explained here: https://detekt.github.io/detekt/index.html#quick-start-with-gradle and here: https://detekt.github.io/detekt/configurations.html Maybe you can open a PR and provide some suggestions on how we can improve after your experience? That would be extremely valuable.

(that page is generated from this .md file https://github.com/detekt/detekt/blob/master/docs/pages/configurations.md)

> Do you want me to make a separate issue for this?

Ideally yes as what you're mentioning is related to how we locate `Processors` and is a bit unrelated to this issue that is more documentation related.

**Comment by erikhuizinga** [comment]
Thanks for your elaborate reply. I'll take some actions. I've created #2854 to extend the docs on configurations. I'll create a separate issue for my second point in the issue description.

**Comment by schalkms** [comment]
@erikhuizinga thanks again for the awesome contribution! Can you please list the missing bits to close this issue? Right now it's not quite clear, what's missing in order to complete this issue.

**Comment by erikhuizinga** [comment]
What is left for my initial unclarity about the config is an expansion of the [console reports docs](https://detekt.github.io/detekt/configurations.html#console-and-output-reports). Their uses are, to me as a detekt newcomer, still unclear.

Otherwise, this issue has been addressed completely.

**Comment by erikhuizinga** [comment]
Although, the cross-referenced comment by Artur seems to remove the need for such end-user docs. For now, the unclarity remains.

**Comment by schalkms** [comment]
Thanks for the detailed reply. I think this should also be commented in the source code.
