### ISSUE TITLE
ThrowingExceptionsWithoutMessageOrCause should be excluded in tests

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2836]
## Expected Behavior of the rule
This code should be allowed in test environments: `Single.error(Exception())`. This is just a fake. I don't care about the message. I just want to ensure that when an error is emitted I do whatever.

## Context
I already have the exclude in my config. But I think that it will have sense to add it as a default.

**Comment by schalkms** [comment]
That makes sense. Please update the default value in the `default-detekt-config.yaml` file.
