### ISSUE TITLE
Enable more rules by default

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2838]
The same idea as #1911 9 months later :P. All the rules that we add, we add them disabled by default. So we need to enable by default at some point. Any way we should be carefull here as artur say in the linked issue:

> No "highly subjective" rules should be enabled

I extracted a list of rules that I have enabled by default in my projects and I think that they are "safe":

- VarCouldBeVal
- UseRequire
- UseCheckOrError
- UnusedPrivateMember
- UnnecessaryLet
- UnnecessaryApply
- UnderscoresInNumericLiterals
- SerialVersionUIDInSerializableClass
- RedundantVisibilityModifierRule
- UnsafeCast
- UnnecessarySafeCall
- UnnecessaryNotNullOperator
- ImplicitDefaultLocale
- IgnoredReturnValue
- InvalidPackageDeclaration
- ThrowingExceptionsWithoutMessageOrCause
- SwallowedException
- RethrowCaughtException
- ExceptionRaisedInUnexpectedLocation

I'm not saying that we should enable all of these nor any of the others. This is just a first draft so we have a starting point to decide.

What do you think about these ones? Should we add some other?

**Comment by cortinico** [comment]
Imho I'll add to the list:

- NotImplementedDeclaration
- SpacingBetweenPackageAndImports
- UnusedImports
- UnnecessaryParentheses

Moreover we have several rules in the `exceptions` ruleset that are disabled (basically all of them but 2) such as:
- PrintStackTrace
- ThrowingNewInstanceOfSameException
- ReturnFromFinally
and others. 
Is there a reason why they're all disabled?

**Comment by BraisGabin** [comment]
I really like `UnnecessaryParentheses` (I have it active in all my projects) but I think that we shouldn't enable it by default in it's current behaviour. For example for things like #1592.

And I agree about the exception rules. They are good, I have all of them actived except `ThrowingExceptionInMain` because Android.

**Comment by schalkms** [comment]
@BraisGabin I think we should do this before v2.0. What do you think?

**Comment by BraisGabin** [comment]
I think that we have some real good and non controversial rules that we should enable by default for the new users.

We should balance good defaults and changes that could boder some current users that already cherry pick all that they want.

If I read it properly, we don't enable no battle tested rules by default. But after some versions we should be safe to enable them.

Maybe we could document a bit our process here.

**Comment by arturbosch** [comment]
I'm not sure if we wanted to enable all of these but these rules are only enabled in our analysis but not by default:

https://github.com/detekt/detekt/blob/d0734523bb133d429e465573706c2c1398ca33aa/config/detekt/detekt.yml#L136-L160
