### ISSUE TITLE
detekt-cli v1.10.0 intentionally not on maven central?

### ISSUE THREAD

**Issue by tmohme** [detekt/detekt#2842]
First of all: Thanks for the great work!

I'm using detekt in a maven environment (without the "unofficial" maven plugin) and can't find the current detekt-cli version 1.10.0 on maven central (the lates one is 1.10.0-RC1).
But I also can't find any hint that this distribution path is no longer supported.

Could you please clarify this?

**Comment by cortinico** [comment]
> Could you please clarify this?

Ping @arturbosch. I think that the sync between JCenter and Maven Central just failed or was never fired.

**Comment by arturbosch** [comment]
Thanks for letting us now. I manually synced version 1.10 to maven central. It should be up in the next hours.
