### ISSUE TITLE
TooManyFunctions should not penalize implementation if interface has too many methods

### ISSUE THREAD

**Issue by mehwhatever** [detekt/detekt#2843]
## Expected Behavior of the rule
TooManyFunction should ignore functions which are implementations of the interface.

## Context
Let's say I want to implement the ExecutorService interface, which has 12 methods, the implementation should not be penalized under the TooManyFunctions rule. 
If the interface is in the same project it would automatically break the ComplexInterface Rule

I propose to not count methods of a class which are specified by the interface.

**Comment by schalkms** [comment]
In my opinion it should. I remember that we discussed this issue already.
Why should it count also interface methods? One class could implement 5 interfaces with 5 functions each. This results in 25 functions. Each of those interfaces by its own is not complex. It doesn't get flagged by the `ComplexInterface` rule.
However, the class implementing 5 interfaces is complex.

**Comment by cortinico** [comment]
> However, the class implementing 5 interfaces is complex.

Agree here. Moreover Kotlin offers support for Interface Delegation that could help you refactor a class affected by this.

Finally, this rule has a `ignoreOverridden` config flag that you can use to exclude methods with the `override` modifiers from the functions count.

https://github.com/detekt/detekt/blob/09ff7fd7e114d0d3127b04b401e52d05eb206225/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/TooManyFunctions.kt#L34
