### ISSUE TITLE
Merge gradle groovy dsl and kotlin dsl documentation in the same page

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2846]
https://detekt.github.io/detekt/groovydsl.html and https://detekt.github.io/detekt/kotlindsl.html are really similar documentation. The only difference that we should have here is the code snippets. But if you check there are more (little) differences. 

What do you think about using tabs [as gradle does in its documentation](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block)? I'm not sure if Jekyll will allow us to do that.

**Comment by schalkms** [comment]
Good idea. That seems to be possible with the help of a plugin. See here for more information.
https://github.com/clustergarage/jekyll-code-tabs

**Comment by BraisGabin** [comment]
Closed by #2971
