### ISSUE TITLE
UnnecessaryNotNullOperator UnnecessarySafeCall UnsafeCallOnNullableType Not work 

### ISSUE THREAD

**Issue by lovejjfg** [detekt/detekt#2856]
## Expected Behavior

In my Demo , I quick Start with Gradle: https://detekt.github.io/detekt/#quick-start-with-gradle
and add this method to test the rules:
config:

    potential-bugs:
      active: true
      UnnecessaryNotNullOperator:
        active: true
      UnnecessarySafeCall:
        active: true
      UnsafeCallOnNullableType:
        active: true

code:

    fun foo(s: String) {
        val a = 1
        // UnnecessaryNotNullOperator
        val b = a!!
        // UnsafeCallOnNullableType
        val and = b!!.and(2!!)
        if (and!! > 0) {
            println("jahahaa")
        }
        val a1: String = ""
        // UnnecessarySafeCall
        val b1 = a1?.length
        println(b1)
        // UnnecessarySafeCall
    }

I expected Build failed

## Observed Behavior

BUILD SUCCESSFUL
![image](https://user-images.githubusercontent.com/10557477/87002935-40651e00-c1ed-11ea-8130-d2599f1730d5.png)

## Steps to Reproduce

    git clone https://github.com/lovejjfg/DetektTest.git
    cd DetektTest 
    ./gradlew clean detekt      
    

## Context

Android Project with gradle 5.6.4
## Your Environment

* Version of detekt used:1.10.0
* Version of Gradle used (if applicable):5.6.4
* Operating System and version: macOS 10.15.5
* Link to your project (if it's a public repository):
https://github.com/lovejjfg/DetektTest

**Comment by cortinico** [comment]
Hi @lovejjfg 
Thanks for the report and for the sample project you attached.

What I think you're experiencing is this the same as #2359 

Those three rules that you mentioned are all using types and symbol resolution. In the project you provided seems like this is not enabled so those rule will just not run.

Ideally this https://github.com/detekt/detekt/issues/2292 should also help you setup

**Comment by lovejjfg** [comment]
Thank you so much~~  
It's worked for My Demo now.😄
I wish you could provide the `Android Project` Simple in the future .

**Comment by lovejjfg** [comment]
By the way , There is also some warn hint :

    /MainActivity.kt:8:24: error: unresolved reference: synthetic
    import kotlinx.android.synthetic.main.activity_main.*
                        ^
    /MainActivity.kt:15:29: error: unresolved reference: toolbar
            setSupportActionBar(toolbar)
                                ^
    /MainActivity.kt:17:9: error: unresolved reference: fab
            fab.setOnClickListener { view ->
            ^
    /MainActivity.kt:17:34: error: cannot infer a type for this parameter. Please specify it explicitly.
            fab.setOnClickListener { view ->
                                    ^
    ....

What can I do to deal with ?

**Comment by AnDeacracht** [comment]
Running into the same problem, except I'm using the CLI (version 1.10.0) on Windows 10. The project I'm trying this out on is literally just a main method with the non-compliant code samples. Am I missing something?

**Comment by schalkms** [comment]
With the command line you can also set the mentioned attributes.
@AnDeacracht please have a look at the documentation especially at the attributes `jvm-target` and `classpath`.
https://arturbosch.github.io/detekt/cli.html#any-os
