### ISSUE TITLE
Detekt Formatting JAR packaging

### ISSUE THREAD

**Issue by arturdryomov** [detekt/detekt#2868]
Hello there.

Seems like the `io.gitlab.arturbosch.detekt:detekt-formatting` [specifies runtime dependencies](https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-formatting/1.10.0). However, the packaged JAR [seems to bundle its dependencies](https://github.com/detekt/detekt/blob/b6e88a95a11d21c0f4a9aef90455668a21de4060/detekt-formatting/build.gradle.kts#L22-L30). Also [the documentation states](https://detekt.github.io/detekt/extensions.html#let-detekt-know-about-your-extensions) that plugins need to be packaged as UberJARs.

All of this is a bit confusing. I was attempting to use the CLI API (the `--plugins` option) and spent some time thinking about the correct approach. If the plugin specifies dependencies — should I pass them as well? Is the documentation more correct than an IRL artifact? Am I confusing runtime dependencies with something else? 

I ran some experiments and seems like the formatting artifact is in fact an UberJAR. The question is — is this assumption correct and will be correct in the future? If so, is it possible to remove dependencies from the Maven metadata? Or I’m missing something?

**Comment by arturbosch** [comment]
> Hello there.
> 
> Seems like the `io.gitlab.arturbosch.detekt:detekt-formatting` [specifies runtime dependencies](https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-formatting/1.10.0). However, the packaged JAR [seems to bundle its dependencies](https://github.com/detekt/detekt/blob/b6e88a95a11d21c0f4a9aef90455668a21de4060/detekt-formatting/build.gradle.kts#L22-L30). Also [the documentation states](https://detekt.github.io/detekt/extensions.html#let-detekt-know-about-your-extensions) that plugins need to be packaged as UberJARs.

Hm, it should be safe to change this to `compileClasspath`: https://github.com/detekt/detekt/blob/befe2727ff02ad9fc34560fc1377b6dde1193631/detekt-formatting/build.gradle.kts#L24

> 
> All of this is a bit confusing. I was attempting to use the CLI API (the `--plugins` option) and spent some time thinking about the correct approach. If the plugin specifies dependencies — should I pass them as well? Is the documentation more correct than an IRL artifact? Am I confusing runtime dependencies with something else?

My intent when writing this was to always package plugins with all their dependencies as a UberJar.
Passing all your extension dependencies to `--plugins` should be safe too. In the end it is a `URLClassloader` and will get the job done I think :).

> 
> I ran some experiments and seems like the formatting artifact is in fact an UberJAR. The question is — is this assumption correct and will be correct in the future? If so, is it possible to remove dependencies from the Maven metadata? Or I’m missing something?

Yes, formatting will stay packaged. It is easier for us to remove all compiler dependencies from ktlint and make sure it runs in current detekt than expecting our users to deal with maybe conflicted dependencies.

Hope I've answered all your question, best regards.

**Comment by arturdryomov** [comment]
Thanks for the fast and thorough explanation! Feel free to close this issue or keep it open if you want to change the `detekt-formatting` packaging and use it as a reference.
