### ISSUE TITLE
Document Console and Output Reports

### ISSUE THREAD

**Issue by schalkms** [detekt/detekt#2869]
This should be documented on the following web page and in the source code.
https://detekt.github.io/detekt/configurations.html#console-and-output-reports

Successor of #2833

**Comment by sean-abbott** [comment]
using detekt 1.10 (` id("io.gitlab.arturbosch.detekt").version("1.10.0")`), and including the config stanza:
```
output-reports:
  active: true
  exclude:
  #  - 'HtmlOutputReport'
  #  - 'TxtOutputReport'
  #  - 'XmlOutputReport'
```

I get the following error:
```
$ ./gradlew detekt

> Task :jobs:detekt FAILED
Property 'output-reports' is misspelled or does not exist.

FAILURE: Build failed with an exception.
```

Also, the documentation shows this configuration is available, but the default config file linked from the documentation does not have it.

Finally, running without this stanza commented yields empty xml reports:
```
$ cat lib/build/reports/detekt/detekt.html
...
<h2>Complexity Report</h2>

<div>
  <ul>
    <li>224 lines of code (loc)</li>
    <li>169 source lines of code (sloc)</li>
    <li>130 logical lines of code (lloc)</li>
    <li>23 comment lines of code (cloc)</li>
    <li>32 cyclomatic complexity (mcc)</li>
    <li>9 cognitive complexity</li>
    <li>0 number of total code smells</li>
    <li>13% comment source ratio</li>
    <li>246 mcc per 1,000 lloc</li>
    <li>0 code smells per 1,000 lloc</li>
  </ul>
</div>

$ cat lib/build/reports/detekt/detekt.xml
<?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3">
</checkstyle
```

**Comment by schalkms** [comment]
@sean-abbott I moved your comment to a new issue.

**Comment by sean-abbott** [comment]
Thank you, sorry for misfiling...I'm new to detekt so I wasn't sure if this was user error or not.

**Comment by schalkms** [comment]
No worries..
This is issue here is rather a reminder to update the docs accordingly. May I ask you to submit your complete config in the other issue.
