### ISSUE TITLE
Detekt Deployment is missing Gradle Module files

### ISSUE THREAD

**Issue by cortinico** [detekt/detekt#2878]
## Expected Behavior
One of:
- Detekt `.module` files are available on Bintray/MavenCentral.
- Detekt's `pom` file shouldn't contain the Gradle Module marker: `<!--  do_not_remove: published-with-gradle-metadata  -->`

## Observed Behavior
Currently we have published `pom` files that contains the `<!--  do_not_remove: published-with-gradle-metadata  -->` marker for all the modules ([see here](https://repo1.maven.org/maven2/io/gitlab/arturbosch/detekt/detekt-core/1.10.0/detekt-core-1.10.0.pom)).

## Steps to Reproduce
Module files are missing for all the modules ([you can check it here](https://repo1.maven.org/maven2/io/gitlab/arturbosch/detekt/)).

The effective impact of this is probably what was reported in this comment https://github.com/detekt/detekt/pull/2814#issuecomment-659239216

## Context
I did some investigation and seems like the issue is that the gradle-bintray-plugin is failing to publish `.module` files: https://github.com/bintray/gradle-bintray-plugin/issues/229

Given that we are applying both `gradle-bintray-plugin` and `maven-publish` (for publishing on artifactory), my suggestion is that we drop the `gradle-bintray-plugin` as we use only `maven-publish` for publishing (to hit bintray/artifactory).

**Comment by arturbosch** [comment]
I would love to use only `maven-publish`!
The bintray plugin has some annoying bugs and looks unmaintained.
