### ISSUE TITLE
Detekt gradle command line parameter overwriting configuration

### ISSUE THREAD

**Issue by marcorighini** [detekt/detekt#2880]
## Expected Behavior
Be possible to overwrite the detekt autocorrect flag, defined in detekt block in the gradle file, with a command line gradle task parameter. Example: `./gradlew detekt -PautoCorrect=true`.

It would be useful to make possible to overwrite all the config parameters passed to the gradle task from command line.

Reference: https://kotlinlang.slack.com/archives/C88E12QH4/p1594983188219800

## Current Behavior
Expected behavior cannot be achieved

## Context
We need to run detekt without autocorrect in CI but we want a quick way to run detekt with autocorrect locally (without modifying the detekt block in the gradle file).

**Comment by cortinico** [comment]
Thanks for reporting @marcorighini 

One thing we could do is annotate all the properties in https://github.com/detekt/detekt/blob/master/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/Detekt.kt with a `@Option` annotation, like this:

https://github.com/cortinico/kotlin-gradle-plugin-template/blob/41b0a8e19ded0f4a8e76900eabeb4cd7687d0141/plugin-build/plugin/src/main/java/com/ncorti/kotlin/gradle/template/plugin/TemplateExampleTask.kt#L21-L23

This will make possible to configure the detekt task from the command line.
I don't know if we want to follow this path as we have several properties on the Gradle task, and those should ideally be kept in sync with `detekt-cli` to avoid inconsistencies. Moreover, some of our properties (e.g. `debug`) overrides the Gradle default flags (I don't know if you can do something like `gw detekt --debug=true --debug` but that would look weird anyway).

Anyway, you can probably use a Gradle Project Property and configure it using the `-P` option.

**Comment by BraisGabin** [comment]
I don't think that we should support all of them. But this one have a lot of sense. You want to change this value lots of times

But we could add the flag or we could create a different task like ktlint gradle plugin. They have `ktlintCheck` and `ktlintFormat`. It seems more natural than a flag.

**Comment by arturbosch** [comment]
Hm, this can already be done with custom properties: `autoCorrect = System.getProperty("autoCorrect") ?: false`.
Wouldn't  this be enough?
Or you could register a custom task which has the autocorrect already in the name.

**Comment by marcorighini** [comment]
Agree, it can be done with a custom property.
But main idea was to provide a way to make it easier because it's a typical recurring action. A new gradle task `detektFormat` seemed a clean solution.

**Comment by schalkms** [comment]
We have already discussed this in an earlier thread and decided to go on with the mentioned solution in Artur’s post. I don’t think we should change the strategy here. Hence, I‘ll close this.

**Comment by schalkms** [comment]
Reference #2705

**Comment by yitzLefkowitz** [comment]
I know that this is closed, I am genuinely wondering about the pushback to the seemingly reasonable suggestions of @marcorighini . In my case we do not want autocorrect to run, unless the user specifically and intentionally runs it (locally), which means that we dont want the user to have to change some global config. We can register a custom gradle task, however the custom task doesnt have the detekt extension what makes some of the configurations (for example toolVersion) a pain. Not to mention that means that need to duplicate the rest of the detekt configs.

**Comment by cortinico** [comment]
> I know that this is closed, I am genuinely wondering about the pushback to the seemingly reasonable suggestions of @marcorighini . In my case we do not want autocorrect to run, unless the user specifically and intentionally runs it (locally), which means that we dont want the user to have to change some global config. We can register a custom gradle task, however the custom task doesnt have the detekt extension what makes some of the configurations (for example toolVersion) a pain. Not to mention that means that need to duplicate the rest of the detekt configs.

See my other answer here https://github.com/detekt/detekt/blob/d627b9018b59161ef593729225d5fede994e708a/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/extensions/DetektExtension.kt#L43
