### ISSUE TITLE
Migration to 1.10.0 Jenkins lint issue

### ISSUE THREAD

**Issue by komissarovdenis** [detekt/detekt#2881]
Hey! After migration from to 1.10.0 have faced with this issue about missing of `kotlinx-html-jvm`. Could you navigate me what's may be wrong, please?

jcenter() used as a repo

`* What went wrong:
  Could not determine the dependencies of task ':xxx:detekt'.
  > Could not resolve all task dependencies for configuration ':xxx:detekt'.
     > Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.1.
       Searched in the following locations:
         - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/kotlinx-html-jvm-0.7.1.pom
         - https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/kotlinx-html-jvm-0.7.1.pom
         - https://zendesk.jfrog.io/zendesk/repo/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/kotlinx-html-jvm-0.7.1.pom
         - https://dl.bintray.com/paystack/maven/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/kotlinx-html-jvm-0.7.1.pom
         - https://jitpack.io/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/kotlinx-html-jvm-0.7.1.pom
         - https://dl.bintray.com/qameta/maven/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/kotlinx-html-jvm-0.7.1.pom
         - https://developer.huawei.com/repo/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/kotlinx-html-jvm-0.7.1.pom
       Required by:
           project :xxx > io.gitlab.arturbosch.detekt:detekt-cli:1.10.0 > io.gitlab.arturbosch.detekt:detekt-core:1.10.0 > io.gitlab.arturbosch.detekt:detekt-report-html:1.10.0`

**Comment by ts-twt** [comment]
I'm facing the same issue - even with older versions.

Seems to be a jCenter issue.
For some reason, `kotlinx-html-jvm:0.7.1` is not listed there anymore
https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-html-jvm?repo=jcenter

However, as a workaround, you can also pull the dependency from the spring plugins repository:
```
maven { url 'https://repo.spring.io/plugins-release/' }
```

It's at least a _temporary_ workaround which works.

**Comment by cortinico** [comment]
Thanks for the report. I'm closing this one since I've opened #2882. We will use that to track the issue and provide status updates. In the meanwhile please use the workaroud suggested in that ticket description.
