### ISSUE TITLE
kotlinx-html-jvm is missing on JCenter

### ISSUE THREAD

**Issue by cortinico** [detekt/detekt#2882]
## Expected Behavior
Detekt should work correctly with the configuration provided in the Readme.

## Observed Behavior
Builds are failing as the package kotlinx-html-jvm seems to be missing on JCenter. Here the error message:

```
> Could not resolve all task dependencies for configuration ':<REDACTED>:detekt'.
   > Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.1.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/kotlinx-html-jvm-0.7.1.pom
       - ...
```

## Steps to Reproduce
Try to build detekt (make sure you wipe your artifact cache before).

## Current Workaround

Please include the following block in your Gradle configuration:
```
repositories {
    maven {
        url  "https://kotlin.bintray.com/kotlinx" 
    }
}
```
The kotlinx-html-jvm artifact is correctly hosted there: https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/

**Comment by cortinico** [comment]
Here the upstream issue: https://github.com/Kotlin/kotlinx.html/issues/151

**Comment by BraisGabin** [comment]
This is fixed now, right?

**Comment by cortinico** [comment]
> This is fixed now, right?

Yes it's fixed. The dependency has been re-linked on JCenter.
