### ISSUE TITLE
IgnoredReturnValue false positive

### ISSUE THREAD

**Issue by vladimirfx** [detekt/detekt#2890]
## Expected Behavior
Issue should not be reported on chained method call.

## Observed Behavior
IgnoredReturnValue reported for code:

        assertThat(debtor.devicesDebtors)
            .filteredOn { it.device == device1 }
            .extracting(Function<DevicesDebtors, Boolean> { it.isOwned })
            .containsOnly(true)

Method `extracting` marked with `@CheckReturnValue` but it result used on next method call in chain.

## Your Environment
* Version of detekt used: 1.10.0
* Version of Gradle used (if applicable): 6.5.1

**Comment by cortinico** [comment]
Thanks for the report. That's a false positive on chained statements. The fix is in #2895
