### ISSUE TITLE
The tests are slow

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2902]
The tests take around 25 seconds to start running an example:

![Grabación de pantalla 2020-07-27 a las 22 24 51](https://user-images.githubusercontent.com/721244/88588883-8a0c9000-d058-11ea-8eed-78c650e479a9.gif)

It's not a complete record but you get the idea. Why does it take more than 20 seconds to test `:detekt-report-xml`?

**Comment by cortinico** [comment]
> The tests take around 25 seconds to start running an example:

Same. I thought it was a misconfiguration of mine, but apparently not.
@arturbosch was doing profiling so maybe has more insights on this

**Comment by schalkms** [comment]
The same holds true on my machine.

**Comment by arturbosch** [comment]
I've noticed the same recently.
Even running `:detekt-report-xml:test` without any `detekt-test` dependencies/accidentally creating `KtCompiler` the test discovery is slow.

```
 g/r/detekt/detekt-report-xml{} $ gradle cleanTest test -x :detekt-gradle-plugin:test -Dorg.gradle.caching=false -Dorg.gradle.unsafe.watch-fs=false -Dorg.gradle.parallel=false       4s 776ms
```

**Comment by arturbosch** [comment]
I've migrated the report-xml and report-txt module tests to junit jupiter test engine and the test discovery got reduced by 2 seconds (https://github.com/detekt/detekt/pull/new/debug-tests):

With `Spek`:

https://scans.gradle.com/s/mdxkbujmuzqw4/tests

![2020-07-30-112828_992x416_scrot](https://user-images.githubusercontent.com/20924106/88906587-e7226480-d257-11ea-8e66-391dc75b925f.png)

With Junit Jupiter: 

https://scans.gradle.com/s/udwjw43v5ravw/tests

![2020-07-30-112936_848x399_scrot](https://user-images.githubusercontent.com/20924106/88906691-09b47d80-d258-11ea-9934-2a463fc4ffb8.png)

**Comment by arturbosch** [comment]
#2921 introduces many improvements.

The big penalty for us still is and will be: kotlin environment first inits (2s) + mockk first inits (2s) in many modules (multiplier) building in parallel (slowing down each other).

**Comment by BraisGabin** [comment]
> #2921 introduces many improvements.
> 
> The big penalty for us still is and will be: kotlin environment first inits (2s) + mockk first inits (2s) in many modules (multiplier) building in parallel (slowing down each other).

At least the really fast tests that don't need does things will run fast. This will help to keep more threads free or don't the real work. 

2s for mockk? We don't need nearly any mock. I vote to remove them and write fakes.

**Comment by schalkms** [comment]
Maybe we could use another mocking library.
This are the results from a quick search.

```bash
➜  detekt git:(master) grep -R -I "mockk" .
./detekt-report-html/src/test/kotlin/io/github/detekt/report/html/HtmlOutputReportSpec.kt:import io.mockk.every
./detekt-report-html/src/test/kotlin/io/github/detekt/report/html/HtmlOutputReportSpec.kt:import io.mockk.mockk
./detekt-report-html/src/test/kotlin/io/github/detekt/report/html/HtmlOutputReportSpec.kt:    val ktElementMock = mockk<KtElement>()
./detekt-report-html/src/test/kotlin/io/github/detekt/report/html/HtmlOutputReportSpec.kt:    val psiFileMock = mockk<PsiFile>()
./detekt-bom/build.gradle.kts:        api("io.mockk:mockk:1.10.0")
./docs/pages/changelog 1.x.x.md:- Introduces mocking library 'mockk' - [#2055](https://github.com/detekt/detekt/pull/2055)
./buildSrc/src/main/kotlin/commons.gradle.kts:        testImplementation("io.mockk:mockk")
./detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineFilteredResultSpec.kt:import io.mockk.every
./detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineFilteredResultSpec.kt:import io.mockk.mockk
./detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineFilteredResultSpec.kt:        val finding = mockk<Finding>()
./detekt-metrics/src/test/kotlin/io/github/detekt/metrics/ComplexityReportGeneratorSpec.kt:import io.mockk.every
./detekt-metrics/src/test/kotlin/io/github/detekt/metrics/ComplexityReportGeneratorSpec.kt:import io.mockk.mockk
./detekt-metrics/src/test/kotlin/io/github/detekt/metrics/ComplexityReportGeneratorSpec.kt:            val finding = mockk<Finding>()
```

**Comment by cortinico** [comment]
> Maybe we could use another mocking library.

Adding this as it's relevant for the discussion: https://github.com/mockk/mockk/issues/13
I'm using Mockk in another project and so far I'm not slowed down by perfs. But in our case test spin up time seems to be a significant bottleneck so we should probably investigate using mockito or something else.

**Comment by arturbosch** [comment]
Imo we can safely remove mockk in our three uses due to the discovery of Gradle test fixtures :D

I think we only use it to mock Finding or Entity.

Note only the first usage of mocking is slow, after it's loaded it is okay.
If we safe a lot of work with mocking, mocking is the way. If it slows down starting a single test in debugging -> let's remove mocking
