### ISSUE TITLE
v1.10.0: Property 'naming>IsPropertyNaming' is misspelled or does not exist.

### ISSUE THREAD

**Issue by Mygod** [detekt/detekt#2926]
## Expected Behavior

Does not crash with https://raw.githubusercontent.com/detekt/detekt/v1.10.0/detekt-core/src/main/resources/default-detekt-config.yml

## Observed Behavior

```
Property 'naming>IsPropertyNaming' is misspelled or does not exist.
Run failed with 1 invalid config property.
```

## Steps to Reproduce

Run detekt on default detekt config.

## Your Environment

* Version of detekt used: https://github.com/detekt/detekt/releases/download/v1.10.0/detekt
* Version of Gradle used (if applicable): n/a
* Operating System and version: Ubuntu
* Link to your project (if it's a public repository): n/a

**Comment by arturbosch** [comment]
`IsPropertyNaming` was removed just before the release of 1.10.0.
Seems like the config for it is inside the tagged version but not in the release jar.
If you copy-pasted the default config from the tag and used the uploaded jar the property is unknown to detekt.
Will think about how to further automate the release process.

This is fixed now in 1.11-RC1.
