### ISSUE TITLE
UnsafeCallOnNullableType does not work even whit custom gradle task setting jvmTarget and classpath

### ISSUE THREAD

**Issue by chriskn** [detekt/detekt#2930]
## Expected Behavior
Custom gradle tasks with defined jvmVersion and classpath like described in #2259 and the documentation should check for UnsafeCallOnNullableType and other issues related to the type system. 

## Observed Behavior
UnsafeCallOnNullableType issues are not reported for custom task with jvmVersion and classpath set

## Steps to Reproduce
I tried to define a custom task (detektAll) and to edit the existing detekt task
Here is an example task definition: 
```
detekt {
    toolVersion = DependencyVersions.Detekt
    debug = true
    parallel = true
    autoCorrect = true
    input = files("src/main/kotlin")
}

tasks.withType<Detekt> {
    jvmTarget = "1.8"
    classpath.setFrom(project.configurations.getByName("detekt"))
    exclude("**/ignore/**")
}

val detektAll by tasks.registering(Detekt::class) {
    description = "Runs over whole code base without the starting overhead for each module."
    parallel = true
    buildUponDefaultConfig = true
    include("**/*.kt")
    exclude("**/resources/**")
    exclude("**/build/**")
    exclude("**/*.kts")
    exclude("**/ignore/**")
    // baseline.set(file("$rootDir/config/detekt/baseline.xml"))
    classpath.setFrom(project.configurations.getByName("detekt"))
    reports {
        xml.enabled = false
        html.enabled = false
        txt.enabled = false
    }
}
```

and here the example code which should trigger the issue

```
fun useUnsafeSubstring() {
    val unsafeCallResult = unsafeSubstring("detektTest")
    print(unsafeCallResult!!.capitalize())
}

```
When I run detektMain UnsafeCallOnNullableType is reported. When I run detekt or detektAll UnsafeCallOnNullableType is not reported. See full example project here: https://github.com/chriskn/detekt-example 

## Context
I am running detekt using gradle (kotlin). 
I am trying to archive the same checks that the detektMain and detektTests task do while excluding a specific folder.
Since I was not able to override detektMain and detektTest (is this possible somehow?) and to exclude a folder, I tried to define my own task with classpath and jvmVersion.  Unfortunately, my custom task does not report UnsafeCallOnNullableType issues while detektMain reports them. 
I know there are a lot of issues regarding this topic like #2259, #2038 or #2856 . But none of them helped me to fix this issue.

## Your Environment
* Version of detekt used: 1.10.0
* Version of Gradle used (if applicable): 6.3
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): https://github.com/chriskn/detekt-example

**Comment by arturbosch** [comment]
Hey,
could you try to change 

```kotlin
tasks.withType<Detekt> {
    jvmTarget = "1.8"
    classpath.setFrom(project.configurations.getByName("detekt"))
    exclude("**/ignore/**")
}
```

to 

```kotlin
tasks.withType<Detekt>.configureEach {
    jvmTarget = "1.8"
    classpath.setFrom(project.configurations.getByName("detekt"))
    exclude("**/ignore/**")
}
```

I guess `register` is lazy and `withType` is eager so your task is not overwritten with these options.

**Comment by chriskn** [comment]
Thanks, it works now. But I have to remove the `exclude` to avoid compilation errors, which makes sense with the current configuration

Is there a way to exclude all issues/rules for specific folders?
Exclude the folder for each rule inside the configuration would work but isn't very convenient.

**Comment by schalkms** [comment]
Closing this now, since the original question was answered.
