### ISSUE TITLE
Support stdin/stdout processing

### ISSUE THREAD

**Issue by ZacSweers** [detekt/detekt#2937]
## Expected Behavior
We'd like to be able to use https://github.com/hallettj/git-format-staged with detekt, but it requires a stdin input format

## Current Behavior
Detekt only supports file inputs

## Context
See expected behavior

**Comment by schalkms** [comment]
Thanks for the feedback and new ideas!
Would you want to use the ktlint formatting integration of detekt with this tool or the detekt native rules?
Could **git-format-staged** also support files as input parameter?

**Comment by BraisGabin** [comment]
Some of the "detekt native rules" would not work in this case because we need type solving. Would this be ok?

**Comment by ZacSweers** [comment]
I think supporting a subset is fine. For ktlint - we actually run it separately for formatting. We just also run detekt as a commit hook to catch errors early rather than on CI

**Comment by schalkms** [comment]
Having #2936 in mind, we shouldn't support another potential input format. Static analyzers need more context than a single file or a few lines for sophisticated analysis. This creates more problems than it solves.
We have had this discussion in #2320 and in the referenced threads.

I'm not sure, why the mentioned tool doesn't support files as input.
However, one could also redirect stdin to a file and then let detekt analyze it. So fortunately there is an existing solution for that.

**Comment by schalkms** [comment]
Closed due to the mentioned existing solution and the discussion in the linked issue, which lead to a clear decision.
