### ISSUE TITLE
Suggest rule: Class cannot be publish.

### ISSUE THREAD

**Issue by VovaStelmashchuk** [detekt/detekt#2943]
I suggest add rule: Class cannot be publish.

I need the rule in the following case: Inside library and i want to sure all my class are internal or private, exclude API classes. We have this rule in custom company rule set. We want to contribute the rule to origin project, like an optional rule. Maybe someone need this rule too.

Are rule valid to be in the origin project?

We already discussed issue in KtLint https://github.com/pinterest/ktlint/issues/795
I migrate my project to Detekt at the moment.

**Comment by arturbosch** [comment]
Hi @VovaStelmashchuk ,
this sounds like a really good rule for library authors, thanks for the suggestion.
You can take a look at the `LibraryCodeMustSpecifyReturnType` rule how we achieved to only run the rule if specific filters are active.
This is how we expect the users to configure it:
https://github.com/detekt/detekt/blob/66c9afeac2f5c2adf743b09d80b88ad3c1338301/config/detekt/detekt.yml#L119 

Looking forward to your PR!
