### ISSUE TITLE
Standard Gradle detekt tasks do not consider test sources

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#2956]
## Expected Behavior
Plugin rules should be run.

## Observed Behavior
There is a difference between running `gradle detekt` for all projects or just `gradle detektAll`.
We have a lot of unfixed formatting issues. Now with the new ruleset from https://github.com/detekt/detekt/pull/2954 it gets obvious that something is wrong.

## Steps to Reproduce
Run `detektAll` with https://github.com/detekt/detekt/pull/2954 and find a lot of issues which do not get reproted by `detekt`. 

## Context
Plugin authors.

**Comment by arturbosch** [comment]
Rule sets get loaed and rules get executed:

![2020-08-09-215302_828x252_scrot](https://user-images.githubusercontent.com/20924106/89740652-e628d880-da8a-11ea-80b7-6f3418efb76b.png)
![2020-08-09-214801_476x113_scrot](https://user-images.githubusercontent.com/20924106/89740654-e6c16f00-da8a-11ea-9066-8d6e6347c61d.png)

**Comment by arturbosch** [comment]
detekt core works as expected.
The Gradle plugin does not consider test sources by default:

https://github.com/detekt/detekt/blob/ccc727adbbefe38e254c0e6edef01f36bfd63089/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt#L115-L118

https://github.com/detekt/detekt/blob/ccc727adbbefe38e254c0e6edef01f36bfd63089/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/extensions/DetektExtension.kt#L26-L27

https://github.com/detekt/detekt/blob/ccc727adbbefe38e254c0e6edef01f36bfd63089/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/extensions/DetektExtension.kt#L46-L47

This is a bug but fixing this could lead to many new findings for users.
We should probably mention this in the release notes and fix this for 2.0 ?

**Comment by cortinico** [comment]
> We should probably mention this in the release notes and fix this for 2.0 ?

That would be the preferred way imho

**Comment by arturbosch** [comment]
> I think that this is not a breaking change. Every time you update detekt you get new issues and that's expected by the user: we add new rules and fix false positives/negatives. The number of issues depends on your code base, for example the last update of `MandatoryBracesIfStatements` generated a lot of **desired** issues in my project.
> 
> I would fix it and add a note in the changelog: "Fixed this bug, if you want the previous behavior add `exclude ...`."

Yes, that's true. I totally agree on the rule level.
We fix one rule -> some issues in your code base.
We fix this for test sources -> like 50% of your code base was not tested -> huge number of new issues.
detekt has like 45k lines of code, 30k are just test code :)

**Comment by BraisGabin** [comment]
That make sense. I must say that I have the tests in my project since the begging. I thought it was a problem with detekt-gradle-plugin and Android.

**Comment by arturbosch** [comment]
> That make sense. I must say that I have the tests in my project since the begging. I thought it was a problem with detekt-gradle-plugin and Android.

`detektMain`, `detektTest` etc have them. The default plain `detekt` task just runs over only the main sources.

**Comment by krzema12** [comment]
In 1.17.0 test sources are analyzed by default, see PR https://github.com/detekt/detekt/pull/3649. I think this issue can be resolved.

**Comment by BraisGabin** [comment]
Could you provide a reproducer?

**Comment by SPConlin** [comment]
I cannot share the repo, but I have a repository of automated tests. If I run detekt from the Gradle plugin, I get a no issues reported but when I run detektTest it returns 200+ issues. I verified the configurations are correct.

**Comment by BraisGabin** [comment]
I just added this code to a test in the detekt project: `class A {}` and I runned `./gradlew detekt` and I got two issues, so I can't reproduce your issue. Without a way of reproduce it I can't help you.

And it's normal to run `./gradlew detekt` and doesn't get any issue but get issues when running `./gradlew detektTest`. The second one runs detekt with type solving. That enables multiple rules that `./gradlew detekt` just can't run.

If you use type solving you should always run `./gradlew detektMain detektTest`. There isn't a unique task right now to run both. A lot of users create a task `detektAll` that is like an alias for `detektMain detektTest`.
