### ISSUE TITLE
Suggest a new param for LongParameterList

### ISSUE THREAD

**Issue by VovaStelmashchuk** [detekt/detekt#2965]
I suggest to add a new param: ignorePrivateConstructors for rule LongParameterList. We can create a PR. Are changes can be part of project ?

**Comment by schalkms** [comment]
May I ask you why a user would want to ignore a private constructor from this rule? Why should this be good practice to have a private constructor with many parameters?

**Comment by schalkms** [comment]
Furthermore, there’s already a config option called **constructorThreshold** that does exactly what you want.

**Comment by VovaStelmashchuk** [comment]
I want to keep one threshold for public and internall constructor and turn off the rule for private constructor. 
I catch your point about good practice, maybe you are right many arguments in any constructor is a bad practice.

In our case i have the problem with rule, because we implement DI without library, and we have private constructors with many argumnets.

**Comment by schalkms** [comment]
It’s kind of strange that the length of the parameter list depends on the visibility of a constructor. If you have a long parameter list in the constructor, it’s a sign that the given class depends on many other classes.

I think there some options available in your case.
1. Disable the config option regarding constructors
2. Enable the config option and use an Ignore annotation for the private constructor with many arguments.
3. Use a higher value for the threshold
4. Copy the rule over to a custom detekt rule and implement your constraint there. https://detekt.github.io/detekt/extensions.html
