### ISSUE TITLE
Make a release built against Kotlin 1.4

### ISSUE THREAD

**Issue by sschuberth** [detekt/detekt#2974]
## Context

[Kotlin 1.4 was released](https://blog.jetbrains.com/kotlin/2020/08/kotlin-1-4-released-with-a-focus-on-quality-and-performance/) and we'd like to update to it, but we cannot as the compiler would [issue a warning](https://ci.appveyor.com/project/oss-review-toolkit/ort/builds/34691834#L852) (and we break on warnings) due to *detekt* being built against Kotlin 1.3.72, and [we cannot enforce Kotlin 1.4 due to this issue](https://github.com/detekt/detekt/issues/2501#issuecomment-614051994).

**Comment by arturbosch** [comment]
Getting rid of the warning will also require a new Gradle release, won't it?

Kotlin 1.4 support is on the way (https://github.com/detekt/detekt/pull/2931). Unfortunately we are blocked by https://github.com/pinterest/ktlint/issues/830.

**Comment by sschuberth** [comment]
> Getting rid of the warning will also require a new Gradle release, won't it?

Hmm, that triggers a good question for me: I actually don't want to enforce the Kotlin version on the Gradle / pluging classpath, but only on our app's compile classpath. So maybe the `.all` in

    configurations.all {
        resolutionStrategy {
            // ..
        }
    }

simply is too broad and affects the plugin classpath, too... I need to look into this.

**Comment by realdadfish** [comment]
Buildscript (plugin) and project classpath is separated (mostly), however, certain plugins (like e.g. the kotlin allopen plugin) might require the same Kotlin version on both classpaths.

In any case, your issue @sschuberth  might be resolved by this:

```kotlin
  configurations.all {
        resolutionStrategy.eachDependency {
            if (requested.group == "org.jetbrains.kotlin" && requested.name == "kotlin-reflect") {
                useVersion("1.4.0")
            }
        }
    }
```

Most likely because some runtime dependency pulls in kotlin-reflect transitively (moshi-kotlin e.g. does it).

**Comment by sschuberth** [comment]
Thanks @realdadfish for the idea. I'm doing something similar but more *detekt*-specific currently, see

https://github.com/oss-review-toolkit/ort/commit/6976ae0d3d36eb60990fc7d4de98f765ac221875#diff-392475fdf2bc320d17762ed97109a121R176
