### ISSUE TITLE
 1.10.0 to 1.11.0 | Could not find org.spekframework.spek2:spek-dsl-jvm

### ISSUE THREAD

**Issue by BrunoTrovoN26** [detekt/detekt#2976]
After migrating from 1.10.0 to 1.11.0, I'm seeing the issue below:

```
* What went wrong:
Execution failed for task ':library:my_detekt:compileTestKotlin'.

> Could not resolve all files for configuration ':library:my_detekt:testCompileClasspath'. 
> Could not find org.spekframework.spek2:spek-dsl-jvm:.
Required by:
project :library:my_detekt > io.gitlab.arturbosch.detekt:detekt-test:1.11.0 > io.gitlab.arturbosch.detekt:detekt-test-utils:1.11.0

```
Did I miss anything during migration?

**Comment by arturbosch** [comment]
Hi @BrunoTrovoN26 ,
we had some test discovery performance issues and solved them together with the Spek maintainer.
Currently we are on an alpha release of Spek which unfortunately `detekt-test` depends on. 

A workaround is to add `maven { setUrl("https://dl.bintray.com/spekframework/spek-dev") }` to your build or wait for a new release with https://github.com/detekt/detekt/pull/2922 fixed.
