### ISSUE TITLE
Wrong logic in io.gitlab.arturbosch.detekt.api.internal.PathFilters#isIgnored

### ISSUE THREAD

**Issue by pe4enko** [detekt/detekt#2978]
## Expected Behavior

I'm use detekt-cli with options 

```
./detekt \
--baseline /config/detekt/baseline.xml \
--config /config/detekt/detekt.yml  \
--includes "**/*.kt" \
--excludes "**/resources/**;**/build/**;**/.gradle/**;**/.mvn/**;**/.git/**;**/.idea/**;**/target/**" \
--input /my-project \
--parallel
```

but the excludes option not working correct, because detekt check if path includes and not check excludes option

```
fun isIgnored(path: Path): Boolean {

        fun isIncluded() = includes?.any { it.matches(path) }
        fun isExcluded() = excludes?.any { it.matches(path) }

        return isIncluded()?.not() ?: isExcluded() ?: true
    }
```
Exludes and includes option should check together at the same time, not only if includes is null.

## Observed Behavior

Detekt check only isIncluded and do not use isExcluded

**Comment by arturbosch** [comment]
Hi,
our includes/excludes works as follows:
`**/*.kt` is the default. All kotlin files get analyzed by default.
Then `excludes` get evaluated.
If you have a broad `exclude`, you can `include` some specific files e.g.:

```
--excludes **/generated-src/**
--includes  **/generated-src/**/NeedsCheck.kt
```

This will exclude everything inside `generated-src` except `NeedsCheck.kt`.

For you it should be enough to remove the `includes` flag.

**Comment by pe4enko** [comment]
Ok, thanks. 
1. By default detekt checks not only *.kt files but also *.kts files too.
2. "Include/exclude"  logic differs from the one used when running through gradle. I have configuration when using gradl 
```
val detektAll by tasks.registering(io.gitlab.arturbosch.detekt.Detekt::class) {
    description = "Запускаем проверки на всем проекте сразу"
    parallel = true
    buildUponDefaultConfig = true
    setSource(file(rootDir))
    //config.setFrom(listOf(statisticsConfigFile, configFile))
    config.setFrom(listOf(file("$rootDir/config/detekt/detekt.yml")))
    baseline.set(file("$rootDir/config/detekt/baseline.xml"))
    include("**/*.kt")
    //include("**/*.kts")
    exclude("**/resources/**")
    exclude("**/build/**")
    exclude("**/.gradle/**")
    exclude("**/.mvn/**")
    exclude("**/.git/**")
    exclude("**/.idea/**")
    exclude("**/*.fill.kt")
    exclude("**/target/**")
    exclude("**/fssp-portal/**")
    exclude("**/fssp-deployment/**")
    exclude("**/oktmo-*/**")
    reports {
        xml.enabled = false
        html.enabled = false
        txt.enabled = false
    }
}
```
I use include "**/*.kt" and i don't need exclude **/.kts files. 

3. Ok i'm add exclude for detekt-cli command for **.kts files, thanks

**Comment by arturbosch** [comment]
Yes, the `include` and `exclude` comes from the Gradle `SourceTask` api.
They filter the paths for you and pass a list of all files to detekt.
