### ISSUE TITLE
Baseline adds file path instead package

### ISSUE THREAD

**Issue by kuFEAR** [detekt/detekt#2985]
## Expected Behavior
\<ID>MaximumLineLength:com.example.app.di.Module.kt:23\</ID>

## Observed Behavior
\<ID>MaximumLineLength:com.example.app.di./Users/nikitakarnaukh/Develop/android/application/example/app/src/main/java/com/example/app/di/Module.kt:23\</ID> 

## Steps to Reproduce
DetektCreateBaselineTask with configured baseline file and with warning in code by rule `MaximumLineLength` adds

## Context
I can run detekt tasks on another machines(CI/colleges)

## Your Environment
CI/local macbook pro 15
* Version of detekt used: 1.11.0
* Version of Gradle used (if applicable): 6.6
* Operating System and version: osx 10.15.6
* Link to your project (if it's a public repository): none

**Comment by BraisGabin** [comment]
detekt only works with files, doesn't work with packages. And, for example, `MaximumLineLength:com.example.app.di.Module.kt:23` is not a path. And it's not a fully qualified name (it have `.kt`) And what's the line number 23 of a class? starts at the beggining of the file or at the begging of the class declaration? It's really messy. For that reason it's safer to only work with paths.

Any way... is this `MaximumLineLength:com.example.app.di./Users/nikitakarnaukh/Develop/android/application/example/app/src/main/java/com/example/app/di/Module.kt:23` a real output of detekt? I don't use the formatting plugin so I can't test it easily. But, if it is, it really seems strange.

**Comment by radzio** [comment]
I have same issue, it troubles me because this path can be different between dev envs and ci/cd

**Comment by kuFEAR** [comment]
I've faced with this behavior only on MaximumLineLength rule, another rules works ok

number 23 it's just example, it's line with code which reach limits (120 chars)

**Comment by radzio** [comment]
It seems that it happens in 1.11.1, in 1.10.0 everything is ok

**Comment by arturbosch** [comment]
Thanks for the report! I will look into this and release a bug fix release asap.
