### ISSUE TITLE
Rules with mixed behavior based on Type resolution

### ISSUE THREAD

**Issue by cortinico** [detekt/detekt#2994]
We do have several rules that have a mixed behavior (i.e. perform more checks or more detailed analysis) based on wether Type resolution is enabled or not.

This is a non-exhaustive list (current list can be found by looking for `@Suppress("ViolatesTypeResolutionRequirements")`):

- [x] `ImplicitDefaultLocale` #6344
- [x] `MapGetWithNotNullAssertionOperator` #6345 
- [x] `InstanceOfCheckForException` #6346 
- [x] `MemberNameEqualsClassName` #6347 
- [x] `SpreadOperator` #6351
- [x] `UnusedPrivateMember` #6356
- [x] `UnnecessaryAbstractClass` #5829 
- [x] `UseDataClass` #6355 
- [x] `UseRequire` #6358
- [x] `OptionalUnit` #6359
- [x] `UnusedImport` #6360
- [ ] `LongParameterList`
- [x] `LateinitUsage` #6379
- [x] `FunctionOnlyReturningConstant` #6380
- [x] `UseCheckOrError` #6361

While those rules are providing value also for users that don't have Type resolution enabled, they also lead to false negative reports. Generally, having the behavior of a rule changing based on the configuration of Detekt is not ideal in my opinion.

How should we treat them?

Imho we should guard all of them and make them required to run only with Type resolution enabled (i.e. adding a `if (bindingContext == EMPTY) return` in their body). 
On the other hand, users might complaining that those rules "stopped working" if they don't have type resolution enabled.

EDIT: Updated list

**Comment by arturbosch** [comment]
I think we should support them at least till 2.0 and later rely on the compiler plugin to get first class support for resolution.

**Comment by BraisGabin** [comment]
Agree, I think that we should keep them for now. In my actual project I don't have type solving because it's android with custom build variants and flavors. And, to be honest, I don't know how to enable it properly.

We don't even have a proper documentation. We said that it's an experimental feature, but we already know that it's the way we want for detekt. 


#2787 looks promising. If, after that, we update our documentation to enable type solving by default and then, give the option to disable it we can improve the reports that our users get and decrease the number of issues we get for user that don't have the type solving enabled.

**Comment by cortinico** [comment]
As a rule of thumb I think we should refrain from adding rules that have mixed behavior. 
And I agree on keeping them around till Detekt 2.x and then promote them to type resolution only.

**Comment by cortinico** [comment]
Thanks for the heads up. That will be available:

> starting with AGP 7.3.0-alpha03.

So we'll have to wait a bit before we can use it.

**Comment by andre-krueger** [comment]
Just to clarifiy:
When type resolution is enabled, the `ignoreAnnotated`  seems to be not working anymore for `UnusedPrivateMember` (example from [here](https://detekt.dev/compose.html#unusedprivatemember)).

Will this be fixed by this ticket?

**Comment by BraisGabin** [comment]
No, please open a ticket reporting it.

**Comment by andre-krueger** [comment]
Ok, done.
https://github.com/detekt/detekt/issues/4649

**Comment by cortinico** [comment]
> * In 2 of the 3 rules the exclusion config property is marked as deprecated in favor of `ignoreAnnotated`.

I'd remove the 2 deprecated property, and potentially do the same treatment to the 3rd rule as well (so you can always use `ignoreAnnotated` that will work well if on TR)

**Comment by schalkms** [comment]
There is one task left open called `LongParameterList`. Can we come to a decision here on how to proceed in order to bring this issue over the finish line?

**Comment by atulgpt** [comment]
Hi, @schalkms for `LongParameterList` we don't need to add `RequiresTypeResolution` as it used `BindingContext` just for matching the annotation with `FQName` in `AnnotationExcluder`  which can only be generated in the TR. W/o TR it uses `AnnotationExcluder` also works but fallbacks to `fullQualifiedNameGuesser` based on packagename. For such a small thing we can ignore the `RequiresTypeResolution`

If we get any issue in the future then we can add it back.

@cortinico I think we can close this issue

**Comment by cortinico** [comment]
Yup agree, thanks for the clarification 👌 We now have a mechanism in place to handle those scenarios so we can consider this resolved
