### ISSUE TITLE
Offset calculation in KtLint deprecated/made private

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#3021]
## Expected Behavior
We should probably starting duplicating the code again asap.

## Current Behavior
KtLint deprecated/made the methods to calculate offsets we use in formatting private.
 
## Context
https://github.com/pinterest/ktlint/pull/857
https://github.com/detekt/detekt/pull/2760

**Comment by timurt** [comment]
Hello, I want to contribute to this project as part of the Hacktoberfest event, 
Can I take this issue? As far as I understood there are two deprecated methods `KtLint.calculateLineColByOffset` and `KtLint.normalizeText` , and we need to copy these methods to `Detekt`, am I right?
