### ISSUE TITLE
Unable to call detektPlugins anywhere in gradle Kotlin DSL

### ISSUE THREAD

**Issue by Veramone** [detekt/detekt#3023]
Hi, I was hoping to get your help with something. I'm trying to use Detekt as well as ktlint using the formatting plugin, but I'm having some trouble getting it set up. 

I have Detekt itself set up (and working) as follows;

build.gradle.kts:
```kotlin
buildscript {
  repositories {
    mavenCentral()
    jcenter()
  }

  dependencies {
    classpath(kotlin("gradle-plugin", version = "1.3.61"))
  }
}

plugins {
  // ...
  id("io.gitlab.arturbosch.detekt") version "1.12.0" apply false
}

subprojects {
  // ...
  apply(plugin = "io.gitlab.arturbosch.detekt")

  dependencies {
     // ...
  }
  
  tasks.withType<Detekt> {
    buildUponDefaultConfig = true
    autoCorrect = true
    reports {
      html {
        enabled = true
      }
    }
  }
}
```

I'm not sure where in this I would be supposed to be able to call `detektPlugins {  ... }`. From the example in the README, I would expect it to be in subprojects -> dependencies, yet Gradle/IntelliJ tell me it's actually an unresolved reference. Am I missing something?

**Comment by zmunm** [comment]
try this

``` 
"detektPlugins"("io.gitlab.arturbosch.detekt:detekt-formatting:$yourVersion")
```

To add a dependency to project'build.gradle.kts' you need to use the String.invoke() form.

**Comment by arturbosch** [comment]
Hi,
that's strange you should be able to put it in the dependencies block without any import needed.
Try changing to `apply true` and see if you get completion.

Your `tasks.withType<Detekt>` block can be converted to our `detekt { ... }` extension, see our build file for an example:

https://github.com/detekt/detekt/blob/609e41168b18e7865592db1003fc42f0ee4fb679/buildSrc/src/main/kotlin/detekt.gradle.kts#L19-L54

**Comment by Veramone** [comment]
@arturbosch 

>  Try changing to apply true and see if you get completion.

That does appear to have done the trick! I added it to the top level dependencies section and that works well. Thank you :) 

> Your tasks.withType<Detekt> block can be converted to our

That's marked as deprecated for me when it was `apply: false`, with a message stating what I did was the recommended way of doing it. Now, however, it seems fine. Thanks a bunch!
