### ISSUE TITLE
`org.spekframework.spek2:spek-dsl-jvm` version is not in the published pom/module. 

### ISSUE THREAD

**Issue by yogurtearl** [detekt/detekt#3031]
## Expected Behavior
`.pom` and `.module` file should contain the version of needed dependencies. 

```xml
    <dependency>
      <groupId>org.spekframework.spek2</groupId>
      <artifactId>spek-dsl-jvm</artifactId>
      <version>2.0.12</version>
      <scope>compile</scope>
    </dependency>
```

## Observed Behavior
`.pom` and `.module` file are **missing** the version

```xml
    <dependency>
      <groupId>org.spekframework.spek2</groupId>
      <artifactId>spek-dsl-jvm</artifactId>
      <scope>compile</scope>
    </dependency>
```

See:
https://repo1.maven.org/maven2/io/gitlab/arturbosch/detekt/detekt-test-utils/1.12.0/detekt-test-utils-1.12.0.pom
https://repo1.maven.org/maven2/io/gitlab/arturbosch/detekt/detekt-test-utils/1.12.0/detekt-test-utils-1.12.0.module

## Steps to Reproduce
Create a project that **doesn't reference `spek`** in any way. 
Create a custom detekt rule, and write a test for it using `"io.gitlab.arturbosch.detekt:detekt-test:1.12.0"`

## Context
My guess is that this is related to you use of a bom module to specify versions.

Our build fails because of the missing version for `spek-dsl-jvm` (and assert-j):

```
> Task :detekt-rules:compileTestKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detekt-rules:compileTestKotlin'.
> Could not resolve all files for configuration ':detekt-rules:testCompileClasspath'.
   > Could not find org.spekframework.spek2:spek-dsl-jvm:.
     Required by:
         project :detekt-rules > io.gitlab.arturbosch.detekt:detekt-test:1.12.0 > io.gitlab.arturbosch.detekt:detekt-test-utils:1.12.0
....

Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.spekframework.spek2:spek-dsl-jvm:.
Required by:
    project :detekt-rules > io.gitlab.arturbosch.detekt:detekt-test:1.12.0 > io.gitlab.arturbosch.detekt:detekt-test-utils:1.12.0

```

## Your Environment
* Version of detekt used: 0.12.0
* Version of Gradle used (if applicable): 6.6.1
* Operating System and version: macOS 10.25

**Comment by arturbosch** [comment]
Hi @yogurtearl ,
have you tried adding our bom dependency? Does this substitute the spek version?

**Comment by fmrsabino** [comment]
> Hi @yogurtearl ,
> have you tried adding our bom dependency? Does this substitute the spek version?

I think the issue is that `spek-dsl-jvm` is declared with the compile scope but for clients consuming it the dependency is not available.

https://github.com/detekt/detekt/blob/0ad39f8cb9e813aef1be800935c03c59e4f6c646/detekt-test-utils/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/KotlinEnvironmentTestSetup.kt#L5-L6


Including the dependency on the module that requires `detekt-test` works:

```groovy
repositories {
    …
    maven { url "https://dl.bintray.com/spekframework/spek/" }
}

dependencies {
    …
    testCompileOnly "org.spekframework.spek2:spek-dsl-jvm:2.0.12"
    testImplementation "io.gitlab.arturbosch.detekt:detekt-test:1.12.0"
}
```

**Comment by fmrsabino** [comment]
Update: It seems that I misunderstood the issue. 

Including the `bom` works. The pom specifies a `dependencyManagement` so this needs to be included

```groovy
repositories {
    …
    jcenter()
}

dependencies {
    …
    testImplementation platform("io.gitlab.arturbosch.detekt:detekt-bom:1.12.0")
}
```

as @arturbosch suggested.

**Comment by arturbosch** [comment]
@fmrsabino thanks for confirming this!
