### ISSUE TITLE
WildcardImport rule conflicts with default IDE settings

### ISSUE THREAD

**Issue by evant** [detekt/detekt#3034]
The default intellij settings will wildcard import if you are using more than 5 classes from the same package. This will cause the WildcardImport rule to be flagged. This means that if I want to bring detekt into a project I have to either disable the wildcard setting in intellij (and require my team to do the same), or turn off this rule in detekt. I'm not a fan of the extra friction this brings. Can this rule be disabled by default or modified to not require this tweaking from the defaults?

**Comment by schalkms** [comment]
Thanks for the feedback!
Basically you have three options here.

1. Disable the `WildcardImport` rule and share the detekt.yml with your team
2. Disable the IntelliJ rule and share it with your team
3. Use two different detekt.yml files. One on the dev machines and the other one on the CI server.

**Comment by evant** [comment]
Just to be clear, I understand how to solve this, I'm arguing that I shouldn't have too. Imo defaults should be good enough to get me started. If I'm forced to change them they aren't good defaults.

**Comment by arturbosch** [comment]
Jetbrains point of view is that the IDE will manage your imports.
detekt is stricter here. Many static analysis tools are stricter than IDE's.

We can leave this issue open for discussion if WildcardImport should be moved to `controversal` and be off by default for 2.0.

Tbh I never used the default IntelliJ setting for imports in my projects as it causes unnecessary VCS noise.

**Comment by evant** [comment]
> Many static analysis tools are stricter than IDE

Understand that, and that's fine! The particular problem here is that strictness actively fights the IDE. 

To be clear I'd be totally ok if intellij changed it's default here instead but feel like that would be a much harder battle to fight.

**Comment by schalkms** [comment]
I wouldn’t want to change this.
Ktlint also has this rule enabled by default.

**Comment by cortinico** [comment]
> I wouldn’t want to change this.

Agree on keeping the status quo. 

> Imo defaults should be good enough to get me started. If I'm forced to change them they aren't good defaults.

I generally agree also on this statement. On the other hand we should definitely avoid to adapt our defaults to the IDE defaults (just because we can't make assumptions on the developer's preferred IDE).

> We can leave this issue open for discussion if WildcardImport should be moved to `controversal` and be off by default for 2.0.

This should be the discussion point from my point of view. We could consider disabling `WildcardImport` in a future version, but so far we haven't received many issue reports related to this rule.
I think that for this specific rule, is fair to have it enabled by default.

**Comment by evant** [comment]
Maybe this is worth a separate issue, but you have an intellij plugin, what about having that plugin automatically configure this for you?

**Comment by schalkms** [comment]
I don't think so. How should the plugin know where to search for the IntelliJ config files? One would need to provide the paths to those files. This would lead to some *magic* in the tooling and unnecessary dependencies to other tools. One would need to go over all rules and identify possible relations to other tools and their rules. I think this would lead to a never ending story.
