### ISSUE TITLE
Consider adding ignoreAnnotated support for TooManyFunctions rule

### ISSUE THREAD

**Issue by mhernand40** [detekt/detekt#3041]
## Expected Behavior of the rule
If a class has an annotation, such as `@Module`, I would like to be able to ignore the `TooManyFunctions` rule for such a class if the `ignoreAnnotated` flag is configured accordingly.

## Context
The `LongParameterList` rule has a configurable `ignoreAnnotated` flag which comes in handy when dealing with dependency injection frameworks such as Dagger. However, I have also seen the case where a Dagger module may grow to have more than 11 dependency provider functions which then leads to the `TooManyFunctions` warning. I think it would be great to add support for the `ignoreAnnotated` to the `TooManyFunctions` rule.

**Example:**
```Kotlin
@Module
class DependencyModule {
    @Provides
    fun provideDep1(): Dependency1 { … }

    @Provides
    fun provideDep2(): Dependency2 { … }

    …

    @Provides
    fun provideDepN(): DependencyN { … } // May raise TooManyFunctions warning
}
```

I would like to suppress the `TooManyFunctions` warning for classes annotated with `@Module`.

Please see [configuration options](https://arturbosch.github.io/detekt/complexity.html#configuration-options-6) for [LongParameterList](https://arturbosch.github.io/detekt/complexity.html#longparameterlist).

**Comment by schalkms** [comment]
Annotation excluding needs to be a cross cutting concern as discussed and proposed in #2231. Please vote for this feature.
We decided to not include framework specifics in configuration options as for instance the `Dagger` framework cases. This adds to the complexity of the rules and creates more maintenance effort. Furthermore, users not using `Dagger` to not profit from such config options.
For now, you could copy the rule and implement this condition in a [custom rule](https://detekt.github.io/detekt/extensions.html#custom-rulesets), if you need it desperately.
