### ISSUE TITLE
Default configuration errors is gradlew

### ISSUE THREAD

**Issue by cschraer** [detekt/detekt#3042]
I generated a config using the gradle command and upon running 

gradlew detekt -c config/detekt/detekt.yml I receive errors base on the comments in the yml file 

* Where:
Settings file '\src\client\config\detekt\detekt.yml' line: 5

* What went wrong:
Could not compile settings file '\src\client\config\detekt\detekt.yml'.
> startup failed:
  settings file '\src\client\config\detekt\detekt.yml': 5: unexpected char: '#' @ line 5, column 5.
         # complexity: 2
         ^

  1 error

Even if I remove the comments and leave values I still get errors.
* What went wrong:
Could not compile settings file '\src\client\config\detekt\detekt.yml'.
> startup failed:
  settings file 'src\client\config\detekt\detekt.yml': 24: expecting EOF, found ':' @ line 24, column 16.
     console-reports:

## Expected Behavior
I would expect the default config file to work

## Observed Behavior
the default config does not work

## Steps to Reproduce
run gradlew detektGenerateConfig
then run gradlew detekt -c 'path to config'

## Your Environment
I am running detekt from a gradle task in an Android project
* Version of detekt used: 1.12.0
* Version of Gradle used (if applicable): 6.1.1
* Operating System and version: Windows 10

**Comment by schalkms** [comment]
What are your line endings (`\n\r`)?

**Comment by cschraer** [comment]
@schalkms unchanged which I have confirmed as LF or \n. I also changed between that and CRLF or \r\n and the result is the same either way.

**Comment by cortinico** [comment]
> gradlew detekt -c config/detekt/detekt.yml I receive errors base on the comments in the yml file

Please note that the `-c` option is interpreted by Gradle as if you're specifying the path of the `settings.gradle` file: https://docs.gradle.org/current/userguide/command_line_interface.html#environment_options

In order to configure the detekt config file you have to either use the configuration in your `build.gradle` file or use a Gradle property/environment variable.
