### ISSUE TITLE
Running multiple Detekt tasks concurrently may cause deadlock

### ISSUE THREAD

**Issue by damianw** [detekt/detekt#3047]
## Context
In my Android app, I have configured separate Detekt tasks for each variant, including test variants, with the full dependency classpath for each (e.g. `detektDebug`, `detektDebugAndroidTest`, etc).

## Expected Behavior
I am trying to run multiple at the same time, e.g. `./gradlew detektDebug detektDebugAndroidTest`, which Gradle (correctly) infers can happen concurrently.

## Observed Behavior
Running multiple Detekt tasks concurrently leads to a deadlock in certain situations. The problem appears to be with [`ClassLoaderCache`](https://github.com/detekt/detekt/blob/c08de812c11c9a84d48ef0ee2e659fa27c8f77b5/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/ClassLoaderCache.kt#L1): `FileCollection.files` resolves the included files, but also (unexpectedly to me) blocks until the dependencies are satisfied if they haven't been already. By calling `files` while being `synchronized` on `ClassLoaderCache`, other `Detekt` invocations become blocked waiting on the monitor, which results in the first `Detekt` never having its dependencies satisfied, leading to a deadlock.

## Steps to Reproduce
I don't have a code sample at the moment (but can provide if necessary) since the configuration and setup would be non-trivial to extract, but the gist is:
- Register a `Detekt` task with a `classpath` containing the classpath of the project's main source set / variant
- Register a `Detekt` task with a `classpath` containing the classpath the project's test source set / variant (I _think_ this is important, based on the fact that the test Detekt task will depend on the classpath of the main source set / variant)
- Invoke Gradle with both tasks as goals (and sufficient cores/workers to run multiple concurrently)

A thread dump for when I have observed this occurring can be found [here](https://gist.github.com/damianw/f96c6db70155974065bc48ec8e0aeb72):
- [`"Execution worker for ':' Thread 3" #266`](https://gist.github.com/damianw/f96c6db70155974065bc48ec8e0aeb72#file-dump-txt-L338-L499) is blocked on `FileCollection.files`, [having locked `ClassLoaderCache`](https://gist.github.com/damianw/f96c6db70155974065bc48ec8e0aeb72#file-dump-txt-L393)
- [`"Execution worker for ':' Thread 11" #274`](https://gist.github.com/damianw/f96c6db70155974065bc48ec8e0aeb72#file-dump-txt-L101-L210) is blocked, [waiting to lock `ClassLoaderCache`](https://gist.github.com/damianw/f96c6db70155974065bc48ec8e0aeb72#file-dump-txt-L102-L104)

If I were to provide a suggestion, I think that moving the call to `FileCollection.files` outside of the `synchronized` block would be the simplest fix.

## Your Environment
* Version of detekt used: 1.12.0
* Version of Gradle used (if applicable): 6.5
* Operating System and version: Mac OS 10.15.6

**Comment by schalkms** [comment]
Thanks for the detailed bug report and the especially helpful suggestion. As we all know, debugging concurrency isn’t that easy. Big thanks to you! 🙂 🙏 

After digging a bit into it, I think you’re right. @arturbosch what do you think?

**Comment by arturbosch** [comment]
Hm, I was pretty sure we just use detekt's class path as a key for the class loader cache. This is indeed wrong.
