### ISSUE TITLE
Creating a baseline for a multi-module project only contains issues from the last module that was run

### ISSUE THREAD

**Issue by polbins** [detekt/detekt#3049]
## Expected Behavior

Following the instructions (as described here: https://detekt.github.io/detekt/baseline.html#gradle) and running `detektBaseline` task should create a consolidated baseline file for all the issues in the multi-module project.

## Observed Behavior

After running `detektBaseLine`, `baseline.xml` will only contain the issues from the *last* module that was run, instead of all the consolidated issues for all the modules.

## Steps to Reproduce

- Multi-module project
- Follow steps as described in: https://detekt.github.io/detekt/baseline.html#gradle 

## Context

- baseline for an old multi-module project w/ 10+ modules

## Your Environment

* Version of detekt used: `1.11.1`
* Version of Gradle used (if applicable): `6.4.1`
* Operating System and version: Ubuntu 20.04
* Link to your project (if it's a public repository):

**Comment by BraisGabin** [comment]
Oh, we need to fix that documentation. Set `baseline = file("baseline.xml")` instead. Or any other relative path. This way the baseline is generated in each module.

**Comment by polbins** [comment]
I actually did that for the mean time and manually collated all the issues into one baseline file.

But I was expecting to have it ALL collated automatically into that one baseline file thru the `detektProjectBaseline` task provided in the documentation?

**Comment by sanogueralorenzo** [comment]
Alternatively you can centralize the baseline generation with the code below (put it in the top level build gradle kts and run with `detektProjectBaseline`)

```
val detektProjectBaseline by tasks.registering(io.gitlab.arturbosch.detekt.DetektCreateBaselineTask::class) {
    description = "Overrides current baseline."
    ignoreFailures.set(true)
    parallel.set(true)
    setSource(files(rootDir))
    config.setFrom(files("$rootDir/detekt.yml"))
    baseline.set(file("$rootDir/baseline.xml"))
    include("**/*.kt")
    include("**/*.kts")
    exclude("**/resources/**")
    exclude("**/build/**")
    exclude("**/buildSrc/**")
    exclude("**/test/**/*.kt")
}
```

**Comment by polbins** [comment]
I'm not sure I understand your suggestion @sanogueralorenzo. The snippet you provided seems to be the same as the one provided in https://detekt.github.io/detekt/baseline.html#gradle except for the following:
```
- buildUponDefaultConfig.set(true)
+ exclude("**/buildSrc/**")
+ exclude("**/test/**/*.kt")
```
