### ISSUE TITLE
Detect unreachable catch blocks

### ISSUE THREAD

**Issue by koral--** [detekt/detekt#305]
Code like that below compiles fine but only first catch block can be ever reached:
```kotlin
try {
	//whatever
} catch (t: Throwable) {

} catch (e: Exception) {

} catch (e: Exception) {

}
```
I can try to make PR for that but want to ask first what do you think. Should `UnreachableCode` rule cover such cases or should it be a separate one?

**Comment by arturbosch** [comment]
I think unreachable code is a good fit. However I do not know if this can be implemented right now. Types are not resolved so we do not have the inheritance hierarchies.

**Comment by arturbosch** [comment]
Well you still can't navigate through an ast of this classes and look for the inherited classes. I don't think we should use reflection. I will label this issue `need resolution`.

**Comment by koral--** [comment]
We can check if given class is a superclass of another one using (https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#isAssignableFrom-java.lang.Class-)[isAssignableFrom] but I agree that reflection doesn't look very well here.

Is there any ticket somewhere in kotlin project to track that type resolution feature?

**Comment by arturbosch** [comment]
The type resolution feature is of course builtin the kotlin compiler. We just haven't figured it out. I prioritize fixing bugs and reviewing PRs in my free time to get a good 1.0 release in the future :). If you have time to spare you can figure out the resolution :)

**Comment by koral--** [comment]
OK, understand. 
I saw this https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ExceptionsRule.kt#L24 and thought that it is not possible.
I'll try to figure it out and check the performance.
