### ISSUE TITLE
1.13.0 changes to detektGenerateConfig

### ISSUE THREAD

**Issue by Tolriq** [detekt/detekt#3065]
## Expected Behavior
Now detektGenerateConfig tries to create the configuration on the configured path.
This change is strange because:
- If the file exist the task refuse to create / update the file as already present
- If the file does not exist the task does not run either as the file is missing

detektGenerateConfig ignores detekt.config paramenter - #2565

The task should not take in account this parameter and eventually there should be a new parameter that allows to define default configuration location.

Currently we can no more generate default configuration and see what new options have been added / changed.

**Comment by arturbosch** [comment]
I couldn't reproduce this.
The file gets generated for me.
A problem exist with multi project gradle builds where only the first subproject generates the file but all sub projects reference it.

**Comment by Tolriq** [comment]
Yes the second issue was due to 1.13 publishing problem.

The problem of using the configured production path and not a default configuration path is that once you are in production you can't generate a new config to see what have changed between releases to update the production configuration.

Having a different file allows to keep both in git, see the diff apply what we want to production file. Now since the production file exist you can't generate a new file. If we delete the production file we can generate the new default but you can't diff since the diff is irrelevant to detekt version update but takes in account previous production file.

There should be 2 different files for default and production configuration using the same config value for both brings a lot of issues without really solving anything.

**Comment by arturbosch** [comment]
You can create a new task based on our task for the diff usecase:

```kt
import io.gitlab.arturbosch.detekt.DetektGenerateConfigTask

val createDetektConfigForDiff by tasks.registering(DetektGenerateConfigTask::class) {
    description = ""
    config.setFrom(buildDir.resolve("detekt-diff.yaml"))

    doFirst {
      // optionally delete the old config diff file first 
    }
}
```

Does this work for you?

**Comment by Tolriq** [comment]
Yes works perfectly, did not thought it would be so easy 👍 

Maybe worth some kind of recipes for others as this sounds like a normal need to know what changes between version and easily update config;

**Comment by arturbosch** [comment]
> Yes works perfectly, did not thought it would be so easy  Thanks.
> 
> Maybe worth some kind of recipes for others as this sounds like a normal need to know what changes between version and easily update config;

Thanks for the suggestion! 
Will post it under `https://detekt.github.io/detekt/news`.
