### ISSUE TITLE
Wrong error:  "error: cannot access 'foo': it is internal in 'com.example.bar'"

### ISSUE THREAD

**Issue by yogurtearl** [detekt/detekt#3067]
`internal` in kotlin means it can't be accessed outside the current module.
https://kotlinlang.org/docs/reference/visibility-modifiers.html#modules

In gradle projects, a "module" is a gradle source set, with the exception that the `test` source set can access the internal declarations of `main`

## Expected Behavior
If gradle/kotlinc don't complain about `internal`, then detekt shouldn't complain either.
detekt should match gradle/kotlinc here.

## Observed Behavior
If a `Test` in `/test` accesses a `internal` `foo` extension function defined in `/main`, then detekt complains `error: cannot access 'foo': it is internal in 'com.example.bar'`

## Your Environment

* Version of detekt used: 1.12.0
* Version of Gradle used (if applicable): 6.6.1
* Operating System and version: macOS 10.15

**Comment by cortinico** [comment]
> then detekt complains `error: cannot access 'foo': it is internal in 'com.example.bar'`

Is this reported by a Detekt rule? If yes, which one?
Can you provide more context to help reproduce?

**Comment by arturbosch** [comment]
@yogurtearl could you try adding `languageVersion = "1.4"` to the detekt tasks via `tasks.withType<Detekt> { ... }` and see if it helps? Thanks

**Comment by chao2zhang** [comment]
`error: cannot access 'foo': it is internal in 'com.example.bar'` is a compiler error issued when running detekt with type resolution. It does not affect the result of detekt. This is reproducible when running `./gradlew detektTest` in the detekt repo itself. Hence I would suggest reopening this issue.

However, this means that our rules may not run correctly. There is a compiler option `-Xfriend-paths` and we can also programmatically `CompilerConfiguration.put(JVMConfigurationKeys.FRIEND_PATHS, friendPaths)`. I think this is the right path but it turns out we need more investigation more to set the friend paths correctly.

**Comment by chao2zhang** [comment]
After digging into the kotlin compiler code a little bit, we can conclude the status quo as:

- We need to tell Kotlin compiler about friend paths
- In `https://github.com/chao2zhang/detekt/tree/internal-fix`, I write the friends path to `JVMConfigurationKeys.FRIEND_PATHS`
- `JVMConfigurationKeys.FRIEND_PATHS` is read in https://github.com/JetBrains/kotlin/blob/d753d21dee4c1b282423ea43db2f90e2b651f5eb/compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/KotlinToJVMBytecodeCompiler.kt#L154
- Detekt uses `PsiFileFactory.createPhysicalFile` to parse the file, which does not invoke `KotlinToJVMBytecodeCompiler.compileModules()`. So the value we passed was never read. 

We need a smarter way for the compiler to respect the friend path.

**Comment by cowmanjoe** [comment]
Is there any workaround to this issue at the moment, e.g. silencing the logs for this part? It can pollute the logs with a lot of messages that are not useful.

**Comment by cortinico** [comment]
> Is there any workaround to this issue at the moment

I believe the best workaround at this stage for those kind of errors is to use github.com/detekt/detekt-compiler-plugin/

**Comment by cortinico** [comment]
Another issue that will most likely be fixed by #4106

**Comment by 3flex** [comment]
I wish stale bot would stop shaming me about everything I'd said I'd do over the last few months :D

I'll come back to this soon enough, there are a few other things I want to to take care of first.

**Comment by TWiStErRob** [comment]
I created a self-contained repro in duplicate https://github.com/detekt/detekt/issues/5396

 * https://github.com/TWiStErRob/repros/tree/master/detekt/BindingContext-internal-test
 * `gradlew cleanDetektTest detektTest`
