### ISSUE TITLE
Scoped check: detekt just those files, that have been changed, not all the source

### ISSUE THREAD

**Issue by Sadwyn** [detekt/detekt#3078]
Is that possible to do with some setting? I want o launch it through git hook

**Comment by BraisGabin** [comment]
You can use de cli for that. But you will not able to use the rules that need type solving.

**Comment by schalkms** [comment]
Thanks for the feedback!
This topic, however, has been covered intensively in the recent past. Please take a look at the following issues including the links. If you have additional question, don’t hesitate to ask.
- #2175 
- #2320 
- #1057

The detekt slack channel Also contains information regarding this topic.

**Comment by schalkms** [comment]
Closed as duplicate

**Comment by Sadwyn** [comment]
Thank you for response. Is there some tutorial how can I use cli detekt
with some file pathes in pre commit git hook?

**Comment by schalkms** [comment]
Yes, there is a tutorial available.
https://detekt.github.io/detekt/git-pre-commit-hook.html
