### ISSUE TITLE
Artifact detekt-test foreces dependency constraining

### ISSUE THREAD

**Issue by gfreivasc** [detekt/detekt#3082]
I'm trying to include `detekt-test` in a project but it fails as it can't find the `api` dependencies `assertj-core` and `spek-dsl-jvm`. It gives me the following message:

```
Execution failed for task ':detekt-extensions:compileTestKotlin'.
> Could not resolve all files for configuration ':detekt-extensions:testCompileClasspath'.
   > Could not find org.assertj:assertj-core:.
     Required by:
         project :detekt-extensions > io.gitlab.arturbosch.detekt:detekt-test:1.13.1 > io.gitlab.arturbosch.detekt:detekt-test-utils:1.13.1
   > Could not find org.spekframework.spek2:spek-dsl-jvm:.
     Required by:
         project :detekt-extensions > io.gitlab.arturbosch.detekt:detekt-test:1.13.1 > io.gitlab.arturbosch.detekt:detekt-test-utils:1.13.1
```

Which appears to be because the artifact expects me to use assertJ and speak. My question is, is it really necessary to use both of these libraries to write tests for custom rules? I'm leaning towards simpler jUnit tests, so I had to depend on these libraries to prevent gradle from breaking. Would it be better to not have the `api` dependencies? Or are these libraries really a requirement?

**Comment by mhernand40** [comment]
Same for me.

**Comment by cortinico** [comment]
> Which appears to be because the artifact expects me to use assertJ and speak. My question is, is it really necessary to use both of these libraries to write tests for custom rules?

Some of the utils functions inside `detekt-test` (and transitively `detekt-test-utils`) are using those libraries. So if you use those utils functions, you need to import those dependencies. If you wish to use only JUnit, you can obviously do it, but you won't be able to use those util functions.

To name a couple:

`setupKotlinEnvironment` is using `spek`:

https://github.com/detekt/detekt/blob/793cecefa48819dcf20f70f675214f916ac9349e/detekt-test-utils/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/KotlinEnvironmentTestSetup.kt#L8-L13

`FindingsAssertions` is using `assertJ`:

https://github.com/detekt/detekt/blob/793cecefa48819dcf20f70f675214f916ac9349e/detekt-test/src/main/kotlin/io/gitlab/arturbosch/detekt/test/FindingsAssertions.kt#L91

**Comment by cortinico** [comment]
You're totally right that we should probably expose a `detekt-test` artifact that is agnostic from the testing framework used. Given that we use internally Spek to run our tests, some of the test utils ended up being coupled with the testing framework.

Agree that we should clean it up a bit and expose as `detekt-test-core` that is fully agostic (PRs are more than welcome 🙏 )

**Comment by arturbosch** [comment]
I've changed the dependencies to `compileOnly` meaning if the anyone wants to use our assertions or spek integration, he needs to explicitly add the dependency to his project.
