### ISSUE TITLE
Could not set unknown property 'ignoredFlavors' for task ':detektAll' of type io.gitlab.arturbosch.detekt.Detekt.

### ISSUE THREAD

**Issue by GitHubMurt** [detekt/detekt#3087]
Android Studio 
my code inside build.gradle
```
plugins {
    id "io.gitlab.arturbosch.detekt" version "1.13.1"
}
dependencies {
    detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:1.13.1"
}
tasks.detekt.jvmTarget = "1.8"

tasks.register('detektAll', io.gitlab.arturbosch.detekt.Detekt) {
   ...
    ignoredFlavors = ["stage"]
    ...
}
```

## Observed Behavior
when sync project

Could not set unknown property 'ignoredFlavors' for task ':detektAll' of type io.gitlab.arturbosch.detekt.Detekt.

**Comment by cortinico** [comment]
> Could not set unknown property 'ignoredFlavors' for task ':detektAll' of type io.gitlab.arturbosch.detekt.Detekt.

As the errors says, you can't set `ignoredFlavors` when registering a new task of type `io.gitlab.arturbosch.detekt.Detekt`. You should use the `detekt{}` extension to configure the `ignoredFlavors`.

As a side note, the impact of setting such field will be to restrict the `detekt<Variant>` tasks that will be generated.
