### ISSUE TITLE
detektTest for KotlinJS?

### ISSUE THREAD

**Issue by levelrin** [detekt/detekt#3121]
About a week ago, I [asked](https://github.com/detekt/detekt/issues/3102) if there is a way to check the test code.
They told me that the [detektTest](https://detekt.github.io/detekt/gradle.html#available-plugin-tasks) should do the job.
Unfortunately, it seems the `detektTest` is not available for the KotlinJS project.
Is there any plan to add a way to check the test code for the KotlinJS project in the future?
Please correct me if I'm mistaken.

Thanks

**Comment by arturbosch** [comment]
Hey,

try adding the test sources to detekt's input array: https://github.com/detekt/detekt/blob/master/buildSrc/src/main/kotlin/detekt.gradle.kts#L34

Now the normal `detekt` task should pick them up. Also see the note in our migration section: https://detekt.github.io/detekt/changelog.html#migration-1

**Comment by levelrin** [comment]
@arturbosch 
I followed your suggestion, and it worked.
I added the test source like this:
```groovy
detekt {
    /* ... */
    input = objects.fileCollection().from(
        "src/main/kotlin",
        "src/test/kotlin"
    )
}
```

Thank you!
