### ISSUE TITLE
Is ArrayIndexOutOfBoundsException too generic?

### ISSUE THREAD

**Issue by aYukiWatanabe** [detekt/detekt#3134]
The [default config](https://github.com/detekt/detekt/blob/782fb75b49d9774916585f1d8d9649dfe7c81dc3/detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/TooGenericExceptionCaught.kt#L38) for TooGenericExceptionCatched reports [ArrayIndexOutOfBoundsException](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-array-index-out-of-bounds-exception/) as a too generic exception. However, this exception type does not seem to have any child class. Are there any other class to catch instead of ArrayIndexOutOfBoundsException or is this simply a mistake in the default rule?

**Comment by BraisGabin** [comment]
I always think about that value as "you should never check for `ArrayIndexOutOfBoundsException`". You should ensure that your code doesn't generate that exception instead of having the try/catch. And if you can't ensure that, your code have a code smell.

**Comment by aYukiWatanabe** [comment]
> You should ensure that your code doesn't generate that exception instead of having the try/catch.

That sounds reasonable, and probably applies to almost all subclasses of RuntimeException.

Maybe catching ArrayIndexOutOfBoundsException could be detected in some other name, as it seems to me that the current name TooGenericExceptionCatched does not convey the point of the issue.

**Comment by schalkms** [comment]
Okay, thanks for your feedback!
Brais explained the intention behind this rule very well.
The default config can be adapted to the users needs.
Detekt strives to keep a good default config for the majority of the user base. I think this is given here, since we discuss this rule config the first time in this repo. Therefore, I'll close this for now.
