### ISSUE TITLE
@Suppress("MaxLineLength") not working for simple block comment inside class

### ISSUE THREAD

**Issue by tmohme** [detekt/detekt#3136]
## Expected Behavior
detekt should *not* flag the too-long line in a simple block-comment inside a class that is annotated with `@Suppress("MaxLineLength")`.

## Observed Behavior
detekt reports a "MaxLineLength" issue for the too-long lines within simple block-comments.
Interestingly, detekt **does not** report such an issue for too-long lines in KDoc-style block comments.

## Steps to Reproduce
```
@Suppress("MaxLineLength")
class SomeClass {
    /*
     this line is too long and will be reported ------------------------------------------------------------------------------------------------>
     */

    /**
     this line is too long and won't be reported ----------------------------------------------------------------------------------------------->
     */
}
```

## Context
Splitting the line in question is no option because it is a "citation" of a source-line of another project.  
I'm using the KDoc-Style as a  workaround but that's brittle as the block is obviously standing for itself and not directly documenting the next declaration, so the next one working on this piece of code might alter the comment style back again.

## Your Environment

* Version of detekt used: 1.14.1
* Operating System and version: MacOS 10.14.6

**Comment by cortinico** [comment]
I was able to reproduce.

> Interestingly, detekt does not report such an issue for too-long lines in KDoc-style block comments.

What is actually happening is that the `@Suppress("MaxLineLength")` is considered only for the KDoc comment, and not for the regular comment.

Fix is here #3164
