### ISSUE TITLE
Export DEFAULT_DETEKT_VERSION

### ISSUE THREAD

**Issue by cldfzn** [detekt/detekt#3140]
I write a plugin for use within my organization and having the current tool version available programmatically would make things easier. When I update the plugin version via dependency, I have to remember to update in the code as well, and with a reference to the const that would no longer be needed.

The DEFAULT_DETEKT_VERSION is currently declared with the internal modifier.

**Comment by cortinico** [comment]
> When I update the plugin version via dependency, I have to remember to update in the code as well

This is easily achievable using a build config flag (or any other mechanism for centralising library versions). Wouldn't that be enough?

**Comment by cldfzn** [comment]
Yeah I understand there are other ways to do it, but I also can't see a compelling reason to keep the internal modifier.

**Comment by arturbosch** [comment]
@cldfzn are you writing a Gradle plugin which wraps detekt? 

please give this a try: add `compileOnly("...detekt-tooling...") dependency and call `VersionProvider.load().current()` in your code.

**Comment by cldfzn** [comment]
Ah, that's very useful. Sorry I missed that and thank you!
