### ISSUE TITLE
ClassOrdering identifies minimum set of reorders

### ISSUE THREAD

**Issue by hbmartin** [detekt/detekt#3144]
## Expected Behavior
ClassOrdering should report the minimum work to properly order a class.

## Current Behavior
As of https://github.com/detekt/detekt/pull/3142 ClassOrdering reports a list of all misordered pairs. @BraisGabin pointed out that this could result in over-reporting issues in a class https://github.com/detekt/detekt/pull/3142#issuecomment-707661931

## Context
Addressing this issue will enable user to more quickly identify and fix misorders.

**Comment by BraisGabin** [comment]
Why is this closed? The feature described here is not implemented yet.

**Comment by arturbosch** [comment]
> Why is this closed? The feature described here is not implemented yet.

Sorry, misread/misinterpreter the PR :)

**Comment by atulgpt** [comment]
Hi @arturbosch / @BraisGabin raised the PR at https://github.com/detekt/detekt/pull/6003
