### ISSUE TITLE
missing baseline files when using .xml file extension

### ISSUE THREAD

**Issue by yogurtearl** [detekt/detekt#3146]
## Expected Behavior

`./gradlew detektBaselineMain detektBaselineTest` should output a separate baseline file for each variant.

```groovy
allprojects { project ->
     project.afterEvaluate {
          detekt {
               def subprojectPath = project.path.drop(1).replace(":", "-")
               baseline file("$rootProject.rootDir/config/detekt/baseline/$subprojectPath/detekt-$subprojectPath-baseline.xml")
          }
     }
}
```

## Observed Behavior

it only outputs for a single variant `config/detekt/baseline/foo/detekt-foo-baseline-release.xml`, but `debug` missing. 

if I change the file extension to anything but `.xml` it works and outputs both `-release` and `-debug`
e.g. `s/xml/xsl` 
```groovy
              baseline file("$rootProject.rootDir/config/detekt/baseline/$subprojectPath/detekt-$subprojectPath-baseline.xml")
```

## Context

means we have to name our baseline files with a file extension other than `.xml` 

## Your Environment

AGP 4.1.0

* Version of detekt used: 1.14.1
* Version of Gradle used (if applicable): 6.7
* Operating System and version: macOS 10.15.7

**Comment by cortinico** [comment]
Hey @yogurtearl,
Unfortunately I wasn't able to reproduce.

Here a sample project where I tried to reproduce.
Your configuration is applied here: https://github.com/cortinico/reproducer-detekt-3146/commit/cc2589704b5911abd49f1f3e5ce17a274fc313a6
The output is here https://github.com/cortinico/reproducer-detekt-3146/commit/5fd0e26d1e9d738fc0d4e572ee4feab6a7a74b8a

**Comment by schalkms** [comment]
Closed because of not being able to reproduce this.
