### ISSUE TITLE
CamelCase should be accepted for top level constant names

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [detekt/detekt#3147]
As an alternative to companion object const variable, we can just create top level constants and CamelCase should be accepted too, example:

```
private const val AndroidxSnapshotBuildId = 6911187
```

**Comment by schalkms** [comment]
Is there a reference that highlights whether this okay according to Kotlin's style guides?

**Comment by JavierSegoviaCordoba** [comment]
@schalkms sorry but I read about it in a discussion about Google members in compose and they referenced JetBrains was using it too (at least in companion object). I think there is no difference between private const inside or outside companion object (just performance)

**Comment by BraisGabin** [comment]
https://kotlinlang.org/docs/reference/coding-conventions.html#property-names

> Names of top-level or object properties which hold objects with behavior or mutable data should use camel-case names

It says that only for mutable objects but we can't know if the object is mutable or not so we should allow it.

**Comment by BraisGabin** [comment]
Ups, nope, sorry. I'm wrong here. That documention doesn't apply here. This are `const` and all the `const` are immutable so it should not apply.

**Comment by JavierSegoviaCordoba** [comment]
ktor source code is using CamelCase multiple times for Companion objects, objects and top level const val properties. I think JetBrains will add it to naming conventions in the future.

**Comment by BraisGabin** [comment]
The thing here is if we want to follow Jetbrains/Google or the convention. And I think that the default values in detekt should follow the convention. We allow the user to customize this rule to do exactly that:

```diff
   TopLevelPropertyNaming:
-    constantPattern: '[A-Z][_A-Z0-9]*'
+    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
```

So, my vote is to follow the convention and wait for Jetbrains to update it. I'm not agains it neither, so if the other maintainer/more users think that this change is good we can merge the PR.

**Comment by schalkms** [comment]
I also prefer to keep it, since this config change would be kind of controversial as of now. If the official style guide is updated, we can still adapt the config later on.

**Comment by JavierSegoviaCordoba** [comment]
Compose released its guidelines, one of them is what I mentioned here.

Should Detekt provides docs about what rules are necessary to change to avoid problems with the Compose guidelines?

I understand the default behavior of Detekt should be following the Kotlinlang guidelines, but having a doc which explain how to use specific rules (and what rules) for Compose should be great.

https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md

**Comment by chao2zhang** [comment]
I checked the code yesterday and believe that androidx compose has implemented lint rules that would perform these checks. I think a short-term quick answer is to configure android lint since both compose and android-lint are maintained by Google.

**Comment by JavierSegoviaCordoba** [comment]
But fixing android lint doesn't fix, for example, that I can see warnings from the Detekt IDEA plugin, no?

**Comment by chao2zhang** [comment]
Android Studio supports showing lint checks as warnings in IDE.

**Comment by JavierSegoviaCordoba** [comment]
Ah, but what I want is hiding Detekt warnings (and avoid that the build fails too) related to some Compose rules that don't match with Kotlinlang conventions.

**Comment by chao2zhang** [comment]
Yeah I think there is an opportunity to
1. Create new a rule set for android or compose
2. Allow the android and/or compose flavor of default build config.

**Comment by BraisGabin** [comment]
This is another good reason to create the detelt-android plugin: #3303

**Comment by JavierSegoviaCordoba** [comment]
@BraisGabin I think Compose should be a separate artifact, at this moment, it can be used without Android in a JVM via Compose Desktop and in a few years it will be fully multiplatform

**Comment by drinkthestars** [comment]
asked a Q relating to this in the Discussions https://github.com/detekt/detekt/discussions/4078

as more teams start to adopt Jetpack Compose, would be good to know how to proceed with this one; should consumers customize this rule locally, or are there plans for something else? thanks!

**Comment by JavierSegoviaCordoba** [comment]
I created an issue in YouTrack, maybe it is added to the default convention so Detekt only have to change the default pattern: https://youtrack.jetbrains.com/issue/KT-48496
