### ISSUE TITLE
Make kotlinc adapted rule comments internal

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3190]
Some of our rules are adaptations from other rules in the kotlin compiler or other sources. We usually add a comment in the code poiting this out and that's good. This way we give credit and in case of bug we can check the source to see if they fixed it already.

But those comments are appearing in our documentation, for example: https://detekt.github.io/detekt/style.html#uselesscallonnotnull or https://github.com/detekt/detekt/pull/3187#pullrequestreview-521122537

I think that this references should not appear in the documentation because they give nearly 0 value to our users and it can be missleading.

My proposal is to remove those comments from the double asterisk comment block and move it to a single asterisk comment block. What do you think?

**Comment by schalkms** [comment]
That’s actually a very good idea. Please go ahead.
