### ISSUE TITLE
Return value in finally block try-catch-finally expression

### ISSUE THREAD

**Issue by rwqwr** [detekt/detekt#3197]
Detekt doesn't check unaffected finally block in try-catch-finally expression on result value.
See: https://kotlinlang.org/docs/reference/exceptions.html#try-is-an-expression
## Noncompliant Code
```kotlin
val expression = try {
    "try"
} catch (e: Exception) {
    "exception"
} finally {
    "finally"
}
```
## Compliant Code
```kotlin
val expression = try {
    "try"
} catch (e: Exception) {
    "exception"
}
```

**Comment by schalkms** [comment]
Thanks for submitting this issue. I suppose **ReturnFromFinally.kt** does not report this snippet.

**Comment by rwqwr** [comment]
You are right. ReturnFromFinally.kt does not report this snippet.
Can I implement this case?

**Comment by cortinico** [comment]
> Can I implement this case?

Sure feel free. I'm assigning this issue to you 👍
