### ISSUE TITLE
Confusing Detekt gradle tasks

### ISSUE THREAD

**Issue by fr373969** [detekt/detekt#3240]
## Expected Behavior

`./gradlew :feature:myFeature:detekt` should reveal violations from `./gradlew :feature:myFeature:detektdebug` and `./gradlew :feature:myFeature:detektRelease`

## Current Behavior

`./gradlew :feature:myFeature:detekt` will not reveal violations locally and show build success

## Context

I found detekt variant and gradle variant are not compatible, for example, in my repo's baseline files, I have identical
`detekt-feature-baseline-debug.xsl` and `detekt-feature-baseline-release.xsl` and when I run the `./gradlew :feature:myFeature:detekt` , I thought I will cover both gradle variant, but it's not, if there's a need for new detekt baseline file, issues are mostly found from CI.

**Comment by cortinico** [comment]
> `./gradlew :feature:myFeature:detekt` should reveal violations from `./gradlew :feature:myFeature:detektdebug` and `./gradlew :feature:myFeature:detektRelease`

Those tasks that you're linking are different as far as it concerns type resolution: https://detekt.github.io/detekt/gradle.html#available-plugin-tasks

So `:detekt` has TR disabled while `:detektDebug` and `:detektRelease` have it enabled.
You're probably looking for the task `:detektMain`

**Comment by BraisGabin** [comment]
What @cortinico say is correct.

I think that, once we move to detekt 2.0 we will change this. And detekt will run detektDebug and detektRelease the same way that test runs testDebug and testRelease

**Comment by chao2zhang** [comment]
https://github.com/detekt/detekt/pull/3334/ was a draft PR to experiment detekt task per source set and create a detektAll/detektCheck task to run all detekt tasks. I could resume working on it.

**Comment by cortinico** [comment]
Closing as this has been clarified here https://detekt.github.io/detekt/type-resolution.html
