### ISSUE TITLE
HtmlReport error in rule: SpacingAroundColon

### ISSUE THREAD

**Issue by comdiv** [detekt/detekt#3241]
I found an error in the html report:
- Rule: SpacingAroundColon
- Detekt version: 1.15.0-RC1
- Stacktrace:
```
java.lang.StringIndexOutOfBoundsException: begin 0, end 8, length 7
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at io.github.detekt.report.html.HtmlUtilsKt.writeErrorLine(HtmlUtils.kt:51)
	at io.github.detekt.report.html.HtmlUtilsKt.access$writeErrorLine(HtmlUtils.kt:1)
	at io.github.detekt.report.html.HtmlUtilsKt.snippetCode(HtmlUtils.kt:35)
```
- How to reproduce it: <WRITE HERE HOW TO REPRODUCE THIS ISSUE. A CODE SNIPPET IS THE BEST WAY.>

**Comment by cortinico** [comment]
> * How to reproduce it:

Are you able to provide the steps to reproduce this?

**Comment by schalkms** [comment]
Since this issue can't be reproduced with the given information, this issue is closed. There's not much that can be done to debug or correct information at the moment. If further information regarding repro scenarios is posted, this issue will of course be reopened.

**Comment by schalkms** [comment]
Since this issue can't be reproduced with the given information, this issue is closed. There's not much that can be done to debug or correct this behavior at the moment. If further information regarding repro scenarios is posted, this issue will of course be reopened.
