### ISSUE TITLE
java.lang.IllegalStateException: Analyzing

### ISSUE THREAD

**Issue by rHlushan** [detekt/detekt#3243]
[linters.gradle.txt](https://github.com/detekt/detekt/files/5575667/linters.gradle.txt)

## Steps to Reproduce
after upgrade from verion 1.13.1 to 1.15.0-RC1

## Context
Execution failed for task ':detekt'.
> java.lang.IllegalStateException: Analyzing /some amazing path/AppContextProvider.kt led to an exception. 
  The original exception message was: kotlin.KotlinNullPointerException
  Running detekt '1.15.0-RC1' on Java '1.8.0_242-release-1644-b3-6915495' on OS 'Mac OS X'
  If the exception message does not help, please feel free to create an issue on our GitHub page.
[detekt-config.txt](https://github.com/detekt/detekt/files/5575631/detekt-config.txt)

on detect version 1.14.0, 1.14.1, 1.14.2: 
Caused by: kotlin.KotlinNullPointerException

## Your Environment

* Version of detekt used: 1.15.0-RC1
* Version of Gradle used (if applicable):  distributionUrl = https\://services.gradle.org/distributions/gradle-6.7-all.zip
AGP version: 4.1.1
* Operating System and version: Mac OS X Catalina version 10.15.7
* original config file format is .yml
* originally linters.gradle.txt is linters.gradle
*  linters.gradle is applies in build.gradle.kts as:
apply(from = "${project.rootProject.projectDir.path}/gradle_support/linters.gradle")

AppContextProvider code:

package com.ruslan.hlushan.android.core.api.di

import android.content.Context

interface AppContextProvider {

    fun provideAppContext(): Context
}

**Comment by egorikftp** [comment]
The same for me, today started crashes without any changes.

Version 1.14.1

**Comment by BraisGabin** [comment]
Do detekt print a full stack trace? Could you share it?

**Comment by rHlushan** [comment]
Sorry, that is full slack.
Also tyied with --info, --debug but was no more info.

**Comment by cortinico** [comment]
Can you please create a reproducer project where we can test what is failing?

**Comment by rHlushan** [comment]
Sorry, but because of some security reasons I can't.
But generally this is a multi-module project.
Maybe I can help u in another way?

**Comment by cortinico** [comment]
> Sorry, but because of some security reasons I can't.

I'm not asking to share your project but rather a reproducer. You can use a template like this one https://github.com/cortinico/kotlin-android-template and try to apply your configuration to reproduce this failure.

As an alternative please provide:
- The full stacktrace
- A Gradle build scan

**Comment by rHlushan** [comment]
Just tried it now.
It works.
Really don't know why it does not.
Uploaded my config: https://github.com/rHlushan/template_30/commit/3f860e32f3b5d967e95b3a3150c6a621b06a21ff
Hope that will help to some one.

**Comment by cortinico** [comment]
> Just tried it now.
> It works.
> Really don't know why it does not.

I've just tested your repo and detekt works fine (it fails with an exception):

```
> Task :detekt FAILED
style - 5min debt
        WildcardImport - [/Users/ncorti/pg/template_30/app/src/main/java/com/ncorti/kotlin/template/app/MainActivity.kt] at /Users/ncorti/pg/template_30/app/src/main/java/com/ncorti/kotlin/template/app/MainActivity.kt:8:1

Overall debt: 5min

FAILURE: Build failed with an exception.
```

Can we close this then?

**Comment by rHlushan** [comment]
for me yes.
if nobody has another opinion.
Thanks
