### ISSUE TITLE
Set level of logging for `io.gitlab.arturbosch.detekt.api.ConsoleReport`

### ISSUE THREAD

**Issue by sboishtyan** [detekt/detekt#3269]
## Current Behavior
As I see in the `io.gitlab.arturbosch.detekt.core.reporting.OutputFacade#handleConsoleReports` all console reports are printed to the `outputChannel`

## Expected Behavior
I could change printing to the `errorChannel`

## Context
We have a plugin that captures all errors from Gradle execution logs.
An alternative solution: our plugin will know where it can find a detekt's txt report but I don't want to tight it with detekt

**Comment by schalkms** [comment]
Hello!
If understand it correctly, this looks to me like a typical use case for a custom detekt extension. You can then configure your preferred output location.
For more information please refer to the guide [here](https://arturbosch.github.io/detekt/extensions.html#custom-reports).

**Comment by sboishtyan** [comment]
It looks fittable. But I will duplicate each existed extension
So my opinion is better to change where to print than duplicate existed extensions only for change where to print.
But you like an owner knows better how `detekt` must be designed

**Comment by schalkms** [comment]
> It looks fittable. But I will duplicate each existed extension

I'm afraid, I don't quite understand. You mentioned that you only the `ConsoleReport`. Did I maybe miss something here? Please correct me if I'm wrong. Thank you!

**Comment by sboishtyan** [comment]
As I understand the detekt has six implementations of `ConsoleReport` for each part of `Detektion`. And I have to copy-paste some of them e.g. `FindingsReport` and then add my code for logging destination

**Comment by schalkms** [comment]
Yes, that's true. Nevertheless, nothing prevents the user from consolidating those reports into 1 custom report extension. The reports are split up in order to allow for a granular configuration.
