### ISSUE TITLE
Rule: Detect open classes/functions that don't have to be

### ISSUE THREAD

**Issue by Mauin** [detekt/detekt#331]
The rule should report any class or function that is marked as `open` that doesn't have to be.

In the case of `open class` it should report the class if no other class extends it. In that case it should be reported as a violation.

**Comment by schalkms** [comment]
I think this rule can be combined with 

`final` member declarations in `final classes`

**Comment by arturbosch** [comment]
Looks like it needs type resolution.

**Comment by BraisGabin** [comment]
I think that we should start thinking about how do we want to support this type of rules. Rules that doesn't work on a `File` level but in a "project" level or even a "multi-project" level.

**Comment by cortinico** [comment]
> In the case of `open class` it should report the class if no other class extends it. In that case it should be reported as a violation.

I don't necessarily agree on this rule. If you're developing a library, you very much need `open` classes. I think we should rethink rules that are tailored for Library authors vs final consumer developers (mobile apps, backend application, etc.)
