### ISSUE TITLE
NamedArguments rule not working after 1.15.0 release

### ISSUE THREAD

**Issue by Skyyo** [detekt/detekt#3314]
## Expected Behavior
When **NamedArguments** rule is active, it should warn about non-named arguments, if there are any above specified threshold

## Observed Behavior
No warnings are observed when using detekt 1.15.0 and **NamedArguments** rule activated for this part inside [MainActivity.kt](https://github.com/Skyyo/detekt-1.15.NamedArguments-issue/blob/ac1e8178617e80eb3c708e02c12dcd92fbd24f46/app/src/main/java/com/skyyo/detektnamedargumentsissue/MainActivity.kt#L7-L17)

## Steps to Reproduce
Attaching a [sample project](https://github.com/Skyyo/detekt-1.15.NamedArguments-issue) to showcase the issue.
Changing version to **1.15.0-RC1** on [this](https://github.com/Skyyo/detekt-1.15.NamedArguments-issue/blob/ac1e8178617e80eb3c708e02c12dcd92fbd24f46/app/build.gradle#L4) line results into correct warning being observed

## Context
Encountered while attempting to update the version of detekt after NamedArguments [issue with varArgs](https://github.com/detekt/detekt/pull/3294) was fixed ( might be the reason why this issue appeared? )

## Your Environment

* Version of detekt used: 1.15.0
* Version of Gradle used (if applicable): 4.1.1, distribution url: https\://services.gradle.org/distributions/gradle-6.5-bin.zip
* Operating System and version: macOS Big Sur, version 11.0.1
* Link to your project (if it's a public repository):https://github.com/Skyyo/detekt-1.15.NamedArguments-issue

**Comment by schalkms** [comment]
This rule now requires type and symbol solving to be configured? May I ask you to check this for your project? You can find helpful information [here](https://detekt.github.io/detekt/type-resolution.html).

**Comment by Skyyo** [comment]
Running `./gradlew detektDebug` gives expected results, while `./gradlew detekt` doesn't. Thank you for the support @schalkms

**Comment by schalkms** [comment]
You are welcome. Thank you for rechecking it.
