### ISSUE TITLE
Simplify Detekt API validation

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#3345]
## Expected Behavior
Detekt API validation should be enabled with minimal setup.

## Observed Behavior
In #3320, we need to use `rootProject.name` as a temporary workaround to exclude api validation of rootProject. This is not addressed by #3322.

## Steps to Reproduce
Run `./gradlew apiDump`

## Context
This is a technical debt that will go overdue soon.

**Comment by schalkms** [comment]
After the linked PR has been merged, shall we close this now?

**Comment by chao2zhang** [comment]
Sounds good.
