### ISSUE TITLE
Don't null check a mutable property

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3353]
## Expected Behavior of the rule
non compliant:
```kotlin
class A(
    var foo: Asdf?
) {
  fun bar() {
    if (foo != null) {
      foo!!.toString()
      doThings(foo!!.value)
    }
  }
}
```

compliant:
```kotlin
class A(
    var foo: Asdf?
) {
  fun bar() {
    val foo = foo // or use let, or whatever you want
    if (foo != null) {
      foo.toString()
      doThings(foo.value)
    }
  }
}
```

## Context

#3352 is the example that make me think about this rule. This is a pattern that I see often in the my project. Usually this errors happens when you translates code from Java to Kotlin.

Maybe we could check this kind of things too:
non compliant:
```kotlin
class A {
  fun getActivity(): Activity? = // whatever

  fun bar() {
    if (getActivity() != null) {
      getActivity()!!.doSomething()
    }
  }
}
```

compliant:
```kotlin
class A {
  fun getActivity(): Activity? = // whatever

  fun bar() {
    val activity = getActivity() // or ?.let or whatever you want
    if (activity != null) {
      .doSomething()
    }
  }
}
```

This pattern is kind of usual in Android because the framework give us this kind of APIs. But I don't think that this as an Android specific rule.

**Comment by cortinico** [comment]
> non compliant:
> 
> ```kotlin
> class A(
>     var foo: Asdf?
> ) {
>   fun bar() {
>     if (foo != null) {
>       foo!!.toString()
>       doThings(foo!!.value)
>     }
>   }
> }
> ```

I believe the root of this rule should be "don't null check a mutable property". The multiple `!!` (or whatever null checks) are needed as `foo` is a nullable mutable property, and therefore checking if it's not null won't suffice to smart cast it to a `Asdf`.

**Comment by atulgpt** [comment]
Hi, @BraisGabin I think this issue got fixed by the above PR. right?
