### ISSUE TITLE
"Search" box on the docs site doesn't work

### ISSUE THREAD

**Issue by yogurtearl** [detekt/detekt#3357]
go here: https://detekt.github.io/detekt/
Enter name of a detekt rule in the search box to find the related docs.

## Expected Behavior

Shows docs for the searched rule

## Observed Behavior
 
Shows "no results found"

**Comment by schalkms** [comment]
Thanks for bringing this to our attention!
As described in #1077, this is a Jekyll issue. It does not support full text search.
The decision here is clearly **won't do**.

> Jekyll doesn't support full text search without any plugins or scripts. It's faster to search after a rule with Google, since the indices for the homepage work very well.

**Comment by BraisGabin** [comment]
Is it possible for us to remove the search feature? I agree that this is a wontdo but we could just remove it because it doesn't work.

**Comment by schalkms** [comment]
> Is it possible for us to remove the search feature? I agree that this is a wontdo but we could just remove it because it doesn't work.

It works as expected. You can search for pages and articles. However, you can't use full text search.
