### ISSUE TITLE
Deprecation rule baseline issue with Java sources

### ISSUE THREAD

**Issue by tasomaniac** [detekt/detekt#3367]
I have the following issue with Deprecation rule with type resolution enabled.
This happens only when the deprecated declaration is in Java code. When deprecated Java code is used in Kotlin, these are not included in baseline creation. I ran `detektBaselineDebug` task to create the baseline

But then when I run regular `detektDebug` task with type resolution, it is successfully reporting these issues.

## Expected Behavior

`detektDebug` and `detektBaselineDebug` should be consistent in terms of discovering issues

## Observed Behavior

`detektBaselineDebug` cannot include some issues that are detected successfully by `detektDebug`

## Steps to Reproduce

- Have a project with Java code deprecated and used in Kotlin
- Enable `Deprecation` rule
- run `./gradlew detektBaselineDebug` to generate a baseline
- run `./gradlew detektDebug` and see build failure.

## Potential Problem

When I observed the baseline created, I see that it mentions the deprecated entity instead of putting line numbers etc. That makes sense a lot. But maybe, it fails because the deprecated declaration is in Java and resolution fails.

**Comment by cortinico** [comment]
The behavior seems related to https://github.com/detekt/detekt/issues/3130 where the `include` of the two mentioned Detekt tasks were not aligned. If the `detektBaselineDebug` is filtering `.java` files out in the `include` of the task, the Java files will be ignored during the baseline creation.

I'm just supposing however, I need to look more into the issue, but hope this helps the investigation.

**Comment by tasomaniac** [comment]
I cannot believe that I didn't try with the latest version. My issue is already fixed in 1.15.0
