### ISSUE TITLE
New rule to enforce trailing commas

### ISSUE THREAD

**Issue by cortinico** [detekt/detekt#3398]
What's our take on trailing commas? 

Given them being optional, I saw them being slowly adopted in several codebases. I was thinking about a `UseTrailingComma` rule to enforce usages of trailing comma (I'm also wondering if this is our domain or is more something for KtLint).

### Compliant

```kotlin
val colors = listOf(
    "red",
    "green",
    "blue",
)
```

### Non-Compliant

```kotlin
val colors = listOf(
    "red",
    "green",
    "blue"
)
```

## Context

Ideally we could offer a couple of config options to:
- Exclude certain context (e.g. `excludeParameters` or `excludeArguments`).
- Exclude the single element scenario, like:
```kotlin
val colors = listOf(
    "red",
)
```

**Comment by chao2zhang** [comment]
The Kotlin official coding convention recommended:
```
Trailing commas are entirely optional – your code will still work without them. The Kotlin style guide encourages the use of trailing commas at the declaration site and leaves it at your discretion for the call site.
```
Like you described, we should have config options to configure declaration only or call site only.

I have also had colleagues disliking the trailing comma, so we should also provide a different rule to suppress using trailing comma 🙈

**Comment by schalkms** [comment]
I guess this is a duplicate of #2398. The referenced ktlint issue regarding this rule seems to be work in progress.

**Comment by cortinico** [comment]
oops 🤦 thanks for pointing out. Closing here.
