### ISSUE TITLE
Split `UnusedPrivateMember`

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#3418]
## Expected Behavior of the rule
This rule has gone way beyond reporting unused member, and covers properties, parameters, and member functions.
I would suggest a split at least for parameters vs (properties + functions).

## Context
This is triggered by reviewing #3417

**Comment by cortinico** [comment]
Agree. Plus what annoys me is that this is one of those rules with Mixed behavior (#2994). Ideally if we split it we can isolate the sections that require type resolution.

**Comment by schalkms** [comment]
> Agree. Plus what annoys me is that this is one of those rules with Mixed behavior (#2994). Ideally if we split it we can isolate the sections that require type resolution.

Yes, please. This is a very good suggestion.

**Comment by chao2zhang** [comment]
Since we already have 1.16-RC, I would postpone this till the next version.. Maybe Detekt 2.0?

**Comment by chao2zhang** [comment]
The bot is a great reminder that I have todo issues in my backlog.

**Comment by BraisGabin** [comment]
Should we consider this a breaking change? I splitted InvalidPackageName in two withoud considering it a breaking change. We can keep `UnusedPrivateMember` for one of the rules and adding another with a better name. Then, for 2.0 we could rename `UnusedPrivateMember` too.

**Comment by chao2zhang** [comment]
I don't consider it when both of the conditions are met:
- The original rule is enabled by default 
- After a split, both rules are still enabled by default
The change should have no impact if the user is not customizing their config.

**Comment by BraisGabin** [comment]
Agree, milestone removed.
