### ISSUE TITLE
Detekt HTML report has invalid link to https://arturbosch.github.io/detekt (404 error page)

### ISSUE THREAD

**Issue by ozmium** [detekt/detekt#3420]
## Expected Behavior
* The bottom of the `detekt.html` file (the auto-generated report file) should have a link to the current live website, of either https://detekt.github.io/  or https://github.com/detekt/detekt
* The text at the bottom of the file is "generated with detekt version x.x.x ...", which is where the link is.

## Observed Behavior
The `detekt.html` (the auto-generated report file) has a link to the old website, of  https://arturbosch.github.io/detekt , which gives a 404 error page.

## Steps to Reproduce
1. Integrate detekt into your gradle project file
2. Run the gradle task: `./gradlew detekt`
3. View and open the html report file in /Path/to/YourProject/app/build/reports/detekt/detekt.html
4. Scroll to the bottom of the page, and observe the text and click the link

## Context
Related Issue: https://github.com/detekt/detekt/issues/2805

## Your Environment

* Version of detekt used: 1.15.0 and also older versions like 1.7.1
* Version of Gradle used (if applicable): Not applicable
* Operating System and version: Any

**Comment by chao2zhang** [comment]
This is a great catch. Fix is linked!
