### ISSUE TITLE
Custom rule isn't checking

### ISSUE THREAD

**Issue by AlinaRakhimova** [detekt/detekt#3435]
## Expected Behavior of the rule
I want to write the custom rule which check that boolean variables have naming starts with "is/has".

## Context
I start command detektMain, but my custom rule is ignored.
Please check my example repository. Most likely I made some stupid mistake when connecting the plugin

https://github.com/AlinaRakhimova/customDetekt

**Comment by schalkms** [comment]
Yes, for this reason there’s a FAQ guide showing common pitfalls available. Did you already consult the following page?
https://detekt.github.io/detekt/extensions.html#let-detekt-know-about-your-extensions

**Comment by AlinaRakhimova** [comment]
Hi!
I did it for root gradle file instead of subprojects. Now it works perfectly. Thank you so much.
You can close this issue
