### ISSUE TITLE
Exceptions - Add rule that prohibits an object (Kotlin singleton) from extending any type of Throwable

### ISSUE THREAD

**Issue by mhernand40** [detekt/detekt#3436]
## Expected Behavior of the rule
Kotlin `objects` should _NOT_ be allowed to extend any type of `Throwable`.

**Noncompliant Code:**
```Kotlin
object FooException : RuntimeException()
```

**Compliant Code:**
```Kotlin
class FooException : RuntimeException()
```

## Context
`objects` in Kotlin are native singletons and remain in memory for the duration of the process. `Throwables`/`Exceptions` on the other hand should typically be instantiated on a case-by-case basis and thrown accordingly. `Throwables` are stateful and come packed with lots of information in their stack traces and may even reference another `Throwable` as the underlying `cause` and/or multiple `Throwables` in a mutable `List` of `suppressedExceptions`. By making an `object` extend a `Throwable` type, it automatically leads to stateful, thread unsafe singletons and it encourages reuse of global and stateful exceptions which can be thrown and referenced from various pleases from different threads. In my opinion, this would be a code smell.

**Comment by cortinico** [comment]
> In my opinion, this would be a code smell.

I generally agree with this rule. However do you have some more concrete examples? Like in which scenario you feel that someone would use a object to represent an `Exception`?

I just wanted to make sure that, if we add a rule to detekt, it serves some real-word scenarios

**Comment by mhernand40** [comment]
> > In my opinion, this would be a code smell.
> 
> I generally agree with this rule. However do you have some more concrete examples? Like in which scenario you feel that someone would use a object to represent an `Exception`?
> 
> I just wanted to make sure that, if we add a rule to detekt, it serves some real-word scenarios

In the code base I currently work out of, I have seen several developer make this mistake and we currently have a decent number of violations, ~20. For some reason I am seeing that devs tend to favor `object` over `class`, which may be a concern in and of itself, but I find it even more problematic when it comes to custom exceptions. Some hypothetical examples that are similar to code I have seen are as follows:
```Kotlin
object BanException : RuntimeException(…)
object AuthException : RuntimeException(…)
```
as well as
```Kotlin
sealed class DomainSpecificException : IllegalStateException() {
    data class FooException(val prop1: Prop1, val prop2: Prop2) : DomainSpecificException
    object BarException : DomainSpecificException("Bar exception") // <-- Violation
    object BazException : DomainSpecificException("Baz exception") // <-- Violation
}
```

Before going the route of introducing a custom Detekt rule in in the code repo I work out of, I figured the Kotlin community overall would benefit from this rule. This rule would require type resolution, i.e., `detektMain`.

**Comment by BraisGabin** [comment]
It seems like a good rule to me. Do you want to provide the implementation?

**Comment by schalkms** [comment]
Looks fine! Thanks for outlining different scenarios. Please go for it. 🙂

**Comment by cortinico** [comment]
Great, thanks for sharing your specific scenario. I think it's going to be a great addition 👌

**Comment by mhernand40** [comment]
Sure, I can take this on. Thank you everyone 🙂

**Comment by BraisGabin** [comment]
😂 I just review a PR at work that had exactly this issue.
