### ISSUE TITLE
I cannot apply option when I execute detekt.

### ISSUE THREAD

**Issue by marcelop3251** [detekt/detekt#3441]
I searched the problem, but I can't found any relation.

I config detekt with help of maven. Conform as shown below.

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-antrun-plugin</artifactId>
  <version>1.8</version>
  <executions>
	  <execution>
		  <!-- This can be run separately with mvn antrun:run@detekt -->
		  <id>detekt</id>
		  <phase>compile</phase>
		  <configuration>
			  <target name="detekt">
				  <java taskname="detekt" dir="${basedir}"
							  fork="true"
							  failonerror="true"
							  classname="io.gitlab.arturbosch.detekt.cli.Main"
							  classpathref="maven.plugin.classpath">
				  </java>
				  <arg value="--config"/>
				  <arg value="${basedir}/detekt.yml"/>
			  </target>
		  </configuration>
		  <goals><goal>run</goal></goals>
	  </execution>
  </executions>
  <dependencies>
	  <dependency>
		  <groupId>io.gitlab.arturbosch.detekt</groupId>
		  <artifactId>detekt-cli</artifactId>
		  <version>1.16.0-RC1</version>
	  </dependency>
  </dependencies>
</plugin>
```

And it executed, but i would like to config a new detekt.yml so I created file with the help detekt-clie and put the values and some some rules. After that I executed again and I didn't see that it not use my detekt.yml instead it used the default.
```
<arg value="--config"/>
<arg value="${basedir}/detekt.yml"/>
```
I also receive this message after run.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (detekt) on project my-projet: An Ant BuildException has occured: Java returned: 2
[ERROR] around Ant part ...<java fork="true" classname="io.gitlab.arturbosch.detekt.cli.Main" taskname="detekt" failonerror="true" dir="/home/user/Documents/workspace/my-projet" classpathref="maven.plugin.classpath"></java>... @ 4:216 in /home/user/Documents/workspace/my-projet/target/antrun/build-detekt.xml

I belive the settings are correct. Any idea what it migth be?

Please if aren't let me know.

**Comment by cortinico** [comment]
Have you considered using a Detekt Maven plugin: https://github.com/Ozsie/detekt-maven-plugin

**Comment by marcelop3251** [comment]
Hey Cortinico, this plugin is Unofficial and I prefer use only official.

**Comment by cortinico** [comment]
I'm unable to help you then. We don't really have an official Maven Plugin other than this page: https://detekt.github.io/detekt/mavenanttask.html

Are you able to run detekt from CLI with the custom configuration and the `--config` flag?

**Comment by marcelop3251** [comment]
No problem, I appreciate you help.

I configured my pom.xml looking at this page hehe and yes I able to run detekt from CLI with the custom configuration.

I will do some test with gradle.

Thank you so much.

**Comment by cortinico** [comment]
If you happen to find the solution, please let us know so we can update the page 👍

**Comment by hotlib** [comment]
I have exactly the same problem, did anyone find a solution?
