### ISSUE TITLE
Detekt doesn't find with and without type resolution mistakes with detektMain command

### ISSUE THREAD

**Issue by AlinaRakhimova** [detekt/detekt#3444]
HI!

## Expected Behavior of the rule
There is custom rule with type resolution to give the boolean variable names correctly.
I want to use one detekt command to find all types of mistakes.

## Context
I added large line and mistake for my custom rule in my project. 
Command DetektMain was run. Detekt found mistake by my custom rule, but didn't find mistake by default rule "MaxLineLength".
When I fix code with Boolean naming mistake and run command again Detekt find "MaxLineLength" mistake.

**Comment by cortinico** [comment]
Hey @AlinaRakhimova 

Can you provide a bit more context? For example having access to your project or a reproducer would be beneficial to understand if there is a bug.

If you can't share the project, please provide the gradle file you're using for configuring detekt.

> When I fix code with Boolean naming mistake and run command again Detekt find "MaxLineLength" mistake.

This happens as you're probably fixing a mistake in the code and making the line too long. You can tune the configuration for `MaxLineLength` using the config file or you can simply reformat your code.

**Comment by AlinaRakhimova** [comment]
I can't share my project. My gradle file:

buildscript {

    apply from: 'gradle_common/version.gradle'
    apply from: 'gradle_common/dependencies.gradle'

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:perf-plugin:1.3.1'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        classpath 'org.apache.commons:commons-csv:1.7'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${project.ext.kotlin}"
        classpath "org.jetbrains.kotlin:kotlin-serialization:1.4.10"
    }
}

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.15.0"
}

detekt {
    version = "1.15.0"
    input = files(".")
    config = files("default-detekt-config.yml")
}

tasks.withType(io.gitlab.arturbosch.detekt.Detekt) {
    exclude(".*/resources/.*,.*/build/.*")
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.google.com/' }
        maven { url "https://maven.mozilla.org/maven2/" }
    }
}

subprojects {
    apply {
        plugin("io.gitlab.arturbosch.detekt")
    }

    detekt {
        config = rootProject.files("default-detekt-config.yml")
        reports {
            html {
                enabled = true
                destination = file("build/reports/detekt.html")
            }
        }
    }

    dependencies {
        detektPlugins project(path: ':custom_detekt_rules', configuration: 'default')
    }
}

**Comment by AlinaRakhimova** [comment]
> This happens as you're probably fixing a mistake in the code and making the line too long. You can tune the configuration for MaxLineLength using the config file or you can simply reformat your code

You didn't understand. 
First, I have two mistakes in my code - "MaxLineLength" and custom naming mistake - in the different parts of project.
But Detekt only found custom mistake and didn't find the second mistake. Next, I fix it and run detektMain command again. Then detekt will find the second mistake too.
I want the detekt to find both mistakes at the same time

**Comment by AlinaRakhimova** [comment]
I do this mistakes to check my custom rule and run the command detekt with type resolution

**Comment by BraisGabin** [comment]
The issue that you reports is really strange. The spected behavior of detekt is what you want. Could you create a sample project to reproduce the issue?

Does your custom rule implemet the auto correct feature? or edit the KtFiles in any way?

**Comment by AlinaRakhimova** [comment]
I found the reason.
I called super methods in fun visitXXX() after my own code.
Thank you so match for you time!
