### ISSUE TITLE
Upgrade to 0.7.2 of kotlinx-html-jvm

### ISSUE THREAD

**Issue by ber4444** [detekt/detekt#3461]
## Expected Behavior
Can build without Jcenter which is going away soon. Use mavenCentral only.

## Observed Behavior
```
  > Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.1.
     Required by:
         project :ocr > io.gitlab.arturbosch.detekt:detekt-cli:1.7.4
```

## Steps to Reproduce
Run the detekt Gradle task.

## Context
0.7.2 is published but not 0.7.1: https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-html-jvm?repo=kotlinx

**Comment by ber4444** [comment]
Ok, I see it's in progress at https://github.com/detekt/detekt/pull/3455

**Comment by cortinico** [comment]
kotlinx-html is not hosted on Central. We have to wait for JetBrains to move it and then we can merge #3455

**Comment by ber4444** [comment]
The latest version of `kotlinx-html` is on Central, check the link I posted above. Also commented on https://github.com/Kotlin/kotlinx.html/issues/173

**Comment by ber4444** [comment]
ok, let's wait for https://github.com/Kotlin/kotlinx.html/issues/173

**Comment by Tapac** [comment]
kotlinx.html 0.7.3 was published to JetBrains repo, see [comment](https://github.com/Kotlin/kotlinx.html/issues/173#issuecomment-806910768)

**Comment by BraisGabin** [comment]
Yeap, if someone is in a hurry to remove `jcenter()` could add `https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven`. But I think that we shouldn't add that to our documentation.

**Comment by malenalbc** [comment]
Problem is latest version 1.16.0 has an earlier, not supported, dependency:
```
   Required by:
         project > io.gitlab.arturbosch.detekt:detekt-cli:1.16.0 > io.gitlab.arturbosch.detekt:detekt-bom:1.16.0
   > Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.2.
  Searched in the following locations:
       - https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom
```
[Version available in `maven.pkg.jetbrains.space` is `0.7.3`](https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven/org/jetbrains/kotlinx/kotlinx-html-jvm/)

**Comment by chao2zhang** [comment]
@malenalbc I see that 0.7.2 is in [the jetbrains.space link](https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/). Is it working for you if you define a custom maven() repository pointing to jetbrains.space?

**Comment by Tapac** [comment]
@chao2zhang , yes, it works fine when I replace `jcenter` with `maven("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")`

**Comment by malenalbc** [comment]
@chao2zhang Yeah, I can see it now but the url it tries to resolve within the space doesn't exist:

`     maven { url "https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven" }`
```
Execution failed for task ':app:detekt'.
> Could not resolve all files for configuration ':app:detekt'.
   > Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.2.
     Searched in the following locations:
       - https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom
     Required by:
         project :app > io.gitlab.arturbosch.detekt:detekt-cli:1.16.0 > io.gitlab.arturbosch.detekt:detekt-bom:1.16.0
```

**Comment by Tapac** [comment]
@malenalbc , the link to pom file looks strange, it should be:
https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom

**Comment by alvindizon** [comment]
@Tapac what's the fix then?
