### ISSUE TITLE
Can not suppress too long line with infix functions

### ISSUE THREAD

**Issue by wyhasany** [detekt/detekt#3480]
## Expected Behavior
I cannot suppress too long line with infix functions which cannot be broken in multilines

## Observed Behavior
Imagine following line:
```kotlin
@Suppress("MaxLineLength", "MaximumLineLength")
await withPollInterval ONE_HUNDRED_MILLISECONDS atMost THIRTY_SECONDS ignoreException ConnectException::class untilAsserted {
  //...
}
```
when it exceeds limit of line @Suppress won't help. The very same is visible on following printscreen:
![image](https://user-images.githubusercontent.com/317662/108207587-411d4580-7128-11eb-8df1-b22c542648c0.png)

## Steps to Reproduce
Write too long infix functions line and try to suppress. In my case I've used awaitility Kotlin's DSL.

## Your Environment
* Version of detekt used: 1.15.0

**Comment by wyhasany** [comment]
There is following workaround (extracting local variable):
![image](https://user-images.githubusercontent.com/317662/108209026-13390080-712a-11eb-87f8-a11a92b725b0.png)

**Comment by cortinico** [comment]
Would you be able to provide a reproducer? This will help us fix this issue faster

**Comment by BraisGabin** [comment]
I'm on my phone now so I can't check it but isn't this rule from ktlint? We have real problems suppressing those. I think that we just support suppressing in all the file with `@file:Suppress("MaxLineLength")`.

**Comment by cortinico** [comment]
> isn't this rule from ktlint? We have real problems suppressing those

Yes you're right this is from KtLint.

**Comment by wyhasany** [comment]
Sorry for delay. you're correct it happens because of `ktlint` it can be solved as you mentioned:
![image](https://user-images.githubusercontent.com/317662/108556725-c0ad3f00-72f7-11eb-81e8-5f16d4895116.png)

Here is sample project, I've added a class to play around org.awaitility.kotlin.KotlinTest
[kutils.zip](https://github.com/detekt/detekt/files/6012698/kutils.zip)

is it expected behavior? Maybe it would be enough to document it somewhere or add additional description in report? btw thanks for awesome support!

**Comment by cortinico** [comment]
Thanks for the reproducer @wyhasany 

Yes, it's the intended behavior but I understand is suboptimal. In this case we have a rule that offers this more fine grain control over suppression (`MaxLineLength` instead of `MaximumLineLength`).

I've updated the docs to make this more clear #3503
