### ISSUE TITLE
Exclude not working.

### ISSUE THREAD

**Issue by alexanderbezverhni** [detekt/detekt#3481]
## Expected Behavior
Files with matching pattern are getting excluded from `Detekt` checks.

## Observed Behavior
Files with matching pattern are **not** getting excluded from `Detekt` checks.

## Steps to Reproduce
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath("io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.15.0")
    }
}

allprojects {
    apply plugin: "io.gitlab.arturbosch.detekt"
}

subprojects {
    detekt {
        parallel = true // Can lead to speedups in larger projects. `false` by default.
        buildUponDefaultConfig = true // Interpret config files as updates to the default config. `false` by default.
        config = files("$rootDir/detekt/config.yml") // This config is applied to all modules.

        def baselineFile = project.file("detekt-baseline.xml")
        if (baselineFile.exists()) {
            baseline = baselineFile
        }

        reports {
            xml.enabled = true
            html.enabled = true
            txt.enabled = false
            sarif.enabled = false
        }
    }
}

tasks.withType(io.gitlab.arturbosch.detekt.Detekt).configureEach {
    exclude("**/graphqlTemp/**") // exclude temp Apollo GraphQL classes
}
```

```
./gradlew module-name:detekt
```

## Context
We are running custom Gradle task that runs `:detekt` task for every module in our multi-module project.

## Your Environment
* Version of detekt used: `1.15.0`
* Version of Gradle used (if applicable): `6.6`
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: macOS Catalina, 10.15.4
* Link to your project (if it's a public repository):

**Comment by cortinico** [comment]
> tasks.withType(io.gitlab.arturbosch.detekt.Detekt).configureEach {
>     exclude("**/graphqlTemp/**") // exclude temp Apollo GraphQL classes
> }

The problem is that you need to move your `tasks.withType` either:
- Inside the `subprojects` block
- In the `build.gradle` files of the projects where you want the exclude to be applied

In your current script you're applying the exclude only on the `detekt` task on the top level project

**Comment by alexanderbezverhni** [comment]
@cortinico Thank you for the prompt response Nicola!
