### ISSUE TITLE
Was passed main parameter

### ISSUE THREAD

**Issue by nailshakurov** [detekt/detekt#3516]
![image](https://user-images.githubusercontent.com/11345578/110119114-c5ccbc80-7dd4-11eb-88db-ac79ea88c76b.png)
What is the problem?

**Comment by cortinico** [comment]
The problem is that if you invoke with `--baseline` you need to pass the path to the baseline file.
So the invocation will be something like:

```
./detekt-cli-1.15.0/bin/detekt-cli --baseline <path-to-your-baseline.xml-file>
```
