### ISSUE TITLE
Add compiler plugin to main project

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#3520]
## Expected Behavior
Recommend detekt-compiler-plugin to enable type resolution.

## Current Behavior

Manual setup or flaky automated creation of Gradle tasks to enable features requiring type resolution.

## Context

Make type resolution easier to activate and faster during builds.

**Comment by cortinico** [comment]
> Recommend detekt-compiler-plugin to enable type resolution.

Following up to your comment here: https://github.com/detekt/detekt/issues/3327#issuecomment-791871644
I agree that the long term recommendation should be to suggest the compiler plugin.
However, I'll refrain from suggesting it till is fully production ready. The Gradle plugin we offer right now is battle tested while I am unaware of anyone using the compiler-plugin.

**Comment by 3flex** [comment]
Works on my machine :)

As a starting point the code could be brought into the main project and some documentation added. That would at least help with visibility.

It also needs to get feature parity with the existing Gradle plugin. I think it's only baseline generation that's missing.

**Comment by BraisGabin** [comment]
I agree with @3flex here. If we want to give it visibility we need to me it here an add some documentation about it. This way some people will start using it and they will report any issues or lack of information in the documentation so we can promote it to stable.

So... any ideas? Would it be enought to add a new gradle module in the project with it? @3flex do you want to make the PR?

Things to do:
- Move code to the main repo
- Add baseline generation
- Add documentation so anyone can try it out but knowing that it's in alpah state.

Am I missing something?

**Comment by chao2zhang** [comment]
The other gap (probably a feature request) is to configure output reporting. Command-line may not always be machine-readable.

**Comment by 3flex** [comment]
It may be better to target the K2 compiler plugin API instead, which is planned for stabilisation: https://youtrack.jetbrains.com/issue/KT-49508

It means waiting longer to do this, but in addition to allowing us to target a stable API, it should provide support for type resolution on non-JVM platforms thanks to the unified compiler front-end.

**Comment by chao2zhang** [comment]
@3flex That's my exact thought as well when I was watching https://youtu.be/iTdJJq_LyoY?t=1393
