### ISSUE TITLE
SwallowedException: Multi-line code block renders wrong in docs

### ISSUE THREAD

**Issue by sschuberth** [detekt/detekt#3523]
This

https://github.com/detekt/detekt/blob/2fbb7c99e171648bc458e7fb25909881528de52b/detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedException.kt#L67-L70

[renders](https://detekt.github.io/detekt/exceptions.html#swallowedexception) like

![image](https://user-images.githubusercontent.com/349154/110237736-d3518600-7f3d-11eb-9cf4-23893aaded9e.png)

I'm not quite sure how to fix this in the best way, though.

**Comment by sschuberth** [comment]
Hmm, I started looking into this, but some magic that I don't understand seems to be going on. When running

    ./gradlew :detekt-generator:generateDocumentation --build-cache --parallel

the generated `docs/pages/documentation/exceptions.md` contains double-backticks like

```
#### Configuration options:

* ``ignoredExceptionTypes`` (default: ``- InterruptedException
    - NumberFormatException
    - ParseException
    - MalformedURLException``)

   exception types which should be ignored by this rule
```

Is that intended? As it seems unnecessary, and all double-backticks should be single backticks.

**Comment by schalkms** [comment]
I think this is a bug in the `RuleSetPagePrinter.kt`. Multi-line code configurations are not supported, as it seems like.

https://github.com/detekt/detekt/blob/master/detekt-generator/src/main/kotlin/io/gitlab/arturbosch/detekt/generator/printer/rulesetpage/RuleSetPagePrinter.kt

**Comment by sschuberth** [comment]
> As it seems unnecessary, and all double-backticks should be single backticks.

That particular bug seems to stem from

https://github.com/detekt/detekt/blob/2fbb7c99e171648bc458e7fb25909881528de52b/detekt-generator/src/main/kotlin/io/gitlab/arturbosch/detekt/generator/out/Markdown.kt#L42

But I agree there seem to be multiple bugs. I'll look into them.

**Comment by schalkms** [comment]
> But I agree there seem to be multiple bugs. I'll look into them.

Thank you! 🙂

**Comment by BraisGabin** [comment]
The double quote is intended. We have some code blocks that contains a single `` ` `` for example ``fun `hola`()`` if we use single quote this happen: `fun `hola`()`

**Comment by sschuberth** [comment]
@BraisGabin please have a look at https://github.com/detekt/detekt/pull/3545.

**Comment by BraisGabin** [comment]
Thanks! https://detekt.github.io/detekt/naming.html at the function naming you can see the issue without the double backtick

**Comment by sschuberth** [comment]
So for the lazy ones (like me), at https://detekt.github.io/detekt/naming.html#functionnaming 😉
