### ISSUE TITLE
SwallowedException: ignore ParseException with version 1.16.0-RC3

### ISSUE THREAD

**Issue by sschuberth** [detekt/detekt#3524]
## Expected Behavior

`SwallowedException` by default should not be reported when rethrowing as a `ParseException` [according to the docs](https://detekt.github.io/detekt/exceptions.html#swallowedexception).

## Observed Behavior

`SwallowedException` is reported when using the default config and rethrowing a `ParseException`:

```
> Task :lib:detekt FAILED
exceptions - 40min debt
        SwallowedException - [reader] at C:\Users\sebastian\Development\GitHub\sschuberth\stan\lib\src\main\kotlin\parsers\PostbankPdfParser.kt:95:11
        SwallowedException - [<anonymous>] at C:\Users\sebastian\Development\GitHub\sschuberth\stan\lib\src\main\kotlin\parsers\PostbankPdfParser.kt:129:19

Overall debt: 40min
```

## Steps to Reproduce

- Checkout `detekt-bug` branch of https://github.com/sschuberth/stan
- Run `./gradlew --no-build-cache --rerun-tasks detekt`.

## Your Environment
* Version of detekt used: 1.16.0-RC3
* Version of Gradle used (if applicable): 6.8.3
* Operating System and version: Windows 10 x64
* Link to your project (if it's a public repository): https://github.com/sschuberth/stan

**Comment by sschuberth** [comment]
I was wondering why the belonging test passes, but it seems to me as if the test is actually implemented in "reverse", see

https://github.com/detekt/detekt/blob/2fbb7c99e171648bc458e7fb25909881528de52b/detekt-rules-exceptions/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedExceptionSpec.kt#L216-L226

But shouldn't it rather be

```
try {
} catch (e: Exception) {
    throw ${exceptionName}("")
}
```

as the point of the exception to the rule is to *allow* rethrowing *without* passing `e` if the rethrown exception's constructor has no way to pass `e`?

**Comment by sschuberth** [comment]
In fact, to me it seems the rule itself is implemented in the wrong way regarding the ignored exceptions:

https://github.com/detekt/detekt/blob/2fbb7c99e171648bc458e7fb25909881528de52b/detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedException.kt#L92-L94

This applies the ignored exceptions to the exception in the `catch` clause, whereas it should be applied to the rethrown exception in the `catch` body, or?

**Comment by cortinico** [comment]
Is this something that is happening only in RC3? Can I ask you to try `1.15.0`, `1.16.0-RC1` and `1.16.0-RC2`? I'm trying to understand if this is a regression we introduced or not.

**Comment by sschuberth** [comment]
Unfortunately, I cannot (easily) try with any version below `1.16.0-RC3` as I seem to be affected by (a variant of) https://github.com/detekt/detekt/issues/3248 in these (I'm getting a `kotlin/UninitializedPropertyAccessException`). 

I'm already looking into contributing a fix, but I'd first like to get a common understanding of *how* the ignoring *should* work: Should it apply to the exception in the `catch` *clause* (which IMO makes not so much sense), or to the exception in the `catch` *body* (which makes more sense IMO), or both?

**Comment by sschuberth** [comment]
I went for the "for both" approach to not break backward compatibility in https://github.com/detekt/detekt/pull/3525.

**Comment by schalkms** [comment]
I think it's okay to do ignore it in both cases. This is an improvement and not really a bug.

**Comment by sschuberth** [comment]
> I'm trying to understand if this is a regression we introduced or not.

BTW, I don't think it's a regression. It's just that version 1.16.0 started to active this rule by default; it probably never was implemented correctly.

**Comment by sschuberth** [comment]
> This is an improvement and not really a bug.

So, you're saying that the current behavior to ignore the exception in the *clause* is intended? I'd then be curious about the rationale for the choice of the by default ignored exceptions.

As I wrote in the PR, ""What all by default ignored exceptions have in common is that none of their constructors allows to pass an exception as the cause. Thus, it does not make sense to complain when these are used in the catch body to replace the original exception". That's the rationale of ignoring these exceptions in the *body*. What's the corresponding rationale to (also) ignore them in the *clause*?

**Comment by schalkms** [comment]
The rationale behind this is that the mentioned ignored exceptions were considered just for the given catch clause but not for the throw clause. Detekt hasn't had any reports for ignoring the specified exceptions also in the throw clause. That's why it wasn't considered. You are actually the first one to report this scenario.

**Comment by sschuberth** [comment]
> the mentioned ignored exceptions were considered just for the given catch clause but not for the throw clause.

But *why* were they just considered for the catch clause? Why would you allow to swallow an exception based on what the *original* exception was?

I *guess* the real rationale was that people tend to write code like

```
val isValid = try {
    // Parse
    true
} catch (e: ParseException) {
    // Swallow
    false
}
```

which would have otherwise triggered a *detekt* issue. But for such cases I would have argued `runCatching {}` should be used instead.

**Comment by schalkms** [comment]
> But why were they just considered for the catch clause? Why would you allow to swallow an exception based on what the original exception was?

I browsed through the history of the rule. I now can give you more detailed answers.

As it seems like, detekt includes a rule similar to the one in [Sonar Java](https://rules.sonarsource.com/java/RSPEC-1166?search=exception). If you take a look at the description of the rule, you can see the reason for this implementation in the **exceptions** section.
#1342 contains the initial draft of this config option.
Maybe the reason should be stated in the rule description in order to recall it later on.
What do you think, Sebastian? Does this answer your question?

> InterruptedException, NumberFormatException, DateTimeParseException, ParseException and MalformedURLException exceptions are arguably used to indicate nonexceptional outcomes. Similarly, handling NoSuchMethodException is often required when dealing with the Java reflection API.
> 
> Because they are part of Java, developers have no choice but to deal with them. This rule does not verify that those particular exceptions are correctly handled.

**Comment by sschuberth** [comment]
> Does this answer your question?

Yes, thanks a lot for digging this out; that's finally a proper rationale.
