### ISSUE TITLE
Switch SARIF report off jackson

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#3542]
We probably still want to leverage JSON encoding/decoding library. The Android Lint https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:lint/cli/src/main/java/com/android/tools/lint/SarifReporter.kt does not feel that good to emit handcrafted JSON.

We also need to keep our bundle size down, and from https://medium.com/@dannydamsky99/heres-why-you-probably-shouldn-t-be-using-the-gson-library-in-2018-4bed5698b78b we know that Jackson is probably the largest among all other well-known options with a high method count.

**Comment by BraisGabin** [comment]
I imagine that you read #3045 and the reason to use Jackson. I think like you, jackson is far too heavy and it doesn't have sense that we need to sort the JSON entries. That doesn't follow the JSON standard. I'd vote to use moshi or kotlinx.serialization (I prefer the first one but I don't know any good reason to not use the second).

**Comment by chao2zhang** [comment]
Specifically about
https://github.com/detekt/detekt/issues/3045#issuecomment-688960454 
https://github.com/detekt/detekt/issues/3045#issuecomment-689039863

Yes, I am just stating that Jackson is the worst, I agree that we should try other libraries.

**Comment by cortinico** [comment]
> I'd vote to use moshi or kotlinx.serialization (I prefer the first one but I don't know any good reason to not use the second).

I'm in for both. Potentially would pick `kotlinx.serialization` given that we already use `kotlinx.html` but nothing prevents us from picking moshi

**Comment by schalkms** [comment]
> Potentially would pick kotlinx.serialization given that we already use kotlinx.html

Agree +1

**Comment by chao2zhang** [comment]
We need first to convert the [SARIF json schema](https://github.com/oasis-tcs/sarif-spec/blob/master/Schemata/sarif-schema-2.1.0.json) into the specific POJO that is compatible with the serialization framework (moshi or kotlinx).
- For moshi, there is a popular tool [jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo) to convert JSON schema to moshi-compatible pojo. However, even with these POJOs, we still have Kotlin specific wrappers like https://github.com/detekt/detekt/blob/master/detekt-report-sarif/src/main/kotlin/io/github/detekt/report/sarif/SarifDsl.kt
- For kotlinx, there is no popular tool to convert JSON schema to POJO. The one I can find is https://github.com/Ricky12Awesome/json-schema-serialization which does not seem mature enough.  Meanwhile, there are still applications like https://github.com/quicktype/quicktype to generate the POJO manually.

Assuming SARIF schema is not updated often (last update was March 2020), I am inclined to and will begin with generating the POJO manually using https://github.com/quicktype/quicktype.
