### ISSUE TITLE
Add more info about rules to website

### ISSUE THREAD

**Issue by rock3r** [detekt/detekt#3568]
It would be great if the website would display the following info about the rules:

 * Is it on by default
 * Which version it was introduced in

Right now, the first info is only found in the default detekt configuration file on the repo, and the latter is not available easily anywhere. It's a bit of a pain.

**Comment by rock3r** [comment]
CC @cortinico 🙌

**Comment by chao2zhang** [comment]
+1 to this issue. I thought I had open an issue for this.

Here is a proposal to use annotation to represent metadata. https://github.com/detekt/detekt/issues/3562

**Comment by schalkms** [comment]
Yep, this is a good idea. I think having the ideas collected in #3562 and probably some subsequent issues if necessary is the key here. Therefore, I'm marking this as a duplicate. Feel free to share further ideas with others in #3562.
