### ISSUE TITLE
Detect type resolving rules run without type resolution classpath set

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#3577]
This is raised from https://github.com/detekt/detekt/issues/3537#issuecomment-795846800. 
1. If the type resolution classpath is not set, but there are active type resolving rules, we should print out warnings to remind users.
2. We can also skip type resolving rules if type resolution classpath is not set.
3. We probably need to wait for #3562 to be implemented.

**Comment by cortinico** [comment]
> We can also skip type resolving rules if type resolution classpath is not set.

We're basically already doing it, no?

**Comment by chao2zhang** [comment]
What I was looking for `Rule.isActive()` should be false for those type resolving rules without classpath set. In SARIF output, we should show the active rules run.

**Comment by cortinico** [comment]
> 1. we should print out warnings to remind users.

I'm unsure about this. We might have users that are fine having rules enabled only on `detektMain` and not on `detekt`. Perhaps the warning should be configurable?

I'm also wondering what was the original use case of this feature request.

**Comment by cortinico** [comment]
> 1. If the type resolution classpath is not set, but there are active type resolving rules, we should print out warnings to remind users.

Following up here: we could add a warning when we do the _if bindingContext is empty_ check that instead of just returning it's printing something like "Rule xyz was skipped because Type Resolution is not available".

**Comment by eygraber** [comment]
> I'm unsure about this. We might have users that are fine having rules enabled only on detektMain and not on detekt. Perhaps the warning should be configurable?

Yes please :smile: 

My detekt runs just got very noisy with 1.22.0-RC1. I have one config file that contains all the enabled rules for my project, but I sometimes run detekt without type resolution.

**Comment by BraisGabin** [comment]
Could you open this as a new issue? You can link there this issue to haver better context.

**Comment by eygraber** [comment]
https://github.com/detekt/detekt/issues/5334
