### ISSUE TITLE
Reformat the project

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3593]
I remember that Arthur talked about this time ago and we decide not to do it but maybe now is the time. #3579 has a lot of changes that provides 0 information about what the PR really does. The problem is that the old code isn't properly formatted.

I vote to activate the formatting plugin of detekt or add ktlint to the project directly so we ensure that the format in all the code is consistent. This will create a big PR changing a lot of lines but we know that those changes doesn't affect the behaviour so they are safe.

**Comment by marschwar** [comment]
+1

**Comment by cortinico** [comment]
Yup, I'd say let's apply the formatting plugin so we have a direct way to test it on the repo.
