### ISSUE TITLE
Standardize `KotlinType.getJetTypeFqName`

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#3605]
We have several references to 
`org.jetbrains.kotlin.js.descriptorUtils.getJetTypeFqName(printTypeArguments: kotlin.Boolean)` but the package path is really weird. This method is not JS specific per its [source code](https://github.com/JetBrains/kotlin/blob/29b23e79f32791e456a5b4a453277f0f0b3e984d/js/js.frontend/src/org/jetbrains/kotlin/js/descriptorUtils/descriptorUtils.kt#L22-L41). Below are the list of potential solutions:
- Make contributions to Kotlin to move this to a platform-agnostic package
- Copy this into detekt-psi-utils

**Comment by BraisGabin** [comment]
> Make contributions to Kotlin to move this to a platform-agnostic package 

At least an issue, I agree.

I think that if we know that it's a kotlin issue we should do nothing. As soon as they fix it we can change the import.

**Comment by cortinico** [comment]
I've opened a thread here https://kotlinlang.slack.com/archives/C7L3JB43G/p1616756284026500
