### ISSUE TITLE
Correct ExplicitCollectionElementAccessMethod rule

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#3609]
## Expected Behavior of the rule
The rule picks up all usage of `get` and `set` indexed access operators, as well as calls to `put` on any class that implements `MutableMap` or `AbstractMap`.

## Context
Right now the rule only picks up usage of `get` on `Map`, `MutableMap`, `List`, `MutableList`, `AbstractList` and `AbstractMap`, and `put` on `MutableMap` and `AbstractMap`.

`set` is not detected at all.

The rule is unfortunately named in a way that it only applies to collection elements, though you can technically (though shouldn't) override the `get` and `set` operators on any class. But this is probably OK to leave as is.

**Comment by BraisGabin** [comment]
I agree that the naming is not so great but I think that this rule should check for all the usages of `operator get`, `operator set` and `operator put`. But probably this change should imply a change in the rule name.

**Comment by 3flex** [comment]
Perhaps a new, configurable rule for enforcing use of operators generally? It can cover all operator types, not just `get` and `set`, with flags to enable or disable checks for each operator type (e.g. you might want to enable for indexed access operators but disable for comparison operators). I'd enable all checks by default.

`put` is a funny one because it works the same as `set` on mutable maps but isn't actually an operator, so it would be an awkward fit for that potential new rule covering operator usage, but it also sort of logically belongs. Maybe it could have its own flag.

**Comment by BraisGabin** [comment]
I like the idea! I'd disable some of them in my code bases (`invoke`, `plus`...) but that's just a taste preference.

This rule will deprecate `ExplicitCollectionElementAccessMethod`, right?

**Comment by 3flex** [comment]
Yes, if it was a new rule to check operators then I'd say the old rule should be deprecated and eventually removed.

**Comment by Whathecode** [comment]
Possibly obsolete since the following PR was merged: https://github.com/detekt/detekt/pull/4201/

However, there are still things mentioned here (such as renaming the rule), which seem to be [reiterated in other open issues for this rule](https://github.com/detekt/detekt/issues/4918#issuecomment-1163715942).
