### ISSUE TITLE
Must upgrade kotlinx-html-* to 0.7.3

### ISSUE THREAD

**Issue by ber4444** [detekt/detekt#3642]
## Expected Behavior
Be able to get rid of jcenter and use 0.7.3 published in the jetbrains repo, see https://github.com/Kotlin/kotlinx.html/issues/173

## Current Behavior
Need to use jcenter which is being decommissioned real soon

**Comment by chao2zhang** [comment]
Hello @ber4444 , thanks for reporting. This is under our radar
- Our gradle [build file](https://github.com/detekt/detekt/blob/main/settings.gradle.kts) includes jCenter only for `kotlinx-html-jvm`
- We are also tracking the issue under https://github.com/detekt/detekt/pull/3455

**Comment by chao2zhang** [comment]
Please feel free to reopen in you have new information.
