### ISSUE TITLE
Support Codeclimate/GitLab report format

### ISSUE THREAD

**Issue by cromefire** [detekt/detekt#3668]
## Expected Behavior

Support for a report format for the [codeclimate format](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md) (or at least the [GitLab subset](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool) of it).

## Current Behavior

No direct report format is available and I can't find any converters for sarif or checkstyle to codeclimate/gitlab.

## Context

[GitLab supports code quality reports](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html) via it's CI. For it to create that report the tool has to support the [GitLab supported subset](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool) of the [codeclimate spec](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md).

**Comment by chao2zhang** [comment]
Hello @cromefire. If you could provide the list of static analysis tools that are supporting `codeclimate format`, that could help us to determine whether Detekt needs to provide first-party support for it. It seems cumbersome for Detekt to support a variety of output reports. 

- Recently we added SARIF format output in 1.16.0 and there is a trending thread https://gitlab.com/gitlab-org/gitlab/-/issues/118496 to discuss adding SARIF support for GitLab.
- Alternatively, you could build [custom extension](https://detekt.github.io/detekt/extensions.html#custom-reports) that would fit your case.

**Comment by cromefire** [comment]
> f you could provide the list of static analysis tools that are supporting `codeclimate format`

codeclimate itself (+ their engines) which is what GitLab uses internally, pmd, flake8 (3rd party), ansible-lint and probably some more, that's what I found with a quick google search.

> Recently we added SARIF format output in 1.16.0 and there is a trending thread https://gitlab.com/gitlab-org/gitlab/-/issues/118496 to discuss adding SARIF support for GitLab.

I agree, that would probably be the ideal case, but having seen the lifecycle a few issues at GitLab it probably won't be coming anytime soon (it's on backlog, so it's going to be scheduled for a releases sometime (could be in a day or some years) and then it's probably moved 3 times or so until it's implemented, so I'd say it'll take a few months _minimum_ if nobody contributes it externally) so I wouldn't bet on that one yet.

> Alternatively, you could build [custom extension](https://detekt.github.io/detekt/extensions.html#custom-reports) that would fit your case.

I'll have a look, if it's not too complicated that could be a viable option, especially given that the format isn't too complicated.

**Comment by BraisGabin** [comment]
I agree that this could be a third party plugin. If someone develop it we should link it in the Readme so anyone can find it and use it easily.

**Comment by cromefire** [comment]
I've wrote a little extension overe here, although I haven't checked if it actually works yet and it isn't really usable with a multimodule project yet: https://gitlab.com/cromefire_/detekt-gitlab-report

**Comment by schalkms** [comment]
Nice project. 👍
The usual process here is to add this custom report to our readme so that it can be found by other users. This project deserves appreciation.

**Comment by cromefire** [comment]
Thanks
