### ISSUE TITLE
Use dynamic list format for default-detekt-config.yml

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#3671]
## Expected Behavior
The list of default strings that are inferred from the `config` delegate should dynamically choose the appropriate format for the yaml file. 

**Suggestion**:  

When the list fits on one line (less than xx characters), the one-line format is used. 

```yaml
ForbiddenComment:
  values: ['TODO:', 'FIXME:', 'STOPSHIP:', '@author']
``` 
For longer lists, the multi-line format is used.

```yaml
TooGenericExceptionCaught:
  exceptionNames:
   - ArrayIndexOutOfBoundsException
   - Error
   - Exception
   - IllegalMonitorStateException
   - NullPointerException
   - IndexOutOfBoundsException
   - RuntimeException
   - Throwable
```

## Current Behavior
Currently, the single-line format is always generated.

## Context
This is a follow up to #3637.
No matter which format is used, the rule is executed with the correct values. This is rather a matter of readability and maintainability.

**Comment by 3flex** [comment]
It should be multi line in all cases IMHO. Config change diffs are clearer that way.
