### ISSUE TITLE
Add regex support for config delegate

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#3672]
## Expected Behavior
Instead of 

```kotlin
    @Configuration("...")
    private val allowedExceptionNameRegex: String by config("_|(ignore|expected).*")
```

it should be possible to write

```kotlin
    @Configuration("...")
    private val allowedExceptionNameRegex: Regex by config("_|(ignore|expected).*")
```
This should basically mimic to behavior of `LazyRegex` for rules that allow for regular expression config params.

## Context
This is a follow up to #3637.

**Comment by chao2zhang** [comment]
I actually have some local changes to this - I can pick up `detekt-rules-errorprone`
