### ISSUE TITLE
Paralellize tasks detektMain and detektTest

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3682]
## Expected Behavior
If I run `./gradlew :module:detektDebug :module:detektDebugUnitTest` both tasks run in parallel

## Current Behavior
They don't

## Context
In my current project I have a huge monolith that have nearly all the code so detekt take long time in it. So I have 11 idle threads waiting to run 2 long tasks instead of parallelice them.

**Comment by 3flex** [comment]
You're passing the `--parallel` flag to Gradle right? I'm assuming yes but just want to make sure before it's investigated further!

**Comment by BraisGabin** [comment]
Yes, the different modules go in parallel. But those two task in the same module go one behind the other. Even more. First it compiles main. Then it runs detekt main. Then it compiles the tests and then it runs detekt test

**Comment by 3flex** [comment]
It happens in that order because running debug unit tests relies on debug classes being built, and detektDebugUnitTest can't run until test classes are built.

Do you have a build scan to share?

**Comment by BraisGabin** [comment]
Sure, you can see what I'm talking about here: https://scans.gradle.com/s/2ktgllhdfoeje/timeline?end=1618646409701&start=1618646355034

My idea is that `:detekt-rules-style:compileTestKotlin` could start at the same time of `:detekt-rules-style:detektMain`. And, as soon as this one ends (and after those mini tasks that are needed) `:detekt-rules-style:detektTest` could start running.

With the times of this scan the tasks `:detekt-rules-style:detektMain` and `:detekt-rules-style:detektTest` would run 1 second in parallel.

We would save 15.948s because we were moving out `:detekt-rules-style:detektMain` from the "critical path".

**Comment by 3flex** [comment]
I'm not sure if this is possible - Gradle won't run tasks within the same module/project in parallel.

The Worker API offers some ability to parallelise work within the same project. But even if that were used, the two distinct tasks (detektMain & detektTest) might still have to run in sequence even if the `Detekt` task could use the Worker API since as far as I know that only parallelises the work within an individual task's action, not across tasks within a project.

Your build scan did highlight another bug though which I'll raise separately (both detekt tasks are outputting reports to `main.html`, `main.txt` etc. when it should be `main.html` and `test.html`).

**Comment by 3flex** [comment]
I'm closing this as I don't think there's anything we can do here because of Gradle's limitations. I've opened https://github.com/detekt/detekt/pull/3687 to address the report output problem found in the build scan.

**Comment by BraisGabin** [comment]
Yes, I'm afraid that you are right... I checked the worker API and it doesn't suit our case wither. Worker allow us to parallelice the job done inside a task. But it doesn't seem to parallelice code between tasks.

The only idea that I have here is to create a task `detektMainAndTest` that wait until the tests are compiled and then run both analysis at the same time. It's not exactly the same but it would be faster than the current behaviour. The problem is that it will make our "gradle api" uglier.

Maybe we can think about it for 2.0. In 2.0 type solving will be on by default so we could use the name `detekt` or `detektCheck` to run the checks on all the targets at the same time.
