### ISSUE TITLE
Use Gradle 7.0 version catalog

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#3688]
We are managing dependencies in an inconsistent way that 
- Most versions are in https://github.com/detekt/detekt/blob/main/buildSrc/build.gradle.kts
- Some versions are in https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/build.gradle.kts
- We also use Gradle BoM as introduced in https://github.com/detekt/detekt/pull/2792

Gradle 7 comes with an [opinionated way](https://docs.gradle.org/7.0/release-notes.html) to centralize dependency versions. 
Although this is experimental, it is still recommended over BoM platform https://docs.gradle.org/7.0/userguide/platforms.html#sub:platforms-vs-catalog. We should be able to centralize all dependencies in a single place.

**Comment by BraisGabin** [comment]
Agree. I added the bom because the catalogs didn't exist. We should think too what to do with our bom. It was not meant to be published but it's published so we should support it, I imagine. Maybe we can refactor it to at least do what it's meant to do: force to align the detekt versions.

**Comment by 3flex** [comment]
I would stop publishing the BOM (even now, we don't have to wait for this issue to be addressed). Lots of other things to focus on.

**Comment by cortinico** [comment]
> I would stop publishing the BOM (even now, we don't have to wait for this issue to be addressed). Lots of other things to focus on.

I'd publish it in the upcoming version say that this would potentially be the last release of the `detekt-bom` artifact. This would allow us to understand if there are strong concerns or users depending heavily on it.
