### ISSUE TITLE
Precompiled binary not available for 1.16.0

### ISSUE THREAD

**Issue by DavidDTA** [detekt/detekt#3690]
## Expected Behavior

Up through 1.15.0, the `detekt` binary is available as a release artifact.  It should also be available for 1.16.0.

## Observed Behavior

It is not available.

## Steps to Reproduce

See release artifacts here: https://github.com/detekt/detekt/releases/tag/v1.16.0

## Context

We run detekt by running the precompiled binary.  Without this, we can't use version 1.16.0.

Additionally, the quick start instructions in the Readme won't work for version 1.16.0.

**Comment by cortinico** [comment]
That was a decision we took once we bumped to Kotlin 1.4.21 here https://github.com/detekt/detekt/pull/3254#issuecomment-761624329

Please use the `-all.jar` files we ship with every version with `java -jar`. If that doesn't fit your needs, please explain what's your specific use case 👍

**Comment by DavidDTA** [comment]
We'll be able to adapt when we update the version of the library we use.

Please update the [quick start](https://github.com/detekt/detekt#quick-start-) section of the readme, though.  I imagine it will be jarring for new folks.

**Comment by chao2zhang** [comment]
Good point, yes readme was left not updated.
