### ISSUE TITLE
java.lang.NoSuchMethodException: io.gitlab.arturbosch.detekt.cli.Main.buildRunner([Ljava.lang.String;, java.io.PrintStream, java.io.PrintStream)

### ISSUE THREAD

**Issue by hpatel123** [detekt/detekt#3697]
## Expected Behavior
Build should not be failed

## Observed Behavior
Build is failing

## Steps to Reproduce
./gradlew assembleZdevDebug detekt

## Context
We can not generate Android build. Earlier we're using Kotlin version 1.3 that time detekt was working properly but after updating kotlin version 1.4.32 detekt stopped to working.

Getting following error: 
<img width="1095" alt="Screenshot 2021-04-23 at 2 39 46 PM" src="https://user-images.githubusercontent.com/6604701/115848690-c206ff00-a441-11eb-8b26-8c0d324fafe3.png">

## Your Environment
detekt version: 1.16.0
Kotlin version: 1.4.32

**Comment by 3flex** [comment]
Can you please share a Gradle build scan?

Rerun the Gradle command with `--scan` and post the URL.

**Comment by cortinico** [comment]
Can you also post your `detekt{}` block from your build.gradle file? By any chance are you specifying the `toolVersion` in your block?

**Comment by schalkms** [comment]
Unfortunately, this issue can't be reproduced without the needed code and build scan. Without the given information, there's not much we can do here. Hence, I'm closing until a reproducer is available.
