### ISSUE TITLE
Report merge tests are flaky

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#3705]
## Expected Behavior
Tests aren't flaky.

## Observed Behavior
The report merge tests are flaky.

## Steps to Reproduce
Run the tests a few times - sometimes the Gradle plugin tests will fail on `DetektReportMergeTest`

## Context
Causes problems for contributors running builds locally and on CI.

I believe the problem in the test is outlined in the Gradle docs (see point 2 in this section): https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:task_configuration_avoidance_general

In the test, the report merge tasks are being modified in the detekt task configuration action, which according to the Gradle docs will cause indeterminate behavior.

This needs to be reworked to run reliably. I suggest disabling the report merge tests for now if there's no quick fix (and I think the proper solution would be similar to https://github.com/detekt/detekt/pull/3650, since the JaCoCo report merging task is essentially doing the same thing).

cc @chao2zhang

**Comment by chao2zhang** [comment]
Is it failing locally for you without applying https://github.com/detekt/detekt/pull/3703? I am not able to reproduce failures.

I have some tricky gradle setup code that should pass reliably. It will be something like which bypasses the configuration avoidance.
```
        project.gradle.taskGraph.whenReady { graph ->
            graph.allTasks.filterIsInstance(Detekt::class.java).forEach { detektTask ->
                detektMergeTask.configure {
                    (it.xmlReportFiles as ConfigurableFileCollection).from(detektTask.reports.xml.destination)
                }
            }
        }
```

**Comment by 3flex** [comment]
It's very strange, in the CI improvement PR the CI jobs are consistently failing on this test on Java 11. But I can't reproduce that locally on the exact same JDK (Adopt JDK 11.0.11+9).

So "flaky" was the wrong term because it seems to be consistent behaviour, but seems specific to Java 11 and only on the GitHub Actions runner.

Not sure what to do for this one. I'll continue discussion on the other PR.

**Comment by 3flex** [comment]
Closing pending further discussion in #3703
