### ISSUE TITLE
Strange behaviour for autocorrect

### ISSUE THREAD

**Issue by nflorina** [detekt/detekt#3713]
I recently addes the dependency for formatting:
**detekt(io.gitlab.arturbosch.detekt:detekt-formatting:{.....})**
I used to have only: 
**detekt(io.gitlab.arturbosch.detekt:detekt-cli:{.....})**

therefore I added here **autoCorrect**:
`detekt {
         .....
         autoCorrect = true
}`

Also added in my **config** file the rules for formatting.
When running **./gradlew detekt** the formatting errors are found but I don't understand how they are fixed. Seems like some of them are fixed and some not. What are these **Overall debt: 13h 40min** for eg?

**Comment by cortinico** [comment]
> When running **./gradlew detektCheck** the formatting errors are found but I don't understand how they are fixed. 

The `autoCorrect` flag is passed to KtLint to apply corrections.
Detekt by itself does not modify the code.
The `detekt-formatting` module is wrapper on top of KtLint, so there the autocorrection actually happens.

> Seems like some of them are fixed and some not. 
> I run this for several times and still not everything is fixed.

Most likely what happens is that the rule from detekt-formatting (listed here https://detekt.github.io/detekt/formatting.html) are fixed, the other are not.

> In addition, the errors found are different from one run to another (all of them are **formatting** errors). It's never-ending. What should I do to have them fixed? 

THis could be a bug. Can you please provide a reproducer (being that a file or ideally a project that we can look into?

> What are these **Overall debt: 13h 40min** for eg?

That's an estimate of the overall debt that you need to fix. It's just an estimate. Every rule has a score in terms of minutes and the overall score is computed and reported to you in the report.

**Comment by nflorina** [comment]
I added formatting rules in **config.yml**: 

formatting:
  active: true
  AnnotationOnSeparateLine:
    active: true
  AnnotationSpacing:
    active: true
  ArgumentListWrapping:
    active: true
  EnumEntryNameCase:
    active: true
  Indentation:
    active: true
  MaximumLineLength:
    active: true
  NoEmptyFirstLineInMethodBlock:
    active: true
  SpacingAroundAngleBrackets:
    active: true
  SpacingAroundDoubleColon:
    active: true
  SpacingAroundUnaryOperator:
    active: true
  SpacingBetweenDeclarationsWithAnnotations:
    active: true
  SpacingBetweenDeclarationsWithComments:
    active: true

It's obviously a lot of formatting errors solved from my first run but now it gets stuck and I keep receiving errors like:

-  ArgumentListWrapping
-  MaximumLineLength
-  Indentation

I mean - all the errors received now are just **formatting** errors. So this is why I expect to fix them.  It's not errors from other category which is not autocorrectable.

Unfortunatelly I am not able to point you to a project. We had before this ** detekt("io.gitlab.arturbosch.detekt:detekt-cli:${DETEKT}")** dependency in our build.gradle and I jus added the **detekt("io.gitlab.arturbosch.detekt:detekt-formatting:${DETEKT}")** for formatting + **autoCorrect = true** .

**Comment by cortinico** [comment]
> I mean - all the errors received now are just formatting errors. So this is why I expect to fix them. It's not errors from other category which is not auto-correctable.

Not all the errors are fixable automatically. 
Some of the requires human intervention, that's a limit of ktlint.

**Comment by nflorina** [comment]
I see. I understood this and started to fix some of them. The pain is that while I am fixing things is a file and running again, I receive a huge amount of detection in a new file or another existing one (not the one I was trying to manually fix)

**Comment by BraisGabin** [comment]
As @cortinico said not all the errors can be fixed automatically so this is working as expected. There is nothing that we can make at our end to fix that. They need human intervention.

You can check the documentation of each rule here so you can know why detekt is complaining about: https://detekt.github.io/detekt/formatting.html
