### ISSUE TITLE
Indicate Detekt in default baseline file name

### ISSUE THREAD

**Issue by lwasyl** [detekt/detekt#3737]
Detekt 1.17-RC1 [changelog](https://github.com/detekt/detekt/releases/tag/v1.17.0-RC1) mentions the following:
> We now default the baseline file to baseline.xml so you don't have to specify it manually.

It might be reasonable to use a name that implies Detekt, for example `detekt-baseline.xml`. Motivation:
 - this might help avoid potential clashes with other tools that use XML baseline files
 - it'd help with readability - `baseline.xml` name doesn't suggest it has anything to do with Detekt, and even the contents don't have `Detekt` mention anywhere

**Comment by BraisGabin** [comment]
@lwasyl thank you for try the RC / read the changelog and report this isse. For this kind of reasons we release RC.
