### ISSUE TITLE
Detekt still depends on JCenter for kotlinx.html

### ISSUE THREAD

**Issue by blundell** [detekt/detekt#3746]
I might be wrong here but wanted to be sure.

It seems Detekt uses kotlinx html, as shown here:

https://github.com/detekt/detekt/blob/81c9539eccdb82261e95a1a0216bc0c6f06b7db5/gradle/libs.versions.toml#L27

But in the getting started docs of that dependency it says you need to declare the maven repo to pull it from ([instead of using JCenter](https://github.com/Kotlin/kotlinx.html/issues/173)):

https://github.com/kotlin/kotlinx.html/wiki/Getting-started

```
repositories {
    maven { url "https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven" }
}
```
and I can't see that happening anywhere:

![image](https://user-images.githubusercontent.com/655860/117265868-95dd7c00-ae4c-11eb-8e47-ab62fb52f1ec.png)

I noticed this at the very bottom of the [Getting Started ReadMe](https://github.com/detekt/detekt/blob/9e71fc7e1617a46566f58c72752f6179efe96c57/docs/pages/gettingstarted/gradle.md) and if this change was done, I think it can be removed:

![image](https://user-images.githubusercontent.com/655860/117266009-b7d6fe80-ae4c-11eb-90f7-ee2d4a35a23c.png)

 Happy to contribute and do this change myself, but don't want to waste time if I am wrong

**Comment by BraisGabin** [comment]
The last RC should just need mavenCentral as repository to work. Which version are you using?

> I noticed this at the very bottom of the Getting Started ReadMe and if this change was done, I think it can be removed:

That documentation is outdated here. We can remove that section from the documentation.

**Comment by blundell** [comment]
:+1:  nice, we're on 1.11.1. I'll bump that to 1.16.0 since the higher is an RC I'll wait.
