### ISSUE TITLE
Redesign blog

### ISSUE THREAD

**Issue by zmunm** [detekt/detekt#3766]
Now we have a awesome logo #2717 
Detekt has maintained a blue blog for a long time, but I think we need to consider changing it to harmony with logo.

The blog is the origin of this issue, but the context is branding.

**Comment by cortinico** [comment]
see https://github.com/detekt/detekt/issues/4235 for some updates 🎉

**Comment by 3flex** [comment]
Thoughts on the new site design?

I think this one can now be closed, thanks to the excellent work @cortinico has done!

**Comment by zmunm** [comment]
I think it is very beautiful. If anyone has a different opinion, please create a new issue.
