### ISSUE TITLE
Website doesn't show a doc page for `documentation` rule set

### ISSUE THREAD

**Issue by schalkms** [detekt/detekt#3767]
## Expected Behavior
The website shows the rule documentation for all rule sets.

## Observed Behavior
The website doesn't show the rule documentation for the `documentation` rule set.

## Steps to Reproduce
Visit the website and take a look at the navigation menu on the left
https://detekt.github.io/detekt/

![image](https://user-images.githubusercontent.com/30376729/118035653-ca30cb00-b36b-11eb-98e1-f48c2d04d412.png)

**Comment by marschwar** [comment]
The rules from the `documentation` rule set can be found under `comments`. I do not know how this came to be.

**Comment by schalkms** [comment]
> The rules from the `documentation` rule set can be found under `comments`. I do not know how this came to be.

The rule set is actually named `comments`. The rule set name does not match the package name, which is the case for a long time. I forgot that. So the documentation is displayed as it should be.

**Comment by cortinico** [comment]
> The rule set name does not match the package name, which is the case for a long time.

Should we at least rename the gradle module to `detekt-rules-comments`?

**Comment by marschwar** [comment]
Also there is `detekt-rules-errorprone` which is called `potential-bugs` in the documentation.

**Comment by cortinico** [comment]
A side effect of renaming would be that the maven artifacts will also be renamed. I'm unsure this is a problem as they're not directly used but still... The overhead of having to know that `errorprone` maps to `potential-bugs` is painful every time :/

**Comment by schalkms** [comment]
I agree. Renaming is a good idea. Maybe we should create a new issue for all the differences in the naming scheme.
