### ISSUE TITLE
Gradle plugin documentation is outdated regarding source directories

### ISSUE THREAD

**Issue by Marcono1234** [detekt/detekt#3781]
#3649 made it so the Detekt Gradle plugin by default also checks the test source directories `src/test/java` and `src/test/kotlin`.
The [Gradle plugin documentation](https://github.com/detekt/detekt/blob/main/docs/pages/gettingstarted/gradle.md) has not been updated accordingly yet (there are 4 occurrences which need to adjusted).

**Comment by cortinico** [comment]
>  The [Gradle plugin documentation](https://github.com/detekt/detekt/blob/main/docs/pages/gettingstarted/gradle.md) has not been updated accordingly yet (there are 4 occurrences which need to adjusted).

Thanks for pointing out. Would you be up for sending a PR to fix it? 👌
