### ISSUE TITLE
detektBaselineDebug task doesn't get the jvmTarget value

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3785]
## Expected Behavior
The error
> calls to static methods in Java interfaces are prohibited in JVM target 1.6. Recompile with '-jvm-target 1.8'

is not shown when executing `./gradlew detektBaselineDebug` with this in my configuration:

```kotlin
    tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
        jvmTarget = "1.8"
    }
```

## Observed Behavior
It does.

## Context
I fixed it by adding this:
```kotlin
    tasks.withType<io.gitlab.arturbosch.detekt.DetektCreateBaselineTask>().configureEach {
        jvmTarget = "1.8"
    }
```

I don't know if we could fix this without adding this line, but if we can not we should add this to our documentation too.

This problem was there in 1.16.0 and previous versions too.

## Your Environment
* Version of detekt used: 1.17.0

**Comment by The-MM** [comment]
What if you just use this?

```
tasks.withType<io.gitlab.arturbosch.detekt.Detekt> {
        jvmTarget = "1.8"
    }
```
I'm not sure the `configureEach` is needed.

**Comment by 3flex** [comment]
This should be added to docs at minimum.

Another option is adding a jvmTarget property to the detekt Gradle extension which sets the default for all tasks in the project.

**Comment by cortinico** [comment]
> Another option is adding a jvmTarget property to the detekt Gradle extension which sets the default for all tasks in the project.

Totally agree on this
