### ISSUE TITLE
detektBaselineMain is noisy 

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3788]
## Expected Behavior
This kind of messages doesn't appear
```
Ignoring a file detekt cannot handle: /Users/brais.gabin/projects/XXXXX/Class.java
```

## Current Behavior
If I run `./gradlew detektMain` this messages never appear (it ws fixed at #3655). But if I run `./gradlew detektBaselineMain` or `./gradlew detektBaselineTest` they do appear.

## Context
When we fixed #3019 we didn't saw that the baseline task had the same issue and that we didn't fix it.

## Your Environment
* Version of detekt used: 1.17.0

**Comment by cortinico** [comment]
> `Ignoring a file detekt cannot handle: /Users/brais.gabin/projects/XXXXX/Class.java`

I believe we should not log this for `.java` files. They're actually used as part of the compilation. I would add an extra case in the `when` for those files:

https://github.com/detekt/detekt/blob/7bbd83d369eff4337b64d5c1d9cb890bbe78eaf3/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/KtTreeCompiler.kt#L23-L30
