### ISSUE TITLE
Rules: JUnit/Spek

### ISSUE THREAD

**Issue by schalkms** [detekt/detekt#379]
I think this would be a nice new feature.

To be more precise, PMD does also have this kind of rules
reference:
http://pmd.sourceforge.net/pmd-4.3.0/rules/index.html#JUnit_Rules

Detection of unit tests
- lies in the tests package
- class name ends with Test/Spek
- class imports JUnit/Spek package
- has JUnit annotations

**Comment by arturbosch** [comment]
A ruleset for testing code smells seems reasonable.

**Comment by arunvelsriram** [comment]
I wrote a ktlint ruleset for linting JUnit test name. I am also planning to add more rules.

https://github.com/arunvelsriram/ktlint-ruleset-junit/

By looking at detekt readme it looks like detekt is more configurable than ktlint. So I am thinking of changing the ruleset to detekt. Do you have any suggestions on this?

**Comment by schalkms** [comment]
> By looking at detekt readme it looks like detekt is more configurable than ktlint.

Yes.

> So I am thinking of changing the ruleset to detekt. Do you have any suggestions on this?

Ktlint also uses the PSI.
You can at least copy over the logic, but you would need to use the corresponding `visit_()` method. Testing the rules also works differently in detekt, but that shouldn't be an issue, since you could copy over the test snippets.
May I ask you what test related rules you want to see in detekt? @arunvelsriram 
We'd really appreciate any contributions in that regard.

**Comment by arunvelsriram** [comment]
I have the following rules for JUnit in my repo:

1. test description style 
```
fun `should add two numbers`() { }
```
2. test must contain least one assertion
3. ignored tests should not cross a threshold

I will add the above in `detekt` and raise a PR.

**Comment by schalkms** [comment]
I think 2 and 3 are a nice addition. 1 is IMHO too specific.
Thanks!

**Comment by arunvelsriram** [comment]
we could make 1 configurable like backticks style, camelCase style or custom regex.

**Comment by schalkms** [comment]
Excellent idea!

**Comment by BraisGabin** [comment]
I would vote to close this. The idea to have a rule set jor JUnit seems a good idea. But we want to keep detekt platform/library agnostic so it should be done in a custom rule set (it could be a first party one, but out of this repo)
