### ISSUE TITLE
`UnusedImports` marks all Java imports as unused

### ISSUE THREAD

**Issue by andrey-bolduzev** [detekt/detekt#3791]
## Expected Behavior
Not unused imports from Java files in Kotlin files shouldn't be reported as part of `UnusedImports`.

## Observed Behavior
After upgrading to detekt 0.17.0, all Java imports are marked as unused.

## Steps to Reproduce
1. Create a Java file
2. Create a Kotlin file
(the files can be in the same gradle module)
3. Import and use some Java dependency in the Kotlin file

## Your Environment
* Version of detekt used: 0.17.0
* Version of Gradle used (if applicable): 7.0
* Relevant part of the config applied to every gradle module in the project:

```groovy
detekt {
    parallel = true
    failFast = false
    autoCorrect = !project.hasProperty("ci")
    buildUponDefaultConfig = true
    config = project.parent.files(".static/config/default-detekt-config.yml")
    reports {
        html.enabled = true
        xml.enabled = false
        txt.enabled = false
        sarif.enabled = false
    }
}
```

**Comment by BraisGabin** [comment]
I'm having similar issues with `ReplaceSafeCallChainWithRun` and `UnreachableCode`. It seems to be an issue introduced by me in #3655

I'm researching a bit more and I'll create a PR to fix it.

**Comment by cortinico** [comment]
Just a small heads up, we're aiming at releasing this in a patch version `1.17.1` soon-ish
