### ISSUE TITLE
Inconsistent use of deprecation information in default-detekt-config.yaml

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#3806]
While looking into #3671 I came across something that I thought was a little inconsistent but was not sure if it is intended or not.

When the `default-detekt-config.yml` is generated we do not include simple deprecated config options. That seems reasonable to me. But we do include those config properties that allow the user to specify a list (at the moment there are none). For rule sets no all config options are always included.

Is there a reason behind all this or should it be _hide when deprecated_?

**Comment by cortinico** [comment]
> But we do include those config properties that allow the user to specify a list (at the moment there are none). For rule sets no all config options are always included.

Just to clarify: Are you saying that we would generate a config files with **list config keys** regardless if they're deprecated or not, right?

If that's it's the case, I believe the treatment of deprecated should be tweaked to be consistent across all the keys (the type should be irrelevant).

**Comment by marschwar** [comment]
That is correct. There are none at the moment so it is not urgent.
