### ISSUE TITLE
Running detektFormat Gradle task sometimes work fine and other times throw an exception

### ISSUE THREAD

**Issue by MustafaKhaled** [detekt/detekt#3819]
## Expected Behavior
To run detekt normally as any other files, to cleanup the code.

## Observed Behavior
Sometimes, when running this gradle task, it throws this exception below

io.github.detekt.psi.KtFilesKt.toFilePath(Lorg/jetbrains/kotlin/com/intellij/psi/PsiFile;)Lio/github/detekt/psi/FilePath;
  Running detekt '1.15.0' on Java '1.8.0_242-release-1644-b3-6915495' on OS 'Mac OS X'

## Steps to Reproduce
It can't reproduce a standard sceanrio.

## Context
I'm using detekt, to be able to cleanup the code to avoid code smells in SonarQube

## Your Environment

* Version of detekt used: 1.15.0
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: mac OS version 10.15.7

**Comment by cortinico** [comment]
Can you please update to Detekt 1.17.1 and verify if the issue is still happening?

**Comment by MustafaKhaled** [comment]
Update to the latest version, solve the issue.
I'll close it.

**Comment by sofronovic** [comment]
Hi, I'm still facing this issue on the 1.17.1 version, do you have any suggestions?

**Comment by cortinico** [comment]
Hey @MustafaKhaled @sofronovic The information provided is too less to help us reproduce.
Can I ask you to try with `1.18.0-RC2` and provide a full stacktrace if the issue is still happening?

**Comment by MustafaKhaled** [comment]
Hey @cortinico 
For me, update to the latest version solved my problem.
