### ISSUE TITLE
Avoidable creation of range

### ISSUE THREAD

**Issue by Marcono1234** [detekt/detekt#3823]
## Expected Behavior of the rule
Similar to the existing rule [ForEachOnRange](https://detekt.github.io/detekt/performance.html#foreachonrange), there are cases where functions have overloads with a range and with two separate index parameters, for example [`String.substring`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/substring.html):
- `String.substring(range: IntRange)`
- `String.substring(startIndex: Int, endIndex: Int)`

It looks like the Kotlin compiler (1.5.0 with JVM target) does not seem to perform any optimization here, so even when creating the range at the call site, the byte code will still create an `IntRange` which is rather wasteful:
```kt
println("test".substring(1..2))
```

Byte code:
```
29: ldc           #23                 // String test
31: new           #25                 // class kotlin/ranges/IntRange
34: dup
35: iconst_1
36: iconst_2
37: invokespecial #29                 // Method kotlin/ranges/IntRange."<init>":(II)V
40: invokestatic  #35                 // Method kotlin/text/StringsKt.substring:(Ljava/lang/String;Lkotlin/ranges/IntRange;)Ljava/lang/String;
```

I am not sure if a rule covering this can be written in a general way, e.g. "if a function is called with a range created at the call site, but there exists an overload with separate parameters of the same type"; or if such functions where a non-range overload exists would have to be hardcoded to prevent false positives.

## Context
The rule should detect wasteful creation of ranges when calling functions, where overloaded functions with separate parameters exist, e.g.:
`"test".substring(1..2)` → `"test".substring(1, 3)`

**Comment by BraisGabin** [comment]
Thanks for the proposal! Do you have a benchmark to support this?

**Comment by Marcono1234** [comment]
Sorry, I don't have a professional benchmark for this, but profiling the following (contrived) code shows a large number of allocated `IntRange` objects:
```kt
fun main() {
    var s = "test".dropLast(0)
    while (true) {
        s = s.substring(0 until s.length)
    }
}
```
(Kotlin version 1.5.0-release-749 (JRE 11.0.5+10))

VisualVM profiler:
![VisualVM profiler screenshot](https://user-images.githubusercontent.com/11685886/119419416-825e5c00-bcfa-11eb-942e-fbce03503a0e.png)

I guess using a range in non-performance critical code is fine, but it looks like you should avoid it in tight high-performant loops.

**Comment by BraisGabin** [comment]
I think that this rule should be disable by default because we should usually prefer readability over performance except in code that should be really performant.

**Comment by cortinico** [comment]
Can we close this issue or do we still believe this is achievable? I recall seing similar issues in the past mentioning minor tweaks to get some perf. improvements. I believe this is going a bit in a opposite direction than Detekt's missing: helping you write clean code (the cleaner code might not necessarily be the most performant).

**Comment by Marcono1234** [comment]
It probably really depends on the use case whether this is a performance issue, and you are right that refactoring such code could decrease readability.
So feel free to close this issue, if you don't think implementing a rule for this is worth it.

**Comment by BraisGabin** [comment]
I agree with @cortinico, maybe this could be developed as a custom rule and if someone needs its code to e performant can use it.
