### ISSUE TITLE
Bump minimum supported Gradle to 6.1

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#3832]
## Expected Behavior
Gradle plugin can take advantage of new features for plugin authors to simplify plugin implementation.

Also see https://github.com/detekt/detekt/pull/3647

## Current Behavior
Plugin supports Gradle 5.4 which was released April 2019.

## Context
Kotlin Gradle plugin 1.5.0 supports 6.1 and up.

**Comment by BraisGabin** [comment]
I did this yesterday at #3830

**Comment by 3flex** [comment]
Oh sorry, missed that!
