### ISSUE TITLE
Use apiVersion to keep compatible with previous version Kotlin stdlib

### ISSUE THREAD

**Issue by arhont375** [detekt/detekt#3849]
## Expected Behavior

`detekt` using `apiVersion` compilation flag to ensure that used classes and methods backward compatible with previous version of Kotlin stdlib.

## Current Behavior

Currently `detekt` doesn't use `apiVersion` compilation flag that lead to the situation that `detekt` may not be used if old version of Kotlin stdlib on classpath.

### Real world example

We have complex project that using Gradle with many plugins and seems one of them bringing Kotlin stdlib 1.3.x on the classpath, `detekt` since a long time was build with stdlib 1.4.x that not fully backward compatible with stdlib 1.3.x. Therefore we can't use `detekt` in current setup before we find and update all used plugins to the 1.4.x compatible version.

### Ktlint

Some time ago [ktlint made similar move](https://github.com/pinterest/ktlint/pull/848)   

### Docs

- [Kotlin Gradle plugin flags](https://kotlinlang.org/docs/gradle.html#attributes-common-for-jvm-and-js)
- [Kotlin compatibility tools](https://kotlinlang.org/docs/kotlin-evolution.html#compatibility-tools)

**Comment by cortinico** [comment]
> We have complex project that using Gradle with many plugins and seems one of them bringing Kotlin stdlib 1.3.x on the classpath

Are you asking to have `apiVersion = "1.3"`? Detekt is currently build with Kotlin 1.5. I believe we could set `apiVersion = "1.4"` and give up on some methods from the stdlib (like `uppercase` or similar).

Having `apiVersion = "1.3"` sounds unrealistic to me, we bumped Kotlin to 1.4 long ago and I believe we do extensive usage of 1.4.x methods.

**Comment by arhont375** [comment]
I'm just suggesting to start using this to ensure compatibility with some version, to avoid unexpected stdlib incompatibility in the future (like I had with 1.3).
I'm totally fine if you will select `1.4` now.

I think this table also will need to be updated after that: https://github.com/detekt/detekt#requirements

**Comment by cortinico** [comment]
> I'm just suggesting to start using this to ensure compatibility with some version

I believe we could support up to one previous version (also given that Gradle is still on Kotlin 1.4).
See #3852
