### ISSUE TITLE
UnnecessaryParentheses is invalid for expressions used for delegation.

### ISSUE THREAD

**Issue by Sintrastes** [detekt/detekt#3851]
## Expected Behavior

In Kotlin, an expression used to delegate to an interface by using the `by` keyword sometimes needs to be parenthesized. In particular, this seems to occur when using expressions with tailing lambda arguments (though I am not sure exactly what causes this behavior in the parser). For example:

```
interface MyInterface {
    val someProperty: String
}

fun mkInterface(value: String): MyInterface = 
    object: MyInterface {
        override val someProperty = value
    } 

fun MyInterface.map(f: (String) -> String): MyInterface {
    val orig = this
    return object: MyInterface {
        override val someProperty = f(orig.someProperty)
    }
}

class MyClass: MyInterface by (
    mkInterface("hello").map {
        it + "!"
    }
)
```

If the parenthesis after the "by" are removed, the above will not parse. So the expected behavior is that detekt will not report a UnnecessaryParentheses error for the above. 

## Observed Behavior

Detekt will report an UnnecessaryParentheses error for the expression above, even though the parenthesis are actually nescesary.

## Context

I use this sort of delegation all the time, so I get a ton of mis-reported "UnnecessaryParentheses" in my code-base that are actually necessary.

## Your Environment

* Version of detekt used: 1.17.1

**Comment by cortinico** [comment]
That's indeed a false positive. Another smaller reproducer is:

```kotlin
class Clazz: Comparable<String> by ("hello".filter { it != 'l' })
```
