### ISSUE TITLE
UnderscoresInNumericLiterals acceptableDecimalLength is off by one

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#3860]
If I set `acceptableDecimalLength` to 4, then `2021` is flagged as violating the rule.

The description is `Length under which decimal base 10 literals are not required to have underscores`, which means the rule is working correctly. The issue is that the name indicates that anything with this length will be acceptable, when in reality the rule is that anything less than this length will be acceptable.

**Comment by schalkms** [comment]
If I understand you correctly, the name of the parameter and the corresponding documentation is misleading.
Do you have a suggestion to improve the documentation for this parameter?

**Comment by eygraber** [comment]
Probably the best approach would be to make the behavior match the documentation (i.e. if I set `acceptableDecimalLength` to 4, then the rule should only apply to decimals 5 digits or greater), but that would be a breaking change.

For a non breaking change, deprecate `acceptableDecimalLength` and make a new config called `minimumApplicableDecimalLength` or `minimumDecimalLength`.

**Comment by schalkms** [comment]
Guys, shall we introduce a breaking change for one of the next versions? The naming of this configuration option is really misleading.
@BraisGabin @cortinico @chao2zhang

**Comment by BraisGabin** [comment]
We don't need to add a breaking change. We can deprecate the old one and create a new one that, by default uses the current value - 1

**Comment by cortinico** [comment]
> Guys, shall we introduce a breaking change for one of the next versions? The naming of this configuration option is really misleading.

Imho that's not even a breaking change, it's a bug in the implementation that we should probably fix and mention in the release notes.
