### ISSUE TITLE
Require `use` for `Closeable`s

### ISSUE THREAD

**Issue by yogurtearl** [detekt/detekt#3865]
## Expected Behavior of the rule
Any time a reference to `Closeable` is created or comes into scope, it should be only used within the lambda of a [`.use` ](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html)

This should be an error or warning. 

Non-compliant code: 
```kotlin
val myCloseable = MyCloseable()
// do stuff with myCloseable
```

Compliant code: 
```kotlin
MyCloseable().use {
    // do stuff with myCloseable
}
```

## Context

Closing `Closeable`s is easy to get wrong. An exception might be thrown, or you might have multiple `Closeable`s. `.use` help make sure they get closed properly.

**Comment by schalkms** [comment]
Good idea!

**Comment by BraisGabin** [comment]
I like it! But we should be carefull with this snipped:

```kotlin
fun foo(bar: Closable) {
  bar.something()
}
```

This code should be compilant.

**Comment by cortinico** [comment]
Can you provide more examples of compliant/non-compliant code. Having some real world scenario will also help. I like the idea behind this rule but have the gut feeling this could be a bit too strict.

**Comment by yogurtearl** [comment]
We start by limited the non-compliant code to only be on constructor invocations of classes that implement `Closable` or functions that returns a type that implements `Closable` (but don't take a Closable as an argument)

Anything else is compliant. Start with by only flagging these 2 cases, but could expand over time

Non-compliant: 
```kotlin
MyClosable().doStuff()
```

Compliant: 
```kotlin
MyClosable().use { it.doStuff() }
```

Non-compliant: 
```kotlin
val closable = MyClosable()
closable.doStuff()
```

Compliant: 
```kotlin
val closable = MyClosable().use {
   it.doStuff()
}
```

Non-compliant: 
```kotlin
functionThatReturnsClosable().doStuff()
```

Compliant: 
```kotlin
functionThatReturnsClosable().use { it.doStuff() }
```

Non-compliant: 
```kotlin
val closable = functionThatReturnsClosable()
closable.doStuff()
```

Compliant: 
```kotlin
val closable = functionThatReturnsClosable().use {
   it.doStuff()
}
```

Compliant
```kotlin
fun foo(bar: Closable) {
  bar.something()
}
```

Compliant (takes a Closable as a param, so it is exempt)
```kotlin
fun modifyClosable(bar: Closable): Closable { ... }

val moddedClosable = modifyClosable(myClosable)
```

Compliant (takes a Closable as a receiver, so it is exempt)
```kotlin
fun Closable.modifyClosable(): Closable { ... }

val moddedClosable = myClosable.modifyClosable()
```

**Comment by samuelneff** [comment]
Would this rule fall under `Potential-bugs Rule Set` (`detekt-rules-errorprone`)? I'd like to take a look at implementing as I think it's very useful and would like to have it in our own project.

**Comment by schalkms** [comment]
> Would this rule fall under `Potential-bugs Rule Set` (`detekt-rules-errorprone`)? I'd like to take a look at implementing as I think it's very useful and would like to have it in our own project.

Thanks for helping out! Yes, I think the rule set `detekt-rules-errorprone` is a good start. 👍

**Comment by samuelneff** [comment]
What about this use case which is very common in Java:

```kotlin
val lines = BufferedReader(
    FileReader("somefile.txt")
).use { it.lines() }
```

Here the `BufferredReader()` construction is fine because it is followed by `.use { }`, but the `FileReader()` call would trigger under the above guidelines. 

Should a constructed closeable that's immediately passed to another class's constructor be considered compliant?

Even if this were the case it is possible to still have issues with code not getting closed:

```kotlin
val whatever = MyCloseable(
    FileReader("somefile.txt"),
    getSomeValueButGenerateException()
).use { ..whatever.. }
```

In this case we declared `MyCloseable(closeable: Closeable, whatever: Any)` so in the code we instantiate a `FileReader` and pass it to the custom closeable, which we presume will chain the `close()` call to it. However, if `getSomeValueButGenerateException()` throws an exception, `MyCloseable()` constructor never gets called and `FileReader` never gets closed. 

Edge case if we call passing to constructors compliant; mostly thinking out loud.

**Comment by schalkms** [comment]
I guess the target state for the first version of this rule should be to keep it simple.
The example you mentioned requires data flow analysis to be flagged, which is at least currently out of scope for detekt. The compiler plugin might change this, but this is a discussion for another day.

**Comment by yogurtearl** [comment]
**Non-compliant:** 
```kotlin
val whatever = MyCloseable(
    FileReader("somefile.txt"),
    getSomeValueButGenerateException()
).use { myClosable -> whatever(myClosable) }
// do something with whatever
```
**Compliant:** 
if `whatever` does NOT return `Closable`: 
```kotlin
val whatever = FileReader("somefile.txt").use { fileReader ->
    MyCloseable(
        fileReader,
        getSomeValueButGenerateException()
    ).use { myClosable -> whatever(myClosable) }
}
// do something with whatever
```

AND `whatever(myClosable)` must not keep a reference `myClosable` after it returns.

**Compliant:** 
if `whatever` DOES return `Closable`: 
```kotlin
    FileReader("somefile.txt").use { fileReader ->
        MyCloseable(
            fileReader,
            getSomeValueButGenerateException()
        ).use { myClosable -> whatever(myClosable) }
    }.use { whatever ->
        // do something with whatever
    }
```


**But agree, we should only handle the simplest cases to start with.**

**Comment by samuelneff** [comment]
@yogurtearl Thanks for the extra test cases answering my question. 

I'm glad to hear agreement about it being out of scope. I'll ignore for now. :+1:

**Comment by atulgpt** [comment]
Hi, @BraisGabin / @yogurtearl added the code for this rule. Here my approach is also to flag only simple use-cases as mentioned in this PR. Please let me know if more TCs need to be added
