### ISSUE TITLE
Are custom rules still disabled by default

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#3890]
### Discussed in https://github.com/detekt/detekt/discussions/3850

<div type='discussions-op-text'>

<sup>Originally posted by **sschuberth** June  2, 2021</sup>
I'm just wondering whether [the sentence](https://github.com/detekt/detekt/blame/main/docs/pages/extensions.md#L226-L228)

> By default all rules not annotated with `@ActiveByDefault` are disabled.
That means your custom rules are also disabled if you have not explicitly enabled
them in the `detekt` yaml configuration file.

is still true, as my custom rules neither have the `@ActiveByDefault` annotation, nor are they activated in the YAML configuration file, but still they work fine.

So, is this really still valid, or can the sentence be deleted?</div>

**Comment by schalkms** [comment]
I guess we should remove examples that use the `EmptyConfig` as base class. We shouldn’t promote this kind of rule writing style. A comment in the `EmptyConfig` code to describe this *special* behavior is definitely helpful.
