### ISSUE TITLE
detekt-daemon which runs in background and can be reused for further analysis

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#39]
- like gradle-daemon or kotinc-daemon
- faster analysis, jvm warmup on start only

**Comment by schalkms** [comment]
Puhh, this issue is very old. We've done a lot to improve the performance of detekt.
@arturbosch Is this issue still up-to-date in your opinion? Otherwise, I'd like to close this.

**Comment by arturbosch** [comment]
Yep, a compiler is the way to go which also brings the desired performance boost.

**Comment by schalkms** [comment]
I didn't think about the compiler-plugin. Yes, this will sky-rocket the performance level. 😃
