### ISSUE TITLE
Spread operator when using extern libraries

### ISSUE THREAD

**Issue by tianhao-au** [detekt/detekt#391]
I got a spread operator issues with some function created by Spring and I can't easily change the function signature to `fun foo(vararg strings: String) { /* ... */ }`

Here is the example:

`SpringApplication.run(MyApplication::class.java, *args)`

What's the best solution for this if I don't want to bypass this error?   

Thanks.

**Comment by vanniktech** [comment]
Suppress it?

**Comment by schalkms** [comment]
Is it an overridden method?
Detekt might also want to ignore the spread operator in overridden methods.

**Comment by arturbosch** [comment]
Good suggestion @schalks. That's the way to go for many rules which have findings developers can't do anything about. Will provide a PR later.

**Comment by arturbosch** [comment]
Actually this requires type resolution which we currently do not have. For now you just can _suppress_ it or add it to the _baseline_ (black or white list it). Blocked.

**Comment by schalkms** [comment]
Well, detekt could just ignore overridden methods for the moment.

**Comment by arturbosch** [comment]
Well, the spread operator is only used in FunctionCalls and we can't resolve to the declared function -> we do not know which function to check for overriding? Or do I miss something?

**Comment by schalkms** [comment]
Yes. Thanks for clarifying.

**Comment by BraisGabin** [comment]
Closing. I think that with #3145 this issue is solved or at least mitigated. And because there was a lot of time without any update on this (not even a 👍). Please, comment if you think that this is still an issue in detekt that we should address.
