### ISSUE TITLE
unable to generate detektBaseline.xml in multimodule android project

### ISSUE THREAD

**Issue by TheReprator** [detekt/detekt#3915]
Hi,

Right now i am trying to generate baseline in my app for all modules in a common place,  but when i execute the following command,

./gradlew detektBaseline

It completes but no baseline file is executed.

Repo: https://github.com/TheReprator/Wipro/tree/detekt

Looking forward for a solution.

Regards,
Vikram Singh

**Comment by BraisGabin** [comment]
> in a common place

That is the problem. Each detekt task is independent of each other. So each one writes to the same path and the last one wins. I assume that the last module doesn't have any issue so the the task removes the file.

Detekt doesn't support a unified baseline out of the box.

**Comment by TheReprator** [comment]
but even last module was not able to generate the baseline.

**Comment by BraisGabin** [comment]
If the last one doesn't have issues it will remove the baseline file

**Comment by TheReprator** [comment]
so, if i have to generate the baseline, how could i?

**Comment by BraisGabin** [comment]
You need to have one for each module. If you want only one you can create it once in different plases and then merge them (you can create a script to do it or by hand) and then use that file. But I'd recommend it. Your modules should work independendly so they should have their own baseline.
