### ISSUE TITLE
Rename `input` property to `source` in the DetektExtension of the gradle plugin

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#3918]
### Discussed in https://github.com/detekt/detekt/discussions/3917

<div type='discussions-op-text'>

<sup>Originally posted by **peter-budo** June 28, 2021</sup>
... (post shortened)...

However when I try to assemble build I do run in following message
```
* What went wrong:
A problem occurred evaluating script.
> A problem occurred evaluating script.
   > Could not set unknown property 'input' for task ':app:detektAll' of type io.gitlab.arturbosch.detekt.Detekt.

```

Can anybody please explain me what I am doing wrong?</div>

In my opinion we should consider to rename the `input` property to `source` in the extension as well to avoid confusion. Since this will break everyone's builds the change cannot be done before 2.0, but we could add the source property and change the documentation already while supporting both.

**Comment by cortinico** [comment]
> In my opinion we should consider to rename the `input` property to `source` in the extension as well to avoid confusion

Seems like a good move to me.
I can't foresee any major issue with this rename 🤔 Other than `input` being more self-explanatory than `source`.

**Comment by BraisGabin** [comment]
The inconsistence if bad... But I agree with @cortinico that `input` seems more self-explanatory to me. But if `source` is the "standard" in the gradle world I think that we should embrace it.
