### ISSUE TITLE
EmptyDefaultConstructor is false positive for `expect class`

### ISSUE THREAD

**Issue by ArcticLampyrid** [detekt/detekt#3929]
## Expected Behavior
This should not be alerted.

## Details
https://github.com/ArcticLampyrid/KtJsonRpcPeer/security/code-scanning/1

**Comment by cortinico** [comment]
> ArcticLampyrid/KtJsonRpcPeer/security/code-scanning/1

This gives me a 404

Can you also provide a snippet?

**Comment by ArcticLampyrid** [comment]
I'm sorry that I forgot the code scanning is only visible to the owner
Rule ID `detekt.empty-blocks.EmptyDefaultConstructor`
[Image]



Sent from Outlook for Android<https://aka.ms/ghei36>

**Comment by ArcticLampyrid** [comment]
I'm sorry that I forgot the code scanning is only visible to the owner
Rule ID `detekt.empty-blocks.EmptyDefaultConstructo
![Screenshot_20210703_233924_com microsoft office outlook](https://user-images.githubusercontent.com/9017609/124359696-a6e21800-dc58-11eb-9146-75b7e3976aba.jpg)
