### ISSUE TITLE
Add `ignoredFlavorDimensions`

### ISSUE THREAD

**Issue by yogurtearl** [detekt/detekt#3950]
## Proposed New Behavior

Would like to be able to ignore all [flavors in a given dimension](https://developer.android.com/studio/build/build-variants#flavor-dimensions).

```
    // Android: Don't create tasks for the specified build flavor dimensions
    ignoredFlavorDimensions = ["mode"]
```

## Current Behavior

I can ignore specific flavors, but not ignore a whole dimension unless I enumerate all the flavors in that dimension.

```
    // Android: Don't create tasks for the specified build types (e.g. "release")
    ignoredBuildTypes = ["release"]
    
    // Android: Don't create tasks for the specified build flavor (e.g. "production")
    ignoredFlavors = ["production"]
    
    // Android: Don't create tasks for the specified build variants (e.g. "productionRelease")
    ignoredVariants = ["productionRelease"]
```    

## Context

Sometimes we have a dimension that we always want detekt to ignore, without having to update detekt config every time we add a flavor to that dimension

**Comment by chao2zhang** [comment]
Would it be acceptable if we expose a predicate `BaseVariant` -> `Boolean` and deprecate the existing `ignoredBuildTypes`, `ignoredFlavors` or `ignoredVariants`?

**Comment by yogurtearl** [comment]
`BaseVariant` doesn't seem to be listed in [their public API list](https://developer.android.com/reference/tools/gradle-api/4.2/classes)

I think [`ComponentIdentity`](https://developer.android.com/reference/tools/gradle-api/4.2/com/android/build/api/component/ComponentIdentity) -> `Boolean`  could probably work.

**Comment by chao2zhang** [comment]
Good call. `ComponentIdentity`/`Variant` is something we should consider. 

https://issuetracker.google.com/issues/170650362 This is an issue that I found is missing in the AGP 7.0 public API. I would like to give it try to see if we can migrate to `DetektAndroid` to use AGP 7.0 API only. (https://developer.android.com/studio/releases/gradle-plugin-roadmap)

**Comment by cortinico** [comment]
> I would like to give it try to see if we can migrate to `DetektAndroid` to use AGP 7.0 API only

Ideally in the future, yes. Right now it's unfeasible imho. AGP 7.0 stable is not out yet, and we would cut out the majority of our users if we do that.

**Comment by chao2zhang** [comment]
As far I as I know, we can't exclusively use AGP 7 API yet because of https://issuetracker.google.com/issues/170650362

**Comment by chao2zhang** [comment]
Looks like we should wait for Google to provide their opinions with regards to this issue.

Alternatively, the direction would go towards detekt-compiler

**Comment by cortinico** [comment]
> Looks like we should wait for Google to provide their opinions with regards to this issue.

IMHO we should not implement `ignoredFlavorDimensions` but instead have something like:

```
var disableDetektForVariant: (BaseVariant) -> Boolean
```

Which allow users to specify a lambda where they can access the BaseVariant + have their own login. Moreover we could move to Variant API once we bump to AGP 7.x and hook inside the `onVariants` and so on.
