### ISSUE TITLE
Autocorrect not working

### ISSUE THREAD

**Issue by ngarelimdex** [detekt/detekt#3963]
## Expected Behavior

When running the detekt gradle task in Android Studio with autoCorrect = true, I am expecting the formatting to autocorrect.

## Observed Behavior

No formatting is applied.

## Steps to Reproduce

See public repo here:
https://gitlab.com/ngarelimdex/MyApplication.git

Open project with Android Studio 4.2.1

Config:

```
detekt {

    autoCorrect = true
    toolVersion = "1.18.0-RC2"
    input = files(
            "src/main/java/"
    )
    config = files("config/detekt/detekt.yml")
    buildUponDefaultConfig = true
    basePath = projectDir
    debug = true
}
```

The detekt.yml is in the default location (app/config/detekt).

MainActivity has some import statements unused, unordered and the onCreate() has multiple spaces :

```
import android.view.AbsSavedState
import androidx.navigation.findNavController
import androidx.navigation.ui.AppBarConfiguration
import androidx.navigation.ui.navigateUp
import androidx.navigation.ui.setupActionBarWithNavController
import android.view.Menu
import android.view.ActionMode

import android.view.MenuItem
import com.example.myapplication.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {

    private lateinit var appBarConfiguration: AppBarConfiguration
    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?)  {
        super.onCreate(savedInstanceState)


```

## Your Environment

* Version of detekt used:1.18.0-RC2
* Version of Gradle used (if applicable):4.2.1
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: Android compileSdk 30
* Link to your project (if it's a public repository):
https://gitlab.com/ngarelimdex/MyApplication.git

**Comment by cortinico** [comment]
`autoCorrect` works only from rule from `detekt-formatting`, an external plugin that you need to include in your `build.gradle` file like:

```
dependencies {
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.18.0-RC2")
}
```

(As described here https://detekt.github.io/detekt/extensions.html#integrate-your-extension-with-the-detekt-gradle-plugin)

Seems like you haven't done it here:
https://gitlab.com/ngarelimdex/MyApplication/-/blob/main/app/build.gradle

**Comment by ngarelimdex** [comment]
Thanks, 
Working now.

This needs to be declared at the top of the gradle file too:
`apply plugin: 'io.gitlab.arturbosch.detekt'`
