### ISSUE TITLE
Template to share custom rules

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3967]
This is a follow up of #3829

There, @cortinico and @JavierSegoviaCordoba proposed to create a custom-rule template and encorage the usage of jitpack to make it easier for the users to share their custom rules.

I created that repository and I want feedback: https://github.com/BraisGabin/detekt-custom-rule-template (right now the repo is under my username but as soon as we agree that it's ready I would move it under the detekt organization)

I found one problem: The users should not use the example package name. That could create collisions in the future. For that reason I created a script to make it easy to decide your own packagename.

**Comment by cortinico** [comment]
>  found one problem: The users should not use the example package name. That could create collisions in the future. For that reason I created a script to make it easy to decide your own packagename.

On this side: we could add a Github Action that _prepares_ the repository after you create a new one from the template.

@martinbonnin helped me do something similar with the `kotlin-android-template` here:
https://github.com/cortinico/kotlin-android-template/blob/master/.github/workflows/cleanup.yaml

Basically once you use the template, a Github Action gets triggered only once that will cleanup the project and create a unique package name from the repository name.

**Comment by schalkms** [comment]
Good job! I like it. 🎉

**Comment by cortinico** [comment]
As for the template: it's great 👍 

I just have one note:
https://github.com/BraisGabin/detekt-custom-rule-template/blob/da93b57d5e19694e570dd906f4e246c2e6d58dfd/src/test/kotlin/org/example/detekt/MyRuleTest.kt#L5-L7

I would not use Spek for the sample test. Ideally I would create a plain JUnit test. I'm fine with us using it internally, but I'd try to simplify the template as much as possible to reduce frictions on the template/tool adoption.

**Comment by BraisGabin** [comment]
Workflow created (really nice trick!) and moved from Spek to JUnit. I agree that JUnit suits better for a template. I'll keep this issue open for some days to get more feedback (or even PRs :P) and then I'll move the repository to the detekt organization and create some documentation in the web pointing to it.

**Comment by JavierSegoviaCordoba** [comment]
Maybe the cleanup workflow can be a workflow dispatch where you can put the package name and every needed input (package, data for publishing and so on).

**Comment by schalkms** [comment]
Maybe we should also put a tag `custom-rules` on this repo in order to find it via GitHub search.

**Comment by BraisGabin** [comment]
> Maybe we should also put a tag `custom-rules` on this repo in order to find it via GitHub search.

Done

> Maybe the cleanup workflow can be a workflow dispatch where you can put the package name and every needed input (package, data for publishing and so on).

The problem I see is that I don't want anyone to use package `org.example`. And if I transform the workflow to a workflow dispatch I'm worried that the users will not use it and just use the `org.example` package. But I agree that a workflow dispatch would be nicer and will allow a bit more customization. Any idea about how to get both?

**Comment by marschwar** [comment]
I really like the template repository idea. Should its Readme.md maybe contain some basic information on how to integrate the rules into a project once they are released?

**Comment by BraisGabin** [comment]
That sound reasonable any suggestion about how to document that?

The README of the template is a bit "strange" because you want it to be a readme for the template AND to be a template for a readme for the real project that will be generated on top of it. So it is in between two worlds that I'm not sure how to handle properly.

**Comment by schalkms** [comment]
However, the readme could contain a link to detekt's website, which shows how to integrate custom rules into a project.

https://detekt.github.io/detekt/extensions.html#custom-rulesets

**Comment by cortinico** [comment]
> I don't want anyone to use package `org.example`

I believe we can update the default package to: `io.github.detekt.community`
or something along those lines.

We already have software under that package:
https://repo1.maven.org/maven2/io/github/detekt/

Users won't be able to publish them to Maven Central, yet they would be easy to browse/recognize and easier to use via Jitpack.

**Comment by BraisGabin** [comment]
What do you think about using `@AutoService` in the template project? I think that it makes the code less error prone. Any change in the package or class name will not break the installation of the plugin.

**Comment by cortinico** [comment]
> What do you think about using `@AutoService` in the template project?

I'm unsure to be honest. I would stick to have it _as vanilla as possible_ so I would opt for not having it, but maybe we can add a note to the README or somewhere in the documentation?

**Comment by BraisGabin** [comment]
> However, the readme could contain a link to detekt's website, which shows how to integrate custom rules into a project.
> 
> https://detekt.github.io/detekt/extensions.html#custom-rulesets

It does :)

> I believe we can update the default package to: `io.github.detekt.community`
> or something along those lines.
> 
> We already have software under that package:
> https://repo1.maven.org/maven2/io/github/detekt/
> 
> Users won't be able to publish them to Maven Central, yet they would be easy to browse/recognize and easier to use via Jitpack.

They can't use our cordinates but they could use that package with other coordinates. I think that I prefer to keep `org.example` to make it "more clear" that the package is just and example and should be changed.

**Comment by BraisGabin** [comment]
Ok, I moved the repo to the organization. New link: https://github.com/detekt/detekt-custom-rule-template
