### ISSUE TITLE
A way to merge Android default lint with detekt reporting would be awesome

### ISSUE THREAD

**Issue by skymansandy** [detekt/detekt#3978]
Your feature request may already be reported!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior
The Android ecosystem already has a linter with lots of rules specified. A way to even catch them with detekt reporting would be awesome if possible, so that we can see all lint issues at one place 

## Current Behavior
Android linter warnings are seperate

## Context
Grow the number of rules.

**Comment by cortinico** [comment]
> The Android ecosystem already has a linter with lots of rules specified. A way to even catch them with detekt reporting would be awesome if possible, so that we can see all lint issues at one place

True, yet I would argue that:
1. Having separate reports makes it easier to enable/disable the linters you wish.
2. This feel like should be a separate tool that consumes lint and detekt output and merges them in some form. What's the reason why Detekt should consumer other tools' output and not vice versa?

**Comment by schalkms** [comment]
Closed due arguments made above. This should really be custom tool and not part of detekt.
