### ISSUE TITLE
ProtectedMemberInFinalClass triggered on Spring component with allopen compiler plugin

### ISSUE THREAD

**Issue by gavvvr** [detekt/detekt#3981]
I have a Spring project with an [allopen plugin](https://kotlinlang.org/docs/all-open-plugin.html) installed to make classes non-final by default. Would be nice for detekt to have a configuration option to denote presence of allopen plugin and behave accordingly.

Otherwise protected methods of Spring components get `ProtectedMemberInFinalClass` false positive:

![image](https://user-images.githubusercontent.com/1719646/127034733-0746bddf-e9e5-4142-a85e-ebf8349ea4f2.png)

**Comment by BraisGabin** [comment]
Would it be enough for your use case to have a new configuration in this rule allowing you to ignore classes with the annotations defined there?

**Comment by gavvvr** [comment]
Need to check if allopen plugin makes **all** classes `open` by default or only those with `@Component`-like annotation

**Comment by cortinico** [comment]
> Would be nice for detekt to have a configuration option to denote presence of allopen plugin and behave accordingly.

That's not trivial. Specifically as we already had in the past problems with compiler flags (and therefore plugins) not being aligned with the Kotlin compilation and the Detekt run.

Potentially something that could be addressed with github.com/detekt/detekt-compiler-plugin

The solution suggested by @BraisGabin would be the safest for you.
Also if you have the `all-open` plugin you can probably disable the `ProtectedMemberInFinalClass` rule entirely as you won't effectively have final classes.

**Comment by BraisGabin** [comment]
I think that after #4102 this can be closed. Open again if that's not true.
