### ISSUE TITLE
show success msg in stdout if no issues at all

### ISSUE THREAD

**Issue by robstoll** [detekt/detekt#4020]
## Expected Behavior
I would like to see something like `detekt findings: 0` or something similar so that I am sure detekt actually ran. 

*Edit*: or even better, provide an afterSuite hook similar as for Test tasks

## Current Behavior
I don't see anything (txt report is empty as well, I guess same behaviour)

## Context
I don't expect a message if the task is up-to-date but I expect a message if I make a code change and run detekt.

**Comment by BraisGabin** [comment]
I disagree here. When you run the test task you don't see anything telling you that all the tests passed. If you want this behavior you can create a doLast task and print that message. But I think that the detekt plugin is consistent with the gradle behavior.

**Comment by robstoll** [comment]
I see your point and agree, yet detekt should still provide a hook like `afterSuite` in order to be consistent with `test` IMO. I forgot that I print the test summary in there myself and that it's not a default behaviour. If detekt provides the same mechanism, then I would be happy too 🙂

**Comment by cortinico** [comment]
As @BraisGabin, the detekt-gradle-plugin is consistent with the behavior of Gradle and other plugin in the ecosystem.

If you wish to see a "success message" you can customize your build as follows:

```
tasks.withType<Detekt>().configureEach {
    doLast {
        logger.lifecycle("Detekt findings: 0")
    }
}
```

**Comment by robstoll** [comment]
Interesting enough, if you change from `buildUponDefaultConfig = true` to `allRules = true` (I had failFast in previous versions, probably the reason why I always saw a summary so far) then you always see the summary :man_shrugging:

**Comment by robstoll** [comment]
Just in case someone else stumbles over this issue and wonders why `tasks.withType<Detekt>()` does not work in case of a
MPP project. I guess it's due to this:
https://github.com/detekt/detekt/blob/75622d3ba88b0ae0357aec5f2d82a55aa6c6d157/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektMultiplatform.kt#L26

You can work around it by evaluating `tasks` within a double `project.afterEvaluate`:
```kotlin
tasks.withType<Detekt>().configureEach {
    println("withType: $this") // prints only :detekt if the below workaround is not applied
}
project.afterEvaluate {
  project.afterEvaluate {
    tasks.filter{true} // seems to trigger tasks evaluation in the right moment so that tasks.withType above works as expected
  }
}
```
@cortinico :point_up: could be interesting for you to know as well as you are the author of the comment

**Comment by cortinico** [comment]
> @cortinico ☝️ could be interesting for you to know as well as you are the author of the comment

Thanks for pointing this out. I believe we should clean it up and potentially try to remove that `afterEvaluate{}` block.
