### ISSUE TITLE
ThrowingExceptionsWithoutMessageOrCause should use Type Resolution to avoid False Positives

### ISSUE THREAD

**Issue by mhernand40** [detekt/detekt#4037]
Take the following code snippet for example:
```Kotlin
fun foo() {
    val result: FooResult = FooResult.Error()
    println(result)
}

sealed class FooResult {
    object Success : FooResult()
    data class Error(val message: String? = null) : FooResult()
}
```

## Expected Behavior
Detekt should not flag a `ThrowingExceptionsWithoutMessageOrCause` for this code.

## Observed Behavior
Detekt flags a `ThrowingExceptionsWithoutMessageOrCause` violation for calling `FooResult.Error()` even though it is not an actual `Throwable`.

## Context
We have custom Result sealed classes in our codebase where the subtype is called `Error`. Whenever an instance of one is created without any constructor arguments, Detekt wrongfully flags them as `ThrowingExceptionsWithoutMessageOrCause`. When I upgraded from `1.17.1` -> `1.18.0` and re-generated the baselines I noticed new suppressions were added for `ThrowingExceptionsWithoutMessageOrCause` for these particular scenarios which indicates to me that this false positive was recently introduced.

## Your Environment

* Version of detekt used: 1.18.0
* Version of Gradle used (if applicable):
```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.9 (Eclipse OpenJ9 openj9-0.23.0)
OS:           Mac OS X 10.16 x86_64
```
* Operating System and version: MacOS Big Sur 11.5

**Comment by BraisGabin** [comment]
I think that this is a regression. We added `Error` to the default list so we know have this problem.

As a workaround you can remove `Error` from that list in your configuration.

My porposal is in two steps:

1. Remove `Error` from the default list for now.
2. Make `ThrowingExceptionsWithoutMessageOrCause` use Type Resolution to avoid other false positives.
