### ISSUE TITLE
Cannot disable DoubleMutabilityForCollection and AvoidReferentialEquality from config

### ISSUE THREAD

**Issue by geojakes** [detekt/detekt#4039]
## Expected Behavior
DoubleMutabilityForCollection and AvoidReferentialEquality rules should be disabled when specified in the detekt-config

## Observed Behavior
These rules still show up as errors in a project, even though specifically disabled with the recommended config.

## Steps to Reproduce
- Attempt to disable one of these issues via config file

## Context
This issue is preventing me from upgrading my project to detekt 1.18.0 until the specific rules are completely addressed.

## Your Environment

* Version of detekt used: 1.18.0
* Version of Gradle used (if applicable): 7.0.2
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by cortinico** [comment]
Fixed by #4040
Will be released in `1.18.1`.

**Comment by geojakes** [comment]
@cortinico Do you have an ETA on 1.18.1 atm?

**Comment by cortinico** [comment]
> @cortinico Do you have an ETA on `1.18.1` atm?

No promise but I'll say in a couple of days. We also want to make sure that users can report any other critical bug (so hopefully we won't need a `1.18.2` 🤞 ).

**Comment by geojakes** [comment]
Next week would be awesome! :)

**Comment by geojakes** [comment]
@cortinico Can you advice me on how to use a local build of detekt in one of my other projects. I just want to confirm if the issues we had are completely resolved.

**Comment by cortinico** [comment]
> Can you advice me on how to use a local build of detekt in one of my other projects.

You can follow the instructions here: https://detekt.github.io/detekt/snapshots.html

**Comment by geojakes** [comment]
@cortinico Awesome, thank you. Do you have any updates on the micro version release or a place where I can find the status?

**Comment by cortinico** [comment]
Updated infos are here: https://github.com/detekt/detekt/pull/4066
