### ISSUE TITLE
start path with file:// so that intellij turns it into a link in the console

### ISSUE THREAD

**Issue by robstoll** [detekt/detekt#4041]
Your feature request may already be reported!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior
one can click in the console on the path related to the issue and can jump there immediately

## Current Behavior
the path is in the console but one has to go there manually

## Context
Following an example:
```
/home/robert/projects/kbox/src/jvmMain/kotlin/ch/tutteli/kbox/JvmSynchronized.kt - 5min debt
        EndOfSentenceFormat - [JvmSynchronized] at /home/robert/projects/kbox/src/jvmMain/kotlin/ch/tutteli/kbox/JvmSynchronized.kt:3:1
```
if it would be the following, then it would be recognised by intellij as link and would be clickable:
```
/home/robert/projects/kbox/src/jvmMain/kotlin/ch/tutteli/kbox/JvmSynchronized.kt - 5min debt
        EndOfSentenceFormat - [JvmSynchronized] at file:///home/robert/projects/kbox/src/jvmMain/kotlin/ch/tutteli/kbox/JvmSynchronized.kt:3:1
```
Much nicer isn't it? :slightly_smiling_face: 

I can also provide a PR if you can give me a pointer where to look

**Comment by cortinico** [comment]
Yes it makes sense 👍 Perhaps all the paths should be updated (not just the second one in your example)?

If you want to contribute you should look into those files:
https://github.com/detekt/detekt/tree/main/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/reporting/console

**Comment by marschwar** [comment]
As a side note, running the detekt tasks in the IDE allows me to click on the link directly

![Screenshot_2021-08-17_14-07-45](https://user-images.githubusercontent.com/4807823/129723037-cfcffdf9-839a-4208-b22c-3003873b2b52.png)

Version: IntelliJ Idea 2021.1.3

**Comment by robstoll** [comment]
> Perhaps all the paths should be updated (not just the second one in your example)?

I would only update paths which include a line number. I'll draft a PR.

**Comment by chao2zhang** [comment]
Echoing @marschwar, it works for me in intelliJ console without the additional `file://`

**Comment by robstoll** [comment]
@chao2zhang when you say in the IntelliJ console, then you are also referring to the detekt-plugin right? if you ran `./gradlew detekt` then it does not, isn't it?

**Comment by BraisGabin** [comment]
🤔 I'm not 100% sure here. For example, the "basic" Terminal from mac doesn't allow to click that kind of links. But `iTerm2` does. I'm a bit worried that adding `file://` could break another terminals.

**Comment by robstoll** [comment]
Terminal wise I don't see an issue, either the terminal renders such things as links and allows clicking on it or it does not (or ask beforehand and the like). Why do you think it could break someone's terminal?
