### ISSUE TITLE
LongParameterList: Customization for @Composable functions?

### ISSUE THREAD

**Issue by pocmo** [detekt/detekt#4061]
With [JetpackCompose](https://developer.android.com/jetpack/compose) I start to hit `LongParameterList` much more often, since state is passed down the call stack. In addition to that `@Composable` functions tend to have a bunch of parameters with default values (see [`TextField()`](https://cs.android.com/androidx/platform/tools/dokka-devsite-plugin/+/master:testData/compose/source/androidx/compose/material/TextField.kt;l=156-176) for example).

So I wonder if it makes sense to allow customization `LongParameterList` to handle `@Composable` differently.

**Comment by pocmo** [comment]
Actually, I noticed there's `ignoreDefaultParameters` which may be able to help in a lot of those cases (assuming most parameters in `@Composable` functions actually have default values).

**Comment by cortinico** [comment]
> Actually, I noticed there's `ignoreDefaultParameters` which may be able to help in a lot of those cases

Ideally this. We tend to be as platform/framework agnostic as possible: https://github.com/detekt/detekt/discussions/3894

**Comment by pocmo** [comment]
Yeah, let's close.
