### ISSUE TITLE
Line length and threshold in the `MaxLineLength` message

### ISSUE THREAD

**Issue by GirZ0n** [detekt/detekt#4076]
## Expected Behavior of the rule
I think the `MaxLineLength` message should contain line length and threshold, as it is done in other metrics.

Now the message looks like this: "Line detected that is longer than the defined maximum line length in the code style".

But it could look something like this: "Line detected that is longer than the defined maximum line length in the code style (146/120)".

## Context
I'm working on a tool that analyzes student code. We need code metrics, in particular line lengths that exceed a threshold.

**Comment by chao2zhang** [comment]
This is a quality-of-life improvement to me. We actually have two rules with regards to the maxlinelength rule:
- The first one is Detekt native rule (https://github.com/detekt/detekt/blob/main/detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MaxLineLength.kt), where you pointed out that we are missing the information on the stats.
- The second one is Ktlint rule (https://github.com/pinterest/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/MaxLineLengthRule.kt) where it does seem to provide some statistics info in the error message.

You are always welcome to contribute to the Detekt native rule. On the other hand, feel free to try out detekt-formatting according to [the doc](https://detekt.github.io/detekt/extensions.html#integrate-your-extension-with-the-detekt-gradle-plugin) to see if the second approach meets your need.

**Comment by GirZ0n** [comment]
@chao2zhang Thank you! Unfortunately, Ktlint rule only shows the threshold, but not the line length. :pensive:

**Comment by BraisGabin** [comment]
If ktlint doesn't do that you can report it to ktlint. Or, if you have the time, create a PR there.

**Comment by BraisGabin** [comment]
Closing because this issue is not fixable by detekt.
