### ISSUE TITLE
MaxLineLength rule is duplicated by MaximumLineLength

### ISSUE THREAD

**Issue by sergeys-opera** [detekt/detekt#4079]
## Expected Behavior
When adding `@Suppress("MaxLineLength")` no "max line length" issue should be reported.

## Observed Behavior
`MaximumLineLength` is being reported. I need to suppress both `MaxLineLength` and `MaximumLineLength` which is a bit confusing (given also the fact that these checks work differently). 

## Steps to Reproduce
Define a constant with a long string.

## Context
I have long SQL queries (primarily auto-generated by Room) in constant fields for the database migration. As I don't want to change anything in them I'd like to suppress the "long line" warning which works well with `MaxLineLength` but not so well with `MaximumLineLength` (I cannot really disable this check for some reason). But I shouldn't be disabling both checks - one line length check should be enough, having two checks with the similar name is just confusing:
https://detekt.github.io/detekt/style.html#maxlinelength
https://detekt.github.io/detekt/formatting.html#maximumlinelength

## Your Environment
* Version of detekt used: 1.18.0-RC2
* Version of Gradle used (if applicable): 7.0.1

**Comment by marschwar** [comment]
Is this a typo in your code or just the issue? `MaxLineLenght` != `MaxLineLength`

**Comment by cortinico** [comment]
Those are effectively two distinct rules: https://github.com/detekt/detekt/discussions/4049#discussioncomment-1193682

**Comment by marschwar** [comment]
I was talking about the typo in the word _length_. It should be `@Suppress("MaxLineLength")`

**Comment by cortinico** [comment]
> I was talking about the typo in the word _length_. It should be `@Suppress("MaxLineLength")`

Yup you're right :) I actually dropped my thoughts by just reading the issue title, my bad.

**Comment by sergeys-opera** [comment]
@marschwar sorry for the confusion. I actually used the correct `MaxLineLength` and `MaximumLineLength` in the code. Corrected the original message now.

@cortinico sure, I know that these are two separate rules (I even left links to them in the first message).

My question is "why are there two similar rules?" Can't they be merged?
I can come up with several issues which might be caused by having two rules instead of one:
1. Changing `maxLineLength` in one doesn't affect another.
2. Suppressing one rule doesn't suppress the other.
3. `ignoreBackTickedIdentifier` is supported by one rule but not another. The same goes for `excludeImportStatements`, etc

**Comment by cortinico** [comment]
Thanks for clarifying,

> My question is "why are there two similar rules?" Can't they be merged?

My original link (https://github.com/detekt/detekt/discussions/4049#discussioncomment-1193682) should actually answer your question. One of the rule is a first-party rule (from `detekt`). The other is an external rule (from `detekt-formatting`, that means is wrapping a KtLint rule).

So no, they can't be "merged" but you can disable one of the two if you wish 👍

**Comment by sergeys-opera** [comment]
Yes, that's why I did - I disabled `MaximumLineLength` but I wonder if that should be done by default in `detekt`.
Closing the issue.

**Comment by cortinico** [comment]
> Yes, that's why I did - I disabled `MaximumLineLength` but I wonder if that should be done by default in `detekt`.

I don't think so. Detekt does not enable `detekt-formatting` by default. You have to specifically add the extra dependency for it. Once you do it, you're also responsible of which rules to enable/disable.

**Comment by sergeys-opera** [comment]
> Detekt does not enable detekt-formatting by default
How come it's enabled in my Android project then? I use `buildUponDefaultConfig = true` with some minor overrides in a custom config. The default configuration has `formatting` (with `MaximumLineLength`) enabled by default.
https://github.com/detekt/detekt/blob/3ecac0d82bed34d22844250671c3f4a509072ffc/detekt-core/src/main/resources/default-detekt-config.yml#L268

**Comment by cortinico** [comment]
> How come it's enabled in my Android project then?

If you're using the detekt-gradle-plugin, you most likely have a `detektPlugins` dependency on detekt formatting as described here https://detekt.github.io/detekt/extensions.html#integrate-your-extension-with-the-detekt-gradle-plugin

**Comment by sergeys-opera** [comment]
Right, there is `detektPlugins` defined in the project but that doesn't explain why the rule gets enabled.
 From the documentation:
> All rules are disabled by default and have to be explicitly enabled in the detekt yaml configuration file.

And I see that the default configuration file enables this rule: https://github.com/detekt/detekt/blob/3ecac0d82bed34d22844250671c3f4a509072ffc/detekt-core/src/main/resources/default-detekt-config.yml#L307

**Comment by BraisGabin** [comment]
I think that is enabled because the default configuration has the config of the formatting plugin. That's misleading. I know that we have an issue tracking this point but I can find it from my phone. The point is that, right now, the pluggings can not provide their default configuration so, because formatting is inside this repo, its configuration is added. This is because historical reasons but we should fix it.

**Comment by cortinico** [comment]
> I think that is enabled because the default configuration has the config of the formatting plugin. That's misleading

Yes I believe that's an inconsistency that we probably want to tackle. In my opinion `detekt-formatting` should nto have any special treatment and be considered as all the other 3rd party rules.
