### ISSUE TITLE
value internal and internal value both show warnings

### ISSUE THREAD

**Issue by VincentJoshuaET** [detekt/detekt#4087]
![image](https://user-images.githubusercontent.com/19756326/131966148-7183ea23-fffa-4192-8a9f-4e0ce5418abb.png)

![image](https://user-images.githubusercontent.com/19756326/131966176-1179b68e-34c8-4d67-ba50-e2b4d7b8fbc0.png)

**Comment by BraisGabin** [comment]
Could you elaborate? What is the expected? Which one is the wrong one? Which version of detekt are you using?

**Comment by VincentJoshuaET** [comment]
1.18.1. I think value internal is incorrect because that's what IntelliJ shows the warning for. Also internal value just sounds more correct.

**Comment by 3flex** [comment]
If the warning (top screenshot) is from detekt IntelliJ plugin, it's because the plugin hasn't updated its dependencies in a while and is using 1.17.1 internally which doesn't recognise `value` in the ModifierOrder rule.

This should be fixed with the next IntelliJ plugin update.

**Comment by cortinico** [comment]
> This should be fixed with the next IntelliJ plugin update.

That is coming soon 👍 https://github.com/detekt/detekt-intellij-plugin/pull/133

**Comment by 3flex** [comment]
This should be fixed by [release 1.18.1 of detekt-intellij-plugin](https://github.com/detekt/detekt-intellij-plugin/releases/tag/v1.18.1)

Please reopen if that's not the case or if there's something else to this issue, thanks!
