### ISSUE TITLE
Find unused public methods, enum values

### ISSUE THREAD

**Issue by tarasmurzenkovv** [detekt/detekt#4111]
## Expected Behavior of the rule 

Is there any rule that could check if the public class method (non-abstract) and/or enum value is used in the project?

**Comment by BraisGabin** [comment]
There isn't. Right now detekt works at a file level. It doesn't know even about other usages in the module. But I think that we should think about how to handle this for 2.0. It's not an easy task at all...

Maybe we could start looking at internal usages. But as I said this isn't an easy task. We should check how other tools solve this. Any ideas are more than welcome.

**Comment by cortinico** [comment]
> is used in the project?

Little side note: how this rule should behave regarding external projects that are consuming your project? If you declare a field `public` it means that everyone can depend on it, also consumer that are outside of the codebase.

**Comment by tarasmurzenkovv** [comment]
> > is used in the project?
> 
> 
> 
> Little side note: how this rule should behave regarding external projects that are consuming your project? If you declare a field `public` it means that everyone can depend on it, also consumer that are outside of the codebase. 

My use case is simple: the linter should fail if it detects unused public methods.

I think for the MVP implementation it could be sufficient

**Comment by BraisGabin** [comment]
I think that this rule should be useful for application developers but it would not be useful for library developers.

**Comment by BraisGabin** [comment]
I vote to close this. It's a completely legit issue but it's not feasable for detekt short/mid term. We need to develop a way to handle a project and not just individual files as we do right now. Once we have that we can start developing this kind of rules.
