### ISSUE TITLE
Disable UnsafeCallOnNullableType on tests by default

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4119]
In general, I don't see any problem with the operator `!!` on test. If you want to assume that something is not-null you should do it freely. It's a test. If you are wrong it will fail and you will need to fix it. Encorage the usage of the safe call operator `?.` or `if`s in tests seems to me even mor problematic than the usage of `!!`. You would use `?.` just to make detekt happy because "it will be always not-null" and then you end up with unexpected behaviours on your test.

There is an example and some comments about this here: https://github.com/detekt/detekt/pull/4102#pullrequestreview-757305499

So, I'd like to add `excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']` to this rule.

**Comment by cortinico** [comment]
Agree on disabling this for tests on our users. I also actively use `!!` inside tests to catch failures early on.
