### ISSUE TITLE
Request: Clearer setup documentation

### ISSUE THREAD

**Issue by ColtonIdle** [detekt/detekt#4129]
I had some trouble configuring detekt and went to kotlinlang slack to reach out for some help. Apparently there is some confusion on how to set this up in a kmm project vs an android project, and I think it could use an overall revamp.

For example, here it looks like the android configuration says that you should put this in your root build.gradle
<img width="874" alt="Screen Shot 2021-09-26 at 8 32 57 PM" src="https://user-images.githubusercontent.com/31751141/134829914-67858e52-dc81-4c19-aa9b-c1c2e6c402e4.png">

while on kotlinlang @cortinico says it should go into the module itself.

**Comment by cortinico** [comment]
Thanks for reporting. Fixed in #4141. Also for the future feel free to edit the page yourself and send a PR 🙏 We try to do the best to keep the doc. quality high but is not always easy
