### ISSUE TITLE
Fix FOSSA GitHub check

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#4138]
## Expected Behavior
FOSSA GitHub Action succeeds.

## Observed Behavior
FOSSA GitHub Action fails, so we have a string of ❌ on `main` branch, and ![image](https://user-images.githubusercontent.com/170028/135414250-b979f0ff-423f-4911-8eab-785c3bd22144.png) showing on the README badge.

## Steps to Reproduce
N/A - see GitHub check status on any recent build on `main`.

## Context
Our `main` build should pass CI consistently.

## Your Environment
N/A

**Comment by cortinico** [comment]
This is now fixed. There was a missing license for Guava that I entered manually.
