### ISSUE TITLE
Nested SwallowedException are not detected

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4153]
## Expected Behavior
```
> Task :detekt FAILED
exceptions - 20min debt
        SwallowedException - [f] at src\main\kotlin\test.kt:4:4
        SwallowedException - [f] at src\main\kotlin\test.kt:7:4
```

## Observed Behavior
```
> Task :detekt FAILED
exceptions - 20min debt
        SwallowedException - [f] at src\main\kotlin\test.kt:4:4
```

## Steps to Reproduce
```kt
fun f() {
	try {
		println("verifySomething")
	} catch (ex: AssertionError) {
		try {
			println("verifySomethingElse")
		} catch (ex2: AssertionError) {
			throw ex.initCause(ex2)
		}
	}
}
```

## Context
No context, just noticed it. See usage at https://github.com/TWiStErRob/net.twisterrob.cinema/blob/master/Heroku/backend/network/src/test/kotlin/net/twisterrob/ktor/client/ConfigureLoggingTest.kt#L212-L220
The nested AssertionError is guaranteed after "noMore" throwing.

## Your Environment

* Version of detekt used: `io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.18.1`
* Version of Gradle used (if applicable): 6.9
* Gradle scan link (add `--scan` option when running the gradle task): -
* Operating System and version: Windows 10
* Link to your project (if it's a public repository):
https://github.com/TWiStErRob/net.twisterrob.cinema/blob/master/Heroku/backend/network/src/test/kotlin/net/twisterrob/ktor/client/ConfigureLoggingTest.kt#L212-L220 but Detekt integration is not merged yet.

**Comment by chao2zhang** [comment]
Since `throw ex.initCause(ex2)` refers `ex2`, I think the observed behavior is correct because `ex2` is not swallowed.

**Comment by BraisGabin** [comment]
I agree with chao that this doesn't seem a `ShallowedException`... but I think that we are missing a super call  in this rule. I just notice it reading #4158. We could add a test to ensure this.
