### ISSUE TITLE
Some checks have very verbose "names" in GitHub code scanning

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4163]
This affects multiple rules.

## Expected Behavior of the rule
When looking at https://github.com/org/repo/security/code-scanning I want to see a short quick summary of the issues, not repeated details and default values which I might've overridden anyway. Sadly I noticed that `Issue` doesn't have a title and a description field like Android-lint, so I think what's missing is a consistent scheme of defining check descriptions. What goes into the Issue definition and what goes into the documentation.

## Context
I did as suggested by https://github.com/detekt/detekt/issues/3045#issuecomment-933033224 and I managed to set up Detekt. When I first ran it (with some issues to test), I received a long list with some very verbose titles. When looking at this list I would want to see a quick summary.
![image](https://user-images.githubusercontent.com/2906988/136093861-bdbf73ea-9dee-42df-bafb-95cad5cc029c.png)

Here's one long one when I open it:
![image](https://user-images.githubusercontent.com/2906988/136093685-11018e37-6624-4eca-8f15-696d430a8165.png)

**Comment by 3flex** [comment]
Closing, see https://github.com/detekt/detekt/issues/4750#issuecomment-1109627132

**Comment by TWiStErRob** [comment]
I think agree with @BraisGabin that this is a generic issue, because the issue is systematic. I think the solution is to add a single test (is there a rule base test?) that validates that the description of every rule is <100 (arbitrary) characters and then fix the long ones. No-one should manually read and validate messages... 😅

**Comment by BraisGabin** [comment]
That sounds like a good idea to me.
