### ISSUE TITLE
Sarif output from detekt is not finding paths on GitHub 

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4165]
## Expected Behavior
![image](https://user-images.githubusercontent.com/2906988/136093431-af7498bc-218d-4bb9-b0ca-c598e3747a7e.png)

## Observed Behavior
![image](https://user-images.githubusercontent.com/2906988/136097214-896ec1ac-d621-48d9-b731-4e4698b0ec20.png)

## Steps to Reproduce
<details><summary>High level guidance</summary>

Follow: https://detekt.github.io/detekt/reporting.html#integration-with-github-code-scanning
Then make a change that triggers Detekt and view the annotations.
And view code scanning annotations for the PR:
![image](https://user-images.githubusercontent.com/2906988/136097285-0e561983-3e25-4426-9f16-76f964dadd84.png)
![image](https://user-images.githubusercontent.com/2906988/136097310-92ae9902-0109-4e61-abfd-4dcf17d70ecd.png)
</details>

 * Create a repo on GitHub
 * Get https://github.com/TWiStErRob/repros/tree/main/detekt/sarif-github-previews locally
 * `git init .`
 * `git remote add origin <url>`
 * Review CI.yml and choose the branch in checkout (e.g. detekt/detekt v1.23.1)
 * commit and push
 * CI will execute as [shown in the testing setup](https://github.com/detekt/detekt/pull/6331#issuecomment-1660541102)

## Context
I'm trying to set up Code scanning as suggested here: https://github.com/detekt/detekt/issues/3045#issuecomment-933033224

I was trying to make the annotations show the preview, but the default setup didn't let me. Then I looked at the code of the action referenced in the doc:
https://github.com/github/codeql-action/blob/7d56b0cd44f66136d094ee8b67d457c9cec4b8ef/src/upload-lib.ts#L376
this replaces the default `${{ github.workspace }}` file path with a file uri (i.e. prepending with `file://` in case of an absolute path.

then I see this in the documentation of the github endpoint:
https://docs.github.com/en/rest/reference/code-scanning#upload-an-analysis-as-sarif-data

I tried to get a reference from documentation on this, but it's really hard to understand:
https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317430

So finally I understood that the `uri` property must be a URI to work with GitHub, so I added this build step:
```
      - name: Fix detekt paths.
        run: >
          sed -re 's!"uri": "${{ github.workspace }}!"uri": "file://${{ github.workspace }}!g'\
              <build/reports/detekt/detekt.sarif\
              >build/reports/detekt/detekt-fixed.sarif
```
and uploaded the resulting file. Notice that the sarif file still has absolute URIs in them, but in the screenshot they're showing relative paths.

## Your Environment

* Version of detekt used: 1.18.1
* Version of Gradle used (if applicable): 6.9
* Gradle scan link (add `--scan` option when running the gradle task): -
* Operating System and version: ubuntu-latest (GitHub actions)
* Link to your project (if it's a public repository): wouldn't see much because probably I will have fixed all issue by the time you see this. Refer to screenshots.

**Comment by TWiStErRob** [comment]
Note: I'm using this setup in Gradle
```gradle
plugins {
	id("io.gitlab.arturbosch.detekt")
}
allprojects {
        // These above 4 lines are effectively the same as `detekt { ... }`, but work with `allprojects` block in root build.gradle.kts.
	plugins.withId("io.gitlab.arturbosch.detekt") {
		val detekt = this@allprojects.extensions
			.getByName<io.gitlab.arturbosch.detekt.extensions.DetektExtension>("detekt")
		detekt.apply {
			ignoreFailures = true
			buildUponDefaultConfig = true
			allRules = true
			config = rootProject.files("config/detekt/detekt.yml")
			baseline = rootProject.file("config/detekt/detekt-baseline-${project.name}.xml")

			parallel = true

			reports {
				html.enabled = true // human
				xml.enabled = true // checkstyle
				txt.enabled = true // console
				// https://sarifweb.azurewebsites.net
				sarif.enabled = true // Github Code Scanning
			}
		}
	}
}
tasks.named<io.gitlab.arturbosch.detekt.Detekt>("detekt") {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
	description = "Runs over whole code base without the starting overhead for each module."
	setSource(files(rootProject.projectDir))
}
```

**Comment by BraisGabin** [comment]
You should define the `basePath` in the plugin configuration. I think that with that detekt will use relative paths in the sarif report.

I think that we should set that value by default so no one need to setup it.

**Comment by TWiStErRob** [comment]
Ah, I thought it was automatic, good improvement. But even if it's not set, using the right absolute path format also works. So I also suggest to convert the File.absolutePath to URI.fromFile(path) when it's absolute to match their expectations.

**Comment by 3flex** [comment]
Basepath should be set automatically with detekt 2.0 I think.

If possible can we confirm if setting basepath to rootDir fixes this? What about projectDir?

**Comment by TWiStErRob** [comment]
I think I used rootDir, because I merge many modules into 1 sarif to upload to GH. And rootdir is (usually) the root of the repository as well. In my most complex repo I have this: https://github.com/TWiStErRob/net.twisterrob.cinema/blob/main/Heroku/gradle/plugins/src/main/kotlin/net/twisterrob/cinema/build/detekt.gradle.kts#LL20C35-L20C46 notice how it uses `.parentFile`, because the `settings.gradle.kts` is inside the Heroku folder of my repo. Essentially Sarif for GH needs the repo root, and rootDir is the best approximation for that.

**Comment by 3flex** [comment]
I took another look at this. Setting `basePath` worked around the original issue because the logic in the SARIF report module correctly included `file://` prefix in the SARIF file. But when base path wasn't set, and absolute paths were included in the report, the scheme and `///` were missing.

I'll open a PR to fix this.
