### ISSUE TITLE
Move to versioned documentation

### ISSUE THREAD

**Issue by JpCodeTask** [detekt/detekt#4168]
## Expected Behavior
Config shouldn't complete with error with correct fields.

## Observed Behavior
Config validator completes with error. The errors inform about misspelled or not existed fields, although they are correct according to the documentation. At the same time correctness of fields with config validation turned off has been proved.

## Steps to Reproduce
Add default fields fo rules listed below and turn on config validation.
  LongParameterList:
    excludes: *daggerClasses
    active: true
    functionThreshold: 4
    constructorThreshold: 7
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotatedParameter: [ ] <-- default value

  UnderscoresInNumericLiterals:
    active: false
    acceptableLength: 5 <-- default value

## Context
Turning on config validation after detekt plugin version update

## Your Environment

* Version of detekt used: 1.18.1
* Version of Gradle used (if applicable): 6.8.3

**Comment by cortinico** [comment]
This is still a thing. I'm actually looking into it 👍

**Comment by cortinico** [comment]
I'm happy to jump back on this 👍
