### ISSUE TITLE
Gradle detektBaselineMain task not creating baseline for particular folder structure 

### ISSUE THREAD

**Issue by tinder-kuldeeptanna** [detekt/detekt#4177]
## Expected Behavior
Baseline file should be created when running detektBaselineMain for a module 

## Observed Behavior
Baseline file is not created when running detektBaselineMain for a module 
(detektBaseline does create the baseline file for same module)

## Steps to Reproduce
1. Clone https://github.com/ktanna/TestDetekt
2. Run `./gradlew :swipe-party:card-stack:data:detektBaselineMain`
3.  Notice no baseline file was created in swipe-party/card-stack/data folder. 

Note: If you run `./gradlew :swipe-party:card-stack:data:detektBaseline`, the baseline file will be created. 

## Context
We use baselines to allow to suppress warnings for legacy code. With this bug, some modules don't have baseline created. 

## Your Environment
* Version of detekt used: 1.18.1
* Version of Gradle used (if applicable): 7.0.2
* Gradle scan link (add `--scan` option when running the gradle task): https://gradle.com/s/m6ncaprqjcg3k
* Operating System and version: Mac OS Big Sur (11.6)
* Link to your project (if it's a public repository): https://github.com/ktanna/TestDetekt

**Comment by chao2zhang** [comment]
`SourceProvider.getKotlinDirectories` is added in Android Gradle Plugin 7.0.0, which drops Java 8. Therefore, we can't resolve this issue until https://github.com/detekt/detekt/discussions/4130 is resolved.

**Comment by osipxd** [comment]
Looks like fixed in #4554 isn't it?

**Comment by cortinico** [comment]
Yes this can be closed 👍
