### ISSUE TITLE
More detailed code metrics

### ISSUE THREAD

**Issue by schalkms** [detekt/detekt#418]
Since detekt's code metrics are only measured globally at the moment this could be done more detailed. (e.g. per package)

Furthermore, I think the following pdf gives a great overview of additional metrics which can be implemented. However, some of them need type resolution.

**reference:**
http://www.hanselman.com/blog/content/binary/NDepend%20metrics%20placemats%201.1.pdf
https://en.m.wikipedia.org/wiki/Halstead_complexity_measures

**Comment by arturbosch** [comment]
I like it, the more metrics the better (Pick the ones most useful for your software). This will need a major design/redesign. For now detekt threats all kotlin files as input files. A more granular separation into modules, packages, test code is desirable. But this should take place after 1.0.
