### ISSUE TITLE
False Positive Detection In Compose Code

### ISSUE THREAD

**Issue by abhishekdewan101** [detekt/detekt#4181]
## Expected Behavior

Detekt shouldn't detect the start of the file to violate the `NewLineAtEndOfFile` rule.

## Observed Behavior

Detekt is detecting the start of the file as violation of the `NewLineAtEndOfFile` rule.

## Steps to Reproduce

There are couple of different files that can reproduce this issue.
[Themes.kt](https://github.com/abhishekdewan101/CatchUp/blob/main/app/src/main/kotlin/com/catchup/app/ui/theme/Theme.kt)
[Color.kt](https://github.com/abhishekdewan101/CatchUp/blob/main/app/src/main/kotlin/com/catchup/app/ui/theme/Color.kt)
[Shape.kt](https://github.com/abhishekdewan101/CatchUp/blob/main/app/src/main/kotlin/com/catchup/app/ui/theme/Shape.kt)
[Type.kt](https://github.com/abhishekdewan101/CatchUp/blob/main/app/src/main/kotlin/com/catchup/app/ui/theme/Type.kt)

I am using detekt gradle plugin 1.18.1 and running the detekt gradle command.

As can be seen in the image, there are 4 issues in the project and the place where it reports the error is `1:1` which seems to be the start of the file.

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/2817833/137076997-78333b04-2128-4404-b527-618bfd08eeb7.png">

## Context

These 4 files are the default files that are created when creating a [Jetpack Compose Project](https://developer.android.com/jetpack/compose?gclid=Cj0KCQjw5JSLBhCxARIsAHgO2SdvrHxpmjcBMIjdTM2I5wGpMZLsofeuXloJxV8Fw6NYhYF3B1jNim8aArP7EALw_wcB&gclsrc=aw.ds) so technically having to suppress detekt warnings on these isn't the most ideal situation.

## Your Environment

* Version of detekt used: 1.18.1
* Version of Gradle used (if applicable): 7.0.2
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/clo3t2rdmzzdi
* Operating System and version: MacOS Catalina
* Link to your project (if it's a public repository): https://github.com/abhishekdewan101/CatchUp

**Comment by BraisGabin** [comment]
This is not a false positive. Those files doesn't end with a new line so detekt flags them. If you don't agree with that rule you can disable it. Or you can fix those files adding the new line at the end of the file.

In general I saw that the files created by AS doesn't add the new line at the end of the file. To me that's a bad default but that's what AS give us.

**Comment by BraisGabin** [comment]
@abhishekdewan101 oh! That's a good feedback! If that was the reason we defenetly need to do something with this rule. Because it is true that the problem was noy at the beginning of the file but at the end.
