### ISSUE TITLE
False positive TooGenericExceptionThrown

### ISSUE THREAD

**Issue by scottkennedy** [detekt/detekt#4197]
## Expected Behavior
```kotlin
println("Some log that I want the stack trace with\n${Exception().stackTraceToString()}")
```

This triggers `TooGenericExceptionThrown`, even though no exception is actually thrown.

## Observed Behavior
See above

## Steps to Reproduce
See above code sample

## Your Environment

* Version of detekt used: 1.18.1
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: MacOS 11.6
* Link to your project (if it's a public repository):

**Comment by BraisGabin** [comment]
Closing because we can not reproduce the issue without more information. Thanks @Whathecode for the research :). Don't hesitate to write if you can provide a way to reproduce it.
