### ISSUE TITLE
SpacingBetweenPackageAndImports rule name is misleading

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#4208]
## Expected Behavior of the rule
The rule only checks for spacing issues between package & imports, in line with the name of the rule.

## Context
It also checks for spacing issues between imports & any following KtElements, which would make more sense as a separate rule.

**Comment by BraisGabin** [comment]
I agree that it's misleading. But I'm not sure if we should work on this rule. To me we should deprecate it and let `formatting` do that job. I know that some overlapping have sense between detekt and ktlint but that rule is purely formatting. I would vot to deprecate it or just mark it to be removed for `2.0`.

**Comment by 3flex** [comment]
I'm fine with that approach too, as I don't think it makes sense to duplicate checks that ktlint does anyway.

**Comment by PoisonedYouth** [comment]
The rule is mentioned in the actions for renaming: https://github.com/detekt/detekt/discussions/6035#discussioncomment-5702473. 
Is renaming then still necessary? Or should I remove it from the list to rename?

**Comment by cortinico** [comment]
This to me should be renamed to `SpacingAfterPackageDeclaration`

**Comment by marschwar** [comment]
fixed by #6133
