### ISSUE TITLE
Baseline creation not capturing all issues

### ISSUE THREAD

**Issue by fluxxion82** [detekt/detekt#4216]
I've added deket to my multimodule android project with a config file (issues getting reported are included in config and are active). I create baseline files using the command `./gradlew detektBaseline`. After creating baselines for my modules, I then run detekt but detekt fails with lot of errors that didn't get added to the baseline for some reason. If I manually add an issue that detekt fails on in the baseline, it will be respected next run, however, if I generate the baseline again, the issues I manually added get removed.

## Expected Behavior
The baseline file should include all current issues, at least issues enabled in config. After creating the baseline, detekt should run without failures. 

## Observed Behavior
Detekt fails with many issues. Issues like 'UnusedImports', 'MandatoryBracesIfStatements', 'SpacingBetweenPackageAndImports', 'ExpressionBodySyntax', etc are all getting flagged and are not included in the baseline. 
Some classes with these issues are included in the baseline while other classes with these issues are not, and some classes that are in the baseline with particular issues won't have all of the issues listed in the baseline. For example, I have a class with several WildcardImport issues, and all of the issues but one are included in the baseline - there's one instance of the WildcardImport that isn't included in the baseline.

## Steps to Reproduce
Add detekt to multi module project with lots of issues, including 'UnusedImports', 'MandatoryBracesIfStatements', etc. Create baseline files with command. Run detekt.

## Your Environment

* Version of detekt used: 1.18.1
* Version of Gradle used (if applicable): 7.2
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: MacOS 11.6 (Big Sur)
* Link to your project (if it's a public repository):

**Comment by fluxxion82** [comment]
I've updated my config file - I copied the default one and have been trying to update it to match what I was using before - but I'm still seeing a lot of issues getting flagged. I'm guessing that the baseline is getting created against the default configs. If so, how do I specify the configs that the generate baseline uses?

**Comment by fluxxion82** [comment]
So I created the DetektCreateBaselineTask task and pointed to my config file and I think that is creating the baseline file against my config file. However, I can't seem to preserve the default baseline file location. The default functionality creates a baseline file at the root of each module, which I'm fine with, but the DetektCreateBaselineTask keeps putting one file at the project root. 
I would be nice if the detektBaseline task could see the location of the baseline file I put when configuring detekt instead having to create this create baseline task with new properties. I would also like to not have to specify a baseline file in the DetektCreateBaselineTask task and have it use the default location of each module.

**Comment by fluxxion82** [comment]
Ok I got things setup and working satisfactorily. I hadn't updated my config file in a while so updating that helped with some things. Getting the baseline stuff setup was definitely a struggle and the documentation could have been a little clearer I thought.

**Comment by lakshmi-udaan** [comment]
Hi @fluxxion82, I'm facing a similar issue as specified by you. Can you help me with the steps you followed to resolve it?
### My Environment
detekt-cli : v1.20.0
Multi module maven project

**Comment by fluxxion82** [comment]
hey @lakshmi-udaan I can try to help but I don't recall exactly what all I did to resolve this. I guess you could start by telling me more about the situation? I guess per my previous comments, double check your config file.
