### ISSUE TITLE
ignoreAnnotated config doesn't work on FunctionNaming rule

### ISSUE THREAD

**Issue by yachoor** [detekt/detekt#4230]
## Expected Behavior
Being able to suppress `FunctionNaming` rule on functions annotated with `@Composable`

## Observed Behavior
All `@Composable` function names reported as violations

## Steps to Reproduce
Run detekt 1.19.0-RC1 analysis on a project with Composable functions

## Context
It seems that naming rules are all run through one MulitRule: [NamingRules](https://github.com/detekt/detekt/blob/28830b8db5adb37c08c65e70f9251d9396681b24/detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/NamingRules.kt) which is not ConfigAware so [getSuppressors](https://github.com/detekt/detekt/blob/edabb6f2b98cf4021606ff48e6acd13be1ef6207/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt#L13) returns empty list

## Your Environment
* Version of detekt used: 1.19.0-RC-1

**Comment by BraisGabin** [comment]
🤦 `MultiRule` beats again. i didn't have the time to check this but I think that you are completely right. I didn't thought about MultiRules while I was implementing this.
