### ISSUE TITLE
New Detekt Website - Looking for feedback & Improvements

### ISSUE THREAD

**Issue by cortinico** [detekt/detekt#4235]
Hey all,

Happy to share a first draft of the new detekt website: http://ncorti.com/detekt/ (it's on my fork cortinico/detekt).
I've migrated the website from Jekyll to Docusaurus as I think it will add a lot of freshness to the website, while still being Jekyll-compatible. Plus we can it has a lot of nice features (some are not enabled in the preview) such as:

* Dark theme
* **Versioned Docs**
* Algolia full text search
* Multilanguage
* Check for broken HTML link

You get a sneak peak of a fully-feature website checking out the Docusaurus one: https://docusaurus.io/

I'm looking for some feedbacks or opinions before I keep on spending time on it.
If anyone is interested, the code is in this branch: https://github.com/cortinico/detekt/tree/nc/new-website

## What is missing so far

- [x] The Detekt Version is not populated correctly in the doc.
- [x] The Changelog is missing an entry for 1.19.0-RC1
- [x] The Github Actions workflow must be updated to support this + add Yarn setup
- [x] Rules should be in the `rules/` folder. Now they're inside the `docs/documentation/` folder
- [x] onBrokenLinks should be removed + all the broken links should be fixed.
- [x] Remove all the build warnings
- [x] The `generateDocumentation` task should be verified to work correctly with the current setup.
- [x] The KDoc generation should be verified. Specifically it has broken HTML tags in it.
- [x] The redirectes from the old website should be verified
- [x] Detekt Version should be visible on the home page

Closes #3766

**Comment by BraisGabin** [comment]
It's SO cool! and with Dark theme <3.

I like much more the new landing page. It was so outdated.

One think that I miss from the landing page is the last version of detekt. That's something that I don't like from the gradle page. It's difficult to find which is the last stable version.

I think that we need to rethink the menus. For example, where in this version you have "tutorial" and "blog" I would have:

- getting started
  - introduction (explain difference between plain and type solving)
  - cli
  - gradle
    - jvm
    - android
    - multiplatform
- "advanced topics" (I don't know how to name it
  - Configuration file
  - Baseline
  - Suppressing issues
  - Reports
  - pre-commit
  - Extending detekt
  - Use SNAPSHOTs
- Releases
  - Changelog
  - Compatibility table
- Rules
- References
- Blog (Do we want to maintain it?)

**Comment by cortinico** [comment]
> It's SO cool! and with Dark theme <3.
> I like much more the new landing page. It was so outdated

Thanks for the feedback 🙏 

> One think that I miss from the landing page is the last version of detekt. That's something that I don't like from the gradle page. It's difficult to find which is the last stable version.

Added to the list on top

> I think that we need to rethink the menus. For example, where in this version you have "tutorial" and "blog" I would have:

Yeah so I'd like to ship just a redesign of the website and iterate on the content afterwards otherwise it gets impossible to review 👍

**Comment by BraisGabin** [comment]
> Yeah so I'd like to ship just a redesign of the website and iterate on the content afterwards otherwise it gets impossible to review 👍

That have a lot of sense. I wasn't sure which type of feedback you were looking for :P

**Comment by cortinico** [comment]
>  I wasn't sure which type of feedback you were looking for :P

Mostly if Docusaurus is a no-go, or if we're fine with it and the general look-n-feel of the website.

**Comment by chao2zhang** [comment]
How were you able to generate svg icons with red-to-purple gradients? It does have a designer look-and-feel now.

**Comment by BraisGabin** [comment]
Oh, then it's a clearly go!! It supports Mark down, night mode, versioned documentation and it can be hosted by github. I think that's all we need.

**Comment by chao2zhang** [comment]
How do we want to collaborate on this? 
- 1. Merging into `detekt-website/`, and switch to use it to replace `docs/` when it is ready
- 2. Use a collaborative PR to make the switch directly
Approach #2 maximizes the probability of reserving the git history. I don't think the git history for doc is of high value though.
