### ISSUE TITLE
Should we deprecate MultiRule?

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4240]
I'd like to do some benchmarks the actual `NamingRules` that is a `MultiRule` agains all the rules that it handles runned individually. Is it worth the speed boost that we get from it?

The `MultiRule` class create complexity in the code:

- When you test a Rule that is inside a MultiRule you aren't testing exactly what it will be executed (https://github.com/detekt/detekt/pull/4147#discussion_r721468277)
- The multi rule and the configuration does't work nicely and we forget about them frequently (#4230 and #4071)
- We need to add code checking if the rule is a `Rule` or a `MultiRule` to do different things (#4239):

https://github.com/detekt/detekt/blob/f944be01561efd80b35c6b4427434caf63dcf88c/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/Analyzer.kt#L98-L102

https://github.com/detekt/detekt/blob/f944be01561efd80b35c6b4427434caf63dcf88c/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/rules/RuleSets.kt#L37-L42

For all that reasons I think that we should get some benchmarks so we could take an informed decission. If the performance impact is not really high I'd vote to deprecate it.

**Comment by cortinico** [comment]
> Is it worth the speed boost that we get from it?

If you have some benchmark results, would be great to make an informed decision.
To me, `Multirule` is unnecessary complexity given that we also support the `parallel` execution and we should probably clean it up.

**Comment by schalkms** [comment]
I'd also vote for removing the `MultiRule`.

**Comment by chao2zhang** [comment]
Another argument would be that it is quite difficult to implement auto correct correctly with MultiRules (Some rules can be auto-correctible while other rules may not)

**Comment by marschwar** [comment]
I hacked up a very naive benchmark using the `EmptyBlocks`multi rule.

This particular multi rule actually seems to be 3.5 times  faster than executing each rule individually. Nevertheless I do support getting rid of the multi rule for all the reasons you all mentioned.

```kotlin

private val fileCounts = listOf(10, 20, 50, 100, 500, 2000)

class EmptyBlocksMultiRuleBenchmarkSpec : Spek({

    val file by memoized { compileForTest(resourceAsPath("Benchmark.kt")) }

    describe("multi rule benchmark") {

        it("warmup") {
            repeat(2000) {
                EmptyBlocks().visitFile(file)
                EmptyBlocks().rules.forEach { it.visitFile(file) }
            }
        }

        it("runs as single rules") {
            var findings = 0
            println("All rules of multi rule:")
            fileCounts.forEach { fileCount ->
                val duration = measureTimeMillis {
                    repeat(fileCount) {
                        EmptyBlocks().rules.forEach { rule ->
                            rule.visitFile(file)
                            findings += rule.findings.size
                        }
                    }
                }
                println("$fileCount -> ${duration.toDouble().div(fileCount)} ms per file")
            }
            println("Total findings: $findings")
        }

        it("runs as multi rule") {
            var findings = 0

            println("Mutli Rule:")
            fileCounts.forEach { fileCount ->
                val duration = measureTimeMillis {
                    repeat(fileCount) {
                        val rule = EmptyBlocks()
                        rule.visitFile(file)
                        findings += rule.findings.size
                    }
                }
                println("$fileCount -> ${duration.toDouble().div(fileCount)} per file")
            }
            println("Total findings: $findings")
        }
    }
})

```

**Comment by 3flex** [comment]
So there's very likely a perf impact, but I didn't see any objections to doing this - just want to check in case I (or someone else) decides to pick this one up...

**Comment by marschwar** [comment]
I would like to do this.

**Comment by BraisGabin** [comment]
I think that the performance is something that we should track. For that reason I opened this discussion to see how can we do it: #5183

I'm 100% sure that we should deprecate `MultiRule`. But we should check the performance of detekt to take good decissions. That information could help a lot defining the API for detekt 2.0.
