### ISSUE TITLE
Gradle sync fails when older Kotlin version used

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#4274]
## Expected Behavior
I can successfully apply detekt plugin to an existing project that is using a recent Kotlin version.

## Observed Behavior
Applying detekt 1.19.0-RC1 to a project using Kotlin 1.5.21 fails.

## Steps to Reproduce

1. Clone https://github.com/3flex/detekt-mismatch-kotlin
2. Run `gradlew tasks`
3. See failure:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not create task ':compileKotlin'.
> Could not create task of type 'KotlinCompile'.
   > Could not create an instance of type org.jetbrains.kotlin.gradle.tasks.KotlinJavaToolchainProvider.
      > Could not generate a decorated class for type KotlinJavaToolchainProvider.
         > Cannot have abstract method KotlinJavaToolchain.getJdk().
```

## Context
With this dependency view from the Gradle scan it can be seen that the Kotlin Gradle plugin version dependencies of kotlin-gradle-plugin-api and others are changed from 1.5.21 to 1.5.31 to match the detekt Kotlin dependency version used on detekt Gradle plugin's runtime classpath: https://scans.gradle.com/s/3ohyjhgsh3xig/build-dependencies?dependencies=1.5.21&expandAll&focusedDependencyView=versions&resolutionFilter=WzFd

## Your Environment

* Version of detekt used: 1.19.0-RC1
* Version of Gradle used (if applicable): 7.3
* Gradle scan link (add `--scan` option when running the gradle task): https://gradle.com/s/3ohyjhgsh3xig
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): https://github.com/3flex/detekt-mismatch-kotlin

**Comment by chao2zhang** [comment]
I think we would recommend the latest Kotlin version when we release detekt. So I believe the correct way to address such an issue is to print warnings if the client project's Kotlin is below the recommended version.
https://detekt.github.io/detekt/compatibility.html#tool-versions

**Comment by 3flex** [comment]
I disagree, that conflicts with this:

> When shipping the Detekt Gradle Plugin, we depend on both the Kotlin Gradle Plugin and the Android Gradle Plugin.

> Those dependencies are applied as compileOnly (see here) to allow our users to pick the version of the Gradle plugin they prefer and don’t impose the one we use inside detekt.

Also, Compose requires specific Kotlin versions to be used, so if detekt does the same, it can make it more difficult to find a combination that works. Compose 1.0.1 requires Kotlin 1.5.21 only, so can't be used with detekt 1.19.0 as the Kotlin Gradle plugin API version dependency in our plugin is 1.5.31 which conflicts and breaks the build.

**Comment by cortinico** [comment]
>          > Cannot have abstract method KotlinJavaToolchain.getJdk().

So is this happening on a Compose project?
Could you verify if this happens also on a plain JVM project?

**Comment by chao2zhang** [comment]
I believe the repro project does not depend on Compose. (It does not even have code)

It is unfortunate that Compose requires pinning the Kotlin version. This shouldn't be an issue once the compiler plugin API is stable, but given the existing prevalence of Compose, now I do agree with you that we should try to make Detekt more flexible.

**Comment by 3flex** [comment]
> Could you verify if this happens also on a plain JVM project?

The repro contains only these lines in the build file:

```kotlin
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.5.21"
    id("io.gitlab.arturbosch.detekt") version "1.19.0-RC1"
}

repositories {
    mavenCentral()
}
```

> It is unfortunate that Compose requires pinning the Kotlin version.

That's true, but there may be other reasons a project is using one version of Kotlin instead of another - detekt needs to stay out of the user's way where we can. Increasing KSP usage might also force our hand... I think that's part of the reason the Compose Kotlin dependency is fixed. Of course there's a risk that relying on the runtime dependency of Kotlin Gradle plugin API will cause exceptions, but it should improve compatibility overall.

**Comment by cortinico** [comment]
> The repro contains only these lines in the build file:

Yup I missed that there was a repro attached, my bad.
