### ISSUE TITLE
UnderscoresInNumericLiterals can't handle non-standard groupings

### ISSUE THREAD

**Issue by scottkennedy** [detekt/detekt#4276]
## Expected Behavior
In my codebase, we store numbers as cents.

As such, we need to be able to write values as `50_000_00` for $50,000.00

The current check does not permit this.

I've seen a couple other cases where it's not a strict grouping of 3, but this is, by far, the biggest annoyance for us right now.

## Observed Behavior
UnderscoresInNumericLiterals check fails.

## Steps to Reproduce
`const val FOO = 50_000_00`

## Your Environment
* Version of detekt used: 1.18.1
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by BraisGabin** [comment]
So, what is the expected behavior for you? Allow any number if it contains `_`? That's not the idea of this rule. Allow patterns could be other option but it would make the rule way more complex.

To me this seems the perfect fit to a custom rule. You can disable the default rule from detekt, create a copy and modify it to fit your needs.

**Comment by marschwar** [comment]
This seems like a bug to me. Thank you for reporting.

According to https://github.com/Kotlin/KEEP/blob/master/proposals/underscores-in-numeric-literals.md all kinds of formats are valid and the purpose of the rule is to make large numbers easier to read, which your format clearly does.

I think we should change the rule to check that there is no more than  `acceptableLength` consecutive digits without an underscore.

**Comment by marschwar** [comment]
There is no indication in the [original issue](https://github.com/detekt/detekt/issues/1398) as to why code like this should be flagged as a violation.

**Comment by marschwar** [comment]
I have created a PR but I am not sure how to go forward with this. The [documentation of the rule](https://detekt.github.io/detekt/style.html#underscoresinnumericliterals) clearly states.

> Underscores that do not make groups of 3 digits are also reported even if their length is under the configured acceptableLength.

So changing this now would be a breaking change. Even though I agree, that we should not flag this.
