### ISSUE TITLE
ExplicitCollectionElementAccessMethod false positive

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4288]
## Expected Behavior
`ExplicitCollectionElementAccessMethod` Shouldn't flag this ussage but it does: [`Rectf.set(left, top, right, bottom)`](https://developer.android.com/reference/android/graphics/RectF#set(float,%20float,%20float,%20float))

## Your Environment
* Version of detekt used: main (c66b8d67bb78b3361710e70bd9a060f877ef527d)
* Version of Gradle used (if applicable): 7.3

**Comment by BraisGabin** [comment]
Sorry, I just realised that I could use `RectF[left, top, right] = bottom`. That's completely odd but I assume that the rule is working as expected.

What could we do here to fix it? Should we ignore if the function is defined using java? Or should we create a `Suppressor` or something similar to ignore these cases?

**Comment by schalkms** [comment]
I think this is the best option in this case.

> Should we ignore if the function is defined using java?

**Comment by chao2zhang** [comment]
Alternatively, we can report **only** when the set/get has exactly one parameter for the key.
