### ISSUE TITLE
Make baseline task faster

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4289]
## Expected Behavior
If I run `detektMain` and it throw an issue that I want to include in the baseline (for example, a false-positive) it would be nice to run `detektBaselineMain` be really fast because I didn't change anything in my code.

## Current Behavior
detekt needs to run a complete inspection again.

## Context
Lately, with the introduction of Compose in my code base I have a lot of false-positives (1.19.0-RC2 should fix nearly all of them). Usually I was running `detektMain` find out that it was a false positive and then run `detektBaselineMain`. The cicle was so slow that I end up running `detektBaselineMain` and using the changes in the baseline to know if I really have any new issue.

That approuch works but it's far from ideal because I don't get the benefit from the html report with the snippets and because I end up modifing by hand the baseline.

## A way to fix it
I was thinking that `detektMain` could generate the baseline file too. But, instead of saving it in the defined location by the user we could save it somewhere inside the `/build` folder. This way, if I run `detektBaselineMain` the only thing that we need to do is to copy that already generated file in the defined location by the user and that's it. That should be really fast.

The big problem: when we run `detektMain` that task fails, so, probably, gradle will not think of it as "UP-TO-DATE" but I imagine that we could do something to fix it.

This fix would help us with the real issue behind #3785 too.

**Comment by 3flex** [comment]
We can also act like Android Lint - there is no separate baseline task. The baseline file path is optional. If specified, the Lint task will generate a baseline file if it doesn't exist, and will read it if it does exist. To regenerate the baseline, delete the file and keep the baseline path specified. To stop using baselines, delete the file and remove the config specifying the file path.

I have suggested this before but couldn't find the comment though it was suggested we don't do this, but I can't recall why. I suppose it might be confusing for those not familiar with Android.

**Comment by BraisGabin** [comment]
That wouldn't fix my use case, would it? I mean, I run `detektMain` with my current baseline. I found out a new false positive. I remove `baseline.xml` and I need to re-run `detektMain` and it should do the complete scan again.

**Comment by 3flex** [comment]
I see, I misread your issue. So you want to run `detektMain`, then if you see an issue raised that you want to actually ignore, then you want to run detektMainBaseline so the baseline is rebuilt. And what you want is for the run of detektMainBaseline, if run after detektMain, to run quickly, since the analysis had already been done by detektMain.

Gradle Enterprise Gradle Plugin has a feature that's conceptually similar - after running a build, if you decide you want to upload the build scan data after the build, you run `gradlew buildScanPublishPrevious` to publish the result of the build that was just run. In this case, a task that copies the output of detektMain to the baseline path of detektBaselineMain on demand would do this for you.

I'm not sure this should be part of the plugin though. We could change the detektMain task like you suggested to generate the baseline in the build folder, then I think a custom Copy task that has the detektMain baseline output as an input and copies to wherever it needs to would achieve what you want.

**Comment by BraisGabin** [comment]
I was thinking about other option:

1. Create a task that generates the reports and the baseline. Thst task will never fail. It doesn't care about how much issues it found.
2. Make `detektMain` (and family) depend on that task. Now detektMain is the one that reads the output of that task and decides if it should fail or not.
3. Make `detektBaselineMain` (and family) depend on that task. This task will just copy the file.

A bonus would be if we would be able to make that the first task only creates one file as output. Not a report nor the baseline. Just all the raw data that we need to generate the reports and the baseline. And then, in `detektMain` and `detektBaselineMain` we read that file and based on its information we create our reports, baselines, decide if we should fail, etc.

Would that be doable?

**Comment by BraisGabin** [comment]
My issue is not related with RC1 (I'm still on 1.18.1) It's a bit related with our lack of support for Compose but not only. In general I found my self using more baseline just because I know what rule does and if it appears in the baseline I can fix it and remove it directly from the baseline and it works and it's faster. But I don't feel that no one should use baseline instead of the main task just because it is faster. For that reason I was thinking on this.

> but it sounds complicated to build and possibly to use.

Which part seems complicated? I think that the complicated part is to create a file with all the needed information and the "map it" to different reports and baselines? I was hoping that sarif could be that "raw" format. It seems that it was created with this propouse "Static Analysis Results Interchange Format". But I don't feel it would have all the information we need.

**Comment by BraisGabin** [comment]
I think that this idea could work but for sure it's not for 1.0 nor 2.0 so closing.
