### ISSUE TITLE
Add Renovate Bot

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#4292]
## Expected Behavior
We get automatic PRs when dependencies need updating.

## Current Behavior
This is manual.

## Context
Doing this manually is annoying. Renovate now supports Gradle version catalogs: https://github.com/renovatebot/renovate/issues/8692#issuecomment-911897526

I don't have necessary permissions on this repo, but someone who does could install this app: https://github.com/apps/renovate

**Comment by schalkms** [comment]
I approved your request. The app should now have the corresponding permissions.
Since I'm currently on mobile, I didn't configure anything except approving the request.

**Comment by schalkms** [comment]
related #4294

**Comment by chao2zhang** [comment]
Do we configure Renovate for Java/Gradle dependencies and Dependabot for ruby dependencies? I'd like to make sure that there is no overlap between these tools.

**Comment by 3flex** [comment]
@chao2zhang see #4294, I've customised the config to ignore Ruby bundler. Suggest other config customisations be discussed there, but I think it can be merged since all PRs it raises will need to be manually reviewed anyway so it's low risk.

**Comment by 3flex** [comment]
Closed by #4294

**Comment by cortinico** [comment]
> Do we configure Renovate for Java/Gradle dependencies and Dependabot for ruby dependencies? 

Just linking this issue as dependabot is not supporting versions catalog yet: https://github.com/dependabot/dependabot-core/issues/3121

If possible, I'd migrate the ruby deps to renovate as well.
