### ISSUE TITLE
Could not resolve Gradle plugin download

### ISSUE THREAD

**Issue by diegocunhawarren** [detekt/detekt#4346]
## Expected Behavior

When Gradle runs, should be able to resolve download the Detekt Plugin Version.

## Observed Behavior
There is an error saying it's not possible to resolve Gradle plugin

```
 > Could not resolve io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:1.17.1.
     Required by:
         project :
      > Could not resolve io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:1.17.1.
         > Could not get resource 'https://dl.bintray.com/kotlin/kotlin-eap/io/gitlab/arturbosch/detekt/io.gitlab.arturbosch.detekt.gradle.plugin/1.17.1/io.gitlab.arturbosch.detekt.gradle.plugin-1.17.1.pom'.
            > Could not HEAD 'https://dl.bintray.com/kotlin/kotlin-eap/io/gitlab/arturbosch/detekt/io.gitlab.arturbosch.detekt.gradle.plugin/1.17.1/io.gitlab.arturbosch.detekt.gradle.plugin-1.17.1.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.4.
```
## Your Environment

* Version of detekt used: 1.17.1
* Version of Gradle used (if applicable): 7.0.3
* Operating System and version: Ubuntu 20.04 LTS

**Comment by 3flex** [comment]
Can you please provide a build scan?

Add `--scan` to the Gradle command your running and then pay the link here.

It looks like the repositories configured for build dependencies is incorrect. It should be configured to download from the Gradle Plugin Portal.

**Comment by chao2zhang** [comment]
There seem to be spotty reports of bintray not accessible in some of my slack domains.

Would you mind check if your repositories section includes jcenter? Bintray is now in read-only mode and can be sunset in the near future. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by cortinico** [comment]
> * Version of detekt used: 1.17.1

Please update to the latest stable version. 1.17.x was still depending on dependencies that are on JCenter/Bintray.

**Comment by diegocunhawarren** [comment]
Hey folks, 
We are using this version for the last 6 months without any change (the last chage was update Android Gradle Plugin to 7.0.3 and this issue started today without any changes in our side.

I'm attaching the logs from our CI to you check it out, The issue looks like is happening at line 587
[apps_c4a0067a9b089e3b_4de76be2-9ad7-4f0c-9e78-012232efcecb-full.txt](https://github.com/detekt/detekt/files/7629805/apps_c4a0067a9b089e3b_4de76be2-9ad7-4f0c-9e78-012232efcecb-full.txt)


cc @cortinico @chao2zhang @3flex

**Comment by hijamoya** [comment]
Same issue here:

Could not HEAD 'https://dl.bintray.com/kotlin/kotlinx/io/gitlab/arturbosch/detekt/io.gitlab.arturbosch.detekt.gradle.plugin/1.18.1/io.gitlab.arturbosch.detekt.gradle.plugin-1.18.1.pom'. Received status code 502 from server: Bad Gateway

**Comment by 3flex** [comment]
Based on the multiple reports, and a quick look at #bintray on Twitter, this seems to be a problem with the bintray repo. There's nothing we can do directly to fix this.

You can update the repositories configured in your `buildscript {}` and `pluginManagement {}` blocks so it includes gradlePluginPortal() or mavenCentral() above the bintray repository. The detekt Gradle plugin should then resolve.

Regarding plugin's runtime dependencies, you may also need to update detekt, as some of the dependencies it relies on in earlier versions aren't available on Maven Central as pointed out above.

If you're still having trouble please provide a link to a build scan as requested so the configured repositories can be confirmed and we can provide more specific guidance. But I'd ask that detekt be upgraded to 1.18 or 1.19 first.

**Comment by diegocunhawarren** [comment]
Hey folks, just an update about this: Yesterday fixed the problem by himself without any changes in my side but I followed your instructions and updated the library to 1.19.

Thanks for your support! <3
