### ISSUE TITLE
UnnecessaryAbstractClass should report empty abstract classes

### ISSUE THREAD

**Issue by severn-everett** [detekt/detekt#4357]
The rule `UnnecessaryAbstractClass` will not mark an abstract class that has no member declarations (e.g. `abstract class Foo`) as violating the rule. However, adding brackets to the class declaration (e.g. `abstract class Foo{}`) will trigger the rule. Semantically, these appear to be the same declaration, so `UnnecessaryAbstractClass` should be refactored to trigger in both scenarios.

**Comment by BraisGabin** [comment]
I checked the code of this rule and found that this exception was added on propouse. I found that it was added to fix #550. @schalkms, is there any reason for this?

**Comment by schalkms** [comment]
That was a long time ago. As far as I remember, this was added due to a clash with the **EmptyClass** rule.

**Comment by severn-everett** [comment]
Would you be able to elaborate about this? The `NoEmptyClassBody` rule doesn't have any specifications about whether it's an abstract class, which is what this rule would be specifically analyzing.

**Comment by schalkms** [comment]
If both rules are enabled, this snippet triggers both rules resulting in 2 reports.

**Comment by severn-everett** [comment]
How would this get reproduced? Running Detekt on `abstract class Foo` with both `UnnecessaryAbstractClass` and `NoEmptyClassBody` set to active on Detekt 1.19.0 doesn't trigger either issue.

**Comment by BraisGabin** [comment]
So, green light. @severn-everett can you create a PR fixing this?

**Comment by severn-everett** [comment]
Will do, after I work on another use case I discovered for PR #4353

**Comment by schalkms** [comment]
This was the case back then before detekt v1.0 got released. Quite some time passed since then. ☺️

**Comment by schalkms** [comment]
Closed by  a9ce1e2
