### ISSUE TITLE
ReturnFromFinally not report

### ISSUE THREAD

**Issue by mingervic** [detekt/detekt#4361]
```
fun foo() {
    try {
        throw JSONException("")
    } finally {
        return 
    }
}
```
## Expected Behavior
report ReturnFromFinally 

## Observed Behavior
ReturnFromFinally not report

## Your Environment

* Version of detekt used:1.19.0
* Version of Gradle used (if applicable):4.2.1
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:macOS Catalina 10.15.7

**Comment by BraisGabin** [comment]
Are you using type-solving? This rule can't run without it: https://detekt.github.io/detekt/exceptions.html#returnfromfinally

**Comment by schalkms** [comment]
Please try the mentioned type-solving setting. If this problem persists, feel free to reach out.
