### ISSUE TITLE
<experssion> expected , got ')'

### ISSUE THREAD

**Issue by cumody** [detekt/detekt#4382]
i don't know why my build.gradle file does not sync when i put this 

tasks.withType<Detekt>().configureEach {
    reports {
        html.required.set(true) // observe findings in your browser with structure and code snippets
        xml.required.set(true) // checkstyle like format mainly for integrations like Jenkins
        txt.required.set(true) // similar to the console output, contains issue signature to manually edit baseline files
        sarif.required.set(true) // standardized SARIF format (https://sarifweb.azurewebsites.net/) to support integrations with Github Code Scanning
    }
}

**Comment by severn-everett** [comment]
Your declaration of `withType` is incorrect: you need to specify that you want to configure all tasks of the `Detekt` type in the diamond brackets which are missing in your code snippet. As per the config file snippet on the [Detekt project page](https://detekt.github.io/detekt/):
```
tasks.withType<Detekt>().configureEach {
    reports {
        xml.required.set(true)
        html.required.set(true)
        txt.required.set(true)
        sarif.required.set(true)
    }
}
```

**Comment by cumody** [comment]
thank you it helped me
