### ISSUE TITLE
Ability to ban the use of functions/methods

### ISSUE THREAD

**Issue by LifeIsStrange** [detekt/detekt#4391]
Our team needs the ability to specify a list of methods and for detekt to check if there is any occurence in the project (or maybe in a directory and its descendants)
Ktlint allow to ban specific imports but that is not suffisant, since our methods are not shown in imports.
Our use case if about making Kotlin collections interoperables between JS and Kotlin multiplatform/JVM, to do this, we must ban the use of MutableList.addAll and instead mandate the use of MutableList.addAllMPP()
Without such linter ability, our codebase could use .addAll() which would **silently** break our pure JS code (since addAll() performs a deepcopy)

**Comment by LifeIsStrange** [comment]
@cortinico friendly ping

**Comment by BraisGabin** [comment]
Thats what the rule forbiddenMethodCall does.

**Comment by LifeIsStrange** [comment]
You are amazing!!
