### ISSUE TITLE
Allow skipping detekt based on property like `skipDetekt`

### ISSUE THREAD

**Issue by rocketraman** [detekt/detekt#4396]
## Expected Behavior
I would like to skip a run of Detekt via a command line flag, such as a property.

## Current Behavior
Currently, skipping can be done via the Gradle `onlyIf` mechanism:

```
tasks.named<io.gitlab.arturbosch.detekt.Detekt>("detekt")
  .get()
  .onlyIf { !project.hasProperty("skipDetekt") }
```

However, for some reason, this actually breaks baseline processing. After adding that and running the build *without* `-P skipDetekt`, my baseline file is ignored and detekt reports errors.

## Context
I wanted to skip Detekt for a particular build in which I know there will be Detekt errors, but I want to ignore them so that the build finishes successfully.

**Comment by BraisGabin** [comment]
What about `./gradlew check -x detekt`? That will not execute the Detekt task.

**Comment by rocketraman** [comment]
Thank you, that works.
