### ISSUE TITLE
UnusedImports false positive on Flows.collect extension function

### ISSUE THREAD

**Issue by rock3r** [detekt/detekt#4426]
## Expected Behavior
Import should not be flagged — it is used.

## Observed Behavior
Import is flagged as unused.

## Steps to Reproduce
1. Check out https://github.com/code-with-the-italians/bundel/
2. Run Detekt (e.g., via the `:staticAnalysis` task)
3. Observe the import at [`BundelNotificationListenerService.kt#L15`](https://github.com/code-with-the-italians/bundel/blob/d0d5d71de0bd8b8774789d7028f49cff47a7f331/app/src/main/java/dev/sebastiano/bundel/notifications/BundelNotificationListenerService.kt#L15) is marked as unused
4. Observe the import is used at [line 53](https://github.com/code-with-the-italians/bundel/blob/d0d5d71de0bd8b8774789d7028f49cff47a7f331/app/src/main/java/dev/sebastiano/bundel/notifications/BundelNotificationListenerService.kt#L53)

## Context
I _suspect_ the issue may be somewhat related to the fact that `Flow` has a member function (but that is `@InternalCoroutinesApi`) that's called `collect` as well.

## Your Environment
* Version of detekt used: 1.19.0
* Version of Gradle used (if applicable): 7.3.2
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/lazvc7t6pj6vu
* Operating System and version: Windows 11
* Link to your project (if it's a public repository): https://github.com/code-with-the-italians/bundel/

**Comment by severn-everett** [comment]
Which `Flow.collect()` function is being called? There are two `collect()` extension functions for `Flow` that would require an import: one that does not take any lambda arguments, and one that does but is marked as `Deprecated.HIDDEN` in version 1.6.0 of the library and should thus not be available for use.
