### ISSUE TITLE
Add documentation for `Suppressor`s

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4440]
The `Suppressor`s is a new concpet introduced in detekt `1.19.0` to give more flexibilty to ignore some issues. But it is not documented yet. So we should add a new documentation to it.

The problem here is: should it be automated? So any new `Suppressor` automatically adds it's documentation? Or should iy be an static code?

**Comment by schalkms** [comment]
In my opinion, it could be a mixture of both.
1. Use a separate entry on detekt's home page.
2. Document the code inline. This way, one can look into the code and grasp more details if necessary.
