### ISSUE TITLE
Align inputs for detekt type resolution tasks with Kotlin compilation tasks

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#4465]
## Expected Behavior
The detekt `BindingContext` is identical to that used in equivalent Kotlin compilation task.

## Current Behavior
There are multiple existing issues:
1. Compilation classpath differs between detekt & Kotlin compilation task
2. Input files used to generate `BindingContext` differs
    * #3488 
    * https://github.com/detekt/detekt/issues/3272
    * https://github.com/detekt/detekt/issues/3409
    * https://github.com/detekt/detekt/issues/3684
    * https://github.com/detekt/detekt/issues/3913
3. Other compilation options differ (e.g. friend paths, compiler args, API version, target, language version)
    * #3067 
    * https://github.com/detekt/detekt/issues/3639
    * https://github.com/detekt/detekt/issues/3684
    * https://github.com/detekt/detekt/issues/3874

## Context
The main reason detekt-compiler-plugin works with no fuss is because it lets the Kotlin Gradle plugin and compiler infrastructure generate `BindingContext` then provides a separate list of files to analyze using that `BindingContext`. We can mimic this with detekt by configuring the detekt tasks based on the Kotlin compilation tasks and allowing detekt to treat files to be analysed separately from files used to generate `BindingContext`. In addition, support should be added for relevant compiler args that aren't currently recognised by detekt.

The tasks would be automatically setup by the plugin similar to this:
```kotlin
tasks.register<Detekt>("detektTask") {
    // files to analyse. This can be filtered at will.
    source = tasks.compileKotlin.get().source

    // New parameter: files used to generate BindingContext. Java & Kotlin source files, includes generated sources (as used
    // by Android Data Binding library & Android BuildConfig for example). Should not be filtered by users at all, as missing
    // files may lead to unresolved references.
    compilerFiles = tasks.compileKotlin.get().source

    classpath.setFrom(tasks.compileKotlin.get().classpath)

    // existing parameters for Detekt task
    languageVersion = tasks.compileKotlin.get().kotlinOptions.languageVersion
    jvmTarget = tasks.compileKotlin.get().kotlinOptions.jvmTarget

    // new parameters to add to Detekt task
    apiVersion = tasks.compileKotlin.get().kotlinOptions.apiVersion
    freeCompilerArgs = tasks.compileKotlin.get().kotlinOptions.freeCompilerArgs
    friendPaths = tasks.compileKotlin.get().friendPaths
}

detekt {
    // new parameter to add to detekt extension
    explicitApi = kotlin.explicitApi
}
```

For the automatically generated tasks this should be possible to wire things up completely transparently, and once done for JVM targets should be easy to roll out for Android (and hopefully for JVM/Android targets in MPP projects too).

On Android we can also reduce the dependency on `com.android.tools.build:gradle`, as we'll take advantage of the setup done within the Android & Kotlin Gradle plugins, without having to reverse engineer how all the inputs to the compilation task are derived.

~~This should also fix https://github.com/detekt/detekt/issues/3365, as `sourceSet.output.classesDirs` wouldn't be an input to the detekt task anymore. This is what creates the task dependency from the detekt task to the Kotlin compilation task (the dependency would still be there for detektTest but that's unavoidable as mentioned in https://github.com/detekt/detekt/issues/3365#issuecomment-758331328).~~ This is no longer true - for now, there's some redundant compilation, but that's a performance issue rather than a problem with the way detekt sets up the compiler which was the main problem I wanted to address.

One day we should move to the K2 compiler plugin, but as [the API won't be stablised](https://youtrack.jetbrains.com/issue/KT-49508) until Kotlin 1.8 or 1.9 (late 2022/early 2023) this would resolve the issue in the meantime.

**Comment by BraisGabin** [comment]
Thanks for the detailed description! Given all of that: do it have more sense to add effort to improve/fix the current plugin or to make `detekt-compiler-plugin` viable for general use?

Last weeks I was thinking that probably detekt should provide two different plugins: one for type solving and another for "plain detekt". They should be compatible between then but both plugins are very different. And for the users it would be easier to pick one: Do you want fast but simpler checks or other slower but with richer checks.

And maybe we could let the "plain" one to be developed and maintained  by the community (third party). I think that we have a lot on our plate right now.

**Comment by 3flex** [comment]
> do it have more sense to add effort to improve/fix the current plugin or to make detekt-compiler-plugin viable for general use?

I kept changing my mind about this, but now the Kotlin roadmap indicates timelines for stable K2 compiler and the plugin API I think it's more beneficial to update the plugin we have today. It's not that much work, some pieces are in place already or spiked in previous draft PRs, and I'd like to take it on.

**Comment by 3flex** [comment]
ICYMI @cortinico - it would be good to get your thoughts!

**Comment by cortinico** [comment]
Looks great, thanks for taking the time to write this down @3flex. Sorry I couldn't answer earlier but my GH Inbox is pretty full atm.

I do have only a couple of questions:

>     // new parameters to add to Detekt task
>    apiVersion = tasks.compileKotlin.get().kotlinOptions.apiVersion
>    freeCompilerArgs = tasks.compileKotlin.get().kotlinOptions.freeCompilerArgs
>    friendPaths = tasks.compileKotlin.get().friendPaths

Will those be mutable? How can a user remove/add a compiler flag without wiping the one provided by the compiler (should they need to remove one, probably not. Add one, maybe yes).

>    compilerFiles = tasks.compileKotlin.get().source
>    classpath.setFrom(tasks.compileKotlin.get().classpath) 

This looks great to me. Just to clarify for the readers that this will apply only for the `detekt*` tasks and not for the plain `detekt` task (i.e. we're not changing the condition how we enable type resolution).

Do you happen to have a draft PR? Would be interesting to know how Android/KMP projects are integrated inside this.

**Comment by 3flex** [comment]
> Will those be mutable? 

They're intended to be, yes - likely using Gradle's `ListProperty` (which allows adding values, clearing values, but not removing individual values)

> Just to clarify for the readers that this will apply only for the detekt* tasks and not for the plain detekt task

Yep will find a way to present this appropriately, but as you say, type resolution will still only be enabled when the `classpath` property is set.

> Do you happen to have a draft PR?

Not yet, was looking for endorsement first, but I'll work on one soon. I'd like to have appropriate functional tests in place first though.

> Would be interesting to know how Android/KMP projects are integrated inside this.

I have a plan for that, but it will be easier to start with plain JVM. The functional tests for Android/KMP are particuarly important to have in place first - we can test type resolution tasks on detekt itself easily enough.

**Comment by Abhimanyu14** [comment]
Hi,
Do we have any updates on this issue?
