### ISSUE TITLE
Need configuration for StringLiteralDuplication

### ISSUE THREAD

**Issue by neostage** [detekt/detekt#4466]
## Expected Behavior of the rule
StringLiteralDuplication can be configured to ignore string templates.

## Context
StringLiteralDuplication detekts string templates and I think string templates can duplicate because they include variable things so making them as constant is not a good idea.

**Comment by BraisGabin** [comment]
Why the "string templates" shouldn't be duplicated? Can you provide a snippet to show your point?

And, which is your proposal? What should that configuration be?

**Comment by BraisGabin** [comment]
Closing
