### ISSUE TITLE
Baseline not catching multiline string literals correctly

### ISSUE THREAD

**Issue by jelleheemskerk** [detekt/detekt#4480]
## Expected Behavior
A MaxLineLength with multiline string literals will be written in the baseline and not causing problems when running `detekt`.

## Observed Behavior
It's written in the baseline file as follows:

```
<ID>MaxLineLength:MainActivity.kt$MainActivity$ </ID>
```
The task fails. I think the signature is incorrect.

## Steps to Reproduce
- Checkout my project: https://github.com/jelleheemskerk/detekt-bug
- Run `./gradlew detekt`

## Context
I'm trying to integrate detekt with our existing codebase. We use multiline string literals with JSON data for our tests. I don't seem to have this issue on **1.18.1**.

## Your Environment
* Version of detekt used: **1.19.0**
* Version of Gradle used (if applicable): **7.0.2**
* Gradle scan link (add `--scan` option when running the gradle task): https://gradle.com/s/ix7enmucwqthe
* Operating System and version: **Mac OS 12.1**
* Link to your project (if it's a public repository): https://github.com/jelleheemskerk/detekt-bug

**Comment by marschwar** [comment]
I was able to reproduce the issue but there are numerous ways to fix it. I would like to opinion of the maintainers first.

*Violating code*
```kotlin
class C {
    fun foo() {
        """
          "First very very very very very very very very very very very very very very very very very very very long line"
        """

        """
          "Second very very very very very very very very very very very very very very very very very very very long line"
        """
    }
}
```

*Baseline*
```xml
<?xml version="1.0" ?>
<SmellBaseline>
  <ManuallySuppressedIssues></ManuallySuppressedIssues>
  <CurrentIssues>
    <ID>MaxLineLength:C.kt$C$ </ID>
  </CurrentIssues>
</SmellBaseline>
```

There are a couple of things that come together here:
1. The element that is used to create the entity of the finding is the white space before the quotes resulting in the same signature for both violations
2. When reading the baseline file, the signature is trimmed and therefore will not match the signature of the finding

*Possible solutions*
1. Do not `trim()' when reading the baseline file. This does not sound like a viable solution and might break uses baseline files.
2. Use the first "meaningful" element (meaning anything non-blank and not a quote) to report the finding.
3. Extend the way signatures are generated to support entire line contents.
4. ???

Any thoughts?

**Comment by BraisGabin** [comment]
> Use the first \"meaningful\" element (meaning anything non-blank and not a quote) to report the finding.

I think that this is the best option.
