### ISSUE TITLE
InvalidPackageDeclaration doesn't enforce that the rootPackage is present

### ISSUE THREAD

**Issue by mateot1** [detekt/detekt#4483]
The `rootPackage` config for `InvalidPackageDeclaration` allows us to account for a file path that doesn't include the root part of the package, but it doesn't check that the package declaration contains this `rootPackage`. This can lead to inconsistency, for example:

with config `rootPackage: 'my.root.package'`
`file/path` containing a file with `package my.root.package.file.path` passes as expected
`file/path` containing a file with `package file.path` also passes 

## Expected Behavior of the rule
The rule should ensure that all classes in a given file path have the same package declaration. This means that if a `rootPackage` is defined, it should also enforce that it is present in the package declaration. 

## Context
For bettor or worse I work in a codebase that has a file structure that does not contain the root directories for kotlin src files which allows these inconsistencies to arise...

**Comment by cortinico** [comment]
I think this is a nice improvement. However, I would like to point out how this is a behavior change. Specifically, before the `rootPackage` was used just to ignore part of the package declaration.

Please also note how this is explained in the documentation:
https://github.com/detekt/detekt/blob/56e7fa94a47060fefa6c6e7a9e4bb73d1e9d1a16/detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/InvalidPackageDeclaration.kt#L28-L29

If we end up merging #4484, we should also update that documentation to clarify this behavioral change.

**Comment by mateot1** [comment]
updated!

**Comment by cortinico** [comment]
Fixed by #4484
