### ISSUE TITLE
Possibility to exclude Test functions names from maxLine check

### ISSUE THREAD

**Issue by lucsimonato** [detekt/detekt#4485]
## Expected Behavior of the rule
This change would allow to exclude form MaxLines check all those lines stating the name of function annotated with the `@Test` annotation.

## Context
In our project we would love to have the MaxLines rule to check for issues in our test files. However we also like to have our test functions names very, VERY descriptive, like:
`when mute is clicked, given that overlay video is not muted and isMute flag is true, then overlay is updated with muted video`

Unfortunately as of now, these lines cause issues for MaxLine (as they should) and we have a baseline file to keep these issues from making detekt fail. I would be really handy to have to possibility to exclude test functions names from being checked. 🙏

**Comment by BraisGabin** [comment]
Related with #2745 and there I provide a workaround but it's not exactly what you are describing.

I see this request as framework specific (JUnit in this case). There are other test frameworks that doesn't use the function name as the description of the rule. To me detekt shouldn't provide a fix for this but just provide tools to implement it. And I think that adding a custom `ReportingExtension` could help you there. There you can get the list of all the issues and you can filter the ones that meet your criteria.

**Comment by lucsimonato** [comment]
Thanks for linking that issue, the problem described is exactly the same I am having. However, the proposed solution is not quite the charm for me. Instead, the second solution proposed by @cortinico [here](https://github.com/detekt/detekt/issues/2745#issuecomment-635437350) seemed to me like the best solution for my situation (despite the drawbacks).

**Comment by lucsimonato** [comment]
Absolutely. Thanks for the very quick help, it's really appreciated 🙏 . I'll close this
