### ISSUE TITLE
Baseline: Adds issue to xml when file is excluded

### ISSUE THREAD

**Issue by hfhbd** [detekt/detekt#4487]
## Expected Behavior
`gradlew detektBaseline` creates a xml file containing all issues to ignore them. I would expect, this file does not contains issues marked in an `exclude` folder. 

## Observed Behavior
baseline.xml contains issues for files matching the `exclude` filter. This is a little bit confusing.

## Steps to Reproduce
```kt
import io.gitlab.arturbosch.detekt.*

plugins {
    kotlin("jvm") version "1.6.10" apply false
    id("io.gitlab.arturbosch.detekt") version "1.19.0"
}

allprojects {
    repositories {
        mavenCentral()
    }
}

detekt {
    source = files(rootProject.rootDir)
}

tasks {
    withType<Detekt>().configureEach {
        include("**/*.kt")
        exclude("**/*.kts")
        exclude("**/resources/**")
        exclude("**/build/**")
    }
}

fun b() {

}
```

`./gradlew detekt`

## Context
I want to ignore issues in some files, mostly generated Kotlin files from code generators (sqlDelight). 

If I add manually a new file which contains some issues which should be ignored and I run detektBaseline, the resulting diff is much larger because now baseline adds all issues, not my new issues but also issues from generated code.

## Your Environment

* Version of detekt used: 1.19
* Version of Gradle used (if applicable): 7.3.3
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: macOS 12.1
* Link to your project (if it's a public repository): 
[baselineExclude.zip](https://github.com/detekt/detekt/files/7856760/baselineExclude.zip)

**Comment by BraisGabin** [comment]
These seems like an issue in our documentation. You need to add this too:

```kotlin
    withType<DetektCreateBaselineTask>().configureEach {
        include("**/*.kt")
        exclude("**/*.kts")
        exclude("**/resources/**")
        exclude("**/build/**")
    }
```

**Comment by hfhbd** [comment]
@BraisGabin Thanks!
