### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [detekt/detekt#4496]
Hey there!

I belong to an open source security research community, and a member (@ready-research) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by chao2zhang** [comment]
Hello @JamieSlome! Thanks for sharing about the vulnerability found.

- We are definitely planning to add `SECURITY.md`, but we are still waiting on a few things including our newly setup OpenCollective and our specific domain.
- Which vulnerability management platform would you recommend for us to communicate effectively?

If you think the security vulnerability is urgent, we can definitely find other ways to speed things ups.

**Comment by JamieSlome** [comment]
@chao2zhang - thanks for the response! ⚡ 

Let me know if you need any help establishing the `SECURITY.md` - happy to contribute!

We currently have the report on our platform, which you can view here: [report](https://huntr.dev/bounties/23e37ba7-96d5-4037-a90a-8c8f4a70ce44/).

It is private and only accessible to maintainers with repository write permissions! 👍  Let me know if you need any assistance or have any questions.

**Comment by cortinico** [comment]
Thanks for your support @JamieSlome 

> Let me know if you need any help establishing the `SECURITY.md` - happy to contribute!

Do you happen to have a template that we can use as a starting point?

**Comment by JamieSlome** [comment]
@cortinico - you are welcome!

Happy to work on #4538 with you!

**Comment by JamieSlome** [comment]
Just further to the [report](https://huntr.dev/bounties/23e37ba7-96d5-4037-a90a-8c8f4a70ce44/), if you could confirm the fix once it has been addressed, that would be appreciated! ❤️

**Comment by BraisGabin** [comment]
Addressed, but no released yet.

**Comment by 3flex** [comment]
Was this the issue fixed in #4499?

If so we can close this.

**Comment by JamieSlome** [comment]
Would be good to know on the above point, so we can close the report off on our side as well:

https://huntr.dev/bounties/23e37ba7-96d5-4037-a90a-8c8f4a70ce44/

**Comment by chao2zhang** [comment]
Done. Please verify that I correctly marked the issue as fixed.

**Comment by JamieSlome** [comment]
@chao2zhang - yes, thank you 🙏
