### ISSUE TITLE
How to quickly navigate to each warning in Intellij IDEA?

### ISSUE THREAD

**Issue by fzyzcjy** [detekt/detekt#4534]
Hi thanks for the lib! I wonder how to quickly navigate to the errors in Intellij IDEA? Currently I look at the HTML report, and go to the corresponding file manually, but obviously this is very slow and not reasonable. I also see a intellij plugin, but that plugin seems not to tell me which file has problem and I have to open each and every file to see warnings. Thanks!

**Comment by cortinico** [comment]
Closing as I've followed up on the issue in the other repo
