### ISSUE TITLE
kotlin source directories not analysed when android variant is used

### ISSUE THREAD

**Issue by yachoor** [detekt/detekt#4553]
## Expected Behavior
Code under src/variant1/kotlin should be analysed when gradle detektVariant1Debug task is run

## Observed Behavior
Only code under src/variant1/java is analysed

## Steps to Reproduce
[DetektBug.zip](https://github.com/detekt/detekt/files/7990740/DetektBug.zip) sample project with one variant and 4 classes with same naming issue:
* Test1 under src/main/java
* Test2 under src/main/kotlin
* Test3 under src/variant1/java
* Test4 under src/variant1/koltin

When running gradle task detekt I get issues in Test1 and Test2, but when running detektVariant1Debug, I get issues only in java files - Test1 and Test3

## Your Environment
Tried android gradle plugin version 4.2.0, 7.0.0, 7.1.0 - same result, using detekt 1.19.0

**Comment by cortinico** [comment]
Thanks for providing a reproducer 🙏 Here the fix https://github.com/detekt/detekt/pull/4554

**Comment by Goooler** [comment]
Link JLLeitschuh/ktlint-gradle/issues/524, `kotlin` sourceSet should be added from AGP 7.0.
