### ISSUE TITLE
Drop Groovy DSL tests in detekt-gradle-plugin

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#4560]
## Expected Behavior
Efficient test suite. We shouldn't run tests that don't provide any extra assurances about the behaviour of the program. I propose dropping all Groovy DSL tests to improve test run time. The detekt-gradle-plugin test suite is one of the slowest in the project.

## Observed Behavior
Almost all of the Gradle plugin tests are run twice - once using the Groovy DSL, again using the Kotlin DSL.

## Steps to Reproduce
N/A

## Context
As far as I'm aware, the Gradle Kotlin DSL is always more strict than the Groovy DSL, with a couple of exceptions. This suggests that testing using Kotlin DSL only would be sufficient.

The exceptions are:
* [Calling Kotlin extension functions from Groovy](https://docs.gradle.org/7.3.3/userguide/kotlin_dsl.html#static_extensions) requires different syntax. This issue can be avoided by avoiding extension functions entirely. The plugin doesn't currently have any as part of its public API.
* [Calling Kotlin functions with named arguments from Groovy](https://docs.gradle.org/7.3.3/userguide/kotlin_dsl.html#calling_kotlin_from_groovy) requires use of positional parameters, and can't be called with named arguments from Groovy. I don't believe there are any such functions as part of the plugin's public API.
* [Calling Kotlin functions with default arguments from Groovy](https://docs.gradle.org/7.3.3/userguide/kotlin_dsl.html#calling_kotlin_from_groovy). Values must be passed for all parameters. Again, I'm not aware of any such public functions in the detekt plugin.

We may be able to add custom detekt rules to prevent this occurring, though I don't think that should be a blocker.

Otherwise, Kotlin is more strict. From https://docs.gradle.org/7.3.3/userguide/migrating_from_groovy_to_kotlin_dsl.html#prepare_your_groovy_scripts:
* Kotlin requires double quotes for all strings. In Groovy single quoted strings are also acceptable.
* Kotlin requires parentheses when invoking functions. In Groovy it's optional.
* Kotlin requires the `=` assignment operator when assigning properties. In Groovy it's optional.

When [applying plugins](https://docs.gradle.org/7.3.3/userguide/migrating_from_groovy_to_kotlin_dsl.html#applying_plugins), applying the plugin with `plugins {}` block means statically typed accessors will be available in the build script. This is the case in all current Kotlin DSL tests to guarantee the plugin is behaving correctly, with the exception of `DetektJvmSpec` which uses the `apply` method. As long as functional tests are covering all plugin behaviour this will not become a problem.

When [configuring plugins](https://docs.gradle.org/7.3.3/userguide/migrating_from_groovy_to_kotlin_dsl.html#configuring-plugins), the Kotlin DSL will be difficult to work with if any Groovy dynamic features are used. None are currently used.

When [applying configurations & dependencies](https://docs.gradle.org/7.3.3/userguide/migrating_from_groovy_to_kotlin_dsl.html#configurations-and-dependencies), the `plugins {}` block is required to generate configuration accessors (`detektPlugins` and `detekt`) in Kotlin DSL.

When [using the Provider API](https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_properties), the `set()` method on the property needs to be used instead of `=` when using Kotlin DSL.

**Comment by BraisGabin** [comment]
I really like your issues. Very well structured and with lots of links to understand in more depth what you are talking about.

I agree with you. If they don't provide that much value we should simplify the tests from the plugin. They are the slowest and the more difficult to work with. So any improvement in that regard seems a big win to me.

**Comment by cortinico** [comment]
Generally agree on this 👍 I think we can safely drop Gradle Groovy DSL tests without worrying too much. The benefit in terms of test runtime would be really beneficial.

There is only one thing that I'd like to point out:

> When [using the Provider API](https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_properties), the set() method on the property needs to be used instead of = when using Kotlin DSL.

I'm a bit afraid that we're essentially losing any integration test with the Gradle/Groovy ecosystem. Specifically, as the Gradle APIs are not the easiest to work with. We might end up in situations where we accidentally ship breaking changes for Gradle/Groovy (as we effectively don't test at all that our plugin works in a Gradle/Groovy environment) without noticing.

Again, not a big deal as our API is fairly simple, and I believe we're good to spot some  breaking changes at PR-review time.

Perhaps reducing the Groovy test suite to just a smaller group of tests (instead or running everything twice) could be a better approach to provide a decent amount of confidence.

**Comment by 3flex** [comment]
Thanks all!

> When using the Provider API, the set() method on the property needs to be used instead of = when using Kotlin DSL.

I think I've worded this poorly. `.set()` is required in Kotlin. Groovy can use either `=` or `.set()`. So we wouldn't break Groovy without breaking Kotlin if we moved to or from the Provider API.

That said, I agree that a Groovy sanity test will give comfort it's not being inadvertently broken by any changes. I'll just add a test that hits all public API from a single Groovy build script.

**Comment by BraisGabin** [comment]
> I'll just add a test that hits all public API from a single Groovy build script.

That sounds like a good option to me. The tests will not be that slow and we have something to tell us that we broke something. As you told the kotlin dsl is more restrictive than Groovy. So, one test proving that Groovy works should be enough.
