### ISSUE TITLE
FOSSA action is broken

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#4581]
## Expected Behavior
FOSSA action works on new commits to `main` branch.

## Observed Behavior
It's failing.

## Steps to Reproduce
Merge to `main`.

## Context
detekt uses Gradle 7.4 wrapper. fossa-cli is supposed to run Gradle using the wrapper in the project. It's running Gradle 7.3.3 for some reason which doesn't support some of the new build script declarations introduced in #4576.

This looks like a fossa-action or fossa-cli bug but I haven't investigated further.

**Comment by cortinico** [comment]
Reported upstream here https://github.com/fossas/fossa-action/issues/18
If we see no movements there, we might have to revert to use a REST call rather than a Github Action.

**Comment by 3flex** [comment]
I think the original issue is resolved - the build no longer fails because `notCompatibleWithConfigurationCache` is used in detekt's build files, indicating the right Gradle version is used when fossa-action runs.

Now it's failing when the configuration cache is enabled because the build script injected by fossa-cli is incompatible with the configuration cache. I've opened https://github.com/fossas/fossa-cli/issues/872 since this needs to be fixed there.

**Comment by cortinico** [comment]
Closing as we disalbed config caching for now. Will reopen once we enable it.
