### ISSUE TITLE
Prefix exception message with `Lint failed` or `Analysis failed`

### ISSUE THREAD

**Issue by runningcode** [detekt/detekt#4585]
In order to correctly classify errors in Gradle Enterise, exception messages should be prefixed with any of the messages listed below:

- Analysis failed
- Check failed
- Compilation failed
- Code generation failed
- Generation failed
- Lint failed
- Processing failed
- Test failed
- Tests failed
- Testing failed
- Verification failed

See docs for more information:
https://docs.gradle.com/enterprise/failure-classification/#verification_failures

## Observed Behavior
The current exception message `Build failed with 2 weighted issues.`

Happy to contribute this change.

**Comment by 3flex** [comment]
If only the detekt org had access to a Gradle Enterprise instance to test this with ;)

This change makes sense. Just for my own info, does the GE logic rely on the message bring in an exception?

**Comment by runningcode** [comment]
That's correct. See the failure classification guide for more information. https://docs.gradle.com/enterprise/failure-classification/#verification_failures

**Comment by chao2zhang** [comment]
Do you know if Gradle enterprise is planning to create new interfaces for these verification failures? Using prefix string matches does not feel robust enough to minimize false positives and false negatives.

**Comment by runningcode** [comment]
This is the first false positive I have discovered in my 1.5 years at Gradle. There is no plan @chao2zhang.
Feel free to browse our open source instances of Gradle Enterprise to see if there are any other occurrences of this happening in order to consider prioritizing this feature: https://gradle.com/enterprise-customers/oss-projects/
