### ISSUE TITLE
Outdated "Sample Gradle integrations examples" links

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4590]
Broken links in README.md

https://github.com/detekt/detekt#quick-links
first 2 are broken (removed [here](https://github.com/detekt/detekt/commit/755a15035b86a96a5704c50ca8f2a401d3c3a4b1#diff-adf2d4a720e4e359ca3e4290b0406f2521bb6eb37f1bd83de3fbffa35bd5dcd9))
last 2 are outdated (2019, rc15)

**Comment by cortinico** [comment]
> first 2 are broken (removed [here](https://github.com/detekt/detekt/commit/755a15035b86a96a5704c50ca8f2a401d3c3a4b1#diff-adf2d4a720e4e359ca3e4290b0406f2521bb6eb37f1bd83de3fbffa35bd5dcd9))
> last 2 are outdated (2019, rc15)

What do you mean with first 2 and last 2? They look fine to me

**Comment by TWiStErRob** [comment]
Oops, I removed "Sample Gradle integrations examples" which would've made it clear. There are 5 links in the indented list.

**Comment by BraisGabin** [comment]
Thanks to point it out!
