### ISSUE TITLE
Support Using Type Resolution in Android-Library Project

### ISSUE THREAD

**Issue by xiaoyijun** [detekt/detekt#4593]
## Expected Behavior

I know detekt has supported the Android project right now.  But when I start writing an Android library with detekt, I found that type resolution is not supported in the android library.
I wondering if I was using it in the wrong way, or maybe this can be a new feature being suggested.

**Comment by cortinico** [comment]
> I wondering if I was using it in the wrong way, or maybe this can be a new feature being suggested.

As long as you're using the `kotlin("android")` gradle plugin, the tasks for type resolution should be created.

https://github.com/detekt/detekt/blob/7cce3816dd97872ff7eecba382a65462bf736934/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt#L54-L58

Which task are you invoking?

**Comment by xiaoyijun** [comment]
Thanks for your feedback.
After my research, I found tasks have been generated, but when I invoke the task `detektMain`, the console says "NO-SOURCE".
This is because my source code resides in the `src/main/kotlin` folder.
When I place the code into `src/mian/java` folder, the task works!

**Comment by xiaoyijun** [comment]
Maybe detek tasks can support projects which put their source under `src/main/kotlin` without sourceSet configuration.

**Comment by cortinico** [comment]
This is already supported in the upcoming version of Detekt: 1.20.0
