### ISSUE TITLE
Improve the exception message while running a rule

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4615]
## Expected Behavior
When an exception is thrown while running a `Rule` we should provide information about the file and the `Rule`.

## Current Behavior
We only provide information about the file.

## Context
We had some issues lately where the users report exceptions on a Rule but we need to ask for the full stacktrace to know what's going on (an example: #4612). And the issue is also "detekt fails" instead of a more useful title like "Rule X fails".

This should be easy to implement and it will make the life easier for the reporter and the maintainers.

**Comment by VitalyVPinchuk** [comment]
Hello
May I work on the issue?

**Comment by BraisGabin** [comment]
Sure! And thanks :)

**Comment by jlengrand** [comment]
Is this issue still relevant? Given the MR referenced here has been merged to main?

**Comment by BraisGabin** [comment]
You are right! Thanks!
