### ISSUE TITLE
Extension toolVersion should default to the value from version.properties

### ISSUE THREAD

**Issue by efenderbosch** [detekt/detekt#4618]
## Expected Behavior

`extensions.findByType<DetektExtension>().toolVersion` should return a non-null value, defaulting to the value present in `version.properties`

## Current Behavior

`extensions.findByType<DetektExtension>().toolVersion` returns null if not explicitly configured

## Context

I need this value because I'm writing a Gradle plugin to reduce boilerplate in our services and want to include the `io.gitlab.arturbosch.detekt:detekt-formatting` dependency, but can't use the extension's `toolVersion` to properly include the correct version.

I can workaround using this:
```kotlin
val detektVersion = Properties().run {
    load(DetektPlugin::class.java.classLoader.getResourceAsStream("versions.properties"))
    getProperty("detektVersion")
}
detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:$detektVersion")
```
But referencing `version.properties` feels dirty and the plugin already reads this property file and could set the extension's `toolVersion` from that value.

**Comment by cortinico** [comment]
Yup you're right. That's a "bug" on our end. The fix is here https://github.com/detekt/detekt/pull/4623
