### ISSUE TITLE
Rules for undocumented protected members

### ISSUE THREAD

**Issue by mkrussel77** [detekt/detekt#4633]
The rule or changes you're looking for might have already been suggested!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior of the rule

Would like to get a warning when I have protected functions, properties, or classes that are not documented.  

## Context

As a library provider with classes that are intended to be extended by consuming code, my protected members are part of the public API and should get documented.  I could see this as being an optional flag on the public rules that already exist.

**Comment by marschwar** [comment]
I agree with the issue. The question really is how to go about solving it. Adding a flag to `UndocumentedPublicXxx` feels like a hack, creating a new rule for protected elements I think would be a maintenance nightmare. Could we maybe subclass `UndocumentedPublicXxx` with `UndocumentedXxx`, add a config property there and deprecate the parent rule?  Just spit balling here. Maybe there also is a way to solve this with rule aliases?

**Comment by BraisGabin** [comment]
I would vote to "hack" `UndocumentedPublicXxx`. I mean `protected` is part of your public API.

Other action: We should find a way to rename a rule without introducing a breaking change in the configuration of all our users. This is not the first time where we would like to change the name of a rule. Our only options here are:
- Overloading the name of a rule -> Bad for discoberability
- Create a rule and we end with two rules that should be one with a proper name. -> Bad for discoberability too. The users expect to have both behaviours in the same rule.

**Comment by cortinico** [comment]
> I would vote to "hack" `UndocumentedPublicXxx`. I mean `protected` is part of your public API.

+1 on this. Feels like the approach that opens for better long-term maintainance. We can also add an alias for `UndocumentedXxx` if we wish.

**Comment by cortinico** [comment]
Adding an extra property that checks also for `protected` would be an easy addition here
