### ISSUE TITLE
Magic Numbers in calculation of named Arguments

### ISSUE THREAD

**Issue by jakobulbrich** [detekt/detekt#4634]
In Jetpack Compose we have a Modifier called `aspectRatio` which expects a float value.
To fill this I provided `.aspectRatio(ratio = 4f / 3f)`. MagicNumber detection is by default disabled for named arguments, but still Detekt complains about this because it's a calculation. In my case the above notation provides an easier and more readable solution than the following options
- `.aspectRatio(ratio = 1.33f)`
- `.aspectRatio(ratio = FOUR_BY_THREE_RATIO)`

Is there any way to disable MagicNumber detection for calculations in named arguments for such a case?

**Comment by cortinico** [comment]
> Is there any way to disable MagicNumber detection for calculations in named arguments for such a case?

Not at the moment. In the snippet you mentioned, the Magic Numbers instances are found inside an expression. The named arguments is just one of the parent.

We could add a check here:
https://github.com/detekt/detekt/blob/14c0f11e44555cd55dc0940dec722070db4c8b0b/detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MagicNumber.kt#L158

To verify if the named argument is one of parent, but I'm unsure this is worth. Moreover it's a one-off that will apply only to named arguments and not to all the other config options. I'm not sure we want to go this way.

**Comment by chao2zhang** [comment]
Would it work for you if we suppress `MagicNumber` for all `@Compose` functions (More prone to false negatives)? This is supported by specifying `ignoreAnnotated` under each rule. See https://detekt.dev/compose.html#magicnumber

**Comment by cortinico** [comment]
> Would it work for you if we suppress `MagicNumber` for all `@Compose` functions (More prone to false negatives)?

Closing as a solution was suggested. Feel free to re-open if you wish to discuss further @jakobulbrich
