### ISSUE TITLE
Package declaration doesn't match source file location

### ISSUE THREAD

**Issue by rocketraman** [detekt/detekt#4635]
## Expected Behavior of the rule
A file package declaration may not match with the location of the file in the source tree. This rule would trigger in that situation.

## Context
Ensure package declarations match the physical location of the file.

IDEA flags this with:

"Package declaration does not match the source location".

**Comment by marschwar** [comment]
Do you mean something like [InvalidPackageDeclaration](https://detekt.dev/naming.html#invalidpackagedeclaration)?

**Comment by rocketraman** [comment]
Aha, yes! Is there a reason that rule is not active by default?

**Comment by BraisGabin** [comment]
I think that the only reason is that all the rules at detekt starts disable by default so we can get feedback about the rule and tune it before we enable it by default. I think that, for `1.21` we could check all our rules and enable some of them by default, for example, this one. I'm going to close this issue and open a new one to grab feedback about which rules should we enable.

**Comment by BraisGabin** [comment]
#4643
