### ISSUE TITLE
UnusedPrivateMember flags `contains()` as unused when using `in` operator

### ISSUE THREAD

**Issue by gabrielluong** [detekt/detekt#4636]
In https://github.com/mozilla-mobile/android-components/pull/11868/commits/39e714d2429bf40949b87b01398b870d890685b4#r826641811, we saw a case where `Int.contains()` was flagged as an unused private member when we used the `in` operator to call `contains()` implicitly.

## Expected Behavior

`contains()` should not be flagged as unused if the `in` operator is utilized.

## Observed Behavior

`contains()` is currently flagged as an unused private member.

## Steps to Reproduce

See https://github.com/mozilla-mobile/android-components/pull/11868/commits/39e714d2429bf40949b87b01398b870d890685b4#r826641811

## Your Environment

* Version of detekt used: 1.19.0
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by BraisGabin** [comment]
This should be fixed at 1.20 now in RC. #4242
