### ISSUE TITLE
Enable rules by default for `1.21`

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4643]
All the rules that we add to detekt start disable by default. That's a good default because the early-adopters can give us feedback about them and we don't create a lot of noise for those users that prefer more stability.

But from time to time we should promote those rules and enable them by default. An example of rule that we could enable by default:

- [InvalidPackageDeclaration](https://detekt.dev/naming.html#invalidpackagedeclaration)

Which other rules do you think we should enable by default?

Note: There are some rules that are "controversial" and they will never become enable by default.

**Comment by marschwar** [comment]
Thank you for taking the initiative. There are so many great rules that are not active by default right now. Here is the list of my candidates for 1.21. I am aware that some of them might not make the final cut. Curious for opinions.

* [MethodOverloading](https://detekt.dev/complexity.html#methodoverloading)
* [InstanceOfCheckForException](https://detekt.dev/exceptions.html#instanceofcheckforexception)
* [InvalidPackageDeclaration](https://detekt.dev/naming.html#invalidpackagedeclaration)
* [NoNameShadowing](https://detekt.dev/naming.html#nonameshadowing)
* [AvoidReferntialEquality](https://detekt.dev/potential-bugs.html#avoidreferentialequality)
* [ImplicitUnitReturnType](https://detekt.dev/potential-bugs.html#implicitunitreturntype) - I assume this might be controversial and break some builds :wink: 
* [MissingPackageDeclaration](https://detekt.dev/potential-bugs.html#missingpackagedeclaration)
* [UnreachableCatchBlock](https://detekt.dev/potential-bugs.html#unreachablecatchblock)
* I also like the idea of [CanBeNonNullable](https://detekt.dev/style.html#canbenonnullable) but do not know how battle tested it is
* [ClassOrdering](https://detekt.dev/style.html#classordering) - would definitely break builds, but it enforces the official coding guidelines
* [ExplicitItLambdaParameter](https://detekt.dev/style.html#explicititlambdaparameter)
* [RedundantHigherOrderMapUsage](https://detekt.dev/style.html#redundanthigherordermapusage), [UnnecessaryFilter](https://detekt.dev/style.html#unnecessaryfilter) and [UseAnyOrNoneInsteadOfFind](https://detekt.dev/style.html#useanyornoneinsteadoffind) - Love the rules. Have we seen many false positives?
*  [UnusedImports](https://detekt.dev/style.html#unusedimports)
* [UseArrayLiteralsInAnnotations](https://detekt.dev/style.html#usearrayliteralsinannotations)
* [UseCheckNotNull](https://detekt.dev/style.html#usechecknotnull) and [UseRequireNotNull](https://detekt.dev/style.html#userequirenotnull)
* [UseCheckOrError](https://detekt.dev/style.html#usecheckorerror) and [UseRequire](https://detekt.dev/style.html#userequire)
* [UseIsNullOrEmpty](https://detekt.dev/style.html#useisnullorempty)
* [UseOrEmpty](https://detekt.dev/style.html#useorempty)

**Comment by hfhbd** [comment]
I would like add `HasPlatformType` to the discussion as well.

**Comment by marschwar** [comment]
> > Note: There are some rules that are "controversial" and they will never become enable by default.
> 
> IIRC we decided to annotate them but we never did so right?

Correct, [we never did](https://github.com/detekt/detekt/issues/3560#issuecomment-1035394559). Should we at least create the annotation so We have the option to do so in the future?

**Comment by BraisGabin** [comment]
@marschwar  thanks you so much for that list with all the links! It's so easy to follow it! 

>     * [MethodOverloading](https://detekt.dev/complexity.html#methodoverloading)

I'm not 100% bought with this one... I know in general it's a bad idea to have too much overload methods and probably that you are not using the polymorphism correctly. But to be honest 6 seems like a really good threshold to me.

>     * [ImplicitUnitReturnType](https://detekt.dev/potential-bugs.html#implicitunitreturntype) - I assume this might be controversial and break some builds 😉

This one will break *lots* of builds. This patter is really common: `@Test fun foo() = runBlockingTest {}`

And I don't agree with this part of its description:

> Changing the type of the expression accidentally, changes the functions return type.

That issue is not related with functions returning implicit `Unit` that's generic for any implicit return value.


>     * I also like the idea of [CanBeNonNullable](https://detekt.dev/style.html#canbenonnullable) but do not know how battle tested it is

I agree that it would be really nice but it was introduced in 1.20.0-RC1 so I'm not sure... we could talk about it once 1.20 is released.

>     * [ClassOrdering](https://detekt.dev/style.html#classordering) - would definitely break builds, but it enforces the official coding guidelines

I think this one is controversial too. I for sure will disable this one in my projects.

>     * [RedundantHigherOrderMapUsage](https://detekt.dev/style.html#redundanthigherordermapusage), [UnnecessaryFilter](https://detekt.dev/style.html#unnecessaryfilter) and [UseAnyOrNoneInsteadOfFind](https://detekt.dev/style.html#useanyornoneinsteadoffind) - Love the rules. Have we seen many false positives?

+1! I have them enabled in my code and they work perfectly fine.

--

The other ones that I didn't comment here I agree 100% that we should enable them

**Comment by marschwar** [comment]
I agree with your concerns. I updated my comment above to keep track of the current state of the discussion. Hope that more users chime in as well.

**Comment by BraisGabin** [comment]
My own list (I'm not adding the onces that were mentioned already)

- [`LabeledExpression`](https://detekt.dev/complexity.html#labeledexpression)
- [`NamedArguments`](https://detekt.dev/complexity.html#namedarguments)
- [`ReplaceSafeCallChainWithRun`](https://detekt.dev/complexity.html#replacesafecallchainwithrun) I'm not 100% bought with this one... In general I don't like to chain multiple safe calls because it's not clear what can be `null` but It's a bit too strict some times...
- All the rules from the rule set [`Coroutines`](https://detekt.dev/coroutines.html). They are great
   - Maybe we could deprecate `GlobalCoroutineUsage` now that you need to annotate its usages with `@OptIn(DelicateCoroutinesApi::class)`. How can we deprecate a rule? I think that's not a thing right now on detekt.
- [`NotImplementedDeclaration`](https://detekt.dev/exceptions.html#notimplementeddeclaration)
- [`ObjectExtendsThrowable`](https://detekt.dev/exceptions.html#objectextendsthrowable)
- [`MatchingDeclarationName`](https://detekt.dev/naming.html#matchingdeclarationname)
- [`DoubleMutabilityForCollection`](https://detekt.dev/potential-bugs.html#doublemutabilityforcollection)
- [`IgnoredReturnValue`](https://detekt.dev/potential-bugs.html#ignoredreturnvalue)
- [`LateinitUsage`](https://detekt.dev/potential-bugs.html#lateinitusage), this one could be really polemic on the android world but lateinit is the same as a null on java...
- [`MapGetWithNotNullAssertionOperator`](https://detekt.dev/potential-bugs.html#mapgetwithnotnullassertionoperator)
- [`NullableToStringCall`](https://detekt.dev/potential-bugs.html#nullabletostringcall)
- [`UnreachableCatchBlock`](https://detekt.dev/potential-bugs.html#unreachablecatchblock)
- [`UnusedUnaryOperator`](https://detekt.dev/potential-bugs.html#unusedunaryoperator)
- [`UselessPostfixExpression`](https://detekt.dev/potential-bugs.html#uselesspostfixexpression)
- [`DestructuringDeclarationWithTooManyEntries`](https://detekt.dev/style.html#destructuringdeclarationwithtoomanyentries)
- [`ForbiddenVoid`](https://detekt.dev/style.html#forbiddenvoid)
- [`ObjectLiteralToLambda`](https://detekt.dev/style.html#objectliteraltolambda)
- [`RedundantHigherOrderMapUsage`](https://detekt.dev/style.html#redundanthigherordermapusage)
- I would love to enable [`UnnecessaryLet`](https://detekt.dev/style.html#unnecessarylet) but I think that it's not ready yet...

And I would vote to disable `UnsafeCallOnNullableType`. I saw that it make a lot of devs to abuse from the safe call operator (`?.`) and to me that's even worst. I prefer a NPE than an unexpected behaviour that goes under the radar. But I suppose that this is very controversial so I'm ok maintaining the "status quo".

**Comment by hfhbd** [comment]
I am surprised [NotImplementedDeclaration](https://detekt.dev/exceptions.html#notimplementeddeclaration) is not enabled by default :D

**Comment by marschwar** [comment]
I could get behind most of your suggestions, other than:

**strongly oppose** -> candidates for `@Controversial`? 

* ReplaceSafeCallChainWithRun - it really depends on the use case if it improves the code or makes it harder to understand
* NotImplementedDeclaration - while trying to use continuous delivery it is helpful to be able commit stubs that are not yet used
* NullableToStringCall - never understood the rule


**mildly oppose as that may cause many builds to break**
* IgnoredReturnValue
* LateinitUsage

> And I would vote to disable UnsafeCallOnNullableType.

To me this should stay active by default.

**Comment by BraisGabin** [comment]
I would like to give a more inside about two of those rules and why I think that they should be enabled:

`NullableToStringCall`: Usually, when you use `toString()` is to show that to the user in some way. But it's really strange to want to show `"null"` to the user. But kotlin is completely fine with this: `null.toString()`. What this rule does is to reduce that issue. I think that this one is important.

`IgnoredReturnValue`: I agree, it could fail a lot of buids. But what this rule is to "empower" the library authors to force the users to use theri library properly. By default we just flag the ignored values from functions that were explicitily annotated. I think that the false positives of this rule should be **really** low and it should find lots of real issues. But I'm fine with keeping it disabled until the next "bunch of enabled rules".

(I agree with you in the other ones and I crosslined them)

**Comment by marschwar** [comment]
I guess our use cases differ. I usually work on the server side of things and when ever I use the implicit toString in string Interpolation in a log message, I actually want to see the "null" string.

**Comment by BraisGabin** [comment]
Good point. I crosslined it from the list.

**Comment by BraisGabin** [comment]
I'm changing my mind about enabling this rules:

- `UnusedImport`: I think that we should keep it disable for now because of #4689
- `NamedArguments`: I like this one but I think that it's controversial and it should raise a lot of issues.
- `UnnecessaryLet`: It's not ready.
