### ISSUE TITLE
Add ignoreOverridden support for BooleanPropertyNaming rule

### ISSUE THREAD

**Issue by mhernand40** [detekt/detekt#4652]
## Expected Behavior of the rule
When overriding a Boolean property from a 3rd party library, the [BooleanPropertyNaming](https://detekt.dev/naming.html#booleanpropertynaming) will flag the `override` if it does not adhere to the rule. Since this is out of the developer's control, there should be a way to set the `ignoreOverridden` flag to `true` for such cases.

## Context
One example of this is when overriding the [PagingSource#keyReuseSupported](https://developer.android.com/reference/kotlin/androidx/paging/PagingSource#keyReuseSupported()) property from the Android Paging 3 Library.

Yes, one could configure the rule to accept the naming conventions of the 3rd party library but that may be too invasive if the code base under the dev's control wishes to adhere as close to the default config as possible.

**Comment by cortinico** [comment]
Yup that's a valid addition 👍 Do you want to send a PR?

**Comment by mhernand40** [comment]
Sure. Please feel free to assign to me.

**Comment by BraisGabin** [comment]
Closing as this was already addressed.
