### ISSUE TITLE
The links in our rule descriptions should be clickables

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4656]
## Expected Behavior
The rule description should have links in it's descriptions to give some "bibliography". Those links should be clickable in the documentation.

## Observed Behavior
[ObjectLiteralToLambda](https://detekt.dev/style.html#objectliteraltolambda) Right now they are not.

**Comment by VitalyVPinchuk** [comment]
Hello,
may I work on this?

**Comment by cortinico** [comment]
Yes please 👍 I've assigned it to you
