### ISSUE TITLE
VarCouldBeVal on interface override

### ISSUE THREAD

**Issue by meriouma** [detekt/detekt#4661]
Related to https://github.com/detekt/detekt/issues/4474. Seems to be a similar case, but it still fails with 1.20.0-RC2

## Expected Behavior

Not getting VarCouldBeVal

## Observed Behavior

Getting VarCouldBeVal

## Context

Shortened example :
```kotlin
interface SomeConfig {
    var apiUrl: String
}

class ServerHelper(
    private val mockServer: MockServerContainer
) {
    val someConfig: SomeConfig = object : SomeConfig {
        override var apiUrl: String = mockServer.endpoint // <-- VarCouldBeVal here
    }
}
```

## Your Environment

* Version of detekt used: 1.20.0-RC2
* Version of Gradle used (if applicable): 7.4.1

**Comment by cortinico** [comment]
That's add as we have a test case that is testing exactly this snippet: https://github.com/detekt/detekt/pull/4477/files

I assume you're using type resolution right?

**Comment by meriouma** [comment]
I believe I do. This happens when running `detektTest`.
