### ISSUE TITLE
False positive for `UnusedImports` on functions that are used from generated code (Android ViewBinding)

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#4678]
Using detekt 1.20.0-RC2

I use Android ViewBinding extensively. If I call an extension function or use an extension property on one of the Views exposed by the ViewBinding class, the import for that function/property violates the `UnusedImports` rule.

**Comment by cortinico** [comment]
Thanks for the issue report @eygraber 🙏 Is this a regression? Could you check with 1.19.x if the issue is happening?

Also are you using type resolution?

**Comment by eygraber** [comment]
Same as https://github.com/detekt/detekt/issues/4676#issuecomment-1088267221

**Comment by BraisGabin** [comment]
Same as: https://github.com/detekt/detekt/issues/4676#issuecomment-1133931502

> could you check the detekt's `SNAPSHOT` to see if you can reproduce the same issue after we merge #4723?

**Comment by eygraber** [comment]
The issue is resolved in `SNAPSHOT`

**Comment by BraisGabin** [comment]
Thanks to check it :)
