### ISSUE TITLE
Support preview annotation from Jetpack Compose

### ISSUE THREAD

**Issue by dizyaa** [detekt/detekt#4682]
## Expected Behavior
Detect **not failed** when see unused private function for preview.
## Current Behavior
**Failed** with exception `UnusedPrivateMember - [ScreenPreview] at /home/dizyaa/.../Screen.kt:100:1` 
## Context
Detect failed when see unused private function for Compose `@Preview`.
Example: 
```kotlin
@Preview(showSystemUi = true)
@Composable
private fun ScreenPreview() { /* code */ }
```

To fix this I use, but it looks terrible and is bad practice
```kotlin 
@SuppressWarnings("UnusedPrivateMember")
```

**Comment by schalkms** [comment]
In this case, the **ignoreAnnotated** config setting can be used.
https://detekt.dev/suppressors.html

**Comment by dizyaa** [comment]
Oh, thanks!
