### ISSUE TITLE
Multiline string rules

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#4705]
This could be either a single, configurable rule, or a series of rules, that performs checks on the contents of multiline strings.

## Expected Behavior of the rule
* Check for consistent indentation type (could be done in one of two ways - either check where a mix of indentation is used so it's not a mix of tabs & spaces, or have a rule that enforces either tabs or spaces)
* Check for trailing whitespace on each line
* When using `trimIndent()` or `trimMargin()` check that the left-most indentation is indented x characters from the enclosing element
* Check that every multiline string uses either `trimMargin()` or `trimIndent()` - Kotlin Coding Conventions doc says "To maintain indentation in multiline strings, use `trimIndent` when the resulting string does not require any internal indentation, or `trimMargin` when internal indentation is required"

We could also have a rule that checks for use of `\n` in a regular string literal and recommend converting to a multiline string, as the Kotlin Coding Conventions says "Prefer multiline strings to embedding `\n` escape sequences into regular string literals."

## Context
The above rules would identify inconsistencies in use of multiline strings, and were inspired by the current use of multiline strings in detekt's test sources.

I'll also note that KtLint won't address any of the above, as they have said in https://github.com/pinterest/ktlint/pull/1052 that they do not want to change the content of any strings in their rules, so this is not in their scope.

**Comment by cortinico** [comment]
Yup this sounds like a valid rule to add to me 👍

**Comment by gunishmatta** [comment]
@BraisGabin  I want to work on this
Would love to contribute

**Comment by cortinico** [comment]
Assigned to you @gunishmatta 👍

**Comment by 3flex** [comment]
Personal preference, but I think these should be individual rules, rather than a single rule with multiple config options.

Anyone else have an opinion on this?

**Comment by cortinico** [comment]
> Personal preference, but I think these should be individual rules, rather than a single rule with multiple config options.
> Anyone else have an opinion on this?

+1 on this. Let's make them separate as it's easier to test/review/maintain

**Comment by BraisGabin** [comment]
@gunishmatta did you get any progress?

**Comment by BraisGabin** [comment]
And I have a question which should be the correct way to indent a multiline string:

```kotlin
"""
    hello!
""".trimIndent()
```
or
```kotlin
"""
hello!
""".trimIndent()
```

If we go with the first one we need a configuration for the indentation size.

**Comment by marschwar** [comment]
Reading the [Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html#strings), I interpret it to be the regular 4 space indent to the previous expression such as:

```kotlin
val a = """
    hello
    """.trimIndent()
// or
val a = 
    """
    hello
    """.trimIndent()

// and
val b = a.let {
    it + """
        hello
        """.trimIndent()
}
```

Unfortuately the `trimMargin` example seems to follow a slightly different rule.

**Comment by BraisGabin** [comment]
I'm working on:

> When using trimIndent() or trimMargin() check that the left-most indentation is indented x characters from the enclosing element

But I have an idea for other rule. Forbid this type of things:

```kotlin
val a = """Hello World!
    How are you?
""".trimIndent()
```

and

```kotlin
val a = """
    Hello World!
    How are you?""".trimIndent()
```

It should be:
```kotlin
val a = """
    Hello World!
    How are you?
""".trimIndent()
```

In words: if the raw string is not a single line:
- After openingn `"""` there should be a `\n`
- Before the closing `"""` the line should only contain spaces (` `).

**Comment by BraisGabin** [comment]
What do you think about a `raw-string` rule-set? I think that I can implement 5 or 6 rules related with raw-stings based just on this issue.

- Pro: This will group all the rules related with this topic and a user could disable all at once.
- Pro: less rules to "detekt-style"
- Con: We add a new rule set for a single language feature.

**Comment by atulgpt** [comment]
Hi @BraisGabin, is there any un-implemented rule from this issue? To me it seems all have been implement

**Comment by BraisGabin** [comment]
Yes I feel this is done. If something is missing I think that a new issue will help to understand what should be done.
