### ISSUE TITLE
1.20.0 is not fully released everywhere

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4721]
## Expected Behavior
Consistent display of 1.20.0 in all locations.

## Observed Behavior
https://detekt.dev/changelog.html 1.20.0 released 2 weeks ago
https://github.com/detekt/detekt/releases 1.20.0-rc2
https://search.maven.org/artifact/io.gitlab.arturbosch.detekt/detekt-cli 1.20.0-rc2 (update 15 Apr, sonatype propagation done 1.20.0)
https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt 1.20.0
https://detekt.dev/compatibility.html 1.19.0
https://github.com/detekt/detekt#requirements 1.19.0

## Context
I got the notification of the new version from renovatebot, so it might be too eagerly notifying before you finished the process.

**Comment by TWiStErRob** [comment]
Tip: do you have a play-by-play which nudges to update compatibility table, etc.?

**Comment by cortinico** [comment]
> I got the notification of the new version from renovatebot, so it might be too eagerly notifying before you finished the process.

This 👆 

We're waiting for this #4719 to be merged to update everything.

**Comment by bric3** [comment]
I understand the announcement but this is confusing to see binaries on maven central and gradle plugins but not here.

**Comment by TWiStErRob** [comment]
I agree with @bric3, you should push to master and tag before publishing the binaries.

You don't need to promote the sonatype staging repository immediately. After closing it you can test by referencing the private staging repo, and then either publish or make changes as necessary.

So the best DX from a user's perspective is:
- commit
- build
- upload to staging
- close staging repo to validate
- test via staging repo url
- repeat from step 1 if there are problems
- tag
- push
- promote staging
- publish draft release on GitHub

**Comment by cortinico** [comment]
> I agree with @bric3, you should push to master and tag before publishing the binaries.

That's not possible at the moment. The project relies on the existence of detekt-gradle-plugin (and all the other artifacts) on Gradle Portal/Maven Central. Therefore if we commit/merge before publishing we will effectively break master. In other words, this PR https://github.com/detekt/detekt/pull/4719 won't be green till the artifacts are available online.

I agree that this is sub-optimal and we should look into migrating to a composite build, as it would solve this and other problems.

> [detekt.dev/changelog.html](https://detekt.dev/changelog.html) 1.20.0 released 2 weeks ago

This was a mistake on my end. The changelog generator uses the milestone name. We don't have milestones for RCs and here I forgot to rename it to -RC2. Reviewers also missed that.

> [detekt/detekt/releases](https://github.com/detekt/detekt/releases) 1.20.0-rc2

That's updated now

> [search.maven.org/artifact/io.gitlab.arturbosch.detekt/detekt-cli](https://search.maven.org/artifact/io.gitlab.arturbosch.detekt/detekt-cli) 1.20.0-rc2 (update 15 Apr, sonatype propagation done 1.20.0)

That's correct as 1.20.0 was published on the repos yesterday night CEST time.

> [plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt](https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt) 1.20.0

Same as above.

> [detekt.dev/compatibility.html](https://detekt.dev/compatibility.html) 1.19.0
> [detekt/detekt#requirements](https://github.com/detekt/detekt#requirements) 1.19.0

Those two are generally updated in a subsequent PR:
- https://github.com/detekt/detekt/pull/4725

Also our review policy requires to have at least one approval before merging, therefore things move as fast as our reviewers speed (i.e. the compat table won't be updated till #4725 is merged, so you will still see outdated information).

Finally, I wrote a long discussion on our release process some weeks ago here:
- https://github.com/detekt/detekt/discussions/4696

As I received no comments/feedbacks, would be awesome if you folks could comment over there how you would like the release process to look like and what is creating confusion/problems for you.

Closing as this got solved with the merge of #4719
