### ISSUE TITLE
UnnecessaryAbstractClass is not targeting class name

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4749]
## Expected Behavior of the rule

UnnecessaryAbstractClass should target the name of the class

## Context
I just updated Detekt 1.19.0 to 1.20.0 and got this failure:
https://github.com/TWiStErRob/net.twisterrob.cinema/security/code-scanning/227

as you can see it's showing the `/**` as the "violation", but the real code is:
```
	/**
	 * Internal dependencies in this route group.
	 */
	@Module
	abstract class BackendModule {
```
it should be targeting this part:
```
	abstract class BackendModule {
                       -------------
```

![image](https://user-images.githubusercontent.com/2906988/164910247-930c8fdf-1dcd-40ad-9ae9-bd8268548bb9.png)

**Comment by TWiStErRob** [comment]
Ah, it's actually trying to highlight the whole class? or the first line of the class?
https://github.com/TWiStErRob/net.twisterrob.cinema/security/code-scanning/228
![image](https://user-images.githubusercontent.com/2906988/164910478-58716e23-694e-47f7-b7b1-94b0d36b2fac.png)

**Comment by cortinico** [comment]
Could you provide the source code (the whole file or a repro file) + the sarif output.
If possible having the HTML/TXT report would also be helpful to understand if the bug is in the sarif output or not.

**Comment by BraisGabin** [comment]
Could you provide a PR fixing it? I think that we have some functions when creating the report to tell just to mark the name of the class or function.

**Comment by TWiStErRob** [comment]
Sorry, I won't be near my computer for a few days, hopefully I'll be able to provide details later.
