### ISSUE TITLE
Rule MultilineLambdaItParameter does not work

### ISSUE THREAD

**Issue by neblung** [detekt/detekt#4781]
## Expected Behavior
Violating the rule should be reported and fail the build.

## Observed Behavior
Violation is not reported. The build passes.

## Steps to Reproduce
1. Clone repository https://github.com/neblung/use-detekt
1. Run `./gradlew detekt`

## Your Environment

* Version of detekt used: 1.20.0
* Version of Gradle used (if applicable): 7.4.2
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): https://github.com/neblung/use-detekt

**Comment by BraisGabin** [comment]
This rule needs type resolution. Otherwise it doesn't work. You need to execute `./gradlew detektMain` and define the jvmTarget. More info here: https://detekt.dev/docs/gettingstarted/gradle#using-type-resolution

**Comment by chao2zhang** [comment]
Closing this issue for now - Let us know if this issue persists after enabling type resolution
