### ISSUE TITLE
Add links to the rules documentation in the html report

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4792]
## Expected Behavior
When I read a `html` report I can get the maximum context to fix the issues that detekt found. For example, links to the documentation of each rule that has at least one issue.

## Current Behavior
If you want to know a bit more about one rule and what it does you need to copy the name of the rule, paste it on a web search engine add "detekt" and find that documentation that you need.

## Context
That step of copy&paste to search for a rule is anoying and it should be easily fixed.

This is the current report, as you can see, without any link:
![Captura de pantalla 2022-04-30 a las 12 40 56](https://user-images.githubusercontent.com/721244/166102323-61b0588c-5602-45d3-8fcf-632b28529bfd.png)

**Comment by cortinico** [comment]
Fixed by #4799
