### ISSUE TITLE
InvalidPackageDeclaration: detekt missing package name when root is empty

### ISSUE THREAD

**Issue by rocketraman** [detekt/detekt#4810]
## Expected Behavior of the rule
Currently `InvalidPackageDeclaration` detects a missing package declaration, but only if the `root` is not empty.

With Kotlin/JS, people often follow JS module naming conventions rather than Java naming conventions. With JS conventions, there is generally no common root package, thus `root` must be empty.

But in this case, Detekt no longer sees invalid package declarations where the `package` line is missing entirely.

Can this rule be updated so that it detects missing package declarations even when the root package is `''`?

## Context
Example project: https://github.com/Kotlin/full-stack-web-jetbrains-night-sample

**Comment by BraisGabin** [comment]
We have a different rule for this use case: `MissingPackageDeclaration`.

**Comment by rocketraman** [comment]
@BraisGabin The problem with `MissingPackageDeclaration` is that it triggers on files that are legitimately at the empty package root.

I'm simply looking for a rule that forces the package to match the file location, whether that is at the root or elsewhere.

**Comment by BraisGabin** [comment]
I was thinking about this. Why would you want to mix code with and withoud package in the same project/module? And if you do so I assume that the quantity of files without package would be really small, Am I right? If that's true probably a `@Suppress` is a good fit here. I mean, just to express "I know, all the files should have a package but in this one I don't want a package".

**Comment by rocketraman** [comment]
@BraisGabin The main use case I see is a multiplatform project with a Kotlin/JS module that share a set of Detekt rules. The Kotlin/JS module may have a bunch of files at the root package, whereas the other modules won't, to avoid JavaScript code having to prefix the package name which isn't idiomatic (https://kotlinlang.org/docs/js-to-kotlin-interop.html#package-structure).

I don't have enough cross-project experience with Kotlin/JS to say how many of such files a project may contain -- my current project contains only two. Therefore, I think its a fair solution to use a `@file:Suppress("MissingPackageDeclaration")` though, so I'll go ahead and close, at least for now.

**Comment by jpink** [comment]
[Kotlin coding conventions](https://kotlinlang.org/docs/coding-conventions.html#directory-structure) says:

> In pure Kotlin projects, the recommended directory structure follows the package structure with the common root package omitted. For example, if all the code in the project is in the `org.example.kotlin` package and its subpackages, files with the `org.example.kotlin` package should be placed directly under the source root, and files in `org.example.kotlin.network.socket` should be in the `network/socket` subdirectory of the source root.

I got this error: `InvalidPackageDeclaration: Kotlin source files should be stored in the directory corresponding to its package statement.` which is ok for Java, but not in pure Kotlin. Should I suppress this on every file? (That might be different issue than this thread)

**Comment by marschwar** [comment]
The rule checks exactly  that part of the  coding conventions you reference. If you think you found a bug, please open a separate issue.
