### ISSUE TITLE
A rule for when multiple collection or iterable operations are chained to suggest that a sequence be used instead

### ISSUE THREAD

**Issue by mjsztainbok** [detekt/detekt#4838]
The rule or changes you're looking for might have already been suggested!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior of the rule

When operations such as `map`, `filter`, etc. are chained on an `Iterable` or `Collection`, the rule would say that `asSequence()` should be called before the operations to optimize performance.

## Context

Kotlin provides operations like `map`, `filter`, etc. directory on `Collection` and `Iterable` objects through extension methods. The problem with using these is that if you chain the methods e.g. do a `filter` then a `map` multiple iterations are done over the collection/iterable.
However, if a Kotlin sequence is used then only a single iteration is done over the data as the operations are composed and lazily evaluated in a similar way to how Java streams operate
https://kotlinlang.org/docs/sequences.html talks about this

**Comment by BraisGabin** [comment]
That sounds like good rule. Do you want to give it a try? We can help you with it. I assume that `UnnecessaryFilter` could give you a good start point.

**Comment by themkat** [comment]
If @mjsztainbok don't want to, then I sure would love to 🙂  I already started looking a bit into it, but can step aside if @mjsztainbok would prefer looking at it himself

**Comment by BraisGabin** [comment]
I'm using a FIFO here. And you have extra points if you looked a bit into it already ;) Thanks!

**Comment by BraisGabin** [comment]
Closed by #4855. Thanks!
