### ISSUE TITLE
Website: visible liquid not rendered

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4839]
## Expected Behavior
Website renders HTML.

## Observed Behavior
![image](https://user-images.githubusercontent.com/2906988/169265256-f4db0c26-922a-4f98-907c-bfa8648e0e7e.png)

## Steps to Reproduce
https://detekt.dev/docs/gettingstarted/type-resolution/#is-my-rule-using-type-resolution

## Context
https://github.com/detekt/detekt/blob/7cb5d9603bf4bf1f263dc393764178ef8d1df8cf/website/docs/gettingstarted/type-resolution.md?plain=1#L54

Not sure why it's not rendering, maybe the space between `{%` and `include`?

## Your Environment
Chrome, but I think it's HTML.

**Comment by cortinico** [comment]
Yup I missed this one. It should be converted to a MDX component. That's up for grab if someone wants to do a easy contribution to Detekt :)

**Comment by jlengrand** [comment]
Hey, I've done this, can you please confirm / infirm whether this is what is expected ?

https://github.com/detekt/detekt/pull/5017

<img width="984" alt="image" src="https://user-images.githubusercontent.com/921666/176691874-e4a9df69-1a90-4084-9e4e-ae57dffdccf9.png">
