### ISSUE TITLE
Homebrew install specific version

### ISSUE THREAD

**Issue by AlexProdrom** [detekt/detekt#4840]
## Expected Behavior
To be able to download a previous version than the latest using homebrew. Something like brew install detekt@1.19.0

## Current Behavior
It is possible to install only the latest version through homebrew, the whole github download approach is needed now.

## Context
We have our script in the repo to download all the dependencies required from the project, unfortunately when there is a new version of detekt the script downloads the latest own, which can be a bit dangerous. For example our new colleague ran the script recently and it downloaded 1.20.0 but our rules.configs are written for version 1.19.0. We of course plan to update to 1.20.0 ASAP but it might be a bit delayed and up until then we cannot have a stable dependency setup.

**Comment by cortinico** [comment]
Yup that's a valid request. We don't maintain the brew formula ourselves but it's something we're looking external contributors to help us with :)

**Comment by AlexProdrom** [comment]
Thanks! will have a look when having time :)

**Comment by BraisGabin** [comment]
Closing as there is nothing we can do here
