### ISSUE TITLE
`detektGenerateConfig` fails

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4843]
## Expected Behavior
If I run `./gradlew detektGenerateConfig` the configuration file should be created and gradle should not fail.

## Observed Behavior
The file is created, but gradle fails: https://ge.detekt.dev/s/lpgeopyjrd46k/failure?expanded-stacktrace=WyIwIiwiMC03LTktMTEiXQ&focused-stack-frame=0-7-9-11-0

## Steps to Reproduce
In this project:
```
rm config/detekt/detekt.yml
./gradlew detektGenerateConfig
```

## Context
This is a long standing bug. I thought it was reported but I can't find it.

## Your Environment
* Version of detekt used: 1.20.0 / main
* Version of Gradle used (if applicable): 7.4.2
* Gradle scan link (add `--scan` option when running the gradle task): https://ge.detekt.dev/s/lpgeopyjrd46k
* Link to your project (if it's a public repository): https://github.com/detekt/detekt

**Comment by BraisGabin** [comment]
This is a race condition, different gradle tasks try to write that file at the same time. The first one succed and the other fails. Probably we could just ignore the exception. What do you think?

**Comment by cortinico** [comment]
> If I run `./gradlew detektGenerateConfig` the configuration file should be created and gradle should not fail.

The problem is that you're invoking multiple tasks here `detektGenerateConfig`.
Not sure how to handle this, maybe the task should just not fail if the file already exists but just print a warning to the user? 

Still users will report that warnings are reported when invoking `./gradlew detektGenerateConfig` so it doesn't really solve the underlying issue

**Comment by TWiStErRob** [comment]
I don't think there would be divergence, it would always register on root, simple "rule".
If you apply to root or not it would still execute the same code: `project.rootProject.tasks.maybeRegister`.
If you do `allprojects { apply(plugin = "detekt") }` you still get it only on root project.
If you only apply it on the app module, you still get it on root project.

Are you thinking of perception perspective? Like if I apply it on root then `project.rootProject == project`, so it creates the task in the same project?

**Comment by cortinico** [comment]
A couple of problems that comes to my mind are:
* `detektGenerateConfig` needs to load the `detektPlugin`. If we register it only on the rootProject, you might effectively lose some `detektPlugin` dependency.
* It feels unaligned to register only a `detektGenerateConfig` task on the root project and not other top level tasks like `detektAll` or so.

**Comment by TWiStErRob** [comment]
🤔 Why does it need the plugin applied? Isn't it reading from the classpath of the build?

**Comment by TWiStErRob** [comment]
An alternative solution is to create a separate plugin to be applied on root. As you mentioned it seems there might be other tasks/things that could be hosted in there.

**Comment by TWiStErRob** [comment]
Yet another alternative, circling back to https://github.com/detekt/detekt/issues/4843#issuecomment-1132248171:
 1. make the task idempotent. if the file is already there, verify the contents would be the same as the one that was about to be copied, if this is true, silently pass (the end result is achieved).
 2. maybe ensure that no 2 tasks of this type can be executed in parallel using a build service

**Comment by BraisGabin** [comment]
The first point wouldn't help. This is a race condition, multiple tasks check that the file doesn't exist so all of them try to write it and 💥.

The second sounds nice. I mean, all those tasks share the same output, maybe there's a way on detekt to just execute one of them.

**Comment by TWiStErRob** [comment]
1 + 2 have to be together, sorry that wasn't clear. Do you know about Gradle build services?

**Comment by cortinico** [comment]
> Do you know about Gradle build services?

Yes. But still, even if they don't run in parallel, they will produce output that will override each other.
If we want to evolve the current status for the sake of correctness, we should go with the rootProject solution you suggested and find a way to collect the `detektPlugins` dependencies.

**Comment by TWiStErRob** [comment]
Ah, I think I see your point, execution is not the only problem, Gradle would warn on overlapping outputs as well I think. It would be interesting to learn how to this properly as it seems to come up "often".

**Comment by BraisGabin** [comment]
I think that this issue shows that a big refactor in our gradle plugin is needed. Anyway, I see two different solutions here:

### First

Change this line:

https://github.com/detekt/detekt/blob/0d42e58e1087ac5bffcc0a125d707efbd9bced88/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektGenerateConfigTask.kt#L46

We should not use `rootDir` but `projectDir`. This will help with multiple things:

- All the tasks `detektGenerateConfig` will not have overlapping outputs.
- If in one project I have enabled a detekt plugin (for example rules for Compose) and in other I don't have it the default configurations should be different in those two projects. With this solution you have as many configurations as modules so that's not an issue any more.

Cons:
- I don't know how many people will want to have a file with more than 700+ repeated in all their modules. For sure I don't want it.
- breaking/behaviour change

How do this solve the problem? It doesn't! But our default behaviour will not generate this issue. And if someone overlaps the output of this task that's their problem. Not detekt's fault 🤷.

---

### Second

Use Build Services and ensure that this tasks never run in parallel.

Pros:
- This error is not going to appear
- This task is **really** fast so the performance impact is really low for a task that shouldn't be called that often
- No breaking change/behaviour change

Cons:
- If someone wants different files in each module we are loosing the parallelism. Not a big deal because this task is fast but...)
- We are just hidding the problem that our current gradle plugin doesn't scale too well with the current size of detekt. (This is not a new topic)

---

I'm going to implement the second option but I'm not 100% happy with it.

**Comment by TWiStErRob** [comment]
Just read your comment and I would like to add to your reasons:

First, con: generating many files in different modules as a result of "generate config" might mislead newcomers to think it's "suggested" to not share the config between modules and need to configure each separately.

Second, pro: since there's no behavior change, it can be improved upon easily in the future; reverted, etc.

Although this second one might be implicitly trivial :)
