### ISSUE TITLE
--base-path not working

### ISSUE THREAD

**Issue by manwinder123** [detekt/detekt#4851]
## Expected Behavior
I am running `detekt --base-path "folderA/FolderB/"` and expect detekt to return all issues for kotlin files inside FolderB and nested folders

## Observed Behavior
It returns all issues for all folders, nest folders, and files in my root folder where I call the command

## Steps to Reproduce
`detekt --base-path "folder"`

I've tried `detekt -bp`, I've used quotes, no quotes, regex, no regex, I've tried `--classpath as well`, I have also tried absolute path.

## Context
Don't want to have to `cd` into every folder to run detekt

## Your Environment
* Operating System and version: Mac OS

**Comment by BraisGabin** [comment]
I think that you are looking for `input` instead of `base-path`.

Probably this issue is related with our documentation. How could we make it more clear?

**Comment by manwinder123** [comment]
I didn't see `input` in the usage list, I think it's clear if I had read it more closely. What would `base-path` be used for? I think having examples of each command (unless the command is super clear like `--parallel`) would be useful, in the readme.

**Comment by cortinico** [comment]
It's used for relative path support. It's described here:
https://detekt.dev/docs/introduction/reporting/#relative-path

Closing as this was resolved, but please let us know if the docs are unclear and if we should update them
