### ISSUE TITLE
Support ignoreAnnotated in ArrayPrimitive rule

### ISSUE THREAD

**Issue by ZacSweers** [detekt/detekt#4853]
The rule or changes you're looking for might have already been suggested!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior of the rule

Currently the rule always requires suppression, but there are some annotation-based scenarios where boxed type arrays must be used, such as in Junit 4's `@Parameterized.Parameters`-annotated functions.

## Context

It would be helpful to be able to suppress functions annotated as such to avoid these false positives.

**Comment by cortinico** [comment]
You should be able to use `ignoreAnnotated` on any rule so it should work with `ArrayPrimitive` as well: https://detekt.dev/docs/introduction/suppressors/#annotation-suppressor

**Comment by ZacSweers** [comment]
Thanks, I didn't realize that. It's not documented in detekt's schema here: https://json.schemastore.org/detekt.json (which is what Studio/IJ indexes)

<img width="406" alt="image" src="https://user-images.githubusercontent.com/1361086/170165316-9065db17-e05a-43c8-b348-27192cc6e915.png">

**Comment by cortinico** [comment]
> It's not documented in detekt's schema here: [json.schemastore.org/detekt.json](https://json.schemastore.org/detekt.json) (which is what Studio/IJ indexes)

yup you're right. The problem is that this schemastore is community maintained and hasn't been updated since 2020: https://github.com/SchemaStore/schemastore/commits/master/src/schemas/json/detekt.json

We should look into doing:
- https://github.com/detekt/detekt/issues/4162
