### ISSUE TITLE
Detekt task outputs are not following Gradle convention

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4856]
## Expected Behavior
Using task output property works as expected (automatic dependency on task).

## Observed Behavior
> Gradle detected a problem with the following location: 'module\build\reports\detekt\detekt.sarif'. Reason: Task ':detektReportMergeSarif' uses this output of task ':module:detekt' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#implicit_dependency for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradle.org/7.4.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

## Steps to Reproduce
/build.gradle.kts:
```kotlin
tasks.register<io.gitlab.arturbosch.detekt.report.ReportMergeTask>("detektReportMergeSarif") {
	output.set(rootProject.buildDir.resolve("reports/detekt/merge.sarif"))
}
```
/module/build.gradle.kts:
```kotlin
val detektReportMergeSarif = rootProject.tasks.named<ReportMergeTask>("detektReportMergeSarif")
tasks.withType<Detekt> {
	detektReportMergeSarif.configure { input.from(this@withType.sarifReportFile) }
}
```
Then execute `gradlew :module:detekt :detektReportMergeSarif`.

## Context
Trying to merge files, and use Gradle best practices.

### Workaround
```
detektReportMergeSarif.configure {
	input.from(this@withType.sarifReportFile)

	mustRunAfter(this@withType)
        // or
	dependsOn(this@withType)
}
```

### Possible fix
Stop creating the property manually without a producer:

https://github.com/detekt/detekt/blob/950554c173cbe09c201107194ca7c2a6f2766549/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/Detekt.kt#L280

instead let Gradle create it for us:

```diff
-open class Detekt
+abstract class Detekt

+@get:Optional
+@get:OutputFile
-val sarifReportFile: Provider<RegularFile>
+absract val sarifReportFile: Provider<RegularFile>
-        @OutputFile
-        @Optional
-        get() = getTargetFileProvider(reports.sarif)
```

and then lazily configure it without resolving the location:
```
sarifReportFile.set(report.outputLocation.map/flatMap { })
```

## Your Environment

* Version of detekt used: 1.20.0
* Version of Gradle used (if applicable): 7.4.2
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/huhzubjvpmsuu
* Operating System and version: N/A
* Link to your project (if it's a public repository): https://github.com/TWiStErRob/net.twisterrob.sun/tree/e2646e3f97de5e9f30abec53a44640c47e4cb9f8

**Comment by TWiStErRob** [comment]
I recently attended a Gradle training by Gradle, and the recommendation was to depend on properties of tasks, and not use `dependsOn` which means this needs to be fixed. Target 2.0? Although it's probably not a breaking behaviour change.

**Comment by cortinico** [comment]
Also this is not a breaking change for me, could be fixed in .23 if neede

**Comment by TWiStErRob** [comment]
Using `ObjectFactory` is not good enough, it (`getTargetFileProvider`) is actually the cause of the problem, see the proposal in OP. It doesn't know about the `Task` at hand, it just creates the right type without any of the wiring as far as I know. When you declare an abstract property as in OP, you get a lot more magic and associates the property with a producer (task). (see `AbstractProperty.getProducer()`)

So because of that it would be a breaking change, because of the `open` to `abstract` change, unless we don't treat Gradle API compilation errors between 1.x versions a breaking change. This wouldn't affect `withType<Detekt>`, but it might cause problems if people extended the task type. Which I would imagine could be very very few usages.

Also the solution to this might be a better task graph setup out of the box, which in scope for 2.0 as we discussed in different places.

**Comment by cortinico** [comment]
> Using `ObjectFactory` is not good enough, it (`getTargetFileProvider`) is actually the cause of the problem, see the proposal in OP. It doesn't know about the `Task` at hand, it just creates the right type without any of the wiring as far as I know. When you declare an abstract property as in OP, you get a lot more magic and associates the property with a producer (task). (see `AbstractProperty.getProducer()`)

Yup you're right in saying that `getTargetFileProvider` is the culprit in calling `objects.fileProperty()`.

I'm unsure though about the top level statement of this issue: `Detekt task outputs are not following Gradle convention`. We're providing `Provider<RegularFile>` which is exactly what Gradle suggests to use. 

> It doesn't know about the Task at hand, it just creates the right type without any of the wiring as far as I know. When you declare an abstract property as in OP, you get a lot more magic and associates the property with a producer (task)

I would rather investigate this further, as I believe we should just wire our tasks properly.  
Similarly, if a user creates custom tasks, they should be responsible for the wiring.
Frankly, I'm not a big fan of the "magic" that Gradle does under the hood for tasks dependencies as it's a bit of a hidden behaviour.

> So because of that it would be a breaking change, because of the `open` to `abstract` change, unless we don't treat Gradle API compilation errors between 1.x versions a breaking change. This wouldn't affect `withType<Detekt>`, but it might cause problems if people extended the task type. Which I would imagine could be very very few usages.
> Also the solution to this might be a better task graph setup out of the box, which in scope for 2.0 as we discussed in different places.

I don't think this should be considered a breaking change.

**Comment by TWiStErRob** [comment]
> I'm unsure though about the top level statement of this issue

Sure the form (syntax, type) is correct, but the behavior is unconventional. As you can see from the warning message, it doesn't fit into the Gradle expectations and need extra hoops to correct the behavior which can be provided out of the box by using the right APIs.

> I would rather investigate this further, 

Do you need a minimal repro that proves this "magic" behavior?

> as I believe we should just wire our tasks properly.
> Similarly, if a user creates custom tasks, they should be responsible for the wiring.

I believe that too, I think the key here is that the property definition is part of the Task. The most scary thing here, is that this behavior will be an error in the future, so better get ahead and fix in advance. In this case, we're the custom task authors (`Detekt` task) and we're responsible for creating our tasks that fit into the Gradle builds well.

> I'm not a big fan of the "magic" that Gradle does under the hood for tasks dependencies as it's a bit of a hidden behaviour.

I agree, but we live in the Gradle ecosystem, so we must understand and use it well. It's actually amazing how much code we can remove if we use the right patterns as Gradle recommends. It's really a declarative (annotation based) API.

> I don't think this should be considered a breaking change.

Good then, I'll try to have a stab at it in the new year if no-one did by then.
(I'll be AFK (IDE) for a few weeks)

**Comment by cortinico** [comment]
> The most scary thing here, is that this behavior will be an error in the future

What specifically? Also do you have a reference for this?

**Comment by TWiStErRob** [comment]
See warning message in OP.

**Comment by cortinico** [comment]
> See warning message in OP. Edited it so no need to scroll :)

Ok but this is limited to the edge case where you create a custom task manually. A setup that uses DGP without custom tasks is not affected by this.

So yes, it's an annoyance but a rather small one frankly.

Still. IMHO If you create custom tasks, you wire them accordingly.

**Comment by TWiStErRob** [comment]
Yes, but we provide users a guidance on how to create those custom tasks: https://detekt.dev/docs/introduction/reporting/#merging-reports

I think this might be an xyproblem... my (and probably a lot of other's) goal is to have one Detekt report in CI in a multi-module project of 40+ modules. For this I have to define a custom task based on the API and guidance provided by Detekt. And then we're faced with the above warning 40+ times over in every build.

I focused on a solution, which should be a simple change to adhere to Gradle's way of creating custom tasks and wiring the Detekt tasks fully, so that others can also build their custom tasks / plugins on top and provide the above described single report. Another solution would be to provide a single report task by the DGP. Or something else, but the DX needs to be improved in some way I think.

**Comment by TWiStErRob** [comment]
Earlier I was meant to send this to highlight the recommended custom task patterns:
https://docs.gradle.org/current/userguide/more_about_tasks.html
Notice the 0 mention of `ObjectFactory` and lots of `abstract` keywords.

I found some docs for `ObjectFactory` here:
https://docs.gradle.org/current/userguide/custom_gradle_types.html#nested_objects

Interestingly they show a similar pattern to Detekt task's here:
https://docs.gradle.org/current/userguide/custom_gradle_types.html#constructor_injection
but they're only showing how to do constructor injection, not how to do properties.

Also found the docs for the "magic":
https://docs.gradle.org/current/userguide/custom_gradle_types.html#configuration_using_properties
oddly enough it says:
> Gradle creates values for managed properties in the same way as `ObjectFactory`.

Through these I found a potential for the magic's implementation:
`AsmBackedClassGenerator` or `ManagedProxyClassGenerator`.
Wanted to see the actual magic bytecode, but couldn't find an easy way yet.

**Comment by cortinico** [comment]
> I think this might be an xyproblem... my (and probably a lot of other's) goal is to have one Detekt report in CI in a multi-module project of 40+ modules. For this I have to define a custom task based on the API and guidance provided by Detekt. And then we're faced with the above warning 40+ times over in every build.

Yup I think the underlying problem is that we should offer top level tasks to:
- Run all tasks
- Merge reports

as those gets asked over and over. The solution can't be to just ask people "create a detetkAll task" which ends up raising those warnings.

**Comment by JavierSegoviaCordoba** [comment]
This is already breaking with Gradle 8:

```
Reason: Task ':detekt' uses this output of task ':foo:compileKotlin' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

Possible solutions:
  1. Declare task ':foo:compileKotlin' as an input of ':detekt'.
  2. Declare an explicit dependency on ':foo:compileKotlin' from ':detekt' using Task#dependsOn.
  3. Declare an explicit dependency on ':foo:compileKotlin' from ':detekt' using Task#mustRunAfter.
```

**Comment by cortinico** [comment]
> This is already breaking with Gradle 8:

Where is this happening? Do you have a repro @JavierSegoviaCordoba? We're on Detekt 8 on our own project and we haven't noticed this problem at all

**Comment by JavierSegoviaCordoba** [comment]
@cortinico I am going to try to create a minimal repro but as I shared on slack:

---

I am having an issue with with the detekt task and Gradle 8.0, this is the setup:
- `:gradle-extensions` (it has no code, it just add more subprojects using api(...), like it was an index of all projects)
- `:gradle-extensions-subprojects:gradle-logging-extensions`

And the error is this one:
```
Reason: Task ':gradle-extensions:detekt' uses this output of task ':gradle-extensions-subprojects:gradle-logging-extensions:spotlessKotlin' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

Possible solutions:
  1. Declare task ':gradle-extensions-subprojects:gradle-logging-extensions:spotlessKotlin' as an input of ':gradle-extensions:detekt'.
  2. Declare an explicit dependency on ':gradle-extensions-subprojects:gradle-logging-extensions:spotlessKotlin' from ':gradle-extensions:detekt' using Task#dependsOn.
  3. Declare an explicit dependency on ':gradle-extensions-subprojects:gradle-logging-extensions:spotlessKotlin' from ':gradle-extensions:detekt' using Task#mustRunAfter.
```

As you can see in the Reason, the `detekt` task is on the `gradle-extensions` module, and the the `spotlessKotlin` in a different module.

**Comment by TWiStErRob** [comment]
That would explain why we didn't see it here, it might be how Spotless rewires things (because it modifies source code, it's output is also input to anything that deals with source code).

I would recommend to start a separate issue. While the warning/error is the same the subjects are very different. Solving one of these will almost definitely not solve the other.

**Comment by JavierSegoviaCordoba** [comment]
@TWiStErRob it is not only happening with Spotless, Kotlin Binary compatibility plugin task (apiBuild) crashes with Detekt too.

**Comment by JavierSegoviaCordoba** [comment]
@cortinico I tried to create a minimal repro but it is working correctly, I will try to investigate my setup deeply.

**Comment by JavierSegoviaCordoba** [comment]
I found the issue, I set my detekt config some years ago and from somewhere I copied `detekt.setSource(...)`. After removing it, it started to work.

**Comment by TWiStErRob** [comment]
To make sure try to force the task execution order:
```shell
./gradlew :gradle-extensions-subprojects:gradle-logging-extensions:clean :gradle-extensions-subprojects:gradle-logging-extensions:spotlessKotlin :gradle-extensions:cleanDetekt :gradle-extensions:detekt --no-configuration-cache --no-build-cache --no-parallel
```
This will make sure(r) that spotless generates the output first, before detekt uses it. This is important so that Gradle can notice the undeclared dependency. We had some with this recently https://github.com/detekt/detekt/pull/5773#discussion_r1101876422

**Comment by JavierSegoviaCordoba** [comment]
@TWiStErRob it works :)

**Comment by caiodev** [comment]
> This is already breaking with Gradle 8:
> 
> ```
> Reason: Task ':detekt' uses this output of task ':foo:compileKotlin' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
> 
> Possible solutions:
>   1. Declare task ':foo:compileKotlin' as an input of ':detekt'.
>   2. Declare an explicit dependency on ':foo:compileKotlin' from ':detekt' using Task#dependsOn.
>   3. Declare an explicit dependency on ':foo:compileKotlin' from ':detekt' using Task#mustRunAfter.
> ```

I am having the same issue with Gradle 8.1.1 and detekt 1.23.0

I just happens when I call it from a KTS task: https://github.com/caiodev/GithubProfileSearcher/blob/edge___often_broken___/tools/codeChecking.gradle.kts

`val codeChecking by tasks.registering { dependsOn("clean", "ktlintFormat", "detekt", "jacocoReport") }`

When I call its Groovy task individually, it works: https://github.com/caiodev/GithubProfileSearcher/blob/edge___often_broken___/tools/detekt.gradle

`apply plugin: 'io.gitlab.arturbosch.detekt'

detekt {
    allRules = true
    buildUponDefaultConfig = true
    config.from(files("${rootProject.projectDir}/config/detekt/detekt.yml"))
    debug = true
    ignoredBuildTypes = ["release"]
    ignoredFlavors = ["production"]
    ignoredVariants = ["productionRelease"]
    parallel = true
    source.from(files(rootProject.projectDir))
    toolVersion = "$detektVersion"
}

tasks.named("detekt").configure {
    reports {
        html.required.set(true)
        md.required.set(false)
        sarif.required.set(false)
        txt.required.set(false)
        xml.required.set(false)
    }
}`

This behaviour is reproducible in this project: https://github.com/caiodev/GithubProfileSearcher/tree/edge___often_broken___

**Comment by TWiStErRob** [comment]
I think this is WAI on both detekt and Gradle side, you're declaring `source.from(files(rootProject.projectDir))`, which means "use everything" as the input, including `build` folders! So based on this info Gradle correctly infers that `detekt` is using the output of **all** tasks, notice the path in all of the errors:
```
 - Gradle detected a problem with the following location: '.../GithubProfileSearcher'.
```
if you exclude those folders, it'll be fine:
```groovy
    source.from(fileTree(rootProject.projectDir) {
        exclude("**/.gradle/")
        exclude("**/build/")
    })
```
It should be also faster, and be more cacheable. You might want to exclude other folders like `.idea` and `.git`. Another alternative is to manually include each `allprojects`'s `src/` and `build.gradle.kts`.
Note: to get the most out of detekt, we recommend using the automatically created tasks like `detektMain` and `detektTest`; these take Android flavour and variant directories into account like you configured `ignore`s for. Read more [here](https://detekt.dev/docs/gettingstarted/type-resolution/).

**Comment by caiodev** [comment]
Awesome. Tysm @TWiStErRob  👍

**Comment by 3flex** [comment]
I'm assigning this to myself changes I'm working on will resolve the originally reported issue.

I'd request that other issues are opened for a built in solution for checking Gradle scripts, since I'm not looking at that specifically at the moment.

There are issues open for report merging already, and my hope is that the new plugin will have a deliberate, consistent strategy for setting up task dependencies on different detekt tasks which resolves some of the issues and confusion with the current setup.

Is there anything I've missed?

**Comment by 3flex** [comment]
Please review #6964 which should fix this.
