### ISSUE TITLE
Error:  The original exception message was: FUN_KEYWORD

### ISSUE THREAD

**Issue by Abhimanyu14** [detekt/detekt#4859]
Execution failed for task ':app:detekt'.
> Analyzing /Users/abhimanyu/Documents/projects/finance-manager/codebase/android/app/src/main/java/com/makeappssimple/abhimanyu/financemanager/android/ui/activity/MainActivity.kt led to an exception. 
  The original exception message was: FUN_KEYWORD
  Running detekt '1.20.0' on Java '16.0.1+9-24' on OS 'Mac OS X'
  If the exception message does not help, please feel free to create an issue on our GitHub page.

## Expected Behavior
`./gradlew detekt` runs and shows the code changes required.

## Observed Behavior
Getting the above mentioned error on executing `./gradlew detekt`

## Your Environment

* Version of detekt used: 1.20.0
* Version of Gradle used (if applicable): 7.2.0
* Gradle scan link (add `--scan` option when running the gradle task): 
* Operating System and version: Mac OS 12.4 
* Link to your project (if it's a public repository): https://github.com/Abhimanyu14/finance-manager

**Comment by Abhimanyu14** [comment]
Detekt version `1.18.1` works fine.

I tried upgrading to `1.20.0` to fix `SpreadOperator` [issue](https://github.com/detekt/detekt/issues/3145)

**Comment by Abhimanyu14** [comment]
Update, 
The issue is not related to detekt version.
Adding detekt formatting causes the issue.

`detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:$rootProject.detektFormattingVersion")`

**Comment by BraisGabin** [comment]
So can we close this? Or is there something we should do here?

**Comment by Abhimanyu14** [comment]
Not sure if this is the right place. 
But why does adding the line `detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:$rootProject.detektFormattingVersion")` cause this issue?

If there is a better place to ask this question, please share where to ask.

**Comment by BraisGabin** [comment]
The `detektFormattingVersion` should be the same as the `detektVersion`. I think that's the issue.

To be clear, there is no need to have exactly the same but between 1.0.0 and 1.21.0 we had some breaking changes (I know, our semver is not "perfect").

**Comment by Abhimanyu14** [comment]
I have both as `1.0.0`.
```
// Detekt formatting
detektFormattingVersion = "1.0.0"

// Detekt compose
detektComposeVersion = "1.0.0"
```

And this is in `dependencies` in the app `build.gradle`.

```
// Detekt formatting
// detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:$rootProject.detektFormattingVersion")

// Detekt compose
detektPlugins("ru.kode:detekt-rules-compose:$rootProject.detektComposeVersion")
```

**Comment by BraisGabin** [comment]
Detekt compose is probably at 1.0.0 but formatting is at 1.20.0

**Comment by Abhimanyu14** [comment]
Thank You @BraisGabin,
Updating `detektFormattingVersion = "1.20.0"` resolved the issue.
