### ISSUE TITLE
Baseline file not working as supposed

### ISSUE THREAD

**Issue by BILLyTheLiTTle** [detekt/detekt#4862]
I have 3 Detekt tasks:

- detektCheck: Checks for the issues
- detektFix: Autocorrect the issues wherever is possible
- detektGenerateBaseline: Generate the baseline file for the issues before using Detekt.
```kotlin
def codeQualityGroupName = "code quality"
def projectSource = file(projectDir)
def detektSource = file("$projectDir/code_quality/detekt")
def configFile = file("$detektSource/config.yml")
def baselineFile = file("$detektSource/baseline.xml")
def kotlinFiles = "**/*.kt"
def resourceFiles = "**/resources/**"
def buildFiles = "**/build/**"

def detektTasksConfiguration = {
    group = codeQualityGroupName
    setSource(projectSource)
    parallel = false
    if (baselineFile.exists()) {
        baseline.set(baselineFile)
        println("Baseline file (${baselineFile.toString()}) found for module $project.name")
    } else {
        println("Baseline file (${baselineFile.toString()}) NOT found for module $project.name")
    }
    if (configFile.exists()) { // does not exist configuration file
        config.setFrom(configFile)
        println("Config file (${configFile.toString()}) found for module $project.name")
    } else {
        println("Config file (${configFile.toString()}) NOT found for module $project.name")
    }
    include(kotlinFiles)
    exclude(resourceFiles, buildFiles)
    reports {
        custom {
            reportId = "DetektGitlabReport"
            destination = file("$buildDir/reports/detekt/gitlab.json")
        }
        html.enabled = true
        xml.enabled = true
        txt.enabled = false
        sarif.enabled = false
    }
}

tasks.register("detektCheck", Detekt) {
    configure detektTasksConfiguration

    description = "Run $name for module $project.name"
    autoCorrect = false
}

tasks.register("detektFix", Detekt) {
    configure detektTasksConfiguration

    description = "Run $name for module $project.name"
    autoCorrect = true
}

tasks.register("detektGenerateBaseline", DetektCreateBaselineTask) {
    description = "Run $name for module $project.name"
    group = codeQualityGroupName
    parallel = false
    ignoreFailures = false
    buildUponDefaultConfig = true
    setSource(projectSource)
    baseline.set(baselineFile)
    if (configFile.exists()) {
        config.setFrom(configFile)
        println("Config file (${configFile.toString()}) found for module $project.name")
    } else {
        println("Config file (${configFile.toString()}) NOT found for module $project.name")
    }
    include(kotlinFiles)
    exclude(resourceFiles, buildFiles)
}

dependencies {
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.20.0")
}
```

## Expected Behavior

With a baseline file it `detektCheck` and `detektFix` should return the same number of weighted issues. This works well with small projects.

## Observed Behavior

`detektCheck` shows that there are no issues to fix (respecting the `baseline.xml`). Then, I run `detektFix` and fixes almost all the issues (does not respect the `baseline.xml`)
Without a baseline `detektCheck` returns 16914 (module A) and 153 (module B) weighted issues.
Without a baseline `detektFix` returns 4618 (module A) and 18 (module B) weighted issues.
With a baseline `detektCheck` returns no weighted issues.
With a baseline `detektFix` at first returns 5310*<sup>1</sup> (module A) and 41*<sup>1</sup> (module B) weights issues. If you re-run `detektFix` returns 1080*<sup>1</sup> (module A) and 8 (module B) weighted issues. If you run it even more times it always returns 1044 (module A) and 8 (module B) weighted issues.

*<sup>1</sup>: _The numbers mentioned here are not consistent and they may vary in every run_

## Steps to Reproduce

Run `detektGenerateBaseline`, then `detektCheck`, the `detektFix` in a big project which generates more than 17000 issues!

## Context

I would like to avoid fixing all existing code styling issues at the moment.

## Your Environment

* Version of detekt used: 1.20.0
* Version of Gradle used (if applicable): `'com.android.tools.build:gradle:7.0.2'` and `https\://services.gradle.org/distributions/gradle-7.0.2-all.zip`
* Gradle scan link (add `--scan` option when running the gradle task): X
* Operating System and version: Win10
* Link to your project (if it's a public repository): X

**Comment by BraisGabin** [comment]
That's not what the baseline does. It doesn't prevent an issue to be "auto-fixed". It only prevent detekt to fail when a known issue is found.

I imagine that all those issues that you talk about are realted with formatting (because that are the only rules that have the "auto-fix" feature. If that's correct I recommend you to don't use the `detekt-formatting` plugin and use `ktlint` directly. That's what detekt uses under the hood. `ktlint` has it's own baseline and I imagine that they support exactly what you are looking for.

I'm keeping this open in case I missunderstood something.

**Comment by BILLyTheLiTTle** [comment]
Apart from the baseline file, when I run `detektCheck` without setting a `config.yml` file it detects 16914. When I run `detektCheck` with the generated config file from `detektGenerateConfig` it detects 4458 issues. It should detect the same amount of issues for the default config, shouldn't it?

**Comment by BraisGabin** [comment]
You are right. This is a side effect from this issue: #4812. It will be fixed in the next release.
