### ISSUE TITLE
Mode or task to ensure configuration file is exhaustive

### ISSUE THREAD

**Issue by dzirbel** [detekt/detekt#4873]
## Expected Behavior
On my team I've found it useful to keep our detekt configuration file as exhaustive as possible, meaning that all rules (and all their configuration) are listed explicitly in the file. This serves a few purposes:
- it is trivial to see what rules are available just by skimming through the file rather than consulting documentation
- on detekt upgrades it is clear which rules/configuration have been added
- project configuration is explicit and potentially more stable than either defaulting to ignoring rules or using defaults with `--build-upon-default-config`

This enforcement could take a number of forms: as a config file setting alongside `validation`, as a CLI argument like `--build-upon-default-config`, or as a standalone gradle task (e.g. `verifyDetektConfigExhaustive`).

## Current Behavior
As far as I know, there's no out-of-the-box way to accomplish this currently. Setting `validation: true` in the YAML checks that no rules/properties are unknown but does not guarantee that all rules/properties are present (from what I've seen). `--build-upon-default-config` is a different approach to keep the configuration file minimal, but actually is the opposite of what I personally would like.

My team currently solves this with a custom gradle task which generates the default config file, parses both the current and default and looks for any properties present in one which is not in the other. This is effective but adds some build overhead and complexity.

I would be happy to prototype a solution but first wanted to get some feedback on the idea and decide which of the above methods might be most appropriate.

**Comment by BraisGabin** [comment]
I agree with you about the pros of a full configuration file. I do the same in all the projects I work on.

What I do to keep them up to date is this https://github.com/detekt/detekt/discussions/3558#discussioncomment-483027

I think that this is related with #4517. I think that we need to find a better way to handle our configuration in general.

**Comment by cortinico** [comment]
> or as a standalone gradle task (e.g. `verifyDetektConfigExhaustive`)

This would be the preferred solution from my point of view. It should be fairly straightforward to implement. I'm more concerned on what @BraisGabin raised: we should probably address the whole config management problem from a more holistic approach (i.e. maybe we need an external tool to handle upgrade/validation)

**Comment by dzirbel** [comment]
My 2c is that the current configuration management works well overall, and with the addition of exhaustive verification has been pretty much all I could ask for. I appreciate the simplicity of having it in a plain YAML file without external tools - would also be happy to try other high-level approaches, but I wouldn't want that to delay lower hanging fruit that we can more easily improve now.

**Comment by marschwar** [comment]
Would it help to have a gradle task that

* detects if there are rules missing
* adds all missing rules with their default active flags
* leaves all other rules untouched

I think this should be possible. In the future it may also be used to allow rule/config property renaming.

**Comment by dzirbel** [comment]
That could work; the main use case I have is as part of a CI process that checks the configuration file is exhaustive - such a task which adds missing rules could pretty easily support that flow by checking whether the config file was modified. I'd probably lean towards having separate tasks, but I don't feel strongly.
