### ISSUE TITLE
`compile-test-snippets` is confusing for new contributors

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4874]
### A bit of context:

Our unit tests contain *a lot* of code snippets. Because, in general, we don't compile that code, it's easy to write code that doesn't compile. That makes that our tests doesn't test what we want. To avoid this problem we compile all the snippets to ensure that they are valid.

Problem: This extra step consumes a lot of execution time making our tests even more slow.

Solution: Because this check is testing the test code (and it's not testing production code) it's ok if we don't run it *every time*. So we just check it on CI.

### Current state

But that solution has a problem! The new contributors are bitten by this on CI and they don't know what's going on (an example is #4872 but we had a lot of these in the past).

### One possible solution

We could configure a "bot" to write a comment explaining this when [the workflow `compile-test-snippets` fails](https://github.com/detekt/detekt/blob/2f5b8f593361615dda1f0acb460afdd014ab460d/.github/workflows/pre-merge.yaml#L75). This will give fast feedback to the contributor about what's going on, why we have this "strange" behaviour and how s/he can reproduce it locally.

This is an issue and it's not a PR because the actions that I found to add that comment doesn't work when the PRs come from fork repository. And that's exactly the case when we want to add that comment.

**Comment by cortinico** [comment]
> We could configure a "bot" to write a comment explaining this when [the workflow `compile-test-snippets` fails](https://github.com/detekt/detekt/blob/2f5b8f593361615dda1f0acb460afdd014ab460d/.github/workflows/pre-merge.yaml#L75). This will give fast feedback to the contributor about what's going on, why we have this "strange" behaviour and how s/he can reproduce it locally.

Follow up here: This is yet another thing than can be easily automated with Danger (see more on this here https://github.com/detekt/detekt/discussions/4696#discussioncomment-2619017).

Essentially, once the CI results are complete, this can be one of the message reports on the PR by danger. Something along the line of "hey the `compile-test-snippets` CI job failed. This is because bla bla bla. You can test locally with bla bla bla".

**Comment by dzirbel** [comment]
A near-ideal solution might be to have `compile-snippet-tests` be enabled by default when running a single test but not the entire test suite; that would make individual changes easier to test with minimal impact and wouldn't slowing down the entire build. I've never tried doing something quite like that, so I'm not sure if it's possible - but might be if we can access the JUnit filters at test runtime.

**Comment by cortinico** [comment]
> be enabled by default when running a single test but not the entire test suite; that would make individual changes easier to test with minimal impact and wouldn't slowing down the entire build. I've never tried doing something quite like that, so I'm not sure if it's possible

That's not really easy as, I suppose, you're running a single test inside the IDE. That's at least what I do. So you'll anyway have to instruct the user on how to configure the run config for that specific test

**Comment by dzirbel** [comment]
> > be enabled by default when running a single test but not the entire test suite; that would make individual changes easier to test with minimal impact and wouldn't slowing down the entire build. I've never tried doing something quite like that, so I'm not sure if it's possible
> 
> That's not really easy as, I suppose, you're running a single test inside the IDE. That's at least what I do. So you'll anyway have to instruct the user on how to configure the run config for that specific test

Yep, that's the same situation I'd like to catch; what I'd ideally like to see is a way to automatically capture the running test context and adjust the snippet compilation accordingly. It's not out of the question, for example:

```
@BeforeEach
fun init(testInfo: TestInfo) {
    val isRunningSingleTest = testInfo.testClass.isPresent || testInfo.testMethod.isPresent
}
```

I believe will be able to capture only test classes/methods run from the IDE (or from the CLI with some arcane configuration I can never remember). But of course we don't want to have this logic in each test; whether there's some way to access this data from `RuleExtensions.shouldCompileTestSnippets` is what I don't know.

**Comment by cortinico** [comment]
That is doable I think, yet I think that modifying the env between running 1 or N tests is not the best practice. It might create frustrations during local development and generally confuse new contributors.

**Comment by dimsuz** [comment]
I'd like to add that one more thing that got me a bit confused while reading detekt source code is that project property `compile-test-snippets` gets transformed into a `compile-snippet-tests` — notice the swapping of last two words. 

Relevant lines are in the same file: [one](https://github.com/detekt/detekt/blob/736524fc0204844db7e3e2d75283461643733879/build-logic/src/main/kotlin/module.gradle.kts#L30), [two](https://github.com/detekt/detekt/blob/736524fc0204844db7e3e2d75283461643733879/build-logic/src/main/kotlin/module.gradle.kts#L35).

Setting the first one will only work in detekt repository and won't work in rule authors' repostories, but setting the system property with the latter name should work in other repositories too (it's actually being read by `detekt-test`).

Maybe uniting them somehow could help here.

**Comment by schalkms** [comment]
Update @cortinico @BraisGabin 
Various improvements have been made in that regard, concluding that this issue is not worth to be left open.
What's your opinion?

**Comment by cortinico** [comment]
> Various improvements have been made in that regard, concluding that this issue is not worth to be left open.
> What's your opinion?

I don't know what's the latest on this matter, but I've seen very fewer reports about `compile-test-snippets` so I believe we can safely close now and potentially re-open if the issue gets reported again
