### ISSUE TITLE
Give visibility to the third-party detekt plugins

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4878]
## Expected Behavior
As a user I want to know which detekt plugins are outthere available to use.

## Current Behavior
Good luck with your prefered search engine!

## Proposed Solution

Use github tags/topics. [This is an example](https://github.com/topics/detekt-rules).

I think that we should add a link like that in our main page and in our README and promote the usage of the that tag/topic.

About which tag I would vote `detekt-plugin`.

## Context
This topic was talked many times already without we finding a good solution. Last time: https://kotlinlang.slack.com/archives/C88E12QH4/p1653997999819649?thread_ts=1652964863.956779&cid=C88E12QH4

**Comment by cortinico** [comment]
That would be great. Ideally we could have a `.json` file inside the website used to render a page with a list of rules.

Using the `detekt-plugin` topic sounds like a good starting point till we come up with some good integration

**Comment by BraisGabin** [comment]
There are two issues with my proposal: 

- Anyone can add `detekt-plugin` to it's repo. I'm not worried about this. Github knows how to order the different plugins and the stars will help a lot here.
- Github != Open Source. I mean, there are people out there using other platforms as Gitlab and I don't think that we should promote the usage of Github over any other alternative.

Event with this issues I think that adding a link to the `detekt-plugin` topic is a quick win right now and we should find a better solution in the future. Any help here is more than welcome.

**Comment by 3flex** [comment]
What about a doc page for third party plugins - with text that encourages those who have created a third party plugin to open a PR to add their project?

Doing it this way means it doesn't matter where the project is hosted. We can populate the page with maybe 5 existing third party plugins plus a link to the `detekt-plugin` GitHub topic to get it started.

We should also have a small disclaimer that we don't specifically endorse those third party plugins.

**Comment by cortinico** [comment]
> What about a doc page for third party plugins - with text that encourages those who have created a third party plugin to open a PR to add their project?

I've done some investigation on this and I'll send over a draft PRs in the near future :)
