### ISSUE TITLE
Too many tests running

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4908]
## Expected Behavior
If I edit a file inside `:detekt-rules-style` only tasks inside that module should be recompiled

## Observed Behavior
https://ge.detekt.dev/s/3pohc2lk24wm4/timeline?outcome=SUCCESS 

Test from other modules as `:detekt-core`, `:detekt-rules` or `:detekt-cli` are executed.

## Steps to Reproduce
- `./gradlew test`
- Modify any file inside `:detekt-rules-style`
- `./gradlew test` and watch the runned tasks

## Your Environment
* Version of detekt used: 1.21.0-RC1 // main
* Gradle scan link: https://ge.detekt.dev/s/3pohc2lk24wm4/timeline?outcome=SUCCESS

**Comment by cortinico** [comment]
> Test from other modules as `:detekt-core`, `:detekt-rules` or `:detekt-cli` are executed.

IMHO That's correct, as a change in the `:detekt-rules-style` content is triggering a change in the test classpath of `:detekt-rules`. This also has a cascading effect on `:detekt-core` and `:detekt-cli`.

**Comment by BraisGabin** [comment]
`:detekt-cli:test` is *really* slow. I'm running now the slowest ruleset because it's huge so `detekt-cli:test` is not in the critical path. But I imagine that for any other rule-set that could be the case.

A change in a rule shouldn't affect `:detekt-core`. But we are using `:detekt-rules` to have "sample" rules to test our own core... I imagine that's the price to pay to avoid lots of Fakes.

Probably this is just a "wont-fix" or even "work as expected" but I wanted to point this out because I wasn't expecting this behaviour.

**Comment by 3flex** [comment]
Does our GE instance give us access to Predictive Test Selection?

https://gradle.com/gradle-enterprise-solutions/predictive-test-selection/

It sounds promising.

**Comment by BraisGabin** [comment]
I think so

**Comment by cortinico** [comment]
Yes it does 👍

**Comment by 3flex** [comment]
I'll close this then, and open a new issue to track enabling PTS.
