### ISSUE TITLE
cleanDetekt* doesn't have the same hierarchy as detekt*

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4941]
## Context
I was trying running detekt locally to clean things up, I kept re-running "cleanly" to get a full picture on every execution in the console:
```
./gradlew cleanDetekt cleanDetektMain cleanDetektTest ; ./gradlew detekt detektMain detektTest detektReportMergeSarif --no-build-cache
```
On one of the executions I noticed that if I don't re-execute detektTest, i.e.
```
./gradlew cleanDetekt cleanDetektMain cleanDetektTest ; ./gradlew detekt detektReportMergeSarif --no-build-cache
```
I get stale data in the merged sarif.

Implementing this request would solve this issue, and reduce? other potential surprises related to this quirk.

## Current Behavior
Just cleans the hook task, but not the individual ones.
```
gradlew :cleanDetektTest
> Task :cleanDetektTest
```

## Expected Behavior
Cleans all the tasks that `:detektTest` would produce by calling the corresponding tasks.
```
gradlew :cleanDetektTest
> Task :cleanDetektDebugUnitTest
> Task :cleanDetektReleaseUnitTest
> Task :cleanDetektDebugAndroidTest
> Task :cleanDetektTest
```

## Extension
This should apply to all hook tasks, like `detektMain` and `detektDebug` (when flavors are in play, I'm guessing.)

**Comment by cortinico** [comment]
What is the `cleanDetekt*` task and where is it defined? I don't think we own it

**Comment by TWiStErRob** [comment]
Every x task gets a cleanX equivalent by default.
Have a look at org.gradle.language.base.internal.plugins.CleanRule
https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_rules

**Comment by TWiStErRob** [comment]
Hmm, reading the code of CleanRule this is infeasible as the task is not created until right before it's executed.
