### ISSUE TITLE
Detekt in Android project: How can I enable it for xml layout files?

### ISSUE THREAD

**Issue by Pabloku** [detekt/detekt#4957]
### Discussed in https://github.com/detekt/detekt/discussions/4956

<div type='discussions-op-text'>

<sup>Originally posted by **Pabloku** June 14, 2022</sup>
Hi!

I'd like to create a custom rule to check that every activity layout xml file has a property defined in its parent container. To be able to do that, first I need Detekt to be run over src/main/res/layout/*.xml files. I tried using setSource in my detekt.gradle file but it didn't work.
Any ideas on how to do this?

Thanks very much,

Pabloku</div>

**Comment by 3flex** [comment]
Asked and answered in #4956
