### ISSUE TITLE
Deprecate Detekt's rules around when expression because compiler fails by default

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#4973]
_Originally posted by @BraisGabin in https://github.com/detekt/detekt/pull/4821#pullrequestreview-1003604675_
- DuplicateCaseInWhenExpression
- ElseCaseInsteadOfExhaustiveWhen
- MissingWhenCase
- RedundantElseInWhen

**Comment by cortinico** [comment]
In generally I agree with those deprecation. Still users on older version of Kotlin, might still benefit from them.

**Comment by VitalyVPinchuk** [comment]
Hi! I'd like to work on this
