### ISSUE TITLE
MaxChainedCallsOnSameLine fails on import statements.

### ISSUE THREAD

**Issue by NickButcher1** [detekt/detekt#5014]
## Expected Behavior
detekt should not report any errors.

## Observed Behavior
detekt reports the following for every import statement with 6 or more dots.
MaxChainedCallsOnSameLine - [6 chained calls on a single line; more than 5 calls should be wrapped to a new l(...)] at

## Steps to Reproduce
Update from 1.21.0-RC1 to 1.21.0-RC2 and add this config
  MaxChainedCallsOnSameLine:
    active: true
    maxChainedCalls: 5

## Context
Trying to enable the new MaxChainedCallsOnSameLine rule.

## Your Environment

* Version of detekt used: 1.21.0-RC2.
* 7.4.2
* Operating System and version: Windows 11.

**Comment by BraisGabin** [comment]
@dzirbel could you check this?

**Comment by dzirbel** [comment]
Thanks for the report - this is definitely an issue (along with `package` directives) which should be easy enough to fix in #5020.

**Comment by TWiStErRob** [comment]
Sorry @BraisGabin, found it, didn't look deep enough 😅. I think this issue can be closed as the PR is merged.

**Comment by BraisGabin** [comment]
You are right! Thanks
