### ISSUE TITLE
Add ending line and column to `Location.kt`

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#5025]
External tooling, such SARIF or IDE may need ending lines and columns, in addition to the `SourceLocation`. They should be provided in `:detekt-api`.

_Originally posted by @BraisGabin in https://github.com/detekt/detekt/pull/5011#discussion_r911449557_

**Comment by VitalyVPinchuk** [comment]
Hello!
May I work on this?

**Comment by 3flex** [comment]
Thanks @VitalyVPinchuk, of course you can!
