### ISSUE TITLE
Extend ReportMergeTask for md & HTML

### ISSUE THREAD

**Issue by kvn-stgl** [detekt/detekt#5034]
## Expected Behavior

I would like to use the Markdown Report (#4858) in projects with multiple modules. 

For this, I would like to extend the ReportMergeTask to work also with markdown files. Sadly, this is kind of a problem: We can not simply parse the markdown reports because it's just text.

### Idea
An idea would be to implement a new output generator like `SerializedOutput` which just serializes the `Detektion`-object and extend the ReportMergeTask to generate an MD file out of the serialized `Detektion`-object.

I'm not really happy with this solution but I haven't another idea about how to get a merged markdown report (and maybe we can also use this for the txt/html output).

## Your Environment
Version of detekt used: 1.21.0-RC2
Version of Gradle used (if applicable): 7.4.2

**Comment by 3flex** [comment]
Related to #4827

**Comment by BraisGabin** [comment]
Also related with #4289. If the Detekt task generates a single report or serializes the Detektion list this and other tasks would be more easy. Probably SARIF could be that base report.

The idea detekt-core > SARIF? > Reports (single, merged, baselines, etc)

This would work extremely well with gradle. But this is a huge refactor.

**Comment by 3flex** [comment]
Yeah that's basically what JaCoCo does, as an example.

**Comment by JavierSegoviaCordoba** [comment]
Html is not working too

**Comment by 3flex** [comment]
I propose closing this as "not planned" - see here for rationale: https://github.com/detekt/detekt/issues/5041#issuecomment-2366754443

**Comment by BraisGabin** [comment]
I agree. I close this. If other maintainers think different we can reopen.
