### ISSUE TITLE
continuationIndentSize in formatting

### ISSUE THREAD

**Issue by BILLyTheLiTTle** [detekt/detekt#5038]
## Expected Behavior

Option `continuationIndentSize` is missing.

## Observed Behavior

In v.1.21.0-RC2 the `continuationIndentSize` under `formatting` is missing.

## Steps to Reproduce

Generate config with v.1.21.0-RC2 and search for `continuationIndentSize`.

## Context

I would like to configure `continuationIndentSize`.

## Your Environment

* Version of detekt used: 1.21.0-RC2
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by BraisGabin** [comment]
As far as I know that configuration doesn't exist on ktlint.

**Comment by cortinico** [comment]
Yup that property got removed inside KtLint and we deprecated it in 1.20: #4551
