### ISSUE TITLE
RFC: Enable Kotlin's new approach to incremental compilation

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5049]
## Expected Behavior
Kotlin's incremental compilation can be used alongside Gradle's build cache.

## Current Behavior
We use build cache, which disables Kotlin's incremental compilation. This is a problem in Kotlin 1.6.21 and earlier.

## Context
Kotlin 1.7 has [a new approach to incremental compilation﻿](https://kotlinlang.org/docs/whatsnew17.html#a-new-approach-to-incremental-compilation). [Initial impressions](https://twitter.com/ZacSweers/status/1534944410084986880) are positive, and an issue with occasional corruption of the IC status has been fixed in Kotlin 1.7.10.

This promises significant savings when compilation is required, and likely will help with https://github.com/detekt/detekt/issues/4908, since there will be fewer dependent tasks running which will avoid triggering test tasks.

However, this feature is experimental, and JetBrains recommend using it for evaluation only. I think the pros outweigh the cons, we should enable this, and if we find new issues we can easily turn it off and wait for fixes in newer Kotlin versions, but looking for comments first.

**Comment by BraisGabin** [comment]
I agree. This doesn't affect our users.
