### ISSUE TITLE
Links to ktlint website in detekt documentation are broken or unhelpful.  

### ISSUE THREAD

**Issue by doug-turo** [detekt/detekt#5054]
## Expected Behavior
https://detekt.dev/docs/rules/formatting/ explains what the out-of-the-box rules do.

## Observed Behavior
Every item at https://detekt.dev/docs/rules/formatting/ contains the line, "See ktlint-website for documentation.", with a link to https://ktlint.github.io.  But the ktlint website only contains examples of 10 rules, and does not tell you what the names of those rules are.  

## Steps to Reproduce
Open https://detekt.dev/docs/rules/formatting/ and click on a few of the "See ktlint-website for documentation." links.

## Suggestion
The readme at https://github.com/pinterest/ktlint provides more helpful documentation, and might be a better place to send users.

**Comment by schalkms** [comment]
I guess this should change as described in the initial post.
The readme is more up to date than the web site.
