### ISSUE TITLE
`ReturnCount.excludedFunctions` should be a `List<String>` instead of a `String`

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#5063]
## Expected Behavior
`ReturnCount.excludedFunctions` should be a `List<String>`

## Observed Behavior
It is a `String`.

## Context
#5062

## Your Environment
* Version of detekt used: main/1.21.0-RC2

**Comment by marschwar** [comment]
Maybe it should be valueAndReason?

**Comment by gouri-panda** [comment]
@BraisGabin Can I try this one :)
