### ISSUE TITLE
Could not resolve Kotlin Compiler Embeddable after upgrade to 1.21.0

### ISSUE THREAD

**Issue by javiyt** [detekt/detekt#5091]
## Expected Behavior

After upgrade Detekt should work

## Observed Behavior

Error is thrown:
```
> Could not resolve all files for configuration ':detekt'.
   > Could not resolve org.jetbrains.kotlin:kotlin-compiler-embeddable:1.6.21.
     Required by:
         project : > org.springframework.boot:spring-boot-dependencies:2.7.1
         project : > io.gitlab.arturbosch.detekt:detekt-cli:1.21.0 > io.gitlab.arturbosch.detekt:detekt-parser:1.21.0
         project : > io.gitlab.arturbosch.detekt:detekt-cli:1.21.0 > io.gitlab.arturbosch.detekt:detekt-tooling:1.21.0 > io.gitlab.arturbosch.detekt:detekt-api:1.21.0
         project : > io.gitlab.arturbosch.detekt:detekt-cli:1.21.0 > io.gitlab.arturbosch.detekt:detekt-parser:1.21.0 > io.gitlab.arturbosch.detekt:detekt-psi-utils:1.21.0
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-compiler-embeddable' that satisfies the version constraints:
           Dependency path ':myproject:unspecified' --> 'io.gitlab.arturbosch.detekt:detekt-cli:1.21.0' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-compiler-embeddable:{strictly 1.6.21}'
           Constraint path ':myproject:unspecified' --> 'org.jetbrains.kotlin:kotlin-bom:1.7.10' (enforced-platform-runtime) --> 'org.jetbrains.kotlin:kotlin-compiler-embeddable:1.7.10'
           Constraint path ':myproject:unspecified' --> 'org.springframework.boot:spring-boot-dependencies:2.7.1' (platform-runtime) --> 'org.jetbrains.kotlin:kotlin-compiler-embeddable:1.6.21'
           Dependency path ':myproject:unspecified' --> 'io.gitlab.arturbosch.detekt:detekt-cli:1.21.0' (runtimeElements) --> 'io.gitlab.arturbosch.detekt:detekt-parser:1.21.0' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-compiler-embeddable:1.6.21'
           Dependency path ':myproject:unspecified' --> 'io.gitlab.arturbosch.detekt:detekt-cli:1.21.0' (runtimeElements) --> 'io.gitlab.arturbosch.detekt:detekt-tooling:1.21.0' (runtimeElements) --> 'io.gitlab.arturbosch.detekt:detekt-api:1.21.0' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-compiler-embeddable:1.6.21'
           Dependency path ':myproject:unspecified' --> 'io.gitlab.arturbosch.detekt:detekt-cli:1.21.0' (runtimeElements) --> 'io.gitlab.arturbosch.detekt:detekt-parser:1.21.0' (runtimeElements) --> 'io.gitlab.arturbosch.detekt:detekt-psi-utils:1.21.0' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-compiler-embeddable:1.6.21'
```

## Steps to Reproduce

* Upgrade detekt from 1.20.0 to 1.21.0
* Run detekt

## Context

Dependabot opened a PR in a project we have to upgrade detekt version from 1.20.0 to 1.21.0, we are using kotlin 1.7.10

## Your Environment

* Version of detekt used: 1.21.0
* Version of Gradle used (if applicable): 7.5
* Gradle scan link (add `--scan` option when running the gradle task): can't provide one cause is a private project
* Operating System and version: Mac OS X 12.4
* Link to your project (if it's a public repository): can't provide one cause is a private project

**Comment by 3flex** [comment]
I can't confirm without your build files but this is almost certainly happening because kotlin-bom enforced platform is being applied to all configurations in the build, including the "detekt" configuration.

detekt relies on a specific version of kotlin-compiler-embeddable, and that specific  dependency version is now strictly enforced in the "detekt" Gradle configuration.

Gradle is reporting the conflict between the version detekt needs and the enforced platform override applied in your project.

You'll need to stop the kotlin-bom dependency from being applied to the "detekt" configuration.

**Comment by javiyt** [comment]
yep, I could run the detect task removing the constraint that enforced kotlin version. Thanks for pointing it out.
