### ISSUE TITLE
Sarif: Customize level

### ISSUE THREAD

**Issue by hfhbd** [detekt/detekt#5094]
## Expected Behavior
An option to set the level from warning to error

## Current Behavior
No option, all results are warning,

## Context
I use detekt with GitHub Actions. If I run `detekt` and the Gradle task failed with violations, this build action failed and is red. The uploaded sarif action results into a green successfully run, because the report only contains warnings, no errors.
I would expect a red and failing code scanning status. 
<img width="829" alt="Bildschirm­foto 2022-07-18 um 23 42 59" src="https://user-images.githubusercontent.com/22521688/179622663-164baa7a-1323-4650-9e4a-89a4fec4d555.png">

**Comment by cortinico** [comment]
This is another occurrence of our lack of support for Severity: https://github.com/detekt/detekt/discussions/4895#discussioncomment-2870899

@chao2zhang do you recall if Sarif has some extra support for error/warnings?

**Comment by chao2zhang** [comment]
I believe the severity is configurable at a ruleset level or at a rule level https://github.com/detekt/detekt/issues/3274

**Comment by hfhbd** [comment]
> I believe the severity is configurable at a ruleset level or at a rule level #3274

Okay, but it is not possible to change the severity for all warnings: eg `warningsAsError`/`WError`?

**Comment by chao2zhang** [comment]
It's not possible through a single command line arg or a single line of config.yml at the moment. https://github.com/detekt/detekt/discussions/3942#discussioncomment-990805

**Comment by hfhbd** [comment]
Okay, at least for GitHub you can change the level in the settings:
<img width="800" alt="Bildschirm­foto 2022-08-09 um 15 50 57" src="https://user-images.githubusercontent.com/22521688/183666676-032813f0-47e0-415f-9109-967b332f0a9e.png">

**Comment by BraisGabin** [comment]
Can we close this?

**Comment by hfhbd** [comment]
Okay
