### ISSUE TITLE
DetektGenerateConfigTask does not respect custom config locations in 1.21.0

### ISSUE THREAD

**Issue by dzirbel** [detekt/detekt#5097]
## Expected Behavior
Setting the `config` input on a custom `DetektGenerateConfigTask` should change the location where the config file is generated.

## Observed Behavior
The default configuration file is still created at the default location of `config/detekt/detekt.yml`.

## Steps to Reproduce
```
tasks.register("customDetektConfig", DetektGenerateConfigTask::class) {
    config.setFrom("custom/location.yml")
}
```

## Context
My team uses a custom task to create a default configuration at a custom location and compare it to the current configuration, in order to find differences between the two (see #4873). Specifying a custom location for this default configuration is convenient to make sure it can also be deleted later on.

Interestingly there don't seem to be any changes to [DetektGenerateConfigTask](https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektGenerateConfigTask.kt) in 1.21.0, but I can reproduce this issue reliably after upgrading from 1.20.0 to 1.21.0 in my team's project.

## Your Environment
* Version of detekt used: 1.21.0
* Version of Gradle used (if applicable): 7.5

**Comment by BraisGabin** [comment]
Just to be clear, this is a regression, right?

**Comment by dzirbel** [comment]
Correct, it worked as expected in 1.20.0.
