### ISSUE TITLE
Control exit code by issue severity

### ISSUE THREAD

**Issue by nuth** [detekt/detekt#5104]
## Expected Behavior
I'd like to configure detekt to exit with a non-zero exit code if there are any findings with a severity level of `error`.

You could also make this configurable to say for instance if you have 10 errors, the build fails, or if you have 50 warnings the build fail etc.

Any issues with a severity level of `info` should never fail the build.

## Current Behavior
Currently you can only control the max issues that causes the build to fail.

## Context
I'd like to differentiate between what rules are hard requirements (`error`), which are encouraged (`warning`) and those who are purely nice to know (`info`).

**Comment by cortinico** [comment]
I don't think this is doable out of the box as Severity is essentially unimplemented in Detekt (see https://github.com/detekt/detekt/discussions/4895#discussioncomment-2870899)

**Comment by BraisGabin** [comment]
I'm wonderig if we should improve our implementation of seveity or if we should remove that severity concept completely from detekt. I don't see value to have different severities. If you have a rule you want to follow or ignore it. But we know that the warnings only add noise and nearly no one use them.

**Comment by marschwar** [comment]
I am with Brais I guess. If you don't think a rule is worth breaking your build - disable it.

But I can see your point as well. Should we assign a severity to each rule and allow users to change it globally, per rule set and per rule?

**Comment by nuth** [comment]
Hmm, from what I can tell you can already adjust the severity for each rule https://github.com/detekt/detekt/issues/3274 I've also tested this and it seems to work?

I also see the point about generating noise, but at the same time if you use detekt together with for instance sonarqube, you have the option to discuss an issue and ignore it on a per instance basis. 

With sonarqube you also have the ability to fail a build  based on new code only, meaning you can have setup with some absolute requirements handled by detekt (severity `error`) which will fail the build even if it's code you haven't touched, and then the rest set to `warning` which would only apply to new code. This use case is very relevant for existing projects that are just starting using detekt and want to avoid fixing everything then and there while still getting the insights.

**Comment by marschwar** [comment]
Thank you for pointing that out. i was not aware of it.

> This use case is very relevant for existing projects that are just starting using detekt and want to avoid fixing everything then and there while still getting the insights.

With regards to new code, you could use [the baseline feature](https://detekt.dev/docs/introduction/baseline).

**Comment by nuth** [comment]
> With regards to new code, you could use [the baseline feature](https://detekt.dev/docs/introduction/baseline).
Considered that already, but I really want the information reported to sonarqube... sitting in the baseline the issues will be a bit too hidden away and also it won't discriminate between hard requirements and the ones that should be applied to new code only.

I appreciate the suggestion though.

**Comment by BraisGabin** [comment]
I assume that you mean old code, right @marschwar? The baseline feature is great to introduce detekt to an already existing project.

**Comment by BraisGabin** [comment]
Closing as this feature doesn't seems to fit on detekt. We already have other solutions for that type of use cases.

**Comment by jbarr21** [comment]
@BraisGabin can we revisit this issue now that there is a kotlinc compiler plugin integration? right now the compiler plugin only [reports issues as Kotlin warnings](https://github.com/detekt/detekt/blob/d1933ab4b09bd367aaa8c068a587c2b192976633/detekt-compiler-plugin/src/main/kotlin/io/github/detekt/compiler/plugin/internal/MessageCollectorExtensions.kt#L28-L29), but ideally we can have a way to fail the build via reporting kotlin errors (in a similar fashion to ErrorProne)

**Comment by marschwar** [comment]
As a matter of fact, we are currently revisiting the severity concept for detekt. See #6383 

Please do join the conversation there.
