### ISSUE TITLE
XML report is empty

### ISSUE THREAD

**Issue by anticafe** [detekt/detekt#5113]
## Expected Behavior
When XML report is enabled, then the report should not be empty.

## Observed Behavior
But I notice for now the XML report is empty (`<?xml version="1.0" encoding="UTF-8"?><checkstyle version="4.3"></checkstyle>`).

## Steps to Reproduce
I use the sample code (https://github.com/arturbosch/kutils) which is listed in the ReadMe.
The, enable the XML report
```
detekt {
  reports.xml.enabled = true
}
```

## Context
Since the per-module XML report is empty, the merging report is also empty.

## Your Environment
* Version of detekt used: 1.19.0 (but I try 1.21.0-RC1 and still got the same issue)
* Version of Gradle used (if applicable): 7.5.0
* Operating System and version: MacOS
* Link to your project (if it's a public repository): https://github.com/arturbosch/kutils

**Comment by cortinico** [comment]
A couple of things to note here:
- You're not configuring reports correctly. The correct way is documented here: https://detekt.dev/docs/gettingstarted/gradle#reports
- The XML report is empty if there are no findings. Are you sure there are findings in your project but they're omitted in the report?

**Comment by anticafe** [comment]
Hi @cortinico 
1. Yes I also try to use the new detekt configuration, but see the same result.
```
tasks.named("detekt").configure {
        reports {
            xml.required.set(true)
            xml.outputLocation.set(file("build/reports/detekt.xml"))
            html.required.set(true)
            html.outputLocation.set(file("build/reports/detekt.html"))
            txt.required.set(false)
            txt.outputLocation.set(file("build/reports/detekt.txt"))
            sarif.required.set(false)
            sarif.outputLocation.set(file("build/reports/detekt.sarif"))
        }
    }
```
2. Here is the HTML report.  Although there is no finding, but there are Metrics & Complexity Report.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/340836/180468501-326e9369-a31d-4407-bde0-1aa98489e093.png">

**Comment by marschwar** [comment]
There you go. There are nö findings. The [XML report](https://github.com/detekt/detekt/blob/main/detekt-report-xml/src/main/kotlin/io/github/detekt/report/xml/XmlOutputReport.kt) does not include the complexity metrics.

**Comment by anticafe** [comment]
🥲  Got it. Thank you @marschwar .
@cortinico Should we update the documentation to clarify which info would be show in the HTML, XML.. report?

**Comment by marschwar** [comment]
The [documentation](https://detekt.dev/docs/introduction/reporting/#formats) states that it is checkstyle compatible. Do you think we need to describe what all it does NOT contain?

**Comment by anticafe** [comment]
@marschwar Yeah, it's a bit misunderstanding. Since I mostly work with Kotlin, CheckStyle (for Java) is quite new to me. Detekt documentation of HTML, TXT and MD is very clear on which information to display. However, XML & SARIF is not as clear as HTML.

**Comment by 3flex** [comment]
XML and SARIF formats are designed to be machine- rather than human-readable, so I don't think we need to add anything to the docs - that's already stated plainly for the XML report description. The SARIF report description doesnt explicitly say it's designed to be machine-readable, but it does say it's a JSON format and supported by GitHub code scanning so it's clear what it's for.

I don't think there's anything else to do here.
