### ISSUE TITLE
`UseRequire` relies on type resolution without declaring it

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#5145]
While working on a fix for #5125, I realized that the `UseRequire` rule uses the `BindingContext` to determine whether there is a non-string parameter that is passed to the exception constructor. By doing so this rule behaves differently if run with or without type resolution. Additionally it is not marked with `@RequiresTypeResolution` (same for `UseCheckOrError`).

```kotlin
fun x(a: Int, e: Exception) {
    val message = "a message"
    if (a == 0) throw IllegalArgumentException() // -> always flagged
    if (a == 1) throw IllegalArgumentException("message") // -> always flagged
    if (a == 2) throw IllegalArgumentException("message", e) // -> never flagged
    if (a == 3) throw IllegalArgumentException(message) // -> flagged with type resolution only
    if (a == 4) throw IllegalArgumentException(e) // -> never flagged
    doSomething()
}
```

I think we should avoid rules to behave differently with and without type resolution and here I do not see much benefit of the additional case. I vote to remove the usage of the binding context.

In any event all rules that use the binding context should be marked appropriately.

**Comment by BraisGabin** [comment]
Related with #2994.

I would approve a PR that makes `UseRequire` and `UseCheckOrError` pure type resolution rules (I mean, they report nothing without type resolution.

**Comment by marschwar** [comment]
I think both could still remain rules without type resolution. We would only have one false negative edge case. But everyone would benefit from the rule. I do not see the benefit of type resolution for these two rules.

**Comment by cortinico** [comment]
> I vote to remove the usage of the binding context.

I'm in for this. Don't have a strong opinion on TR vs no-TR for this specific case. If possible, having non-TR rules opens them for a broader audience.
