### ISSUE TITLE
ComplexInterface: do not count method overloads

### ISSUE THREAD

**Issue by pinguinjkeke** [detekt/detekt#5165]
The rule or changes you're looking for might have already been suggested!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior of the rule
It will be nice if `ComplexInterface` rule will have a `skipOverloadMethods` option.

If the option is on, it will count overloaded methods as 1.

**Comment by cortinico** [comment]
Makes sense. I would probably call the parameter `ignoreOverridden` to be consistent with other rules

**Comment by pt2121** [comment]
Can I take a stab at this?
