### ISSUE TITLE
Rule: detect 'also' library function misuse instead of 'apply'

### ISSUE THREAD

**Issue by Mishkun** [detekt/detekt#518]
Lurking codebases came across this kind of pattern (example is obfuscated to not to mess with details):
```kotlin
inline fun foo(block: Buzz.() -> Unit): Buzz =
    Buzz().also {
      it.init()
      it.block()
    }
```
Which is misused `also` pattern and surely can be simplified to:
```kotlin
inline fun foo(block: Buzz.() -> Unit): Buzz =
    Buzz().apply {
      init()
      block()
    }
```
The suggested rule is _"when an `also` block contains only it-started expressions, simplify it to the `apply` block"_

Probably, this pattern also applies to the `let` - `run` pair, although I could not get with the real-world example, so this is the mirrored one:
```kotlin
inline fun foo(block: Buzz.() -> T): T =
    Buzz().let {
      it.init()
      it.block()
    }
```
Correct usage:
```kotlin
inline fun foo(block: Buzz.() -> T): T =
    Buzz().run {
      init()
      block()
    }
```

**Comment by adelnizamutdinov** [comment]
the reason `also` exists is `this`
you can have outer `this@outer` and inner `this`
this becomes very messy very quickly

with `also` & `let` you can name your stuff. So this is not about simplicity or aesthetics

**Comment by Mishkun** [comment]
@adelnizamutdinov This rule is about simplification of non-nested structures, like in the example. no problemo with this@whatever in this case
