### ISSUE TITLE
Timeouts on predective test selection

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#5181]
## Expected Behavior
When I run tests the predective feature shouldn't throw a timeout

## Observed Behavior
I'm getting time outs

## Steps to Reproduce
Just run `./gradlew test` after some changes

## Context
I think our GE instance blow up because of my predictive-test request to it. After the build I clicked on the scan link and the server was not responsive. After a minute or so it reboots itself.

I'm not asking to disable it. I just want to report it if someone else get the same error or this is just a single event. (But to be honest I got the same issue yesterday but I was too lazy to report it)

## Your Environment
* Version of detekt used: main
* Gradle scan link: https://ge.detekt.dev/s/nsdwojjie3qh2

**Comment by 3flex** [comment]
Can you include the timeout error from the log next time you hit this?

**Comment by BraisGabin** [comment]
https://ge.detekt.dev/s/nsdwojjie3qh2/console-log#L271 Here you can see those timeout errors.

I talked with people from GE and they gave us more RAM to our instance. Maybe that was the problem.

**Comment by BraisGabin** [comment]
I think the RAM was the issue, I can't reproduce this issue anymore so I'm closing this :)
