### ISSUE TITLE
Forbid constructor calls

### ISSUE THREAD

**Issue by jcopenhop** [detekt/detekt#5185]
## Expected Behavior of the rule

Forbid the usage of a constructor like the same way we have `ForbiddenMethodCall`.

## Context
I'd like to prevent the usage of the `java.math.BigDecimal(double)` constructor. See https://stackoverflow.com/a/7186298 for explanation.

**Comment by cortinico** [comment]
> I'd like to prevent the usage of the `java.math.BigDecimal(double)` constructor

Out of curiosity: have you tried using `ForbiddenMethodCall` for this?

**Comment by BraisGabin** [comment]
I checked, right now it's not possible. I just created #5195 to address it inside `ForbiddenMethodCall`.
