### ISSUE TITLE
Website search is broken for rules

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5200]
## Steps to Reproduce
1. https://detekt.dev
2. search for UseCheckOrError

## Expected Behavior
As last week, finds and opens https://detekt.dev/docs/rules/style/#usecheckorerror.

## Observed Behavior
![image](https://user-images.githubusercontent.com/2906988/183309490-98c7ec47-9c44-4a67-9411-9123214c9c26.png)

## Context
For rule identifiers for sure it's not finding them, not sure about other types of docs as I usually search for names of rules.

## Your Environment
Windows 10, latest Chrome 103.0.5060.134.

**Comment by cortinico** [comment]
Now it's fixed. I recreated the Algolia index. Thanks for reporting it 👍
![Screenshot 2022-08-08 at 20 54 27](https://user-images.githubusercontent.com/3001957/183502904-9c3e8268-4a4c-48e8-a13b-93ee6c4538ad.png)
