### ISSUE TITLE
Commenting on GitHub sends Danger failures

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5201]
## Expected Behavior
Crickets.

## Observed Behavior
![image](https://user-images.githubusercontent.com/2906988/183310670-a0fcbed5-89e1-465b-b0f7-b48104d4f652.png)

## Steps to Reproduce
Comment on an existing issue. e.g. this one. And then look in your inbox.

## Context
It's not only me, @BraisGabin also confirmed seeing these emails. Failures are visible in Actions:
https://github.com/detekt/detekt/actions/workflows/danger.yaml?query=is%3Afailure
Based on history this issue is about 2 days old, see last page of above list.

**Comment by TWiStErRob** [comment]
Oh, this is it:
https://github.com/detekt/detekt/blob/0d42e58e1087ac5bffcc0a125d707efbd9bced88/.github/workflows/danger.yaml#L4

introduced by https://github.com/detekt/detekt/pull/5194 cc @cortinico @schalkms

**Comment by cortinico** [comment]
Yup my bad. I haven't seen those mails as I have emails disabled for Github. #5202 is the fix
