### ISSUE TITLE
detekt doesn't respect ktlint `RunAfterRule` constraints

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5259]
## Expected Behavior
detekt runs ktlint rules in the order that ktlint expects.

## Observed Behavior
ktlint has a few different visitor modifiers that add constraints to the order rules are run in.

detekt checks and respects `RunAsLateAsPossible` and `RunOnRootNodeOnly` constraints, but does not check `RunAfterRule`. This can affect results when using autocorrect and individual rules aren't run in the correct order.

See https://github.com/pinterest/ktlint/blob/0.46.1/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/Rule.kt#L39-L60

## Steps to Reproduce
I don't have a reproducer, but discovered this when doing some other work on the formatting rule set.

## Context
Can affect autocorrect.

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by schalkms** [comment]
Interesting…
I remember a few bug reports regarding auto-correct. It’s good that we finally discovered the reason for it.
Do you have any ideas how we can fix it in detekt?

**Comment by 3flex** [comment]
Probably reimplementing some version of https://github.com/pinterest/ktlint/blob/master/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/RuleRunnerSorter.kt (used in 0.47, in 0.46 the class is `RuleSorter`) and sorting rules accordingly.

**Comment by 3flex** [comment]
Not stale
