### ISSUE TITLE
MissingPackageDeclaration not active since 1.21.0

### ISSUE THREAD

**Issue by mi0x** [detekt/detekt#5268]
## Expected Behavior
Looking at the published changelogs of 1.21.0 it is mentioned that ~30 rules are now enabled by default. 
When looking at the referred Pull Request (https://github.com/detekt/detekt/pull/4875) I see that the `MissingPackageDeclaration` rule is mentioned as one of those, however, is seems that it is not active by default when looking at the documentation (https://detekt.dev/docs/rules/potential-bugs/#missingpackagedeclaration) or trying it out by purposely violating the rule.

I want to make sure if this was reverted by accident or not.

## Observed Behavior
The `MissingPackageDeclaration` rule is not active by default.

## Steps to Reproduce

- Configure to use the 1.21.0 version of Detekt
- Delete the `MissingPackageDeclaration` from the Detekt configuration
- Create a new class without declaring the package in the file
- Run Detekt

## Context

I was using the changelog to update our config files, I saw a mismatch between the information there and the information in the documentation.

## Your Environment
* Version of detekt used: 1.21.0

**Comment by 3flex** [comment]
It was disabled in the end, see https://github.com/detekt/detekt/pull/4900 & https://github.com/detekt/detekt/commit/87f32e117e932b34566338cfbb6d383ccc219641

I've updated the PR description in #4875 to reflect this - thanks for pointing this out!
