### ISSUE TITLE
Elements accept and respect a Modifier parameter in Jetpack Compose

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#5276]
Relevant convention:
https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md#elements-accept-and-respect-a-modifier-parameter

Rule constraints that is reasonable to implemented in Detekt:
- Element functions MUST accept a parameter of type Modifier. 
- This parameter MUST be named "modifier" and MUST appear as the first optional parameter in the element function's parameter list. 
- Element functions MUST NOT accept multiple Modifier parameters
- Element functions MUST provide their modifier parameter to the Compose UI node they emit by passing it to the root element function they call. If the element function directly emits a Compose UI layout node, the modifier MUST be provided to the node.
- Element functions MUST NOT concatenate additional modifiers to the beginning of the received modifier parameter before passing the concatenated modifier chain to the Compose UI node they emit.

**Comment by BraisGabin** [comment]
Detekt should be framework independent so I don't think we should implement this. But there is already a rule set that implements nearly all of those: https://github.com/appKODE/detekt-rules-compose

I use it on my project and it works great. I think that this issue should be open there with the missing parts that are not yet implemented.

**Comment by cortinico** [comment]
Agree on @BraisGabin message.
If we really wish, we can create a detekt/detekt-compose repo using the rules template and keep those rules there if we want to make them a 1st party rule. Also as we don't have Compose code in the codebase, we won't be using those rules (which is another point for having them in a separate repo).

**Comment by 3flex** [comment]
Agree with the comments above - and the Twitter rule set would be a great one to showcase in the marketplace once #5191 is done.

**Comment by chao2zhang** [comment]
Thanks for the replies! `twitter/compose-rules` seem to be a good third-party repository for people to look into. Hoepfully we will enrich our rules marketplace in https://github.com/detekt/detekt/pull/5191/
