### ISSUE TITLE
Update ktlint to 0.47.x

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5281]
## Expected Behavior
Dependencies are kept up to date.

## Current Behavior
We're on 0.46.1

## Context
Latest update has breaking API changes which detekt must adapt to: https://github.com/pinterest/ktlint/releases/tag/0.47.0

**Comment by cortinico** [comment]
Do we consider this a blocker for 1.22.0?

**Comment by BraisGabin** [comment]
I would not consider it a blocker.

**Comment by 3flex** [comment]
Agreed, not a blocker - it would be better to update, but it didn't seem simple to do when I tried because of the API changes, and I'm not sure if anyone else is working on it.
