### ISSUE TITLE
Cannot deserialize `java.lang.Thread`

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#5289]
## Expected Behavior
The build works

## Observed Behavior
It does not: https://ge.detekt.dev/s/kirsxpe7schkk

## Steps to Reproduce
No idea, this is the previous build and it worked: https://ge.detekt.dev/s/emmk2armn5dsa

And I executed the same task multiple times before

## Your Environment
* Version of detekt used: main

**Comment by cortinico** [comment]
I'd defer to @3flex as this seems to be a Configuration Cache issue. Specifically, we're referencing a `java.lang.Thread` somewhere that can't be serialized so your build failed.

> And I executed the same task multiple times before

Which task you were executing?

**Comment by BraisGabin** [comment]
`test`. I'm using `--no-configuration-cache` for now.

**Comment by 3flex** [comment]
Can you please share the configuration cache report?

Also, is this working with a clean build (no local changes) on your machine? It's building in CI successfully, so it's a bit odd.

**Comment by BraisGabin** [comment]
[configuration-cache-report.html.zip](https://github.com/detekt/detekt/files/9540442/configuration-cache-report.html.zip) (I need to zip it because github doesn't allow to upload a `.html`.

I can reproduce this on `main` if I run `test` twice the second build fails. Scans:
- First: https://ge.detekt.dev/s/r64763ccemcpc
- Second (fail): https://ge.detekt.dev/s/jhussayalb3lw

I tried with `--rerun-tasks`, same error. `./gradlew clean` doesn't help neither.

**Comment by BraisGabin** [comment]
Ok, now, after the first `./gradlew clean` I can't do `./gradlew clean` anymore. It also fail with the same problem: https://ge.detekt.dev/s/rtzdtlfoy5kbg

**Comment by 3flex** [comment]
That's annoying! I can replicate. Unfortunately the configuration cache report is quite useless as it doesn't point to a specific task or property that triggers the issue.

I just tried `./gradlew clean` twice with Gradle 7.6-20220911001843+0000, and it works fine with that version, so I think it's best to disable configuration cache again, unfortunately, and try again when 7.6 is released...
