### ISSUE TITLE
EndOfSentenceFormat highlights everything

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5310]
## Expected Behavior
The highlighted character is wrong (blue)
![image](https://user-images.githubusercontent.com/2906988/190917988-5658bb9b-63a1-480f-90fd-8fd8759c8878.png)

## Observed Behavior
![image](https://user-images.githubusercontent.com/2906988/190917948-715d77ec-af56-4775-b5ff-8c1707466231.png)

## Steps to Reproduce
Copy code from https://github.com/detekt/detekt/blob/main/detekt-rules-documentation/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/documentation/EndOfSentenceFormatSpec.kt to the IDE and configure Detekt with EndOfSentenceFormat.

## Context
Enabling all rules of Detekt on yet another project and reporting back.

## Your Environment

* Version of detekt used: 1.21.0

**Comment by TWiStErRob** [comment]
Submitted PR too: https://github.com/detekt/detekt/pull/5311

(for future reference: for "trivial" fixes like this, do I need issues? or can the above description go straight to the PR?)

**Comment by schalkms** [comment]
In this repo, no strict rule exists regarding this. In any case, documenting the problem helps to refer to it in the future.

> for future reference: for "trivial" fixes like this, do I need issues? or can the above description go straight to the PR?
