### ISSUE TITLE
MandatoryBracesIfStatement to highlight only if/else keywords

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5317]
Pretty much the same as #5316, but a different rule.

## Context
![image](https://user-images.githubusercontent.com/2906988/191109680-dc699de5-6f31-4937-8630-07d220291fb6.png)

Warnings exists in some codebases, and that's ok, but then they make the code harder to read, then it becomes a problem. A warnings should highlight where the problem is, specifically, but some rules report on the blocks which could be quite large, therefor hiding potential crashes, which could be quite serious. In the example above the `MandatoryBracesIfStatement` hides an `UnsafeCallOnNullableType` (potential NPE).

## Expected Behavior of the rule
Move the highlight of the reported violation to the `if` keyword and the `else` keyword. Note to implementer: mind `else if`s.

**Comment by dizney** [comment]
I have created a PR (#5407) to change the behavior of the rule.

The hightlighting looks like this with the PR change:

<img width="309" alt="Screenshot 2022-10-13 at 15 04 04" src="https://user-images.githubusercontent.com/903673/195604414-a72d3037-0ee8-4f21-bcf8-67a19dc7c391.png">

**Comment by TWiStErRob** [comment]
Oh, yeah! Amazing @dizney, thank you!
