### ISSUE TITLE
Severity level for rules

### ISSUE THREAD

**Issue by schalkms** [detekt/detekt#533]
At the moment detekt has severity grades. Additionally, severity levels might be useful.
Some rule violation are not so tragic than others.
A detekt configuration option to only report issues with `severity level < config` might also be useful.

**Comment by Mauin** [comment]
Similar to this, should it be possible to override the severity of an issue in the config? Say I don't consider catching too generic exceptions as an `ERROR` but just a `WARNING`, I could define that in the config?

**Comment by schalkms** [comment]
Good idea!

**Comment by rvoortman** [comment]
I want to add that detekt-cli should also print the severity of the issue; this way I'm able to catch the severity and integrate it with Phabricator (https://github.com/moneybird/arc-detekt-linter).

**Comment by arturbosch** [comment]
Hey, interesting project :).
Have tried running detekt with `--output /your/dir --output-name filename` and parsing the xml file? 
We use the chekstyle xml format.

**Comment by rvoortman** [comment]
@arturbosch not yet; since we needed the project pretty fast and we already had a regex to grab the output, it was easier to get it this way.

That said: I'm certainly going to implement this in the future, since it provides more information.

**Comment by rvoortman** [comment]
Off topic: @arturbosch I've added severity for the arcanist detekt linter; we're reviewing the code and functionality, but it should be online by the end of the week.

On topic: We're now facing similar issues in that we find certain errors less problematic then detekt thinks.

**Comment by arturbosch** [comment]
That's where the configuration file shines. Just turn off rules you dont like or change some thresholds.
Also make sure to make use of the baseline feature if needed ^^

**Comment by rvoortman** [comment]
Sure thing, but for example a 'MagicNumber' is something we consider as an advice, since they are not always a warning. Because it is a warning, phabricator will fail the build, which could result in problems if we're not careful.  However, I still want detekt to show me this error, since it could be that we've missed it. 

We can not override the severity in the config file (as far as I'm aware). I think it would be great to just have an option in the configuration that allows me to override the severity; if it's not set, we can just use the default severity.

**Comment by arturbosch** [comment]
Having an option to change the severity within the configuration file is a good idea (also for suppress aliases).
Just checked the Code (`ConfigAware`, `DefaultContext`, `Rule`). Accessing random configuration properties within the rule is a no brainer (`valueOrDefault`). Unfortunately changing `Issue.severity` from a generic point like `Rule.init` or `DefaultContext.report` is undoable ...

**Comment by arturbosch** [comment]
I'm assuming your parsing the xml output? It is `Checkstyle`-based, so the severity is translated to checkstyle's style
```kotlin
	private val Finding.messageType: MessageType
		get() = when (issue.severity) {
			Severity.CodeSmell -> MessageType.Warning()
			Severity.Style -> MessageType.Warning()
			Severity.Warning -> MessageType.Warning()
			Severity.Maintainability -> MessageType.Warning()
			Severity.Defect -> MessageType.Error()
			Severity.Minor -> MessageType.Info()
			Severity.Security -> MessageType.Fatal()
			Severity.Performance -> MessageType.Warning()
		}
```
One generic way to achieve changing the reported severity could be to implement a new output report format.
or enhance the checkstyle format. (see `OutputReport` and `Extension` classes)

**Comment by chao2zhang** [comment]
Progress will be tracked in #3274
