### ISSUE TITLE
Configure warning users about rules that won't run

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#5334]
My detekt runs just got very noisy with 1.22.0-RC1 due to https://github.com/detekt/detekt/issues/3577.

I have one config file that contains all the enabled rules for my project, but I sometimes run detekt without type resolution, so I don't necessarily care to know that some rules won't be run. I'd like to be able to configure that warning to not print.

**Comment by BraisGabin** [comment]
This should be an "easy" task. But I don't know were that configuration should be printted.

Other option: only print one line telling "Some rules will not be executed [...] run detekt on debug mode to get the list of those rules". Would that be an acceptable behaviour for you?

**Comment by eygraber** [comment]
I'd prefer for it to be as clean as possible. Couldn't this be a flag that gets set in the detekt extension?

**Comment by arturbosch** [comment]
> I'd prefer for it to be as clean as possible. Couldn't this be a flag that gets set in the detekt extension?

I 👍🏼 the gradle/cli flag idea.

**Comment by lcfyhr** [comment]
Was also implementing Detekt and wanted to see if I could filter these warnings out so I can simply have an output solely consisting of the files and the issues within them be printed out.

**Comment by 3flex** [comment]
It might be time to introduce log levels for detekt beyond just "debug" and the default.

If using slf4j we could then show the summary message at WARN level and the individual rules that are not run at INFO level for example.

This would be more futureproof than having a CLI flag specific to this message.

**Comment by arturbosch** [comment]
Should we change the log level for this warning to debug for now to not ship it to the users with 1.22.0?

**Comment by BraisGabin** [comment]
Closing. This was fixed. Now all that out goes to the debug
