### ISSUE TITLE
Mark new AnnotationRule finding from 0.47.0 as non correctable

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#5343]
## Expected Behavior

https://github.com/pinterest/ktlint/blob/6265d7f7b16ced7405f3c3f83cffb2c30ada1df5/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/AnnotationRule.kt#L108-L116

## Current Behavior
0.47.0 update is missing

## Context
IJ plugin should not report KtLint findings which are not corrected as "auto correctable".
See https://github.com/detekt/detekt/pull/5324

**Comment by sanggggg** [comment]
@arturbosch If you are not working on, can I work on this issue?

And I have a question,
ktlint tells us whether the rule is auto-correctable or not by `canBeAutoCorrected` parameter in `emit` callback, so is it okay to solve this issue by using this value?

https://github.com/detekt/detekt/blob/e259980d88cdc0d949552ddf5971621d8ed7bba4/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingRule.kt#L115-L125

[ktlint's declaration of `canBeAutoCorrected` parameter in `emit` lambda](https://github.com/pinterest/ktlint/blob/0.47.1/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/Rule.kt#L42-L54)


Currently checking whether the rule is auto-correctable or not by overriden function `FormattingRule::canBeCorrectedByKtLint`. But I think replacing it with `canBeAutoCorrected` parameter in `emit` callback can solve this problem more consistently with ktlint. (and do not need manual synchronizing)

https://github.com/detekt/detekt/blob/561d25b8eee7123f4b10f330eac167ed2e4932a8/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingRule.kt#L74-L75

I also checked that current behaviors of `FormattingRule::canBeCorrectedByKtLint` in each implementation rules are exactly same as ktlint(0.47.1)'s `canBeAutoCorrected` parameter in `emit` lambda.

**Comment by arturbosch** [comment]
Oh, you are totally right. In line 92 the `_` parameter can be used for this.
Yes, I introduced unnecessary complexity here :/.
@sangggg Yes, please. You can work on it.
