### ISSUE TITLE
KTLint issues when running detekt

### ISSUE THREAD

**Issue by inakirosa** [detekt/detekt#5358]
## Expected Behavior
KTLink is initialized correctly

## Observed Behavior
When detekt is run, for every test we have it throws errors that it couldn't initialize ktlint

## Steps to Reproduce
Run detekt, happens every time

## Context
Fills our logs up with spam and doesn't allow us to easily debug

The error, plus the stack trace fill out for every test we have (1k+)
```The original exception message was: Could not initialize class com.pinterest.ktlint.core.ast.ElementType```

## Your Environment
Running detekt '1.6.0' on Java '11.0.11+9' on OS 'Mac OS X'.
Kotlin Project, Spring

## Full error message:
The original exception message was: Could not initialize class com.pinterest.ktlint.core.ast.ElementType
Running detekt '1.6.0' on Java '11.0.11+9' on OS 'Mac OS X'.
If the exception message does not help, please feel free to create an issue on our GitHub page.
com.pinterest.ktlint.ruleset.standard.ChainWrappingRule.<init>(ChainWrappingRule.kt:36)
io.gitlab.arturbosch.detekt.formatting.wrappers.ChainWrapping.<init>(ChainWrapping.kt:15)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.<init>(KtLintMultiRule.kt:52)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.instance(FormattingProvider.kt:26)
io.gitlab.arturbosch.detekt.api.RuleSetProvider$DefaultImpls.buildRuleset(RuleSetProvider.kt:31)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.buildRuleset(FormattingProvider.kt:21)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$1.invoke(Detektor.kt:72)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$1.invoke(Detektor.kt:12)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:742)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:772)
kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:593)
kotlin.sequences.DistinctSequence.iterator(Sequences.kt:563)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:742)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:772)
kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:763)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:75)
io.gitlab.arturbosch.detekt.core.Detektor.runSync(Detektor.kt:44)
io.gitlab.arturbosch.detekt.core.Detektor.run(Detektor.kt:28)
io.gitlab.arturbosch.detekt.core.DetektFacade.run(DetektFacade.kt:41)
io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:34)
io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:17)

**Comment by BraisGabin** [comment]
Update your version of detekt. 1.6.0 is really old.
