### ISSUE TITLE
Exclude InjectDispatcher rule based on annnoation

### ISSUE THREAD

**Issue by WildOrangutan** [detekt/detekt#5402]
## Expected Behavior of the rule
Add configuration option, to exclude InjectDispatcher rule, if specific method annotation is used.

## Context

Please look at following example. I guess triggering rule for `provideIoDispatcher()` could be avoided. I guess it would be possible to exclude triggering rule, if method is annotated with `@Provides` in this case?

```
@Retention(AnnotationRetention.RUNTIME)
@Qualifier
annotation class IoDispatcher

@Module
@InstallIn(SingletonComponent::class)
object DispatcherModule {

    @IoDispatcher
    @Provides
    fun provideIoDispatcher(): CoroutineDispatcher = Dispatchers.IO

}
```

**Comment by cortinico** [comment]
This is already doable by specifying the `ignoreAnnotated` property in your custom config:
https://detekt.dev/docs/introduction/suppressors/

**Comment by WildOrangutan** [comment]
I see, sorry about that
