### ISSUE TITLE
when opening html report on a browser does not show all the content

### ISSUE THREAD

**Issue by IvanSanchez-uam** [detekt/detekt#5404]
## Expected Behavior

opening the html on android studio and on a browser shows all the content

## Observed Behavior

when the html report is generated and open in on android studio it shows all its content but opening it on a browser just shows too much content , for instance, the report has 167 issues and when opening it up on Chrome it just shows 22.

## Steps to Reproduce

when adding a new custom rule and add it to the config file i always get "a property is misspelled", i need to invalidate cached and restart android studio and then sometimes it fixes all.
when configuring the gradle dependencies it also breaks the report.

## Your Environment

* Version of detekt used: 1.20.0 and 1.21.0
* Version of Gradle used (if applicable): 7.2.1
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by cortinico** [comment]
> ##
> 
> when the html report is generated and open in on android studio it shows all its content but opening it on a browser just shows too much content , for instance, the report has 167 issues and when opening it up on Chrome it just shows 22.

Can you share your report?

**Comment by 3flex** [comment]
Closing manually. This would have been closed already by stale bot, but it seems that adding a new label reset the clock inadvertently.
