### ISSUE TITLE
CI: The `set-output` and `save-state` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5432]
## Expected Behavior
No warnings.

## Observed Behavior
113 warnings on PR CI.
![image](https://user-images.githubusercontent.com/2906988/196203476-2bb4400c-edc2-4810-9266-a6afe96c55c9.png)

## Steps to Reproduce
See recent CI job, e.g. https://github.com/detekt/detekt/actions/runs/3261225698

## Context
> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by TWiStErRob** [comment]
I did a bit of investigation to see which ones are the interesting ones:
 * `website.yml` (example https://github.com/detekt/detekt/actions/runs/3261225698/jobs/5355677542)
   * `actions/checkout` (3)
   * `actions/setup-java` (3)
   * `gradle/gradle-build-action` (6)
 * `pre-merge.yml` (example https://github.com/detekt/detekt/actions/runs/3266022234)
   * `verify-generated-config-file` (10)
     * `actions/checkout` (3)
     * `actions/setup-java` (3)
     * `gradle/gradle-build-action` (4)
   * `compile-test-snippets` (10)
     * `actions/checkout` (3)
     * `actions/setup-java` (3)
     * `gradle/gradle-build-action` (4)
   * `warnings-as-errors` (10)
     * `actions/checkout` (3)
     * `actions/setup-java` (3)
     * `gradle/gradle-build-action` (4)
   * `gradle` (matrix: 11 * 8 ~ 88)
     * `actions/checkout` (3)
     * `actions/setup-java` (3)
     * `gradle/gradle-build-action` (5)

and to make sure that the third parties are making progress on this:
 * `actions/checkout` issue [#959](https://github.com/actions/checkout/issues/959), fixed in [3.1.0](https://github.com/actions/checkout/releases/tag/v3.1.0) on 4 Oct, already released.
 * `actions/setup-java` issue [#393](https://github.com/actions/setup-java/issues/393), fixed in [#390](https://github.com/actions/setup-java/pull/390), 7 Oct, but not released yet on 18 Oct.
 * `gradle/gradle-build-action` issue [#461](https://github.com/gradle/gradle-build-action/issues/461), will be (at least partially) fixed once [#455](https://github.com/gradle/gradle-build-action/pull/455) is merged and released.

**Comment by TWiStErRob** [comment]
@detekt please press the first checkbox at https://github.com/detekt/detekt/issues/4298:
> Update actions/checkout digest to 93ea575

(this is according to [Renovate guru](https://github.com/renovatebot/renovate/discussions/18397#discussioncomment-3911509).)

**Comment by BraisGabin** [comment]
Done

**Comment by BraisGabin** [comment]
@TWiStErRob so now we are just waiting for `gradle/gradle-build-action`, right?

**Comment by TWiStErRob** [comment]
Yeah, seems so, 0 activity so far. They have tons of dependency update PRs open, so I think it's abandoned.

**Comment by TWiStErRob** [comment]
They fixed it as well, not released yet. I'm watching for releases.
