### ISSUE TITLE
FOSSA CI scan is never completing

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5437]
## Expected Behavior
FOSSA action completes successfully.

## Observed Behavior
It sits in pending status for a while.

Also, logging in to FOSSA dashboard, it says:
![image](https://user-images.githubusercontent.com/170028/196300642-fa8b72a5-902c-4007-9ff5-c37056dddc00.png)

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by TWiStErRob** [comment]
I had a quick look I was curious. Based on your screenshot someone with access (that might be you @3flex or @cortinico?) should go through the [setup steps](https://docs.fossa.com/docs/github).

#### Additional info

Last completed execution was
 * on 5 October 2022
 * ![image](https://user-images.githubusercontent.com/2906988/196782514-49a7a4b7-6a3c-491f-bb8a-bdaae31b3eef.png)
 * [workflow](https://github.com/detekt/detekt/actions/runs/3187796510/jobs/5199724561) completed successfully.
 * [report](https://app.fossa.com/projects/custom%2B25591%2Fgithub.com%2Fdetekt%2Fdetekt/refs/branch/main/b4710a2108db0634c5d7f67cd934d633230eb4a9) is accessible.

Most recent execution (and everything between the last completed execution)
 * is pending as stated in OP
 * ![image](https://user-images.githubusercontent.com/2906988/196781635-b0c5d766-58e7-4d60-afb0-f01053277404.png)
 * The [workflow](https://github.com/detekt/detekt/actions/runs/3283964775/jobs/5409339214) is completed successfully.
 * The [report](https://app.fossa.com/projects/custom%2b25591%2fgithub.com%2fdetekt%2fdetekt/refs/branch/main/b656bcc52568cfa54d613d38a347222bdec4aa55) is not available yet.
 * The Check instance is not created yet either.

**Comment by 3flex** [comment]
The FOSSA job now completes, but fails.

**Comment by cortinico** [comment]
> The FOSSA job now completes, but fails.

Thanks for looking into this @3flex I'll keep an eye at the failures 👍

**Comment by TWiStErRob** [comment]
Are these failures for real? That means some part of dokka and ktlint are not licenced, does that mean that their poms are wrong?

**Comment by TWiStErRob** [comment]
Uhm, when I open the latest `main` failure, it shows green now.

**Comment by cortinico** [comment]
> Are these failures for real? That means some part of dokka and ktlint are not licenced, does that mean that their poms are wrong?

I've listed them here https://github.com/detekt/detekt/issues/5457#issuecomment-1287162385
The failures was on FOSSA failing to find the license for those libraries (not sure exactly why). I've resolved them manually
