### ISSUE TITLE
FOSSA job fails

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5457]
## Expected Behavior
CI builds successfully.

## Observed Behavior
FOSSA complains about issues that seem outside our direct control.

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by cortinico** [comment]
I've manually resolved all the issues.
We had some dependencies which FOSSA failed to scan:
- https://github.com/pinterest/ktlint/blob/master/LICENSE (on MIT)
- https://github.com/JetBrains/markdown/blob/master/LICENSE (on Apache2)
- https://github.com/Kotlin/dokka/blob/master/LICENSE (on Apache2)

**Comment by TWiStErRob** [comment]
I would imagine the problems might be on the artifact level not the source code (repository) level.

e.g. https://repo1.maven.org/maven2/org/jetbrains/markdown/0.3.1/markdown-0.3.1.pom (not sure which version was flagged) has the `<licenses>` block, but maybe the ones that failed didn't?
