### ISSUE TITLE
detekt-maven-plugin:1.21.0.1:check failed

### ISSUE THREAD

**Issue by erwinc1** [detekt/detekt#5469]
The error I get is 

``` Front-end Internal error: Failed to analyze declaration Store_success_flow```
Whereas ```store_success_flow``` is a ```.kts``` Spring Cloud Contract file. This issue was not there in ```1.21.0```.

```
The root cause org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException was thrown at: org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18): Descriptor wasn't found for declaration SCRIPT
```

**Comment by BraisGabin** [comment]
Detekt `1.21.0.1` doesn't exist.

**Comment by erwinc1** [comment]
You're right @BraisGabin 

This issue was meant for [detekt-maven-plugin](https://github.com/Ozsie/detekt-maven-plugin)
