### ISSUE TITLE
detektMain is very slow taking more than 10 mins

### ISSUE THREAD

**Issue by spasnoor21** [detekt/detekt#5506]
`detektMain` is very slow, taking more than 10 mins. Is there a way I can configure detekt to use existing buildcache rather than re-running `compileKotlin`
## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by TWiStErRob** [comment]
I guess one answer will be https://github.com/detekt/detekt/pull/5492, @3flex?

**Comment by cortinico** [comment]
> Is there a way I can configure detekt to use existing buildcache rather than re-running `compileKotlin`

As @TWiStErRob suggested already, the solution as of now is to use the detekt-compiler-plugin:
github.com/detekt/detekt-compiler-plugin
