### ISSUE TITLE
Missing Release on GitHub + CLI.zip

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5511]
## Expected Behavior
Release on GitHub drafted before pushing to mavenCentral(), and published right along with it.

## Observed Behavior
Downloading of https://github.com/detekt/detekt/releases/download/v1.22.0-RC3/detekt-cli-1.22.0-RC3.zip failed.
https://github.com/TWiStErRob/net.twisterrob.cinema/actions/runs/3403757084/jobs/5660501785

## Steps to Reproduce
Process timing issue.

## Context
I'm using GitHub releases as the distribution mechanism for the CLI zip to run on non-Gradle Kotlin projects.

## Your Environment

* Version of detekt used: 1.22.0-RC3
* Version of Gradle used (if applicable): N/A
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: Ubuntu GHA
* Link to your project (if it's a public repository): [sources](https://github.com/TWiStErRob/net.twisterrob.cinema/tree/master/map) + [CI](https://github.com/TWiStErRob/net.twisterrob.cinema/blob/master/.github/workflows/map.yml)

**Comment by cortinico** [comment]
Added here:
https://github.com/detekt/detekt/releases/tag/v1.22.0-RC3

I had to wait for the #5509 to be merged before I could create it.
I also had to re-create `v1.22.0-RC2` artifacts as RC3 accidentally overwrote it (this is a reminder that we should automate this process :|)
