### ISSUE TITLE
EqualsWithHashCodeExist enabled throws IllegalStateException in main class

### ISSUE THREAD

**Issue by spoonman01** [detekt/detekt#5517]
## Expected Behavior
Analysis and build (via gradle plugin) should report errors

## Observed Behavior
java.lang.IllegalStateException thrown during the analysis, will not make it run

## Steps to Reproduce
1. Enable EqualsWithHashCodeExist in a detekt config file called "detekt/detekt-config.yaml":
```
potential-bugs:
  active: true
    EqualsWithHashCodeExist:
    active: false
```
2. Configure detekt to run on gradle build in the build.gradle.kts
```
plugins {
    ...
    id("io.gitlab.arturbosch.detekt") version Versions.DETEKT
}
...
detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.22.0-RC2")
...
detekt {
    autoCorrect = project.hasProperty("autoCorrect")
    config = files("detekt/detekt-config.yaml")
    baseline = file("detekt/detekt-baseline.xml")
}
```
3. Have a class like this:
```
package eu.kevin.bankingserviceapi

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.cache.annotation.EnableCaching

@SpringBootApplication
@EnableCaching
class BankingService

fun main(args: Array<String>) {
    runApplication<BankingService>(*args)
}
```
4. Running `gradle check` throws:
```
Caused by: java.lang.IllegalStateException: Analyzing /Users/lucarospocher/Code/kevin-banking-service/src/main/kotlin/eu/kevin/bankingserviceapi/BankingService.kt led to an exception.
Location: io.gitlab.arturbosch.detekt.rules.bugs.EqualsWithHashCodeExist.visitClassOrObject(EqualsWithHashCodeExist.kt:72)
The original exception message was: 'boolean org.jetbrains.kotlin.psi.KtClassOrObject.isData()'
Running detekt '1.22.0-RC2' on Java '17.0.3+0' on OS 'Mac OS X'
```

**NOTE my detekt config file has 900 lines and all the other rules works correctly in my project, the issue is only relevant to EqualsWithHashCodeExist**

## Context
Build is blocked by detekt exception

## Your Environment
* Version of detekt used: 1.22.0-RC2
* Gradle Scan with all the relevant infos: https://scans.gradle.com/s/ysp7ntjyork3q

**Comment by 3flex** [comment]
Can you please try running this again but upgrade your Kotlin plugin to 1.7.20?

The Kotlin version that detekt uses is expected to be 1.7.20 but it's being overridden to 1.7.10 which may explain the problem. See https://scans.gradle.com/s/ysp7ntjyork3q/dependencies?focusedDependency=WzAsNDEsODEsWzAsNDEsWzc2LDgxXV1d&focusedDependencyView=details&toggled=W1swXSxbMCw0MV0sWzAsNDEsWzc2XV0sWzAsNDEsWzc2LDgxXV1d
