### ISSUE TITLE
detekt does not run for all modules in project. It only runs a single module and skips the rest.

### ISSUE THREAD

**Issue by steve1rm** [detekt/detekt#5529]
## Expected Behavior
Should show output for all android modules, presentation, data, domain when running this command `/gradlew detekt`

## Observed Behavior
Only shows output for the data module.
However, when I run the following `./gradlew :domain:detekt` or `./gradlew :presentation:detekt`
It will show the output from those modules.

However, I want to be able to show the output for all modules when running this command `./gradlew detekt`

## Steps to Reproduce
`./gradlew detekt`

## Context
I am trying to output the reports for all modules i.e. presentation, data, and domain by running the detekt command.

## Your Environment

* Version of detekt used: `1.19.0`
* Version of Gradle used (if applicable): `7.4.2`
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/ipz626b3l6tcw
* Operating System and version: `Fedora Linux 36`
* Link to your project (if it's a public repository):
https://github.com/steve1rm/BusbyFood/tree/develop-detekt

**Comment by 3flex** [comment]
Can you please run the tasks with the --scan option?

**Comment by steve1rm** [comment]
@3flex 
I have added the scan like in the description above: https://scans.gradle.com/s/ipz626b3l6tcw

**Comment by 3flex** [comment]
Thanks for providing the build scan.

This is normal Gradle behaviour and not an issue with detekt. See [here](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:continue_build_on_failure) where it says: 

> By default, Gradle will abort execution and fail the build as soon as any task fails. This allows the build to complete sooner, but hides other failures that would have occurred.

You might want to try using Gradle's `--continue` flag which should allow all detekt tasks to run even if one or more fail.
