### ISSUE TITLE
`EnumEntryNameCase` cannot be suppressed on (enum) class or declaration level

### ISSUE THREAD

**Issue by sschuberth** [detekt/detekt#5547]
## Expected Behavior

I should be able to suppress `EnumEntryNameCase` via

```
@Suppress("EnumEntryNameCase")
enum class SpdxLicense(
    val id: String,
    val fullName: String,
    val deprecated: Boolean = false
) {
    _0BSD("0BSD", "BSD Zero Clause License");
}
```

or

```
enum class SpdxLicense(
    val id: String,
    val fullName: String,
    val deprecated: Boolean = false
) {
    @Suppress("EnumEntryNameCase")
    _0BSD("0BSD", "BSD Zero Clause License");
}
```

## Observed Behavior

Suppressing this way has no effect, the inspection hint is already being reporter. However, suppressing on the *file*-level works:

```
@file:Suppress("EnumEntryNameCase")

enum class SpdxLicense(
    val id: String,
    val fullName: String,
    val deprecated: Boolean = false
) {
    _0BSD("0BSD", "BSD Zero Clause License");
}
```

## Steps to Reproduce

See code examples above.

## Context

I ran into this while upgrading to Detekt 1.22 in https://github.com/oss-review-toolkit/ort/pull/6096.

## Your Environment

* Version of detekt used: 1.22
* Version of Gradle used (if applicable): 7.5.1
* Gradle scan link (add `--scan` option when running the gradle task): n/a
* Operating System and version: Windows 11
* Link to your project (if it's a public repository): https://github.com/oss-review-toolkit/ort

**Comment by KarimFikani** [comment]
Having the same issue. For some reason even `@file:Suppress("EnumEntryNameCase")` is not working for me

**Comment by BraisGabin** [comment]
This is a formatting rule. I think that we can't fix this. I'm going to keep this open if someone has an idea to fix it or can confirm that this is a "won't fix".

**Comment by cortinico** [comment]
> This is a formatting rule. I think that we can't fix this. I'm going to keep this open if someone has an idea to fix it or can confirm that this is a "won't fix".

I started to investigate this as it's a sort of recurrent issue, but couldn't find a decent solution that would allow us to support both `@file:Suppress("EnumEntryNameCase")` and local `@Suppress("EnumEntryNameCase")`. I need to get back to it.
