### ISSUE TITLE
Allow AtomicBoolean to be named with "is"

### ISSUE THREAD

**Issue by inktomi** [detekt/detekt#5553]
## Expected Behavior of the rule

I saw this was suggested in https://github.com/detekt/detekt/issues/4675 but it was decided not to make this change at that time. I thought I'd bring it up for discussion as this causes extra suppressions in code that don't really have to happen.  

`val isDaytime = AtomicBoolean(true)` 

This code will trigger the rule `NonBooleanPropertyPrefixedWithIs` - but as an `AtomicBoolean` it makes sense for this to be called "is..". 

## Context

`AtomicBoolean` should be treated as a normal `Boolean` as far as naming goes. This allows it to be used without surpassing rules and without extra gymnastics to name it something that is less meaningful.

**Comment by cortinico** [comment]
> but as an `AtomicBoolean` it makes sense for this to be called "is..".

This probably makes sense as it's part of the JDK
