### ISSUE TITLE
Feature request: Fail when `maxIssues` is higher than actual number of issues

### ISSUE THREAD

**Issue by haluzpav** [detekt/detekt#5563]
## Expected Behavior
When detekt finds less issues than `maxIssues`, it should fail, with error output something like "You can lower maxIssues to X". For example when `maxIssues: 100` and detekt finds only 90, it should fail. This should be optional feature, being off by default I guess.

## Current Behavior
Detekt doesn't output any special message/error when `maxIssues` > found issues.

## Context
I have a project with a lot detekt issues, 200+. We are slowly getting resolving them. When we resolve some, we should lower `maxIssues`, so we can't introduce new issues later on in some other pull request. Currently detekt has no mechanism to enforce this, correct me if I'm wrong pls. Someone in my project implemented a custom PR check, parsing XML report and detekt config manually, which is obviously not great.

**Comment by 3flex** [comment]
The normal workflow for a codebase with existing issues is to generate a baseline file then set maxIssues to zero. As you resolve issues you can generate new baselines which will remove the references to the fixed issues.

**Comment by haluzpav** [comment]
Ah, I forgot baseline existed. 😅

Anyway, the reason why we don't use baseline is that it "hides" the issues. We want *all* the issues to be visible in regular reports, so they annoy developers, and they get "forced" to fix them. 😄

**Comment by cortinico** [comment]
> We want all the issues to be visible in regular reports, so they annoy developers, and they get "forced" to fix them. 😄

I think we should instead add in the report a short summary of the baselined issues.

> "You can lower maxIssues to X". For example when maxIssues: 100 and detekt finds only 90, it should fail. 

This feels intrusive to me and essentially against the semantic of `maxIssues`

**Comment by 3flex** [comment]
Closing in favour of https://github.com/detekt/detekt/issues/5638. We won't implement what was originally requested, but including a summary of baselined issues in reports or CLI output could be used instead for this purpose.
