### ISSUE TITLE
Add configuration for all-open classes

### ISSUE THREAD

**Issue by andrew-simmons** [detekt/detekt#5586]
My team uses the all-open kotlin plugin to ensure that classes that interact with various Java services (eg. JSF, JPA, EJB, ...) are made open by default. See [all-open docs](https://kotlinlang.org/docs/all-open-plugin.html) for more details.

I started rolling out detekt within our projects and have started running into ProtectedMemberInFinalClass errors. But all the errors are in classes that are made open by all-open.

Please add a configuration entry that allows specifying annotations that will used with the all-open plugin and update rules (including ProtectedMemberInFinalClass) that check if the class is open.

**Comment by cortinico** [comment]
> Please add a configuration entry that allows specifying annotations that will used with the all-open plugin and update rules (including ProtectedMemberInFinalClass) that check if the class is open.

You should be able to use `ignoreAnnotated` already for this:
https://detekt.dev/docs/introduction/suppressors#annotation-suppressor

**Comment by schalkms** [comment]
As @cortinico said, the `ignoreAnnotated` does exactly what you want to achieve with your configuration.

If you have further question, feel free to leave a comment in this discussion.

**Comment by andrew-simmons** [comment]
Thanks. Missed that part of the documentation initially.
