### ISSUE TITLE
FunctionMaxLength false positive for overridden methods

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5590]
## Expected Behavior
`FunctionMaxLength` should give actionable results only.

## Observed Behavior
https://github.com/TWiStErRob/net.twisterrob.cinema/security/code-scanning/425
![image](https://user-images.githubusercontent.com/2906988/204913892-809256f9-3626-426d-9bbe-00d0abbdce7a.png)

## Context
The method in question comes from [org.neo4j.ogm.session.EntityInstantiator](https://github.com/neo4j/neo4j-ogm/blob/v4.0.0/core/src/main/java/org/neo4j/ogm/session/EntityInstantiator.java#L49) which I cannot rename, and I **have to** implement this method, otherwise it doesn't compile.

## Steps to Reproduce
 * Find a long method in a library which cannot be changed
   e.g. the above example in `org.neo4j:neo4j-ogm-core:4.0.0`
 * implement the interface or override the method
 * run `FunctionMaxLength` on it

## Your Environment

* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): N/A
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): https://github.com/TWiStErRob/net.twisterrob.cinema/pull/215

**Comment by TWiStErRob** [comment]
During implementation: review other naming rules with the same eye.

**Comment by schalkms** [comment]
It's rather an improvement, since this rule never considered overridden methods to be ignored.

**Comment by mmorozkov** [comment]
Hi I created a [PR](https://github.com/detekt/detekt/pull/5599) with this improvement.
I took into consideration a note by @TWiStErRob above and introduced `ignoreOverridden` for several other naming rules where it made sense
