### ISSUE TITLE
Broken link at EmptyFunctionBlock

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#5601]
The documentation of EmptyFunctionBlock has a "broken link":

> Set the [ignoreOverridden] parameter to... 

https://detekt.dev/docs/rules/empty-blocks#emptyfunctionblock

**Comment by SaumyaBhushan** [comment]
which link is broken @BraisGabin

**Comment by BraisGabin** [comment]
![Screenshot_20221204-154837~3.png](https://user-images.githubusercontent.com/721244/205497546-39cc4fa8-e136-4d94-9075-094552408e39.png)

That one. And I just realized that the // no-op could be marked as code too.

**Comment by SaumyaBhushan** [comment]
@BraisGabin Sorry to ask you I am not clear about this, where should it point to ? Broken link as in .

**Comment by BraisGabin** [comment]
Good point... Probably just remove the `[] `. Or replace them to `` ` ``.

**Comment by SaumyaBhushan** [comment]
Ok , Thanks
