### ISSUE TITLE
`FunctionMinLength` should exclude infix/operator functions

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#5602]
## Expected Behavior
`abstract infix fun or(other: T)` infix function should pass detekt check with default configuration.

## Observed Behavior
`Function names should be at least 3 characters long. [FunctionMinLength]`

## Context
`FunctionMinLength` should exclude infix functions from calculation.

## Your Environment

* Version of detekt used: 1.22
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by schalkms** [comment]
For consistency reasons, the change for infix functions should also be done for the `FunctionMaxLength` rule.

**Comment by BraisGabin** [comment]
I'm not 100% sure about this. To me this seems like a really edge case. A suppress should be added instead. Or (and this one is my favorite) just deprecate this rule because the length of a function doesn't measure if the name is good.
