### ISSUE TITLE
Add wrappers for new rules in ktlint 0.48

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5627]
## Expected Behavior of the rule
I can enable the following ktlint rules:
* Class naming
* Function naming
* Property naming

## Context
We have wrappers for other ktlint rules. We should add wrappers for the rules added in ktlint 0.48.0 (see #5625).

**Comment by cortinico** [comment]
> There are three new rules that I haven't added wrappers for, since we seem to have the same ones in detekt already:

RE To this: I believe we should add those wrappers. The reason is that we've been doing that in the past to keep feature parity between bare Ktlint and our wrapper. We do already have other rules between first-party & our ktlint wrapper that have overlapping features. I won't diverge now

**Comment by atulgpt** [comment]
Hi @cortinico / @3flex so do we want to add the wrapper or not for these new rules?

**Comment by cortinico** [comment]
As mentioned above, I think we should add wrapper for all the rules

**Comment by 3flex** [comment]
It's up for grabs @atulgpt if you want to work on it?

**Comment by atulgpt** [comment]
Sure. Will this conflict with https://github.com/detekt/detekt/pull/6028? Or should I create a PR against your branch?

**Comment by 3flex** [comment]
Yes, it will conflict. I've just pushed the last changes for that PR and don't expect to make any more, so it should be safe to work off that branch until it's merged.

**Comment by atulgpt** [comment]
Hi, @3flex I have created a https://github.com/3flex/detekt/pull/17 against your PR(https://github.com/detekt/detekt/pull/6028).

Although I have a few queries, 1. We already have `ClassNaming`(at https://github.com/detekt/detekt/blob/main/detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/ClassNaming.kt) should we support both rules?
2. While running `./gradlew generateDocumentation` it changed `default-detekt-config.yml` the at https://github.com/3flex/detekt/pull/17/files#diff-f4f2976a0cb59a2678eb657bcd337cd6cb115f5543f02a22ca20b928701f5629R312 is that correct behaviour?
