### ISSUE TITLE
Build: java.lang.AssertionError: Breakpoint wasn't hit within 10000 milliseconds

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5636]
## Expected Behavior
Builds work reliably.

## Observed Behavior
I often get the exception `java.lang.AssertionError: Breakpoint wasn't hit within 10000 milliseconds` when running full builds of detekt or multiple test tasks simultaneously.

## Steps to Reproduce
`./gradlew build` in the detekt project after making a change that impacts several subprojects.

## Context
Trying to work on detekt.

## Your Environment

* Version of detekt used: `main` branch
* Version of Gradle used (if applicable): 7.6
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by schalkms** [comment]
@3flex do you still see this issue?
I haven't seen it so far when building detekt locally on my Mac.

**Comment by 3flex** [comment]
Failed on CI just now: 
https://github.com/detekt/detekt/actions/runs/4765500052/jobs/8471299490#step:4:1
