### ISSUE TITLE
Include summary of baselined issues in report(s)

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5638]
## Expected Behavior
I can see the issues that detekt would have reported if they weren't included in a baseline.

Another option might be to display a count of skipped/baselined issues so there's some visibility, e.g. "Report skipped 86 baselined issue(s)"

## Current Behavior
Baselined issues are silently unreported in all cases.

## Context
From https://github.com/detekt/detekt/issues/5563#issuecomment-1326235897:
> We want all the issues to be visible in regular reports, so they annoy developers, and they get "forced" to fix them.

**Comment by BraisGabin** [comment]
Related with #5607. Could it even be merged?

**Comment by 3flex** [comment]
Apologies, I missed that - this feature wouldn't necessarily be limited to the HTML report only, even though that's likely the only one that would include it. But it makes sense to use your linked issue for tracking.
