### ISSUE TITLE
Unable to retrieve DetektExtension with convention plugin and version catalog

### ISSUE THREAD

**Issue by LinX64** [detekt/detekt#5641]
## Expected Behavior

It seems like in [this PR](https://github.com/detekt/detekt/issues/5205), the user was able to use `DetektExtension`, but mine is integrated with the version catalog.

## Observed Behavior

It cannot retrieve the `DetektExtension`

## Steps to Reproduce

Just use this:

```
class DetektConventionPlugin : Plugin<Project> {

    override fun apply(target: Project) {
        with(target) {
            pluginManager.apply("io.gitlab.arturbosch.detekt")

            val extension = extensions.getByType<DetektExtension>() // what am I missing???


            val libs = extensions.getByType<VersionCatalogsExtension>().named("libs")
            dependencies {
                "detektPlugins"(libs.findLibrary("detekt-formatting").get())
            }
        }
    }
}
```

Source code is also available at: https://github.com/LinX64/CoinCap/pull/26/files

## Context

I am trying to use the version catalog, convention plugin, and integrate Detekt, and configure it only once inside the whole project so that I don't have to repeat the same thing again and again.

More specifically: (the detekt lambda)

```
 detekt {
        config = files("$rootDir/app/config/detekt/config.yml")
        parallel = true
        buildUponDefaultConfig = true
        autoCorrect = true
    }
```

## Your Environment

and here is how I registered it inside the conventional DSL plugins:

**build.gradle.kts:**

```
gradlePlugin {
    plugins {
       register("kotlinDetekt") {
            id = "coincap.kotlin.detekt"
            implementationClass = "DetektConventionPlugin"
        }
}
```

Project level build.gradle.kts:

```
plugins {
    alias(libs.plugins.detekt) apply false
}
```

Version catalog:

```
[Plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
```

Code formatting:

```
# Dependencies of the included build-logic

detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
```

**Comment by cortinico** [comment]
Just looked at your project (thanks for sharing it btw), and the problem is:

```
dependencies {
    compileOnly(libs.android.gradlePlugin)
    compileOnly(libs.kotlin.gradlePlugin)
}
```

that inside your `build-logic/convention/build.gradle.kts` you're not depending on the Detekt Gradle Plugin. Hence you can't access our classes such as `DetektExtension`.

**Comment by shen-david** [comment]
sorry, can i please ask what the specific line to add to the `dependencies` block is?

**Comment by Joao360** [comment]
> sorry, can i please ask what the specific line to add to the `dependencies` block is?

@shen-david you need to define a new dependency on the version catalog (if not there already)
```
detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
```

And then add that dependency to the `build-logic/convention/build.gradle.kts`

```
dependencies {
    compileOnly(libs.android.gradlePlugin)
    compileOnly(libs.kotlin.gradlePlugin)
    compileOnly(libs.detekt.gradlePlugin) // <--- here
}
```
