### ISSUE TITLE
Re-enable test task in detekt-compiler-plugin

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5646]
## Expected Behavior
Tests are run in `detekt-compiler-plugin` project.

## Current Behavior
Tests won't run on Kotlin 1.8 until https://github.com/tschuchortdev/kotlin-compile-testing/issues/336 is fixed.

## Context
Tests were disabled to unblock #5614

**Comment by cortinico** [comment]
> Tests won't run on Kotlin 1.8 until [tschuchortdev/kotlin-compile-testing#336](https://github.com/tschuchortdev/kotlin-compile-testing/issues/336) is fixed.

Small heads up that the upstream issue is actually fixed 👍
