### ISSUE TITLE
Add `ignoreDeprecated` option for all rules to disable analyzing any deprecated functions with that rule. 

### ISSUE THREAD

**Issue by yogurtearl** [detekt/detekt#5662]
For some deprecated functions/classes/properties we don't want to change the implementation because it is going away. 

Would be nice to exclude deprecated functions/classes/properties from some rules.

For example: 
```yaml
  CanBeNonNullable:
    ignoreDeprecated: true
```

should cause `CanBeNonNullable` not to trigger on: 
```kotlin
val oldBusted: Stuff? = newHotness

val newHotness: Stuff = ... 
```

**Comment by BraisGabin** [comment]
Does this work for you?

```yaml
CanBeNonNullable:
  ignoreAnnotated: ['kotlin.Deprecated'] # or just `'Deprecated'`
```

**Comment by schalkms** [comment]
@yogurtearl any feedback here?
Seeing Brais suggestion, I assume this works for you.
