### ISSUE TITLE
Apply input normalization to detekt config yaml

### ISSUE THREAD

**Issue by yogurtearl** [detekt/detekt#5665]
Apply gradle input normalization to detekt config yaml, for example you could remove comments/whitespace, etc. from the yaml during input normalization.

input normalization: https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:configure_input_normalization

**Comment by 3flex** [comment]
Just wondering if you could share a bit about how this would improve your workflow? I know what the feature does, but it seems like we'd have to parse and serialise the YAML file contents in the Gradle plugin to make this work reliably, and I'm not sure there's enough value.

The input normalisation types that Gradle offers out of the box can take advantage of standard Java and Gradle APIs so the cost vs value tradeoff is a bit different to a custom implementation for YAML.

**Comment by yogurtearl** [comment]
Right now, adding/changing a comment to the detekt yaml config invalidates build cache locally and on CI. 
Which may discourage someone from adding/fixing a comment. 
For large builds, that is less that ideal. 

But yeah, understand the tradeoff between effort and value.

**Comment by yogurtearl** [comment]
Still would like to see this implemented.

**Comment by 3flex** [comment]
Are you planning to work on a PR?

I can't speak for all maintainers of course but I think this would be very low on the list of priorities and won't be implemented unless someone decides to contribute.
