### ISSUE TITLE
Enable NamedArguments by default

### ISSUE THREAD

**Issue by mustafaozhan** [detekt/detekt#5677]
The rule or changes you're looking for might have already been suggested!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior of the rule
Arguments should be named by default for long methods, constructors etc.
## Context
With the rise of Jetpack compose both Android and Compose Multiplatform, I think we should re-consider the default value of `NamedArguments`. Currently, people may forget adding them but it is so useful especially in PR reviewing process and readability.

I think the default `threshold` as 3 is not too much to ask.

**Comment by chao2zhang** [comment]
I have hesitation of enabling this rule given its current form depending on the number of arguments - Checking the comments https://youtrack.jetbrains.com/issue/KT-14934 and the in-person conversation with my previous colleagues and current colleagues, there are many perspectives like (e.g. Does Modifier count as an argument that has to be named? What if the function is defined in well-known library where it is more difficult to change?) I would prefer this to be implemented as a compiler plugin, where we know detekt is planning to move towards.

**Comment by BraisGabin** [comment]
I have this rule enabled in the project I work for but I see this rule as a controversial one. And @chao2zhang pointed out it is not only me thinking that. So I think that even I really like this rule I think that we shouldn't enforce it by default.
