### ISSUE TITLE
Properties misspelled or do not exist

### ISSUE THREAD

**Issue by Jultom** [detekt/detekt#5695]
## Expected Behavior
Running detek should not give any errors related to it

## Observed Behavior
Added the recently updated default-detekt-config.yml rulles into my project and when I run detekt, I have the following errors:
<img width="815" alt="Screenshot 2023-01-13 at 16 35 46" src="https://user-images.githubusercontent.com/25204358/212345491-43bab5f9-24b0-4046-a594-a2cd566b88f1.png">

If I remove them from the file and run detekt again, everything works fine.

## Steps to Reproduce
1. use detekt version 1.22.0
2. add the most recent rules from default-detekt-config.yml
3. run detekt

## Your Environment

* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable):gradle-7.3.1
* Verion of OS used : macOS Catalina 10.15.17

**Comment by atulgpt** [comment]
Hi @Jultom `allowOperators` flag is still not added to detekt version 1.22.0 same is true for `ForbiddenAnnotation` rule. These two are targeted for version 1.23.0. You can check the 1.23.0 milestone [here](https://github.com/detekt/detekt/milestone/88?closed=1)

**Comment by BraisGabin** [comment]
Don't copy&paste [default-detekt-config.yml](https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml). Use `./gradlew detektGenerateConfig`. That will create the proper configuration file for your current version and configured plugins.
