### ISSUE TITLE
Exclude new Kotlin Test directories in default config

### ISSUE THREAD

**Issue by remcomokveld** [detekt/detekt#5727]
## Expected Behavior
A project using kotlin's new source directory structure does not enforce rules like `lateinitusage` for files in `src/androidUnitTest/**` and `src/androidInstrumentedTest/**` when using the default configuration.

## Current Behavior

rules that are excluded by tests in the default config should also be excluded in the new test folder structure.

## Context

Kotlin 1.8 introduces a new folder structure https://kotlinlang.org/docs/whatsnew18.html#sourcedirectories

The default detekt configuration file excludes a bunch of different variants of test source sets by default.

It would be nice to either add the new `androidUnitTest` and `androidInstrumentedTest` to those defaults as well, or maybe even better, build in support for defaulting all test source sets to be excluded (not sure how feasible that is).

**Comment by cortinico** [comment]
> It would be nice to either add the new `androidUnitTest` and `androidInstrumentedTest` to those defaults as well, or maybe even better, build in support for defaulting all test source sets to be excluded (not sure how feasible that is).

I believe the best would be to add `**/androidUnitTest/**` and `**/androidInstrumentedTest/**` to our default excludes as suggested 👍

**Comment by chao2zhang** [comment]
Adding this issue the next release milestone as the main branch is already on Kotlin 1.8
