### ISSUE TITLE
Make detekt-cli executable

### ISSUE THREAD

**Issue by mpetuska** [detekt/detekt#5740]
Your feature request may already be reported!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior

detekt-cli jar declares Main field in the manifest and can be run with `java -jar detekt-cli.jar`

## Current Behavior

`MANIFEST.MF` does not contain `Main` field

## Context

Having properly configured manifest would allow for easies use of detekt-cli jar directly.

**Comment by 3flex** [comment]
This won't work though if you're using the standard JAR, because all of detekt's dependencies would have to be manually included on the classpath as well.

The `-all` JAR does set the Main field correctly so that should already work, e.g. `java -jar detekt-cli-1.22.0-all.jar`

**Comment by mpetuska** [comment]
Hmm, is -all jar on maven central too? Couldn't find it

**Comment by 3flex** [comment]
It is: https://repo1.maven.org/maven2/io/gitlab/arturbosch/detekt/detekt-cli/1.22.0/

Also on the GitHub release page: https://github.com/detekt/detekt/releases/tag/v1.22.0

**Comment by mpetuska** [comment]
Awesome, thanks
