### ISSUE TITLE
Sort log output by line then column

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5749]
All warnings are output in order of detekt provider type. They should be logged in order: by line, then column. This makes it easier to review the list of issues detekt finds.

**Comment by BraisGabin** [comment]
This one should be a really easy one. And once #6884 is merged it will be even simplier. All the changes should be done in `MessageCollectorExtensions`. The "more complex" part is to write the tests to ensure that it works.

As a side note, probably sort by `textChar` is easier here and will provide exactly the same effect.

**Comment by neugartf** [comment]
*Working on this
