### ISSUE TITLE
Version 1.22.0 Java Toolchains issue

### ISSUE THREAD

**Issue by CharlieTap** [detekt/detekt#5762]
## Expected Behavior

Detekt succeeds 

## Observed Behavior

 Detekt fails citing 

"> Was passed main parameter ‘--jdk-home’ but no main parameter was defined in your arg class"

## Context

We recently upgraded to 1.22.0 and it broke a java toolchains PR we have in the works. We run the detekt gradle plugin and the previous version works with no issues. 

## Your Environment

* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): 7.5.1
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: MacOS Venture 13.2
* Link to your project (if it's a public repository):

**Comment by 3flex** [comment]
It's hard to know what's going on based on this report & error message alone - a reproducer will help.

**Comment by CharlieTap** [comment]
I'll try my best to get something up for you to test, unfortunately this is on a very large private company repo so it might be challenging to create the exact circumstances 😓
