### ISSUE TITLE
UnnecessaryAbstractClass: add option to only detect interface, not concrete class migrations

### ISSUE THREAD

**Issue by matejdro** [detekt/detekt#5778]
## Current Behavior

UnnecessaryAbstractClass currently serves a double duty:

1. Warn about abstract classes that could be converted to interfaces
2. Warn about abstract classes that could be converted to concrete classes

## Expected Behavior

Split the rule  into two rules or add an option to disable either sub-rule.

## Context

Second rule (converting abstract classes to concrete classes) seems a bit counterintuitive to me. Often I want to mark base classes as abstract, even if they do not have abstract methods, to ensure nobody accidentally constructs them (since they are useless on their own).

With this rule enabled, such abstract classes would get flagged. If I disable the rule, I would also disable the interface part, which I find useful. I could manually suppress every such class, but that would result in a mess.

**Comment by BraisGabin** [comment]
Good idea. This should be an easy one. The code of both rules is already there. We just need to split it.

Proposal for the names:
- `UnnecessaryAbstractClass` -> The `class` can be concrete. Just keep that logic in the current rule.
- `ClassCanBeInterface` -> The `class` can be converted to an `interface`.

The current rule is enabled by default so we can introduce `ClassCanBeInterface` enabled by default too and I think that we don't need a deprecation or anything similar.

@matejdro do you want to give it a try?

**Comment by matejdro** [comment]
Sure, I can give it a go at some point.
