### ISSUE TITLE
Config `checkExhaustiveness` not failing for some missing rules

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#5790]
## Expected Behavior
If `checkExhaustiveness` is set to `true` in the config, and there is a rule not specified, there should be an error/warning.

## Observed Behavior
There is no error or warning.

## Steps to Reproduce
1. Add a config which `checkExhaustiveness` set to `true`
2. Include all rules except `TrailingComma` rules

## Context
At some point I had both `TrailingComma` rules specified in my config to not allow trailing commas. I started getting PRs where there were trailing commas, but detekt wasn't failing (I have `warningsAsErrors` set to `true`). I checked the config, and neither of those rules are present (they must have been removed by mistake).

Removing some other rule (e.g. `EmptyForBlock`) does cause the config to fail.

## Your Environment
* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): 8.0
* Operating System and version: Ubuntu 22.04

**Comment by VitalyVPinchuk** [comment]
@eygraber That's because those rules belong to formatting plugin, whose provider is not an instance of `DefaultRuleSetProvider` which is intentionally filtered here:
https://github.com/detekt/detekt/blob/defabb348b7030811fbfb1722e4118f4fb70335f/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/config/validation/MissingRulesConfigValidator.kt#L75-L80

There're other plugins like `detekt-rules-libraries` and `detekt-rules-ruleauthors`.

Validation of properties for those plugins is also intentionally omitted:
https://github.com/detekt/detekt/blob/defabb348b7030811fbfb1722e4118f4fb70335f/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/config/validation/DefaultPropertiesConfigValidator.kt#L18-L20
  
I don't know the reason behind it but I could fix it if that's what we want. @BraisGabin @TWiStErRob ?

**Comment by TWiStErRob** [comment]
I don't know the history, but I would also expect exhaustiveness check to check for all libraries on the `detektPlugin` configuration classpath, be it first party or third party.

**Comment by BraisGabin** [comment]
I think this is not an issue on `checkExhaustiveness`. Or at least the example was unlucky. `formatting>TrailingComma` is a deprecated rule so probably we are in an exception here. When you have `TrailingComma` on your configuration you should receive a warning. You could enable `warningsAsErrors`.

If that issue also happens with other rules, then we should look at it.

**Comment by eygraber** [comment]
> I had both TrailingComma rules

I'm not using the deprecated `TrailingComma` rule, I'm using the two rules that replace it. Sorry if that wasn't clear. 

In any case, that shouldn't matter because the issue is that those two rules were not present and `checkExhaustiveness` didn't pick up on that. 

I do have `warningsAsErrors` enabled.

**Comment by TWiStErRob** [comment]
@BraisGabin repro:
 * Clone https://github.com/TWiStErRob/repros/tree/master/detekt/checkExhaustiveness-noWarning
 * `gradlew cleanDetekt detekt` -> observe: success (unexpected)

I went through these steps to valid that it's not working as expected.
 * `gradlew detektGenerateConfig`
 * `gradlew cleanDetekt detekt` -> observe: success (expected)
 * Edit detekt.yml: `checkExhaustiveness: true` 
 * `gradlew cleanDetekt detekt` -> observe: success (expected)
 * Edit detekt.yml: comment out a built-in rule
 * `gradlew cleanDetekt detekt` -> observe: success + warning (expected)  
   > Rule '...' from '...' rule set is missing in the configuration.
 * Edit detekt.yml: `warningsAsErrors: true`
 * `gradlew cleanDetekt detekt` -> observe: failure with (expected)
   > Rule '...' from '...' rule set is missing in the configuration.
 * Edit detekt.yml: revert built-in rule and comment out a rule in `formatting` rule set.
 * `gradlew cleanDetekt detekt` -> observe: success (unexpected)

**Comment by VitalyVPinchuk** [comment]
Should it be fixed?

**Comment by cortinico** [comment]
> Should it be fixed?

Yup but I took a brief look at it and realized the fix is most likely a oneliner:
https://github.com/detekt/detekt/pull/5869
