### ISSUE TITLE
Report empty folder

### ISSUE THREAD

**Issue by atulgpt** [detekt/detekt#5814]
## Expected Behavior of the rule
There should be a rule which detects that if an empty folder is present or not. And reports in case of an empty folder. Not sure if this is possible to implement or not.

## Context
While refactoring many times we move files from one code to another module (to modularise the code or for some other purposes). If all files are moved we liked to forget to delete the old folder. Having this rule will prevent this type of scenario

**Comment by BraisGabin** [comment]
That's not possible to do right now. But even if we give the ability to do that I'm not sure about this rule.

Those folders only exist in the local machine, `git` never stores empty folders. And you could use `git clean -fd` to fix all those cases. If you only want to list them `git clean` should do the job.

**Comment by atulgpt** [comment]
Hi @BraisGabin, was not aware of the `git never stores empty folders.`. I think that it should be fine. Closing this issue.
