### ISSUE TITLE
Create a rule to detect common code across if else branch

### ISSUE THREAD

**Issue by atulgpt** [detekt/detekt#5839]
## Expected Behavior
This rule will detect common code across if-else branches which can which simplified using if as an expression of a single parameter.

Adding some examples below:
```kotlin
// uncompliant code
layoutManager = if (someCondition) {
    GridLayoutManager(
        requireContext(),
        resources.getInteger(
            R.integer.color_visualizer_landscape_grid_layout_span_count
        )
    )
} else {
    GridLayoutManager(
        requireContext(),
        resources.getInteger(
            R.integer.color_visualizer_portait_grid_layout_span_count
        )
    )
}

// compliant code
layoutManager = GridLayoutManager(
    requireContext(),
    resources.getInteger(
        if (v.measuredHeight < v.measuredWidth) {
            R.integer.color_visualizer_landscape_grid_layout_span_count
        } else {
            R.integer.color_visualizer_portait_grid_layout_span_count
        }
    )
)
```

```kotlin
// uncompliant code
if (condition1) {
    callFun1()
    logAction()
} else if (condition2) {
    callFun2()
    logAction()
} else {
    callFun3()
    logAction()
}

// compliant code
if (condition1) {
    callFun1()
} else if (condition2) {
    callFun2()
} else {
    callFun3()
}
logAction()
```

## Context
I frequently encounter this issue with users new to Kotlin as they might not be aware of the fact that in Kotlin you can use `if` block as an expression. While the second example is simply a miss which can be pointed out by the `detekt`

Sonar has [similar rule](https://www.sonarsource.com/blog/manage-duplicated-code-with-sonar/) which has a wider scope

This rule can come inside `Complexity Rule Set`

**Comment by BraisGabin** [comment]
I think this rule have a lot of sense but I'm not 100% sure if something like that is a good fit for the standard rule set of detekt. I see it as a third party rule set that could be linked in our [marketplace](https://detekt.dev/marketplace)
