### ISSUE TITLE
`:detekt-compiler-plugin:testPluginKotlinc` never is UP-TO-DATE

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#5847]
The task `:detekt-compiler-plugin:testPluginKotlinc` doesn't declare any output so it is never UP-TO-DATE. This is a slow task so it has impact on the builds: https://ge.detekt.dev/s/yiedfkfac567m/timeline?details=ncqc24rhn4p3m&show-only-critical-path

A fast fix could be create an empty file and declare it as its output. This is an issue instead of a PR doing that because I'm not sure if the task `:detekt-compiler-plugin:testPluginKotlinc` declares correctly its inputs.

**Comment by 3flex** [comment]
Good point... We could write the CLI output to a file (which would help with debugging when there's an issue) but would have to correctly define inputs to make it work correctly.
