### ISSUE TITLE
Refactor DGP off Sarif4k

### ISSUE THREAD

**Issue by cortinico** [detekt/detekt#5864]
Is the remaining action that we should refactor DGP off Sarif4k so that
- Respecting KGP compileOnly dependency
- Not exposing transitive dependency when our client/users depends on KGP

_Originally posted by @chao2zhang in https://github.com/detekt/sarif4k/issues/43#issuecomment-1445413535_

**Comment by chao2zhang** [comment]
There are two ways I can think of
- Depend on simplejson to do lightweight parsing and merging
- Because gradle bundles with GSON or Jackson, we can define the object mapping for Sarif in Gson or Jackson.

**Comment by cortinico** [comment]
> Because gradle bundles with GSON or Jackson, we can define the object mapping for Sarif in Gson or Jackson.

I would prefer this one as it won't bring any extra dependency

**Comment by cortinico** [comment]
Yup that's also an option. Still we use just one method of Sarif4k in DGP, so refactoring might be preferred

**Comment by TWiStErRob** [comment]
I was curious how it would look like, so I raised https://github.com/detekt/detekt/pull/6117.
