### ISSUE TITLE
detekt task failed while using java-19

### ISSUE THREAD

**Issue by anileren5** [detekt/detekt#5866]
Hello everyone,

We are trying to use detekt in our Kotlin project which uses Gradle and Spring Boot. We are using jdk-19. When we try to run detekt task via Gradle. We are getting the following error: 

Invalid value (19) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

Does detekt not support jdk19 or may there be any other workarounds for this ?

Thank you.

**Comment by cortinico** [comment]
> Invalid value (19) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

We actually do support Java 19 (see https://github.com/detekt/detekt/pull/5614) but we haven't made a release yet. You can use `main-SNAPSHOT` in the meanwhile or what for the next stable 👍

**Comment by Hongbo-Miao** [comment]
Upgrading detekt to the new `1.23.0-RC1` works for me now, thanks! 😃
