### ISSUE TITLE
Outdated JSON schema link in the docs

### ISSUE THREAD

**Issue by igorwojda** [detekt/detekt#5879]
This section https://detekt.dev/docs/introduction/configurations/#config-json-schema contains non-working https://json.schemastore.org/detekt URL

Page says:
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

**Comment by cortinico** [comment]
Nice catch. I think the correct link should be https://json.schemastore.org/detekt-1.22.0.json
Would you be up for submitting a PR for the docs to update it @igorwojda ?
