### ISSUE TITLE
"detekt" or "Detekt"

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5898]
## Expected Behavior
Project refers to itself using a consistent name.

## Observed Behavior
I believe `detekt` has been used from the beginning, but I see `Detekt` used more and more in documentation. We should be keeping this consistent.

## Steps to Reproduce
N/A

## Context
I believe @arturbosch named the project `detekt` with lowercase and would want it kept that way.

## Your Environment
N/A

**Comment by VictorIreri** [comment]
I agree and perhaps it could be enforced through an automated check?
I presume the increased use of "Detekt" is because capitalizing names is the norm, and so "detekt" doesn't seem quite right. So maybe styling "detekt" in a particular way across the docs might be an option to satisfy that need to make the name "feel" different. For example by italicizing _detekt_ as we do on this page, although even here it's not consistent.
https://detekt.dev/docs/introduction/configurations/

**Comment by BraisGabin** [comment]
Mixed feelings here:

- If we move to `Detekt` everything would be just easier
- The name of the project is `detekt` and that's it. I'm not sure if we should change it.

I don't know the reason behind `detekt` is not capitalised. But I always assumed that because it started as a `cli`. And as every `cli` it is lowercase.

So, for me, I would treat any `Detekt` as a typo. And, if we want to change it to `Detekt` we should open another issue to decide to "rename".

**Comment by BraisGabin** [comment]
The lower case sometime feels strange. Examples:

> When shipping the detekt Gradle Plugin[...]

Same when it goes at the start of a sentence:

> detekt can be integrated into your development workflow[...]

**Comment by cortinico** [comment]
I believe the name of the project should probably be lowercase. 
This is also consistent with our logo:
![logo](https://raw.githubusercontent.com/detekt/detekt/main/media/icon-text.svg)

When part of another project or a plugin, I think it's fine to go for titlecase:

> When shipping the detekt Gradle Plugin[...]

So this would be Detekt Gradle Plugin. The Detekt Project, The Detekt IntelliJ Plugin, etc.

**Comment by 3flex** [comment]
@arturbosch there are some good considerations raised above, I'm curious what you think.

I've always thought detekt was a stylistic choice that reflects the CLI command name, and this started as a CLI tool, so that made sense. However there's now an extensive list of integrations and some people are naturally gravitating towards the capitalised version anyway.

I do think that whether it's detekt or Detekt, it should be consistent everywhere it's used.

**Comment by arturbosch** [comment]
The name is a wordplay on the verb "to detect sth." and "kt" from Kotlin.
So yes, it was intended as a lowercase `detekt`.
`Detekt` alone always looked wierd to me but Detekt Gradle Plugin looks fine.
The CLI argument sounds reasonable now but wasn't intended back then as Gradle integration was always planned.

> The lower case sometime feels strange. Examples:
> 
> > When shipping the detekt Gradle Plugin[...]
> 
> Same when it goes at the start of a sentence:
> 
> > detekt can be integrated into your development workflow[...]

These are also valid reasons. Italic as @VictorIreri mentioned could work: *detekt* Gradle Plugin.
Or just using uppercase `Detekt` next to other uppercase names.

Btw I quite recently changed to the lowercase detekt spelling in the IJ plugin (which I could change if most maintainers want the uppercase spelling :)):

![Screenshot from 2023-03-13 18-30-22](https://user-images.githubusercontent.com/20924106/225462526-fb6ebefe-b06a-464c-bc9f-6376989773c5.png)

**Comment by TWiStErRob** [comment]
The website then really needs a touch-up... 6 mentions on the home-page, and none of them are lowercase.
![image](https://user-images.githubusercontent.com/2906988/228866056-b9ddc542-8e83-4278-950c-e0ad019c4254.png)
If I wanted to know which way to write it, I would stop here and conclude "Detekt" in all contexts.

**Comment by cortinico** [comment]
> Any reason why the home-home-page doesn't have the logo, @cortinico?

The logo is there in the first block no?

Also my bad, I love uppercase and I used it everywhere. We definitely need to clean this up :) feel free to do it.

**Comment by TWiStErRob** [comment]
> The logo is there in the first block no?

Haha, you got me there, I mean this logo which has the name on it:

https://github.com/detekt/detekt/issues/5898#issuecomment-1469031969

I think the center-mid "Detekt" could be replaced with the named logo.

**Comment by TWiStErRob** [comment]
Raised https://github.com/detekt/detekt/pull/5953 with some "Detekt -> detekt" changes and "Detekt Gradle Plugin" unification.

**Comment by cortinico** [comment]
> Haha, you got me there, I mean this logo which has the name on it:

Yeah you're right :)

**Comment by TWiStErRob** [comment]
Argh, the main "logo" didn't change. It's still a screaming "Detekt" in the middle.

**Comment by TWiStErRob** [comment]
Also the title of the page. I have a feeling these are all one occurrence. 
![Screenshot_20230401-093748](https://user-images.githubusercontent.com/2906988/229275570-ef9848e4-0b18-401c-a946-a27b28122df9.png)

**Comment by TWiStErRob** [comment]
Can someone please rename the org as well? https://github.com/detekt
Because this gives a mixed message:
![image](https://user-images.githubusercontent.com/2906988/229277472-d694a56e-3678-487c-ad89-e2b2e519e813.png)

**Comment by arturbosch** [comment]
> Can someone please rename the org as well? https://github.com/detekt Because this gives a mixed message: ![image](https://user-images.githubusercontent.com/2906988/229277472-d694a56e-3678-487c-ad89-e2b2e519e813.png) ![image](https://user-images.githubusercontent.com/2906988/229277492-024f6ac0-8006-4a0f-ad26-d08b01198efc.png)

Done, thanks for the work!
