### ISSUE TITLE
Website search does not work when embedding the website

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#5900]
## Expected Behavior
I would like to browse the documentation website from inside IntelliJ and use the search to search for rules.

## Observed Behavior

The search inside the embedded website does not work. Tipping does not work. Pasting from clipboard does work however.
Clicking inside the search dialog on the algolia footer opens a new web browser with the algolia website.
The search which seems to be the same as on detekt's website work as a webview.
Do we maybe need to update the search dependency to fix this bug?

![Screenshot from 2023-03-13 18-30-22](https://user-images.githubusercontent.com/20924106/224781363-fa8b97d1-9735-458a-b6b9-410f6625652d.png)

## Steps to Reproduce
1. Install the plugin - https://github.com/detekt/detekt-intellij-plugin/releases/tag/v2.0.0-RC
2. Run the `Show detekt Rules Documentation` action
3. Click the search icon
4. Try to tip something

## Context

I'm currently embedding the documentation and changelog inside the IntelliJ plugin.

![Screenshot from 2023-03-13 18-29-22](https://user-images.githubusercontent.com/20924106/224781120-0199119b-ea4f-4057-9f02-ba0977d96e96.png)

## Your Environment

* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): 8.0.2
* Operating System and version: Linux
* Link to your project (if it's a public repository): https://github.com/detekt/detekt-intellij-plugin

**Comment by cortinico** [comment]
> Do we maybe need to update the search dependency to fix this bug?

I believe this won't be trivial to fix. Does the website works with the IJ built-in browser? Is there a JS Console or anything we can look into to debug this?

**Comment by arturbosch** [comment]
> > Do we maybe need to update the search dependency to fix this bug?
> 
> I believe this won't be trivial to fix. Does the website works with the IJ built-in browser? Is there a JS Console or anything we can look into to debug this?

It looks like the website search is only broken with IJ 2023.1 Beta. Also the dev tools are broken in 2023.1 Beta for me.
2022.3 search and dev tools work, so I guess it might be a JBCefBrowser issue. I will get in touch with the devs.
