### ISSUE TITLE
Naming pattern regexes don't match IntelliJ

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5901]
## Expected Behavior of the rule
Naming rules use regex that aligns to the Kotlin IntelliJ plugin.

## Context
There are properties highlighted in the IDE that are ignored by detekt, for example:

![image](https://user-images.githubusercontent.com/170028/224958673-73105b4a-6906-498a-81d2-80868fb07d6a.png)

The warning says "Private property name 'KOTLIN_FILE_SUFFIXES' should not contain underscores in the middle or the end". This isn't flagged by detekt though.

detekt's regex: `_?[A-Za-z][_A-Za-z0-9]*`
IntelliJ's regex: `_?[a-z][A-Za-z0-9]*`

There may be other discrepancies between them, suggest they all be checked and aligned with IntelliJ.

**Comment by BraisGabin** [comment]
I don't think we should align with IntelliJ. We should align with code conventions: https://kotlinlang.org/docs/coding-conventions.html#property-names

And in the coding conventions that's the correct naming.

**Comment by cortinico** [comment]
Potentially related to https://youtrack.jetbrains.com/issue/KTIJ-24196 (and linked issues). IMHO This is a bug inside IntelliJ

**Comment by 3flex** [comment]
Good points - hopefully this is fixed up in IntelliJ soon.
