### ISSUE TITLE
GeneratorSpec tries to copy files that may be locked for writing

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5902]
## Expected Behavior
Build works reliably.

## Observed Behavior
Because of this:
https://github.com/detekt/detekt/blob/0123e2950137daf75840816435bed989820e5f72/detekt-generator/src/test/kotlin/io/gitlab/arturbosch/detekt/generator/printer/GeneratorSpec.kt#L20-L21

When :detekt-generator:test runs around the same time as either detekt-rules-complexity or detekt-rules-coroutines are building, the task can fail because the files are locked.

## Steps to Reproduce
I think this is only a problem on Windows. I've seen this when the tasks are running in parallel.

## Context
The build should be reliable. Tests should also be self-contained and not rely on input from outside its own module.

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by cortinico** [comment]
> The build should be reliable. Tests should also be self-contained and not rely on input from outside its own module.

+1 to this. We should probably just move the test to use local resources rather than accessing `../`

**Comment by VitalyVPinchuk** [comment]
Hi
How should this be handled?

**Comment by cortinico** [comment]
> How should this be handled?

Practically, instead of copying over things from `../detekt-rules-coroutines`, lets' create a smaller dummy project inside `detekt-generator/src/test/resources` and let's use it for tests

**Comment by VitalyVPinchuk** [comment]
May I fix it?

**Comment by 3flex** [comment]
Help is appreciated! I'll assign to you while you work on a fix - please reply here if you have issues or need to drop it for any reason.
