### ISSUE TITLE
Detekt.jdkHome breaks remote build caching

### ISSUE THREAD

**Issue by ZacSweers** [detekt/detekt#5925]
## Expected Behavior

It should not break build caching

## Observed Behavior

It does because it uses a convention that points to an absolute path, which changes per machine

## Steps to Reproduce

Run detekt with different JDK locations.

The likely solution is to remove the convention here: https://github.com/detekt/detekt/blob/f2cdc1bc0bf772f53be1d85349f79204c3dfe521/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/SharedTasks.kt#L53

## Context

See above

## Your Environment

* Version of detekt used: `1.22.0`
* Version of Gradle used (if applicable): N/A
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): N/A

**Comment by 3flex** [comment]
It's so much the fact that the convention is to set it to an absolute path, but that the `jdkHome` parameter in the task is annotated with `@InputDirectory`.

It could (should?) be changed to `@Internal`, but I'm not sure if we'd then need to consider other attributes as inputs. I believe the Java language version, vendor and implementation are normally considered inputs when toolchains are used, and we'd need them to invalidate the task if the jdkHome input directory isn't tracked as an input.

I think I've just answered my own question, but I'm guessing you're heavy users of the build cache, so I'm interested in what you think is best.

**Comment by ZacSweers** [comment]
Gradle uses just the major version as a cache-invalidating input by default in JavaCompile, not the vendor or implementation. Kotlin uses the same. I think this should be null by default as I believe this is just for kotlinc's analogous option and that is also optional.

**Comment by cortinico** [comment]
> It could (should?) be changed to `@Internal`,

I think we should just change it to `@Internal` and this issue will solve itself. We already account for JDK version for the sake of cache invalidation

**Comment by ZacSweers** [comment]
Note this also affects `DetektCreateBaselineTask`
