### ISSUE TITLE
bug in link for GlobalCoroutineUsage error msg

### ISSUE THREAD

**Issue by kenyee** [detekt/detekt#5949]
## Expected Behavior
I expect the error message to link to the correct docs.
The correct link is here: https://detekt.dev/docs/rules/coroutines/#globalcoroutineusage

## Observed Behavior
Message is:
GlobalCoroutineUsage This use of GlobalScope should be replaced by CoroutineScope or coroutineScope.
See [detekt.github.io#globalcoroutineusage](https://detekt.github.io/detekt/style.html#globalcoroutineusage)

The link to https://detekt.dev/docs/rules/style/#globalcoroutineusage is incorrect.

## Steps to Reproduce
Write code that uses GlobalScope and click on the link in the error msg and test it.

## Context
Error msgs surfaced to users think it's confusing.

## Your Environment
* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): 7.5

**Comment by BraisGabin** [comment]
Where did you find that link? Do you want to give it a try and fix it?

**Comment by kenyee** [comment]
more bad links emitted in the error msgs (pretty much all the coroutine rules I think are emitting wrong URLs).
https://detekt.github.io/detekt/style.html#suspendfunwithflowreturntype
https://detekt.dev/docs/rules/style/#sleepinsteadofdelay
https://detekt.dev/docs/rules/style/#redundantsuspendmodifier
https://detekt.dev/docs/rules/style/#injectdispatcher
https://detekt.dev/docs/rules/style/#globalcoroutineusage

I can have a look at submitting a PR to fix this...I thought you might want to add aliases to the web site instead and then realized you're just letting github server your docs 😄

**Comment by kenyee** [comment]
FYI, this is in the debug.html file that's generated (we scrape the HTML report and insert the msgs into our PR)...it's not in debug.xml and it's also not in the rule's code 🤔

**Comment by kenyee** [comment]
Ahh..it turned out to be a bug in our code...we hardcoded the path because it's not available in the XML report.
It is in the HTML report though:
https://github.com/detekt/detekt/blob/main/detekt-report-html/src/main/kotlin/io/github/detekt/report/html/HtmlOutputReport.kt#L126

Would it be ok to add this to the XML report?
If not, maybe rename the rules so they include the group in the rule name?
detekt.style.TopLevelPropertyNaming instead of just detekt.TopLevelPropertyNaming?

**Comment by kenyee** [comment]
We currently use this to generate a link and it used to work:
"[detekt.github.io#$anchor](https://detekt.github.io/detekt/style.html#$anchor)"
where anchor is the rule name minus the "detekt." prefix.

**Comment by BraisGabin** [comment]
The xml is a implement of checkstyle. And I'm not sure if that format allows an URL.

Any way, I think that you should check the sarif format. It contains way more information than xml. And I'm taking from the top of my head but I think that it contains urls already.

**Comment by kenyee** [comment]
It's just XML tags with attributes...the mandatory attribute/tag names have to stay the same to match the checkstyle ones, but that doesn't mean we can't add new ones :-)

I'm suggesting adding an attribute named "helpURI" to the XML issues to match what Sarif format does:
https://github.com/detekt/detekt/blob/main/detekt-report-sarif/src/main/kotlin/io/github/detekt/report/sarif/RuleDescriptors.kt#L51

**Comment by chao2zhang** [comment]
I would agree with @BraisGabin that we are just mimicking the behavior of checkstyle/XML https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java.

I would recommend migrating your scripts to use Sarif because Sarif has schema, a committee and tooling in its ecosystem, along with Github integration. XML is loosely defined and I think we are intentionally trying to keep it simple.

**Comment by TWiStErRob** [comment]
I agree, use the Sarif report with the upload-sarif action, live example here:
https://github.com/TWiStErRob/net.twisterrob.gradle/actions/runs/4599672377/workflow#L83
And example finding:
https://github.com/TWiStErRob/net.twisterrob.gradle/security/code-scanning/1894
Also as comment on PR:
https://github.com/TWiStErRob/net.twisterrob.gradle/pull/450
If this output is not to your liking, you can parse the Sarif file, it has all the rules and their ruleset IDs along with help URLs. For example the finding above is in `test/build/reports/detekt/detekt.sarif` inside [`Detekt Reports.zip`](https://github.com/TWiStErRob/net.twisterrob.gradle/suites/11998298356/artifacts/630023077) on [workflow run](https://github.com/TWiStErRob/net.twisterrob.gradle/actions/runs/4599672377).

Going from checkstyle XML to sarif with your custom integration should be trivial as JSON parsing is easier than XML :)

**Comment by kenyee** [comment]
True..thanks.
At the time this parser was written, the Detekt sarif format didn't exist.  Was thinking that'd be the best thing to do as well.

**Comment by kenyee** [comment]
Switched to Sarif format and there are still broken links FYI :-)
https://github.com/detekt/detekt/issues/5964
