### ISSUE TITLE
Update from 1.18.0 to 1.22.0 fails with "Property 'formatting' is misspelled or does not exist"

### ISSUE THREAD

**Issue by oshai** [detekt/detekt#5960]
## Expected Behavior
Compilation works

## Observed Behavior
build fails

## Steps to Reproduce
see the PR: https://github.com/oshai/kotlin-logging/pull/295

## Your Environment
github actions CI.

**Comment by 3flex** [comment]
Can you please make a good faith effort to fill out the template. I suspect I know what the issue is, but a build scan will confirm it.

**Comment by oshai** [comment]
I tried to do that, but gets the error:
```
The build scan was not published due to a configuration problem.
```
If it helps I can run it on previous version.

**Comment by BraisGabin** [comment]
I imagine that you are not using the formatting plugin of detekt but you have configuration for it. Just remove the formatting configuration from your configuration file.
