### ISSUE TITLE
UnsafeCallOnNullableType is not working

### ISSUE THREAD

**Issue by alexcibotari** [detekt/detekt#5967]
## Expected Behavior
By enabling **UnsafeCallOnNullableType** I expect that ``!!`` will be not allowed.

## Observed Behavior
``!!`` is still allowed in code, even properly is optional.

## Steps to Reproduce
exact code from the documentation
``
  fun foo(str: String?) {
    println(str!!.length)
  }
``

## Your Environment

* Version of detekt used: **1.21.0**
* Version of Gradle used (if applicable): **8.0.2**
* Operating System and version: **Windows 11**

**Comment by atulgpt** [comment]
Hi @alexcibotari I think you are running the `detekt` w/o type resolution(i.e., plain `./gradlew detekt`). While `UnsafeCallOnNullableType` requires type resolution. Can you add your gradle setup for the detekt?

**Comment by alexcibotari** [comment]
Can you please provide example of it

**Comment by cortinico** [comment]
> Can you please provide example how exactly should I run it.

You should be fine by invoking `detektMain` instead of `detekt`
More on this: https://detekt.dev/docs/gettingstarted/type-resolution/#enabling-on-a-jvm-project
