### ISSUE TITLE
version.properties in jar root may cause issues with other plugins 

### ISSUE THREAD

**Issue by madorb** [detekt/detekt#5968]
Ran into issues when applying both detekt and OpenWrite gradle plugins. Depending on the _order_ the plugins were declared the behavior was different. 

This turned out to be because both expect a `versions.properties` in the root of the classpath, and there were conflicts. Ideally both would scope this a plugin-specific path directory. 

Please see details at https://github.com/openrewrite/rewrite-gradle-plugin/issues/189

## Expected Behavior
{{versions.properties}} from one plugin should not conflict with another

## Observed Behavior
OpenRewrite would fail if applied after detekt, because it would manage to load the `versions.properties` file from detekt, which did not have the information it expected. 

## Steps to Reproduce
See: https://github.com/openrewrite/rewrite-gradle-plugin/issues/189
Create Project, apply detekt followed by openrewrite. 
Run `./gradlew rewriteDry`

## Context
Leads to inconsistent order-dependent bugs. 

## Your Environment

* Version of detekt used: latest
* Version of Gradle used (if applicable): any

**Comment by cortinico** [comment]
Yup we should either move to `detekt/versions.properties` or `detektversion.properties` to prevent this
