### ISSUE TITLE
New Rule proposal: Use `String.toBigDecimalOrNull` instead of `BigDecimal(String)` constructor.

### ISSUE THREAD

**Issue by yogurtearl** [detekt/detekt#5977]
`BigDecimal(String)` constructor throws a `NumberFormatException` which is bad for performance and doesn't get caught by the type system, so might only be caught at runtime. 

`String.toBigDecimalOrNull` checks the value with a regex and avoids throwing an exception internally whenever possible. 

By returning `null` the compiler forces the user to handle the null case and avoids the runtime exception.

**Comment by schalkms** [comment]
@yogurtearl did you try using the `ForbiddenMethodCall` for this case? I don't think a new rule is necessary for implementing this use case.

**Comment by cortinico** [comment]
You can use the `reason` field to specify why a certain method is blocked:
https://github.com/detekt/detekt/blob/f7a45932238e1f6b10ec93ffcc9ecce80c8e0309/detekt-core/src/main/resources/default-detekt-config.yml#L579-L585

**Comment by BraisGabin** [comment]
I think that what @yogurtearl mean is that the rule proposal is not just for himself. It would be good for the Kotlin community to have that as a default.

We talked before that we should have a rule set for the Kotlin Standard Library. And I think that something like this would be a great addition. With 2.0 and the ability to have multiple instances of the same rule we could have forbidden method call with a big list of forbidden methods and their counterpart.

**Comment by cortinico** [comment]
Ah I understand. How about we edit the default `methods` for `ForbiddenMethodCall` adding a clause for this?

**Comment by schalkms** [comment]
In my opinion, this should be a default setting for `ForbiddenMethodCall` but not a new separate rule.
Note that this issue is also flagged by other static analysis tools in the Java universe

**Comment by BraisGabin** [comment]
Yes, I think that would work.

I was suggesting the other option because our override of lists is confusing. Because if you add one you need to copy the default ones too or you lose them. But that's a different issue. I think this is open to grab by anyone and implement it.

**Comment by atulgpt** [comment]
Hi, @BraisGabin can you clarify your statement `I was suggesting the other option because our override of lists is confusing. Because if you add one you need to copy the default ones too or you lose them.`?

**Comment by BraisGabin** [comment]
If you, as a user of detekt has forbidden method call enabled active you will get this method forbidden. But if then you define your own forbidden method you lose the default values because the lists are not merged. We override them.

**Comment by atulgpt** [comment]
> If you, as a user of detekt has forbidden method call enabled active you will get this method forbidden. But if then you define your own forbidden method you lose the default values because the lists are not merged. We override them.

Got it. That is really problematic. We should define some kind of placeholder `defaults` which appends `detekt` defined defaults.

Also is there any bug to tracj this?

**Comment by BraisGabin** [comment]
I think that there is not.

**Comment by atulgpt** [comment]
Hi, @BraisGabin @yogurtearl I have added this method to `ForbiddenMethodCall` as there is already one call `java.math.BigDecimal.<init>(kotlin.Double)` present there. Also for `java.math.BigDecimal.<init>(kotlin.Double)`
I have removed the recommendation to use `java.math.BigDecimal.<init>(kotlin.String)` with `String.toBigDecimalOrNull()`
And shorten the reason string to remove `init` in case of constructor and `kotlin.` in case of `Double` and `String`
