### ISSUE TITLE
UnnecessarySafeCall is not working in Android

### ISSUE THREAD

**Issue by IResetic** [detekt/detekt#6011]
## Expected Behavior

In my Android app I am using detekt as static analsys tool. I expect that unnecessary safe calls are detected.

Here is an example code:

data class First(
    val language: String,
    val time: String
)

data class Secound(
    val first: First,
    val name: String,
)

and here is the code where I use it and exepect that unnecessary safe call is detected (I have called this from onCreaet method in MainActivity):
        val a = First(language = "Hr", time = "Now")
        val b = Secound(first = a, name = "Test")

        b.first?.language 

## Observed Behavior

The unnecessary safe call is detekted.

## Steps to Reproduce

Use the code snippets in Android project.

## Your Environment

* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): 7.5
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: 
* Link to your project (if it's a public repository):

**Comment by 3flex** [comment]
Which task are you running? If it's not one of the tasks that use type resolution then this rule won't work.

**Comment by 3flex** [comment]
https://detekt.dev/docs/gettingstarted/type-resolution#enabling-on-an-android-project

**Comment by cortinico** [comment]
(Closing as the answer was provided)
