### ISSUE TITLE
Naming convention mismatch in `gradle.properties` config name

### ISSUE THREAD

**Issue by atulgpt** [detekt/detekt#6017]
## Expected Behavior
In `detekt` we have two `gradle.properties` `detekt-dry-run` and `detekt.use.worker.api`. Both should use the same naming convention. 

## Observed Behavior
Both use a different naming convention. I am not sure if `detekt-dry-run` is expected to be used by `detekt` clients or not. As same is not documented on the website. If this is for internal use then it is fine o/w we should match the naming convention

**Comment by 3flex** [comment]
detekt-dry-run is only for internal use in our tests.

There's also `detekt.android.disabled` for public use but that's already close to the name for the worker API property.

**Comment by BraisGabin** [comment]
The this is working as expected. Thanks for the heads up!
