### ISSUE TITLE
Certain Detekt rules not working - Detekt gradle plugin v1.21.0

### ISSUE THREAD

**Issue by ashish29dec** [detekt/detekt#6068]
## Expected Behavior
The following rules should show violations in the code when running `./gradlew detekt`
- `NoNameShadowing`
- `AvoidReferentialEquality`
- `DoubleMutabilityForCollection`
- `HasPlatformType`

## Observed Behavior
Running `./gradlew detekt` does not show violation of any of the rules listed above even though I used the non-compliant code from Detekt's Rule documentation page.
Running `./gradlew detektBaseline` also generates baseline but these violations are not listed.

## Steps to Reproduce
Attaching the sample Android project I created and tested the following rules do not work. I am using detekt gradle plugin version 1.21.0.
The above mentioned rules are enabled in the `config/detekt/detekt.yml` file
Baseline does not list any of the violations of mentioned rules (`app/detekt-baseline.xml`)

Run `./gradlew detekt` only shows the violation of `InstanceOfCheckForException` which was intentionally added to make sure that the command is working but none of the other rules show up.
I have added different functions in the code (`DetektTest.kt`) each containing non-compliant code for each of the rule mentioned.

## Context
I am trying to enable these rules in our codebase. However, enabling these rules does not work and none of the violations are caught or flagged causing code smells to creep in the codebase

## Your Environment

* Version of detekt used: 1.21.0
* Version of Gradle used (if applicable): Gradle 7.4
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/vlffzsrwq36aw
* Operating System and version: macOS 13.3.1 
* Link to your project (if it's a public repository):
[DetektTest.zip](https://github.com/detekt/detekt/files/11377682/DetektTest.zip)

**Comment by atulgpt** [comment]
`./gradlew detekt` runs without type resolution; these rules require type resolution. See https://detekt.dev/docs/gettingstarted/type-resolution/

**Comment by cortinico** [comment]
> `./gradlew detekt` runs without type resolution; these rules require type resolution. See [detekt.dev/docs/gettingstarted/type-resolution](https://detekt.dev/docs/gettingstarted/type-resolution/)

Closing as this is the correct answer 👍
