### ISSUE TITLE
Add ignore "callee function" configuration support for NamedArguments rule

### ISSUE THREAD

**Issue by hrach** [detekt/detekt#6081]
Currently, we're enabling NamedArguments rule, which is excellent. But we would like to suppress the rule in certain cases - globally.

So we would utilize the possibility to suppress specific function calls not to be forced to use named arguments, when they're over the threshold. Specific cases from our codebase:

Most importantly it is about some calls that could utilize varargs, but for some reason, they cannot:

- [Flow.combine()](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/combine.html)
- [Flow.combineLatest()](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/combine-transform.html)

**Comment by cortinico** [comment]
Can you elaborate on why those 2 functions needs an exception?

As a workaround, I can suggest to look at our suppressors:
https://detekt.dev/docs/introduction/suppressors/
and use an annotation/function to suppress the offending callsites (if they follow a pattern)

**Comment by hrach** [comment]
> Can you elaborate on why those 2 functions needs an exception?

Our code is forced to add named args when they bring a little value, instead they prolong the line.

```kotlin
class MyVm() {
  val property: Flow<...> = combine(
    flow = myRepostory.flow.onStart {},
    flow1 = anotherUseCase(),
    flow2 = .......
  ) { a, b, c ->
  }
}
```

Yes, we can suppress locally, but that's on devs decision and it is not normalized/centralized. 

I have no idea how to suppress this otherwise.

The point is, those use cases are practically a vararg (currently being skipped in the rule), but from technical reasons they are implemented this ways - as there is no generic vararg support in kotlin.

**Comment by cortinico** [comment]
> The point is, those use cases are practically a vararg (currently being skipped in the rule), but from technical reasons they are implemented this ways - as there is no generic vararg support in kotlin.

It feels oddly specific to your use case, I would potentially suggest forking this rule and re-implement it to fit your requirements.

If `MyVm` is always annotated with a given annotation (like `@Composable` you can use the `ignoreAnnotated` suppressor).

**Comment by BraisGabin** [comment]
Closing in favor of #5510
