### ISSUE TITLE
Add customMessage field for each rule in detekt-config.yaml

### ISSUE THREAD

**Issue by kenyee** [detekt/detekt#6083]
## Expected Behavior
add a customMessage field in the configuration file for each lint rule; allow substitution variables for the URL links to the original Detekt help pages.

## Current Behavior
Detekt's line error messages are static to the rule.

## Context
Sometimes we want to add additional context to an error related to the codebase or maybe a more detailed comparison about how to use it in our codebase.  E.g., the coroutine dispatcher inject rule...we would be able to add an example of how to use it in our codebase.

**Comment by cortinico** [comment]
Are you referring to custom rule? If so, you can achieve this exact behavior by using `valuesWithReason` in your config fields:

https://github.com/detekt/detekt/blob/e41f9f23d5b5c86f86f41d512563eea8931665e3/detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenMethodCall.kt#L71

Some of the Detekt rules use this feature like `ForbiddenMethodCall`

**Comment by BraisGabin** [comment]
And if you mean to change the description for a current rule on detekt that could be made with a plugin. [`ReportingExtension`](https://github.com/detekt/detekt/blob/main/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/ReportingExtension.kt) is what you are looking for. That API gives you all the findings that detekt found and let you manipulate them.

I wouldn't implement something like that on detekt because I think that few people will use it but it should be doable with an extension and we could link it on our marketplace if someone else want to use it.

**Comment by kenyee** [comment]
I mean for current rules, not custom ones (hence the InjectDispatcher example).
The ReportingExtension looks like it might be useful.  
Any docs or examples?  I couldn't find anything on the doc site or a test sample on how to use it...

**Comment by BraisGabin** [comment]
You are right, we don't have too much documentation about that. Luckly the baseline mechanism on detekt is made using it so there are examples.

- https://github.com/detekt/detekt/blob/main/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineResultMapping.kt
- https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/META-INF/services/io.gitlab.arturbosch.detekt.api.ReportingExtension

Those are the two key files that make this work. The complete implementation of baseline is here: https://github.com/detekt/detekt/tree/main/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/baseline

I must say that I never used this API so any help with the documentation is also welcome.

**Comment by BraisGabin** [comment]
Closing as this can be archived with a third party plugin. If you end up implementing it, please add it to our marketplace so anyone can use it.

Also we are more than happy to receive PRs or issues to improve specific rule messages.
