### ISSUE TITLE
Add instructions to use detekt with SDKMAN!

### ISSUE THREAD

**Issue by helpermethod** [detekt/detekt#6086]
## Expected Behavior
The Detekt CLI can be installed via SDKMAN!.

I've just noticed that the Detekt CLI ZIP file has just the correct format to be published to SDKMAN!. Not sure how many users are actually using the CLI, but as some of those are probably using SDKMAN! already, it would be nice if they could install the Detekt CLI via SDKMAN!, too!

New releases could be added manually via SDKMAN!'s [DB Migrations](https://github.com/sdkman/sdkman-db-migrations) project or, preferably, automatically via SDKMAN!'s [Vendor API](https://sdkman.io/vendors) (which is pretty easy to do with JReleaser).

## Current Behavior
The Detekt CLI can be installed via SDKMAN! (yet)

## Context
sdk install detekt

**Comment by BraisGabin** [comment]
I know that we are already on `brew` and other tools without any first party support. Would that be also possible for SDKMAN!? Our current release process is kind of difficult so I don't think that we could take any new step. But if someone wants to do it we will be more than happy. And then a PR to note that on our documentation would be great too.

**Comment by helpermethod** [comment]
Hi @BraisGabin!

I've added Detekt as a community-supported candidate.

**Comment by 3flex** [comment]
Nice! I think this issue can then be repurposed to add a reference to our docs if/when that PR is merged.

**Comment by 3flex** [comment]
https://sdkman.io/sdks#detekt

Documentation can be updated now.

**Comment by cortinico** [comment]
> Hey, I would like to work on this task if it is still available.

Yup I've assigned it to you 👍
