### ISSUE TITLE
`ForbiddenImport` rule: Remove `forbiddenPatterns` config property

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#6090]
## Context

The documentation of the `ForbiddenImport` rule could and should be approved upon. This is addressed in #6088. 

But apart from the documentation to me there is no clear value of having two so very similar configuration properties such as:
* `imports`: the list of imports that are not allowed in _glob_ format (plus a reason).
* `forbiddenPatterns`: a single regex that describes all patterns that are not allowed.

Not only is the naming of the second suboptimal it offers little more flexibility over the first. I would argue that everything that can be specified with `forbiddenPatterns` can be expressed with `imports` instead.

## Proposal
* Mark `forbiddenPatterns` as deprecated in 1.x
* Remove `forbiddenPatterns` in 2.x

**Comment by marschwar** [comment]
Can we agree that we at least mark `forbiddenPatterns` as deprecated or does anyone see a use case that relies on it?

**Comment by TWiStErRob** [comment]
A use case is where the power of regex outweighs glob patterns. e.g. lookarounds, case sensitive/insensitive matching, character classes, etc.

For example:
 * forbid most subpackages, but a few whitelisted ones
 * forbid using classes from relocated packages, but with a whitelist or blacklist for parent package.
 * forbid using any unicodely named classes from other libraries

Probably not common cases, but they might exist.

Note: [what people are using in GitHub hosted code](https://github.com/search?q=+language%3AYAML+ForbiddenImport+forbiddenPatterns+NOT+%2FforbiddenPatterns%3A+%28%22%22%7C%27%27%29%2F&type=code&l=YAML) // gotta love the new GH search!
 * Most of them are false using `.*` as a glob ending, but they're lucky
 * and then there are the lookarounds/whitelistes I mentioned:
   * `io\.kotest\.core\.spec\.style\.(?!BehaviorSpec)`
   * `androidx\.compose\.material\.(?!icons)`
