### ISSUE TITLE
Invalid JVM target?

### ISSUE THREAD

**Issue by JordanLongstaff** [detekt/detekt#6100]
I've configured Detekt to use JDK 17 as the JVM target...

In the project's `build.gradle` file:

```
ext {
    java_version = JavaVersion.VERSION_17
}
```

In the module's `build.gradle` file:

```
def buildConfig = rootProject.extensions.getByName("ext")

tasks.withType(Detekt).configureEach {
    jvmTarget = buildConfig.java_version
}
```

So in theory this should work, yet when I try to run a task I get this error:

```
Execution failed for task ':app:detektBaseline'.
> Invalid value (19) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
```

Why is it trying to use version 19 if I've specified version 17?

**Comment by JordanLongstaff** [comment]
Hmm, actually, if I run the task from Android Studio it works...but it doesn't work if I use `gradlew`.

**Comment by JordanLongstaff** [comment]
I do have this in my module's `build.gradle`:

```
compileOptions {
    sourceCompatibility buildConfig.java_version
    targetCompatibility buildConfig.java_version
}

kotlinOptions {
    jvmTarget = buildConfig.java_version.toString()
}
```

Your example configures the `KotlinCompile` tasks, so it's a bit different, but is there any reason this shouldn't work?

**Comment by atulgpt** [comment]
```
kotlinOptions {
    jvmTarget = buildConfig.java_version.toString()
}
```
will not work for `kapt`. This behaviour got changed recently in Kotlin where now you need to configure `jvmTarget` for each kotlin tasks

**Comment by JordanLongstaff** [comment]
OK well, I just tried your suggestion and it didn't work. I got the same error.

**Comment by JordanLongstaff** [comment]
Oh. I had to actually _run_ `compileDebugKotlin` too.

It works now, thanks! 👍
