### ISSUE TITLE
Rule to disallow `iterable.any { it == <some_value> }` in favor of `iterable.contains(<some_value>)`

### ISSUE THREAD

**Issue by atulgpt** [detekt/detekt#6106]
## Expected Behavior of the rule
`iterable.any { it == <some_value> }` is similar to `iterable.contains(<some_value>)`. Using `iterable.any { it == <some_value> }` complicates the code as the user expects that usage of `any` might follow some complicated `predicate`.

We also have a similar rule in the `detekt` `UseSumOfInsteadOfFlatMapSize` which  enforces similar type of usages

**Comment by BraisGabin** [comment]
I like it! I think it would be a really good addition.

What do you think about: `iterable.find { it == <some-value> } == null`? Should this rule also warn about that?

**Comment by atulgpt** [comment]
Hi @BraisGabin I think there is already a rule `UseAnyOrNoneInsteadOfFind` which suggests `iterable.find { it == <some-value> } == null` to be written as `iterable.any { it == <some-value> }` and which in turn reported by this rule.
Although this would be two step process alternative would be to report this type of structure as well which will result in two violations for a single line of code(of which first one is unnccessary)

**Comment by BraisGabin** [comment]
You are right. Forget about my comment.

**Comment by atulgpt** [comment]
Hi @BraisGabin I have created the PR for the implementing this rule
