### ISSUE TITLE
StringLiteralDuplication: have a option to specifiy how many characters to ingore

### ISSUE THREAD

**Issue by atulgpt** [detekt/detekt#6140]
## Expected Behavior
There should be one config in the rule to set the number of characters to ignore. Currently, there is `excludeStringsWithLessThan5Characters` that is a limiting config as it assumes `5` characters to be the threshold.

Also, we can have the same behaviour from the regex `ignoreStringsRegex` config as well but having the same with a different config will be easier to use
## Current Behavior
There is no similar config

## Context
In the code base, I found some symbols like `"="`, `"&"` and `"%"` to be used for making queries in the backend. To our project it doesn't make sense to refactor all those usages to `EQUAL_OPERAROR` or in similar names

**Comment by cortinico** [comment]
Are you suggesting we deprecate `excludeStringsWithLessThan5Characters` and add a `charactersThreshold` property?

**Comment by atulgpt** [comment]
Hi, @cortinico yes as `excludeStringsWithLessThan5Characters` will be meaning less after `charactersThreshold`.
