### ISSUE TITLE
`UnusedPrivateProperty` should respect `Suppress("Unused")`

### ISSUE THREAD

**Issue by lwasyl** [detekt/detekt#6143]
## Expected Behavior of the rule
Currently to suppress `UnusedPrivateProperty`, one has to use the name explicitly (`Suppress("UnusedPrivateProperty")`. However, similar inspection implemented by Kotlin compiler can be suppressed with `@Suppress("Unused")`. 

Currently to avoid both Detekt errors and compiler warnings, one has to suppress two warnings, even though they mean the same thing. It'd be nice to be able to use only `@Suppress("Unused")` instead

**Comment by TWiStErRob** [comment]
The rule already has that alias:

https://github.com/detekt/detekt/blob/dcfb8415c3ae9864d9e25226faebd26713bdab90/detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateProperty.kt#L52C8-L54

If you use lower-case `"unused"`, does it work?

**Comment by cortinico** [comment]
> The rule already has that alias:

Closing because of this
