### ISSUE TITLE
Support for merging HTML reports

### ISSUE THREAD

**Issue by artsmvch** [detekt/detekt#6178]
## Expected Behavior
I want to be able to merge HTML reports like it can be done to `xml` and `sarif` reports [here](https://detekt.dev/docs/introduction/reporting#groovy-dsl).

## Current Behavior
As for the latest version 1.23.0, the `ReportMergeTask` task can only merge `xml` and `sarif` reports.

## Context
It would be nice to have a single HTML report where I could see findings across all modules.

**Comment by kvn-stgl** [comment]
Related to #5034
