### ISSUE TITLE
Custom rules not working

### ISSUE THREAD

**Issue by snitsaruk** [detekt/detekt#6194]
## Expected Behavior
The sample project with the issue can be found here: https://github.com/snitsaruk/DetektExample
I created a custom rule in a multimodule Android project. 
The rule is in a separate kotlin module, that also contains:
- A ruleset provider
- A provider package name in the file: `resources/META-INF/services/io.gitlab.arturbosch.detekt.api.RuleSetProvider`

The detekt custom ruleset is added into the config file and there's no `Property misspelled or does not exist` error.

When I run `detekt` or `detektAll` task, detekt works fine but the custom rule is not reported.
I also tried doing `gradle --stop` before running detekt, and tried running detekt using
`gradle detektAll --no-build-cache --no-configuration-cache`. It also didn't work.

## Steps to Reproduce
- Clone the example project https://github.com/snitsaruk/DetektExample
- Execute detekt
- Observe that custom rule is not reported

## Context
I'm trying to add a custom rule to an Android project with dozens of modules. 
I added a custom rule and first I had `Property misspelled or does not exist` error for my custom ruleset. I was able to fix it but now I'm facing another issue - seems like the rule is not executed.
I've created a sample project that has the same issue.

Any help is much appreciated 🙏🏻 

## Your Environment

* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): 8.0
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: Mac OS 13.0
* Link to your project (if it's a public repository): https://github.com/snitsaruk/DetektExample

**Comment by snitsaruk** [comment]
I just tried switching to the recommended tool versions and unfortunately, it didn't help, the rule is still not executed.
<img width="832" alt="Screenshot 2023-06-08 at 12 47 31" src="https://github.com/detekt/detekt/assets/11797388/113e9d7d-ff6b-4959-8548-0659f3fd1685">

**Comment by BraisGabin** [comment]
Why don't you use our template to create the custom rule? There are a lot of things that can go wrong with the configuration. I have 3 different third party plugins applied on detekt and they work as expected.

**Comment by snitsaruk** [comment]
> Why don't you use our template to create the custom rule? There are a lot of things that can go wrong with the configuration. I have 3 different third party plugins applied on detekt and they work as expected.

Hey @BraisGabin, thanks for your answer.
While comparing my setup to the template, I discovered I was missing the `config/config.yml` file in the module with the custom rule, where my custom rule was activated. I was adding it only on the main config at the root of the project, and that's why the rule wasn't active.
