### ISSUE TITLE
Configure danger to help the PRs that only update the versioned documentation

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#6228]
## Expected Behavior
When someone does a change in the versioned documentation they should also change the not versioned one. 

## Current Behavior
There is no way a contributor could know that. 

## Proposed solution
Configure danger so it adds a comment to inform about this with a proper explanation. A link to which file should be also modified would be great.

I'm not sure if possible but, if we could try to apply the diff to the not versioned one and it does not have conflicts add it as a suggestion would be really neat! This way a maintainer could just click to merge it and close the issue faster.

**Comment by cortinico** [comment]
> When someone does a change in the versioned documentation they should also change the not versioned one.

Have you noticed this happening? Do you have a link to the PR where this happened?

**Comment by BraisGabin** [comment]
Here you have 3 instaces of these:
https://github.com/detekt/detekt/pull/6226#discussion_r1232408253
https://github.com/detekt/detekt/pull/6166#issuecomment-1568292024
https://github.com/detekt/detekt/pull/6016#issuecomment-1516141630

**Comment by cortinico** [comment]
> Here you have 3 instaces of these: [#6226 (comment)](https://github.com/detekt/detekt/pull/6226#discussion_r1232408253) [#6166 (comment)](https://github.com/detekt/detekt/pull/6166#issuecomment-1568292024) [#6016 (comment)](https://github.com/detekt/detekt/pull/6016#issuecomment-1516141630)

Thanks for referencing. I've implemented it here: https://github.com/detekt/detekt/pull/6412
Hopefully this will catch most of the invalid scenarios
