### ISSUE TITLE
Excluded files affects scanning speed

### ISSUE THREAD

**Issue by illuzor** [detekt/detekt#6240]
## Expected Behavior
Detekt runs fast with skipping excluded folders and files.

## Observed Behavior
Detekt checks all files, even if they are excluded and it takes a very long time

## Steps to Reproduce
-

## Context
I have a big android project with many modules. Each module folder contains **build** folder generated by gradle, which contains huge amount of generated files. All build directories are added to excludes with `**/build/**`.
If project is fresh without **build** directories, detekt task ends in 30 seconds.
When **build**  folders are present, detekt task ends in 5-10 minutes depends on machine.
I looked at the code of detekt and found out the problem is in include-exclude mechanism itself. Detekt takes every file even in and checks it path to include\exclude paths.
So if project contains giant amount of files in excluded directories, it significantly increases scanning time.

## Your Environment
* Version of detekt used:  v1.22.0, v1.23.0
* Version of Gradle used (if applicable): 8.1.1
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: Macos 13,  Windows 10
* Link to your project (if it's a public repository): N/A

**Comment by sw-tracker** [comment]
Are you able to include only specific files? I am trying to do this for it to work together with lint-staged. Essentially, I only want to run detekt on files that have changed and therefore are git staged (detekt runs against all files in the pipeline, thats ok).

Were you able to achieve this? I do something similar for spotless: `mvn spotless:apply -DspotlessFiles=.*${filenames.join(',.*')}`

**Comment by BraisGabin** [comment]
@illuzor could you give more information? Are you using the cli or the gradle plugin? How do you configure gradle in each module? Do you use type solving?

I can't reproduce the behavior that you define.

**Comment by illuzor** [comment]
@sw-tracker the project contains many differently structured folders with sources.  It would be difficult to add paths manually and I have no idea how to add them automatically.

@BraisGabin I`m using cli in custom gradle task. Project root folder passed as input. No type solving used. 
I can try to make a test project if needed.

**Comment by BraisGabin** [comment]
Which exclude mechanism are you using? Could you provide an example?

And does detekt raise any issue in the exclude files? Or is this just a performance issue?

**Comment by illuzor** [comment]
@BraisGabin I use cli exclude `detekt -ex "**/build/**, **/resources/**"`
If I remove the exclusions, detekt issues arise. If I add the exclusions, no issues are found, but the scanning time remains the same as without the exclusions.

**Comment by BraisGabin** [comment]
OK! I wasn't fully understanding the issue. Yes, this have sense and we should fix it. I imagine that we are walking the full file tree. We should fix that.

**Comment by cortinico** [comment]
> When **build** folders are present, detekt task ends in 5-10 minutes depends on machine.

This is obviously bad and something we should fix. Is it specific to your project? Like are you having a huge number of build files for a specific reason? I'd like to get a reproducer so we could investigate this

**Comment by marschwar** [comment]
I think the culprit is the `KtTreeCompiler`.

```kotlin
        val kotlinFiles = Files.walk(project)
            .asSequence()
            .filter(Path::isRegularFile)
            .filter { it.isKotlinFile() }
            .filter { !isIgnored(it) }
```

The input is traversed depth-first and filtered on the result sequence.

**Comment by marschwar** [comment]
I have an idea on how to fix it. Can I take a stab at it?

**Comment by illuzor** [comment]
@cortinico I can try to create a demo project if needed

**Comment by cortinico** [comment]
@marschwar please do 🙏

**Comment by 3flex** [comment]
@marschwar just be aware that the draft PR https://github.com/detekt/detekt/pull/6271 removes all usage of KtTreeCompiler, so the problem could be reintroduced even after your fix and might result in some wasted effort.

Let me know how you'd like to approach it - I think the changes in that PR are important so once I have time to fix the last test failure I'd be looking to merge it.

**Comment by marschwar** [comment]
Thank you for the heads up. I will still try to fix it on the current implementation. Depending on the solution we can look how we can port it to the new structure.

**Comment by marschwar** [comment]
@3flex  I created a draft PR #6302. I do not see how this could be integrated into #6271.  Maybe it is not even necessary.

**Comment by marschwar** [comment]
@illuzor Could you please provide a demo project or test if the changes in the PR fix your problem.

**Comment by illuzor** [comment]
@marschwar https://github.com/illuzor/detekt_big_project_test/tree/master
2 gradle tasks:
- gradlew detekt
- gradlew detektNoExcludes

Both takes the same time (about 20 seconds on my laptop), but detektNoExcludes will find errors.

**Comment by marschwar** [comment]
Thank you for providing the reproducer. I ran detekt with the changed cli.

```
» time java -jar ../detekt/detekt-cli/build/libs/detekt-cli-1.23.0-all.jar -i big_project
./detekt_big_project_test/big_project/module95/build/BG.kts:1:1: The package declaration does not match the actual file location. [InvalidPackageDeclaration]
./detekt_big_project_test/big_project/module95/build/BG.kts:26:2: The file BG.kts is not ending with a new line. [NewLineAtEndOfFile]

Analysis failed with 2 weighted issues.
java -jar ../detekt/detekt-cli/build/libs/detekt-cli-1.23.0-all.jar -i   3.48s user 1.50s system 173% cpu 2.883 total
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

» time java -jar ../detekt/detekt-cli/build/libs/detekt-cli-1.23.0-all.jar -ex "**/build" -i big_project
java -jar ../detekt/detekt-cli/build/libs/detekt-cli-1.23.0-all.jar -ex  -i   2.71s user 1.19s system 166% cpu 2.339 total
```

Using the exclusion `**/build` did make the scan faster.  Excluding `**/build/**` did not improve the scanning since only subdirectories of the build folders would be ignored.

**Comment by atulgpt** [comment]
hi, @marschwar are we making this(excluding the file passed as under `--ex` flag) default? what will happen when we run the detekt with TR at that time we will need to include even excluded files in our compilation unit for proper analysis.

**Comment by marschwar** [comment]
Looking at the code I don't think that I have changed the behavior - at least that was not my intention. Previously we traversed the entire file tree to find the files to check,, applying the exclude filter before collecting everything in a list. Now we do the same thing, just skip entire subtrees that are known to be excluded.

**Comment by BraisGabin** [comment]
> hi, @marschwar are we making this(excluding the file passed as under `--ex` flag) default? what will happen when we run the detekt with TR at that time we will need to include even excluded files in our compilation unit for proper analysis.

As far as I know that's an issue that is an issue that we have right now on the project. This shouldn't change that.
