### ISSUE TITLE
Rename EmptyKtFile to EmptyKotlinFile

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#6254]
## Expected Behavior of the rule
Kotlin files can have a kt or kts extension. The rule name should change for 2.0.0 so the rule name is less specific. It could be EmptyFile, EmptyKotlinFile or something else.

**Comment by segunfamisa** [comment]
hey folks, I can pick this one if you are accepting contributions for this task :)

**Comment by cortinico** [comment]
Assigned to you @segunfamisa 👍
