### ISSUE TITLE
Deprecate or remove UntilInsteadOfRangeTo

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#6263]
## Expected Behavior of the rule
It doesn't exist.

## Context
This rule recommends use of `until` infix function, but Kotlin 1.9 makes the `..<` operator stable and the recommendation now is to use that instead. It was introduced in Kotlin 1.7.20, and now it's stable it's a safe recommendation.

See #6262 which requests introduction of a new rule that would replace this one.

**Comment by cortinico** [comment]
> Deprecate or remove UntilInsteadOfRangeTo

I'd say we can effectively "rename" this rule in 2.0.0 to the one you suggested in #6262 and also update the logic
