### ISSUE TITLE
Point release for Kotlin 1.9.0 support

### ISSUE THREAD

**Issue by credmond-git** [detekt/detekt#6278]
## Expected Behavior
Can build with Kotlin 1.9.0

## Current Behavior
1.23.0 only supports Kotlin 1.8.21

## Context
Hello, would it be possible to get a point release with Kotlin 1.9.0 support? This is currently blocking our projects from upgrading to Kotlin 1.9.0.
I along with the community would be very appreciative if we could get a point release with minimal changes quickly, that will allow us to run our kotlin 1.9.0 builds with detekt. Instead of waiting weeks for a new build with proper Kotlin 1.9.0 updates for the new features.

**Comment by 3flex** [comment]
Snapshots can be used by anyone who wishes to use a version that supports Kotlin 1.9 in the meantime: https://detekt.dev/docs/introduction/snapshots/

**Comment by cortinico** [comment]
> Hello, would it be possible to get a point release with Kotlin 1.9.0 support? This is currently blocking our projects from upgrading to Kotlin 1.9.0.

Yup I believe we can get this sorted out in the next days 👍 Thanks for your patience

**Comment by 3flex** [comment]
detekt 1.23.1 has been released to Maven Central and has support for Kotlin 1.9
