### ISSUE TITLE
Ask update for OutdatedDocumentation rule

### ISSUE THREAD

**Issue by Oshuremy** [detekt/detekt#6312]
Hi,

```
/**
* Test method
*/
fun test(param1: String, param2: String) : Boolean = true
```
-> This KDoc is valid for OutdatedDocumentation rule while no parameters are declared in the KDoc

```
/**
* Test method
*
* @param other
*/
fun test(param1: String, param2: String) : Boolean = true
```
-> This KDoc is not valid for OutdatedDocumentation rule -> ok

```
/**
* Test method
*
* @param param1
* @param param2
*/
fun test(param1: String, param2: String) : Boolean = true
```
-> This KDoc is valid for OutdatedDocumentation rule whereas with the matchTypeParameters(true) rule, the right type must be used

Is an update to this rule planned ?

I would like to force this kind if KDoc
```
/**
* Test method
*
* @param param1 [String]
* @param param2 [String]
*/
fun test(param1: String, param2: String) : Boolean = true
```

**Comment by schalkms** [comment]
Do you have a reference to the official KDoc guide, where the following notation is endorsed? Otherwise, I'm afraid there's no update to the OutdatedDocumentation rule planned. Detekt's included rules align with official conventions and notations. This means you have to rely on a [custom rule](https://detekt.dev/docs/introduction/extensions).

```kotlin
@param param1 [String]
```

**Comment by Oshuremy** [comment]
Indeed it is not required in the official doc : https://kotlinlang.org/docs/kotlin-doc.html

But in this case I don't understand what the "matchTypeParameters" rule does, because type are not mandatory.

**Comment by atulgpt** [comment]
> Indeed it is not required in the official doc : https://kotlinlang.org/docs/kotlin-doc.html
> 
> But in this case I don't understand what the "matchTypeParameters" rule does, because type are not mandatory.

I think that is used to document the generic types present in the method or class declaration so when `matchTypeParameters` is `true`(which is default) then below documentation is non compliant
```
/**
 * @param someParam Description of param
 */
class MyClass<T>(someParam: String)
```
Compliant code will be as below
```
/**
 * @param T Description of type param
 * @param someParam Description of param
 */
class MyClass<T>(someParam: String)
```

**Comment by Oshuremy** [comment]
Thanks
