### ISSUE TITLE
`detekt-generator-1.23.1-all.jar` is missing

### ISSUE THREAD

**Issue by cortinico** [detekt/detekt#6334]
## Expected Behavior
https://github.com/detekt/detekt/releases/tag/v1.23.1 should have `detekt-generator-1.23.1-all.jar` as 1.23.0.

## Observed Behavior
The `detekt-generator-1.23.1-all.jar` is missing.

## Steps to Reproduce
I've noticed that the file is missing entirely:
1. Clone the repo
2. `git checkout release/1.x`
3. `./gradlew build`
4. `cat detekt-generator/build/libs/detekt-generator-1.23.1-all.jar` <- this will fail

## Context
I'm pinging the rest of @detekt/maintainers as I couldn't find what caused the shadow plugin to fail here, but this could be a symptom of an underlying issue.

**Comment by TWiStErRob** [comment]
Investigating. Interesting that I don't have the file from before either:
![image](https://github.com/detekt/detekt/assets/2906988/45ad0863-1453-4799-bc04-abaf1b50bbe7)

**Comment by TWiStErRob** [comment]
`ShadowJavaPlugin.configureShadowTask` registers the `-all.jar` artifact and :detekt-generator:shadowJar` should be creating this file and calling it directly does generate the file.

So the question is: why was it automatic before and now it's not?

**Comment by TWiStErRob** [comment]
> So the question is: why was it automatic before and now it's not?

Looking at the history of `:detekt-generator/build.gradle.kts` I think it's this change:

https://github.com/detekt/detekt/pull/5844/files#diff-e82b2d14a65b97fbbbff582f3413e3137477659cc9189e9e50e9516ffde243ffL38

So previously it was a side effect of docs generation, and now no-one uses it.
