### ISSUE TITLE
Detekt reports UnusedPrivateProperty with traditional for loops

### ISSUE THREAD

**Issue by ccjernigan** [detekt/detekt#6338]
## Expected Behavior
Detekt should not complain about unused variables when they cannot be eliminated, such as in a traditional for loop.

## Observed Behavior
`Private property "index" is unused. [UnusedPrivateProperty]`

## Steps to Reproduce
```
for (index in 0..epochs) {
}
```

## Context
I had this
```
for (_ in 0..epochs) {
}
```

And Detekt 1.23.1 suggested replacing with a standard for loop for performance.

So I wrote 
```
for (index in 0..epochs) {
}
```
And Detekt complains that index is an unused property.  I cannot replace it with `_` because that is not valid in this context.  The workaround is `@Suppress("UnusedPrivateProperty")`

## Your Environment

* Version of detekt used: 1.23.1
* Version of Gradle used (if applicable): 8.2.1
* Operating System and version: macOS 13.5

**Comment by cortinico** [comment]
Can't you just use `repeat(epochs){ }` in your examples?

**Comment by atulgpt** [comment]
dup of close issue https://github.com/detekt/detekt/issues/3566
