### ISSUE TITLE
IllegalStateException when running `detektAll` in an Android multimodule project

### ISSUE THREAD

**Issue by noloman** [detekt/detekt#6357]
## Observed Behavior

Execution failed for task ':detektAll'.
> java.lang.IllegalStateException:        Analyzing /Users/MyUser/Developer/MyAndroidApp/app/src/test/java/myapp/presentation/mappers/formatters/DateFormatterTest.kt led to an exception.
         Location: java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
         The original exception message was: java.lang.IllegalArgumentException: Stack should be empty:
  IndentContext(fromASTNode=Element(kotlin.FILE), toASTNode=PsiWhiteSpace, nodeIndent=, firstChildIndent=, childIndent=, lastChildIndent=, activated=true)
  IndentContext(fromASTNode=Element(CLASS), toASTNode=PsiElement(RBRACE), nodeIndent=, firstChildIndent=, childIndent=, lastChildIndent=, activated=false)
  IndentContext(fromASTNode=Element(CLASS_BODY), toASTNode=PsiElement(RBRACE), nodeIndent=, firstChildIndent=    , childIndent=    , lastChildIndent=, activated=false)
  IndentContext(fromASTNode=PsiElement(LBRACE), toASTNode=PsiElement(RBRACE), nodeIndent=, firstChildIndent=, childIndent=    , lastChildIndent=, activated=true)
  IndentContext(fromASTNode=BLOCK, toASTNode=PsiElement(RBRACE), nodeIndent=    , firstChildIndent=    , childIndent=    , lastChildIndent=    , activated=false)
  IndentContext(fromASTNode=Element(FUN), toASTNode=PsiElement(RPAR), nodeIndent=    , firstChildIndent=, childIndent=, lastChildIndent=, activated=true)
         Running detekt '1.23.0' on Java '17.0.6+10' on OS 'Mac OS X'
         If the exception message does not help, please feel free to create an issue on our GitHub page.

## Steps to Reproduce
I have this in the root level `build.gradle`:

```
apply plugin: 'io.gitlab.arturbosch.detekt'

def projectSource = file(projectDir)
def configFile = files("${rootProject.projectDir}/config/detekt/detekt.yml")
def baselineFile = file("${rootProject.projectDir}/config/detekt/baseline.xml")
def kotlinFiles = "**/*.kt"
def resourceFiles = "**/resources/**"
def buildFiles = "**/build/**"

tasks.register("detektAll", Detekt) {
    description = "Custom DETEKT build for all modules"
    parallel = true
    ignoreFailures = false
    autoCorrect = true
    buildUponDefaultConfig = true
    setSource(projectSource)
    baseline.set(baselineFile)
    config.setFrom(configFile)
    include(kotlinFiles)
    exclude(resourceFiles, buildFiles)
    reports {
        html.required.set(true)
        xml.required.set(false)
        txt.required.set(false)
    }
}

dependencies {
    detektPlugins(libs.detekt.formatting)
}
```
And running `./gradlew detektAll` shows the error.

## Your Environment
* Using `io.gitlab.arturbosch.detekt:detekt-formatting`
* Version of detekt used: 1.23.0
* Version of Gradle used (if applicable): 7.6
* Operating System and version: Mac OSX

**Comment by cortinico** [comment]
What's the reason why you're using:

```
tasks.register("detektAll", Detekt) {
```

and not the tasks provided by detekt gradle plugin?

**Comment by noloman** [comment]
Hey! Thanks for the reply!

I switched to the original `detekt` and I'm still running into issues:

```
Execution failed for task ':app:detekt'.
>        Analyzing /Users/MyUser/Developer/MyApp/app/src/main/java/myapp/presentation/screens/more/profile/customerAddress/updateManually/UpdateAddressManuallyViewModel.kt led to an exception.
         Location: com.pinterest.ktlint.ruleset.standard.rules.IndentationRule.afterLastNode(IndentationRule.kt:965)
         The original exception message was: Stack should be empty:
  IndentContext(fromASTNode=Element(kotlin.FILE), toASTNode=PsiWhiteSpace, nodeIndent=, firstChildIndent=, childIndent=, lastChildIndent=, activated=true)
  IndentContext(fromASTNode=Element(CLASS_BODY), toASTNode=PsiElement(RBRACE), nodeIndent=, firstChildIndent=    , childIndent=    , lastChildIndent=, activated=false)
  IndentContext(fromASTNode=PsiElement(LBRACE), toASTNode=PsiElement(RBRACE), nodeIndent=, firstChildIndent=, childIndent=    , lastChildIndent=, activated=true)
  IndentContext(fromASTNode=BLOCK, toASTNode=PsiElement(RBRACE), nodeIndent=    , firstChildIndent=    , childIndent=    , lastChildIndent=    , activated=false)
  IndentContext(fromASTNode=Element(FUN), toASTNode=PsiElement(RPAR), nodeIndent=    , firstChildIndent=, childIndent=, lastChildIndent=, activated=true)
         Running detekt '1.23.0' on Java '17.0.6+10' on OS 'Mac OS X'
         If the exception message does not help, please feel free to create an issue on our GitHub page.

```

**Comment by cortinico** [comment]
Can you share which code is causing this?

**Comment by noloman** [comment]
Excuse me for the delay! Sorry but I can't share the code as it's proprietary software code

**Comment by Pschsch** [comment]
+1 on detekt 1.23.1, Java 17, Windows 11

**Comment by BraisGabin** [comment]
Sorry but without a reproducer or a full stack trace we can do nothing here. Anything way, it feels like the issue is inside ktlint. Can you reproduce the issue just with ktlint? If so the issue should be open there.

**Comment by prof18** [comment]
A similar issue happened to me. It was caused by an if/else without a body. Not sure if it's the same, but could be a hint to investigate! 

```kotlin
if (something) {
   foo()
} else if (somethingElse)
else if (anotherBoolean) {
   bar()
}
```
