### ISSUE TITLE
Rename UnusedImports to UnusedImport

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#6363]
## Expected Behavior of the rule
Currently it's required to list both to suppress an unused import:
```
@file:Suppress("UnusedImports", "UnusedImport")
```
if we rename the rule the new name would match the IDEA inspection.

Links to implementations:
 * [Detekt UnusedImports](https://github.com/detekt/detekt/blob/v1.23.1/detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedImports.kt)
 * [IDEA Java UnusedImport](https://github.com/JetBrains/intellij-community/blob/master/java/java-analysis-impl/src/com/intellij/codeInspection/unusedImport/UnusedImportInspection.java) ([registration](https://github.com/JetBrains/intellij-community/blob/idea/231.9392.1/java/java-analysis-impl/src/META-INF/JavaAnalysisPlugin.xml#L242-L244))
 * [IDEA Kotlin UnusedImport](https://github.com/JetBrains/intellij-community/blob/idea/231.9392.1/plugins/kotlin/idea/src/org/jetbrains/kotlin/idea/inspections/KotlinUnusedImportInspection.kt) ([registration](https://github.com/JetBrains/intellij-community/blob/idea/231.9392.1/plugins/kotlin/plugin/k1/resources/META-INF/inspections-fe10.xml#L1218-L1226))
 * [IDEA K2 UnusedImport](https://github.com/JetBrains/intellij-community/blob/idea/231.9392.1/plugins/kotlin/code-insight/inspections-k2/src/org/jetbrains/kotlin/idea/k2/codeinsight/inspections/KotlinUnusedImportInspection.kt) ([registration](https://github.com/JetBrains/intellij-community/blob/03799f2298aacc60e32702167810b6c1dc8b8c86/plugins/kotlin/code-insight/inspections-k2/resources/kotlin.code-insight.inspections-k2.xml#L45-L54))

## Context
Similar to https://github.com/detekt/detekt/issues/3643

**Why would I want to suppress `UnusedImports`?**
Because it's a false positive, in both detekt and IJ.
If I remove the import, the code fails to compile, so it's not unused.
Related issue https://youtrack.jetbrains.com/issue/KT-60939
Repro code when unused import is triggered: https://github.com/TWiStErRob/repros/tree/main/kotlin/UnusedImport-package-friendly-overload
I assume that this rule is based on the same code IDEA uses, so if they fix the above issue we'll get the false positive fix for free? Therefore this report is only for reducing the need for double-suppress. Happy to open a separate issue if it's not a "free fix".

**Comment by cortinico** [comment]
This is fine to go inside 2.x 👍

**Comment by atulgpt** [comment]
Hi @TWiStErRob should we also rename `NoUnusedImports`(coming from Ktlint) for consistency

**Comment by TWiStErRob** [comment]
I would think alias at best. Let's not touch it for now (https://github.com/detekt/detekt/discussions/5997).
