### ISSUE TITLE
[Website] Support explicit version reference in URL for latest Detekt version

### ISSUE THREAD

**Issue by Marcono1234** [detekt/detekt#6365]
## Expected Behavior
I would like to create a "permalink" URL of the website for the version which is currently the latest one, so that even if a newer Detekt version is released in the meantime, that URL still points to the documentation for that specific version (instead of the then latest, whose content might not be the same anymore).

For example, let's say I want to refer to the `OptionalWhenBraces` rule:
- For version 1.23.0 the permalink URL is https://detekt.dev/docs/1.23.0/rules/style#optionalwhenbraces
- For version 1.23.1 (currently latest version) I would like to create a similar URL, which contains "1.23.1"[^1]

## Current Behavior
It is impossible to create a permalink for the latest version:
For example for version 1.23.1 (currently latest version) the expected URL would be https://detekt.dev/docs/1.23.1/rules/style#optionalwhenbraces, but that leads to a 404 page

[^1]: Even if that URL then redirects to the "version-less" URL https://detekt.dev/docs/rules/style#optionalwhenbraces while 1.23.1 is still the latest version

**Comment by cortinico** [comment]
That's not how docusaurus work. The current version has a plain URL:
https://docusaurus.io/docs/versioning

What's your use case for wanting to create a URL for 1.23.1 only?

**Comment by Marcono1234** [comment]
> That's not how docusaurus work. The current version has a plain URL:
> https://docusaurus.io/docs/versioning

Thanks for the information; so if this is not possible due to technical limitations, then feel free to close this.

> What's your use case for wanting to create a URL for 1.23.1 only?

My use case was that, in the context of upgrading to Detekt 1.23.1, I wanted to refer to the documentation of the `OptionalWhenBraces` rule. However, if in the meantime a new Detekt version was released, the link I created (which does not contain the version number) would now erroneously point to for example 1.23.2 or 1.24.0, whose documentation might differ and might not be relevant for 1.23.1.

I guess that is not such an important use case though; maybe someone else has a more important one.

**Comment by cortinico** [comment]
Could you open an issue for docusaurus here?
github.com/facebook/docusaurus/issues

I believe this could be a nice addition to every website (i.e. permalinks to the current version which are versioned).

**Comment by Marcono1234** [comment]
> Could you open an issue for docusaurus here?
> github.com/facebook/docusaurus/issues

Apparently there is already an existing issue for this: https://github.com/facebook/docusaurus/issues/1312
And a the corresponding feature request post https://docusaurus.io/feature-requests/p/permanent-url-support-for-current-version which suggests this has been implemented. Though it is not really obvious to me how this feature is available.

One solution might be to set `lastVersion: 'current'` but that would show the not yet released 'next' version by default then, which I assume is not desired for Detekt since it could lead to confusion.

**Comment by cortinico** [comment]
Thanks for linking the two 👍 It seems like we'll need a redirect (https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects) but lets wait what the docusaurus maintainer answer.

**Comment by Marcono1234** [comment]
@cortinico, should this issue here remain open, or do you think the effort for implementing this is not worth it and it should be closed?

**Comment by cortinico** [comment]
> do you think the effort for implementing this is not worth it and it should be closed?

@Marcono1234  I'm leaning towards this. If docusaurus offer this out of the box, I'm happy to enable it. If you want to hack a pre-build script that generates the redirects, I'm happy to review a PR. I won't have time to look into this as it's a low priority task

**Comment by Marcono1234** [comment]
Ok, I am going to close this issue then; thanks anyways for your help with this so far!

(But I guess if anyone else wants to give this a try, feel free to do so)
