### ISSUE TITLE
Implement a new concept for severity

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#6400]
## Expected Behavior

In #6383 we discussed what the severity model for detekt 2.0 should look like. When this issue is resolved, all of the properties below are implemented:

- [x]     The current values of the severity enum is replaced with the severity levels error, warning and info.
- [x]     The default severity of an all rules is error.
- [x]     The severity of a rule instance must be configurable via configuration file.
- [x]     It should be possible to configure to the severity at rule set level to apply it to all rules of the rule set (unless overwritten at rule level)
- [x]     The severity will be moved from the Issue to the Finding as it depends on a configurable rule instance.
- [x]     The concept of maxIssues will be removed. The build fails if (and only if) there is at least one issue with the severity error. #6408 
- [x]     It must be possible to reduce the level that has the build fail. Something similar to warningsAsError but also allowing the threshold to be lowered to info.
- [x]     The concept of weighted issues (build > weights) will be removed. #6389 
- [x]     The SeverityLevel will be removed.

## Current Behavior
The current severity model is confusing because the name suggests something that it really is not.

**Comment by 3flex** [comment]
Is this complete now? The last checkbox looks like it can be ticked off as the linked PR is merged.

**Comment by marschwar** [comment]
Yes. Thanks for the reminder

**Comment by jinia91** [comment]
Hi

This feature has been merged into the main branch and has been confirmed to work properly when run on main.

What is the reason it has not yet been released to the release branch?

Is it planned for a version after 2.0?
