### ISSUE TITLE
Enforce runTest in junit test when coroutine is used

### ISSUE THREAD

**Issue by tyvsmith** [detekt/detekt#6410]
## Expected Behavior of the rule
I suggest a checker for test code to enforce that runTest is used on a junit @Test method when the underlying code launches a coroutine.

Invalid code
```
@Test
fun test() {
  methodThatLaunchesCoroutine()
}
```

Valid Code
```
@Test
fun test() = runTest {
  methodThatLaunchesCoroutine()
}
```

## Context
Coroutines 1.7 has started propagating previously suppressed exceptions via runTest. During our upgrade from 1.6, we have found several cases where previously swallowed exceptions are now breaking tests. Often this happens on an unrelated test because the previous test didn't use runTest when dealing with underlying code that launched a coroutine, making them more difficult to find and resolve.

- https://github.com/Kotlin/kotlinx.coroutines/pull/3449
- https://github.com/Kotlin/kotlinx.coroutines/issues/3821#issuecomment-1647851085
- https://github.com/Kotlin/kotlinx.coroutines/issues/1205#issuecomment-1238261240

**Comment by cortinico** [comment]
Yup this would make for a great addition to the `coroutines` ruleset

**Comment by Rai-Sahil** [comment]
Hi, If no one's planning on working on it. I could get started

**Comment by marschwar** [comment]
Thank you. I assigned this issue to you.

**Comment by dmitriev2000** [comment]
Any news on this one? :)

**Comment by BraisGabin** [comment]
I unasigned Rai from now so this PR is ready to grab by anyone.

**Comment by BraisGabin** [comment]
Go for it! I just assigned it to you.
