### ISSUE TITLE
Remove auto initialization of `Extension::id`

### ISSUE THREAD

**Issue by lexa-diky** [detekt/detekt#6481]
Currently this field is auto initialized from class name

```kotlin
val id: String get() = javaClass.simpleName
```

I suggest to remove this behavior for 2.0, and force users to declare it explicitly.
This will help to avoid issues like #6464

**Comment by BraisGabin** [comment]
Good idea. Go for it!

**Comment by lexa-diky** [comment]
fixed in https://github.com/detekt/detekt/pull/6505
