### ISSUE TITLE
Remove `OutputReport::name` due to misleading name and behavior 

### ISSUE THREAD

**Issue by lexa-diky** [detekt/detekt#6482]
Currently `OutputReport::name` is used for documentation purposes and semantically is closer to `description`. Also documentation for is misleading user to think that it contains same value as `id`

I suggest 2 possible solutions:
- remove `name`, replace it's usages with `id`
- rename `name` to `description`

Personally I vote for first option

**Comment by lexa-diky** [comment]
Exactly 2 places:

```kotlin
    fun write(filePath: Path, detektion: Detektion) {
        val reportData = render(detektion)
        if (reportData != null) {
            assert(filePath.extension == ending) {
                "The $name needs to have a file ending of type .$ending, but was ${filePath.fileName}."
            }
            ....
        }
    }
```

```kotlin
private fun handleOutputReports(result: Detektion) {
        val extensions = OutputReportLocator(settings).load()
        for (report in extensions) {
            val filePath = reports[defaultReportMapping(report.id)]?.path
            if (filePath != null) {
                report.write(filePath, result)
                result.add(SimpleNotification("Successfully generated ${report.name} at ${filePath.toUri()}"))
            }
        }
    }
```

Both are logs, I think putting `id` instead of `name` in both places would be better. Consumer can search for it in their code base, name is not mentioned anywhere except for logs

**Comment by BraisGabin** [comment]
Agree. We can remove name and use I'd for that. Do you want to send the pr?

**Comment by lexa-diky** [comment]
OK, will do

**Comment by lexa-diky** [comment]
https://github.com/detekt/detekt/pull/6500

**Comment by lexa-diky** [comment]
Fixed https://github.com/detekt/detekt/pull/6500
