### ISSUE TITLE
Should we remove all deprecated configs/methods?

### ISSUE THREAD

**Issue by atulgpt** [detekt/detekt#6483]
Currently `detekt` still has lots of deprecated properties inside rules(I think with Gradle rewrite those will be handled). But for rules config properties should we remove the desecrated ones before the 2.0 release?

Searching `@Deprecated` across the project gives the below list(there could be more as well)
<img width="1003" alt="Screenshot 2023-09-13 at 12 37 37 AM" src="https://github.com/detekt/detekt/assets/11026203/71677385-7336-4817-be61-e12d151d7b70">

**Comment by BraisGabin** [comment]
In general: yes. Maybe there is something that we want to keep but, in general, yes we want to remove all the deprecations.

**Comment by 3flex** [comment]
Can we close this then as asked and answered? The task itself could be added to the Detekt 2 discussion that Nicola created.
