### ISSUE TITLE
1.21.0 | 1.22.0 | 1.23.0 : Analyzing /Users/me/myproject/KafkaConsumer.kt led to an exception

### ISSUE THREAD

**Issue by su-dco** [detekt/detekt#6488]
## Observed Behavior

I am currently updating a Spring Boot Application from 3.0.1 to 3.1.3

if I use plugin version "1.21.0" OR "1.22.0" following Error occures
```
Execution failed for task ':detekt'.
> Analyzing /Users/me/myproject/KafkaConsumer.kt led to an exception.
  Location: io.gitlab.arturbosch.detekt.rules.bugs.ImplicitDefaultLocale.checkStringFormatting(ImplicitDefaultLocale.kt:70)
  The original exception message was: 'org.jetbrains.kotlin.psi.KtExpression org.jetbrains.kotlin.resolve.calls.util.CallUtilKt.getCalleeExpressionIfAny(org.jetbrains.kotlin.psi.KtElement)'
  Running detekt '1.22.0' on Java '17.0.7+7' on OS 'Mac OS X'
  If the exception message does not help, please feel free to create an issue on our GitHub page.
```

if I use plugin id("io.gitlab.arturbosch.detekt") version "1.23.0"
```
detekt was compiled with Kotlin 1.8.21 but is currently running with 1.8.22.
```
## Steps to Reproduce
```
# build.gradle.kts
plugins {
 id("io.gitlab.arturbosch.detekt") version "1.22.0"
}

detekt {
    ignoreFailures = true
    config.setFrom(files(System.getenv("DETEKT_CONFIG") ?: "config/detekt/detekt.yml"))
}
```

## My ENV

detekt '1.21.0' on  Java '17.0.7+7' on OS 'Mac OS X'
detekt '1.22.0' on  Java '17.0.7+7' on OS 'Mac OS X'
detekt '1.23.0' on  Java '17.0.7+7' on OS 'Mac OS X'

## Question

I found this solution which works with "1.23.0" but I saw that it will download kotlin 1.8.21 additionally?
Therefore it will slowdown our CI pipelines.
Is there an other solution for this?
```
project.afterEvaluate {
    configurations["detekt"].resolutionStrategy.eachDependency {
        if (requested.group == "org.jetbrains.kotlin") {
            useVersion("1.8.21")
        }
    }
}
```

It would be nice to have a parallel release with Spring Boot or all Kotlin Versions

**Comment by 3flex** [comment]
There's not much we can do here, see https://github.com/detekt/detekt/issues/6198#issuecomment-1700332653

Also see a comment near the end of that thread from one of the Spring Dependency Management Gradle plugin maintainers saying that's the best workaround for now.
