### ISSUE TITLE
Random IllegalStateException in CI

### ISSUE THREAD

**Issue by SebRut** [detekt/detekt#6499]
When running detekt in CI we sometimes get the following exception. Rerunning CI "fixes" the issue:

```
Execution failed for task ':app:detektPlayStoreDebug'.
08:44:58  > java.lang.IllegalStateException: Analyzing [REDACTED].kt led to an exception.
08:44:58    Location: java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
08:44:58    The original exception message was: java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals() or TObjectHashingStrategy.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 = (class java.lang.String), hashCode=0; object #2 = (class java.lang.String), hashCode=0
08:44:58    Running detekt '1.23.1' on Java '17.0.6+0-17.0.6b802.4-9586694' on OS 'Mac OS X'
08:44:58    If the exception message does not help, please feel free to create an issue on our GitHub page.
```

If I understand the stack trace correctly, the problem isn't within our code, but actually, that 2 `String` instances who should be equal aren't in `java.base/java.util.concurrent.CompletableFuture.encodeThrowable`? 

abstracted code of mentioned file:
```kotlin
package myredactedpackage

private const val SOME_CONST = "CONST"

object Initializer {
    fun init() {
        // passing of method reference to loadX
    }

    private fun loadX() {
        loadKoinModules(
            // KOIN MODULE with call to getX
        )
    }

    private fun getX(): X {
        // usage of SOME_CONST
    }
}
```

## Steps to Reproduce

* android project with working type resolution
* run `:app`

## Your Environment

* Version of detekt used: 1.23.1
* Version of Gradle used (if applicable):8.3
* Operating System and version: Mac OS X - Ventura (x86)

**Comment by atulgpt** [comment]
I think we has similar issue in the past https://github.com/detekt/detekt/issues/5403

**Comment by sergeys-opera** [comment]
Happened intermittently in my project too:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':model:notification:detektReleaseUnitTest'.
> java.lang.IllegalStateException: Analyzing /builds/<DELETED>.kt led to an exception.
  Location: java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
  The original exception message was: java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals() or TObjectHashingStrategy.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =com (class java.lang.String), hashCode=98689; object #2 =com (class java.lang.String), hashCode=98689
  Running detekt '1.23.0-RC2' on Java '19.0.2+7' on OS 'Linux'
```

**Comment by 3flex** [comment]
Can we get a stack trace please?

**Comment by SebRut** [comment]
@3flex it's been some time since the last encounter but I think the output posted above is everything we get.

**Comment by 3flex** [comment]
Ok thanks - without a stack trace or reliable reproducer it won't be possible to investigate further unfortunately.

Hopefully one can be provided soon.

**Comment by BraisGabin** [comment]
`object #1 =package.name (class java.lang.String), hashCode=162991530; object #2 =package.name (class java.lang.String), hashCode=162991530`

The thing is that the value in the string is the same and the hashCode IS the same too based on the stacktrace... I'm not sure what can we do here... without a way to reproduce it is really difficult to pinpoint the problem. It seems like an issue on Kotlin or `gnu.trove` but as I said it's impossible to know without a reproducer...
