### ISSUE TITLE
Make easier to find used ktlint version

### ISSUE THREAD

**Issue by emartynov** [detekt/detekt#6515]
## Context
I was looking to repo and documentation and could not quickly locate the compatibility table for the detekt and ktlint versions.

Sure, I can check toml file for the latest version, or I can use the gradle command to find the transitive dependency.

But it would be great to document this as well.

**Comment by 3flex** [comment]
When you say "compatibility table" - I'm not sure why you'd need a compatibility table for this?

Or do you just want to see which rules etc are available? If so our docs for the wrapped ktlint rules now link to the versioned ktlint docs so that should cover you.

Could you please be a bit more specific about the need for this?

**Comment by emartynov** [comment]
I've been in Kotlin Slack discussion about using ktlint gradle plugin or other ways to run ktlint. And one of the advantages claimed for gradle plugin was the ability to specify ktlint version to run. That drew my attention if it is possible with Detekt, and I spent some time trying to find ktlint version wrapped.

Thank you for pointing this out - detekt is a full wrapper of ktlint and it looks like end user don't have to deal with ktlint directly at all, even with configuration. So I assume the compatibility table is the wrong term, and mention of the used version would be enough.

**Comment by 3flex** [comment]
Just treat the formatting ruleset as a ruleset like any other. It happens to wrap ktlint rules but the specific ktlint version isn't really relevant for anything in particular as an end user, except for documentation about how the rules behave, and the detekt documentation already links to versioned ktlint documentation.

If you want any kind of control over the version of ktlint that you use then I would recommend using a different Gradle plugin to run ktlint directly.

**Comment by emartynov** [comment]
@3flex can you point documentation place where version is mentioned?

**Comment by 3flex** [comment]
It's not specifically documented anywhere though the specific version is mentioned in release notes already when the dependency is updated for a new release.

What I'm saying is that with the way we wrap ktlint that I don't see any reason to publish the specific version anywhere in our official docs.

If you really want to know, view release notes, the version in libs.versions.toml for the tagged release, or click a link to the ktlint docs from the detekt formatting ruleset documentation.

**Comment by emartynov** [comment]
That is what I said at the starting point - I can find the ktlint version wrapped in the detekt. I hope that this info will be more exposed. Like if I heard that ktlint got a major update or something interesting, I don't need much energy to find what detekt version I should update.

**Comment by emartynov** [comment]
I'm closing the ticket, since, the current state is intended/as designed.
