### ISSUE TITLE
Add ignoreAnnotatedFunctions to TooManyFunctions 

### ISSUE THREAD

**Issue by matejdro** [detekt/detekt#6516]
## Expected Behavior of the rule

Add `ignoreAnnotatedFunctions` (better name suggestions appreciated) config entry to `TooManyFunctions` rule that would exclude functions with specific annotations from the function count

## Context

We would like to exclude Compose preview functions from this rule. It is generally a good thing to have many Compose previews in file (to cover as many cases as possible), so we usually have several functions with actual UI code, then 10+ `@Preview` functions that just render preview for above code. We feel like those functions should not count into this rule as they do not contain any logic and do not actually make the file more complex.

I am prepared to offer a PR for that, if accepted.

**Comment by cortinico** [comment]
This is kinda tricky as to be consistent with the rest of the other props, this should be called `ignoreAnnotated`. The problem is that we do have a suppressor called also `ignoreAnnotated`.

I feel that this is probably the case for a local suppression?

**Comment by matejdro** [comment]
I wouldn't do it with local suppressions:

1. It's a common pattern in our codebase, so we would have to manually suppress lots of files, which goes against "manually suppress only for exceptional cases"
2. Manual suppressions can only be done for the entire file, meaning that we would also loose `TooManyFunctions`for non-Preview functions in that file.

**Comment by BraisGabin** [comment]
In general I don't like this rules with "magic" thesholds because this kind of things happen.

Could those multiple `Preview`s be reduced by using a `PreviewParameterProvider`? In my case I usually prefer to use it because otherwise the code inside `@Preview` functions is kind of repetitive. Would that help?

**Comment by matejdro** [comment]
I guess they could in some cases, but in not in the other. So this is only a half solution.

**Comment by kenyee** [comment]
I stopped by to request the same feature 😂 
The TooManyFunctions rule doesn't have an ignoreAnnotated option: https://detekt.dev/docs/rules/complexity/#toomanyfunctions

But jetpack compose composable previews tend to have a lot of state passed into them...at least that's our use case.

**Comment by matejdro** [comment]
Any verdict on this? I'm prepared to start a PR for this.

**Comment by cortinico** [comment]
Probably `ignoreAnnotatedFunctions` is the preferred way to go to don't clash with `ignoreAnnotated` from the suppressor then

**Comment by arekolek** [comment]
Shouldn't it use fully qualified names instead?

**Comment by matejdro** [comment]
ignoreAnnotated also doesn't use fqn annotations, so it was made to be consistent with that. Plus fqn requires type resolving.
