### ISSUE TITLE
Upload Baseline to GitHub (Sarif Report)

### ISSUE THREAD

**Issue by hfhbd** [detekt/detekt#6554]
## Expected Behavior
Upload the baseline to GitHub
Idea: Create a Sarif file for the baseline in `build/reports/detekt/baseline.sarif` which can be uploaded to GitHub using the existing sarif upload action.

## Current Behavior
The baseline is only stored locally as XML.
You can remove the baseline xml file, run the now failing `detekt` task, upload the sarif file containing the baseline code smells and add the baseline again to your repo to not fail in futher runs.
If you want to add a new code smell to the baseline, you need to repeat this step.

## Context
We use detekt and GitHub Advanced Security by uploading the Sarif report. 
We also want to ignore some code smells by using the baseline xml file. This file is stored locally in each repository, unknown to GitHub.

We want to upload this baseline to GitHub to see the baseline in the UI and to see a aggregated view of all accepted code smells of all repositories in the organization view.

But it is currently not easily possible to upload the baseline to GitHub. 
There is a workaround though, see the current behavior.

So I want to upload the baseline to GitHub too: Ideally, just create a sarif file for the baseline. The GitHub upload action allows you to upload multiple sarif files.

**Comment by cortinico** [comment]
> But it is currently not easily possible to upload the baseline to GitHub.
> There is a workaround though, see the current behavior.

I don't think GitHub supports the concept of Baseline with Sarif:
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning

Or I misunderstood your request?
How do you envision this to work? Where will the `baseline.sarif` file will be stored?

**Comment by hfhbd** [comment]
I just want to generate a `baseline.sarif` file stored under `/build/reports/detekt/baseline.sarif`, which only includes the baseline detektions.

I want to sync/upload the baseline.xml to GitHub too. GitHub does not support the custom detekt xml file, but sarif.
This additionally sarif file will be uploaded to GitHub to show open/not handled detektions.

At the moment, it is not possible to see open/not handled detektions in GitHub because detekt don't upload suppressed detektions.
At the same moment I want to not fail my build (`./gradlew detekt`) because of suppressed detektions.

If you don't want to implement this GitHub only feature, you could allow to register a custom reports/output formats for the baseline task too.

**Comment by cortinico** [comment]
> I just want to generate a `baseline.sarif` file stored under `/build/reports/detekt/baseline.sarif`, which only includes the baseline detektions.
> 
> I want to sync/upload the baseline.xml to GitHub too. GitHub does not support the custom detekt xml file, but sarif. This additionally sarif file will be uploaded to GitHub to show open/not handled detektions.
> 
> At the moment, it is not possible to see open/not handled detektions in GitHub because detekt don't upload/report suppressed detektions. At the same moment I want to not fail my build (`./gradlew detekt`) because of not handled detektions, this feature is called baseline.
> 
> If you don't want to implement this GitHub only feature, you could allow to register custom reports/output formats for the baseline task too.

You can rename the baseline file (to say `baseline-temp.xml`), rerun detekt which will output all the findings in .sarif format, and upload that file to GitHub.
If you don't want to manually rename the file, you can use a Gradle property/environment variable to achieve the same behavior

**Comment by hfhbd** [comment]
@cortinico Thank you for the answer. This does work! I am okay with this solution too, so feel free to close this issue if you don't see a use-case to support (custom) renderer for the baseline file.
