### ISSUE TITLE
detektPlugins invisible from allprojects

### ISSUE THREAD

**Issue by GrzegorzBobryk** [detekt/detekt#6555]
## Expected Behavior

I should have a posibility to add `detektPlugins` in `allprojects`

## Observed Behavior

After migration to kts it is imposible to use `detektPlugins` from `allprojects`. It works fine when putted in every module manually and works in `allprojects` groovy.

## Steps to Reproduce

![obraz](https://github.com/detekt/detekt/assets/38888282/1121591c-566e-44af-a7d7-e735a25af768)

## Context

Trying to make my migration to kts and this one line is blocking me.

## Your Environment

* Version of detekt used: 1.23.1
* Version of Gradle used (if applicable): 8.0
* Gradle scan link (add `--scan` option when running the gradle task):
Script compilation error:
  Line 26:        detektPlugins(Libs.Detekt.detektFormatting)
                  ^ Unresolved reference: detektPlugins
* Operating System and version: Windows 11 Pro
* Link to your project (if it's a public repository):
https://github.com/GrzegorzBobryk/ViewBindingDelegate/pull/13

**Comment by GrzegorzBobryk** [comment]
workaround:
```kts
fun DependencyHandlerScope.detektPlugins(dependencyNotation: Any) {
    add("detektPlugins", dependencyNotation)
}
```

**Comment by cortinico** [comment]
> This is a Gradle limitation. Please see this section of the docs: [docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:accessor_applicability](https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:accessor_applicability)

@3flex are we fine closing this as a Gradle limitation then?

**Comment by CoolMind** [comment]
See https://slack-chats.kotlinlang.org/t/487265/i-m-trying-to-have-some-plugins-applied-universally-across-a.
