### ISSUE TITLE
v1.23.2 does not report to be compiled with Kotlin 1.9.10

### ISSUE THREAD

**Issue by Nava2** [detekt/detekt#6581]
## Expected Behavior
Successfully runs

## Observed Behavior
```
> detekt was compiled with Kotlin 1.9.0 but is currently running with 1.9.10.
  This is not supported. See https://detekt.dev/docs/gettingstarted/gradle#dependencies for more information.
```

## Steps to Reproduce
`libs.versions.toml`
```toml
detekt = "1.23.2"
kotlin = "1.9.10"
```

## Context
This blocks upgrading to Kotlin 1.9.10.

## Your Environment
* Version of detekt used: 1.23.2
* Version of Gradle used (if applicable): 8.3
* Operating System and version: macOS

**Comment by cortinico** [comment]
Thanks for spotting this. We indeed missed the 1.9.10 bump on the 1.x branch. A point release is forthcoming: https://github.com/detekt/detekt/pull/6582

**Comment by 3flex** [comment]
Fixed in https://github.com/detekt/detekt/releases/tag/v1.23.3
