### ISSUE TITLE
Failed to execute detekt-generator-1.23.3-all.jar

### ISSUE THREAD

**Issue by ChanningShaw** [detekt/detekt#6600]
execute cmd: 
```
java -jar detekt-generator-1.23.3-all.jar -gcrc -i /path/to/rule1, /path/to/rule2
```

## Expected Behavior

executed successfully

## Observed Behavior

reports:
```
has no main manifest attribute
```

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by 3flex** [comment]
There shouldn't be a space between the input paths. Can you please remove and try again?

**Comment by BraisGabin** [comment]
I can confirm the issue. Even running `java -jar detekt-generator-1.23.3-all.jar` you get that message.
