### ISSUE TITLE
`<ktlintVersion/>` substitution in docs is broken

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#6602]
## Expected Behavior
https://detekt.dev/docs/rules/formatting links point to existing pages.

## Observed Behavior
All links in https://detekt.dev/docs/rules/formatting are missing the version number from the path in the URL:
![image](https://github.com/detekt/detekt/assets/2906988/076a1a22-2154-47f0-8855-bd3e372107e9)
For detekt docs version 1.23.3.

## Context
I diffed #6575 changes.

## Your Environment

* Version of detekt used: 1.23.3
* Version of Gradle used (if applicable): N/A
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): N/A

**Comment by TWiStErRob** [comment]
Original PR https://github.com/detekt/detekt/pull/6103, potential breaker https://github.com/detekt/detekt/pull/6468

**Comment by TWiStErRob** [comment]
Hmm, on `main` this actually works.

**Comment by TWiStErRob** [comment]
I checked out `v1.23.0` and `v1.23.1` and both those produce broken links, so it makes sense that `v1.23.3` also does.

@cortinico where did you build `docs/versioned_docs/version-1.23.1` from, because that has versioned links?

**Comment by marschwar** [comment]
I am not sure we backported the link substitution.

**Comment by TWiStErRob** [comment]
Yeah, I think so too, but then how did it have versions on 1.23.1?

e.g.
https://detekt.dev/docs/1.23.1/rules/formatting#finalnewline
vs
https://github.com/detekt/detekt/blob/v1.23.1/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/FinalNewline.kt#L14

**Comment by marschwar** [comment]
That is really weird. I don't understand how the release process works I guess. Why are the 1.23.1 docs not in the `release/1.x` branch?

**Comment by TWiStErRob** [comment]
I think that's as simple as gh-pages being published from `main`'s `/doc/`. So there's no need for it on the branch.

**Comment by cortinico** [comment]
> Yeah, I think so too, but then how did it have versions on 1.23.1?

I don't recall exactly, but I believe I might have done this by hand. I'll fix it as I do 1.23.4

**Comment by TWiStErRob** [comment]
@cortinico https://github.com/detekt/detekt/pull/6606 is RTM.

**Comment by cortinico** [comment]
> @cortinico #6606 is RTM.

Oh just saw it passing over my inbox 👍

**Comment by TWiStErRob** [comment]
Closing as #6606 is merged, and this problem only targets 1.x, will likely never reach `main`.
