### ISSUE TITLE
Please stop renaming things

### ISSUE THREAD

**Issue by sgammon** [detekt/detekt#6616]
Please, for the love of god

**Comment by 3flex** [comment]
Can you please rephrase your request and issue title so it's actionable? Otherwise you might like to open a discussion instead, though you'll need to provide more specific information.

**Comment by schalkms** [comment]
@sgammon may I ask you to please give us more details? This way we could improve the next versions of detekt and incorporate your valuable feedback. Thank you!
BR

**Comment by sgammon** [comment]
@schalkms I posted this in a pretty upset state as you might imagine, Detekt had just broken again during an update.

I realize you guys are OSS maintainers, it is a thankless job, I am one too.

I will summarize my request in clear terms in a new issue and tag it here.

**Comment by cortinico** [comment]
> Detekt had just broken again during an update

@sgammon Which update?
We're renaming things on `main` and releasing from the 1.23.x branch to prevent scenarios like this one exactly.
