### ISSUE TITLE
Provide to custom rules information about applied gradle plugins

### ISSUE THREAD

**Issue by Pschsch** [detekt/detekt#6618]
## Expected Behavior
I expect that Config object will include information about applied Gradle plugins. Example:
```
class CustomRule(config: Config): Rule(config) {
  //issue field
  
  private val appliedGradlePluginsIds: Set<String> by config()

  override fun visitSomething() {
      val isPluginApplied = appliedGradlePluginsIds.contains("plugin.id.which.i.expect.to.be.applied")
      if (!isPluginApplied) return
  }
}
```

## Current Behavior
I have no information about applied plugins at the rule execution time

## Context
So I've written at the expected behavior section what I try to get. I want apply rule only if specific Gradle plugin has been applied. Seems like that it's not so hard and it does not require any API changes. Also there would not be any Gradle configuration issues because it's need only at Gradle execution step. I could try create PR if you interested with

**Comment by 3flex** [comment]
I'm sure it's possible but I don't know if it's necessary. What problem are you trying to solve?

**Comment by Pschsch** [comment]
The problem described at this issue: https://github.com/rickclephas/KMP-NativeCoroutines/issues/140

**Comment by cortinico** [comment]
We try to keep detekt as agnostic as possible from the executing environment. So detekt is effectively invoked as a cli, and doesn't know which other Gradle plugins are applied to your build.

We could expose this information somehow, if we're running via DGP, but it feels really specific to your use case and not an API that a generic detekt rule would benefit from

**Comment by BraisGabin** [comment]
I think that this has an easy workaround. Your rule is going to be inside a third party rule set. You just add the rule when you are applying the plugin.

If the plugin is yours you can even check if the detekt plugin is applied to the project and adding your third party rule set automatically.

I'm closing this one because of the reasons that Nico said already and because I think that there are options to workaround this.

**Comment by Pschsch** [comment]
Ok, got it, thanks for feedback
