### ISSUE TITLE
Why is there not available to use digits for RuleSet id

### ISSUE THREAD

**Issue by Pschsch** [detekt/detekt#6619]
## Expected Behavior

override val ruleSetId: String = "SomeIdContaining1"

runs successfully

## Observed Behavior
RuleSet id does not match regex

**Comment by schalkms** [comment]
Could you please elaborate what you mean? Which test case, which scenario fails?
What's your use case behind overriding a `ruleSetId`?

**Comment by atulgpt** [comment]
Ruleset id in `detekt` has regex which doesn't allow digits in it. It is defined in `io.gitlab.arturbosch.detekt.api.internal` and regex is `[aA-zZ]+(-[aA-zZ]+)*`

**Comment by BraisGabin** [comment]
The things you learn... I don't see any good reason for that restriction. I thing that we could relax it. I can imagine custom rule sets called `dagger2` or `junit4`. Those names should be valid.

**Comment by atulgpt** [comment]
@BraisGabin it should at least be valid class name. Right?
