### ISSUE TITLE
UnreachableCode elvis operator bug

### ISSUE THREAD

**Issue by amertaslan** [detekt/detekt#6625]
## Expected Behavior
fun function() {
    val value = nullableVar.getFirstOrNull ?: return
    updateValue(value)
}

in this function UnreachableCode rule should not give error

## Observed Behavior
but it gives error where elvis operator used

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by atulgpt** [comment]
Hi @amertaslan can you make a reproducible code snippet or project?

**Comment by josephlbarnett** [comment]
same as #6129 ?

**Comment by BraisGabin** [comment]
Yes, it looks the same, closing in favor of that other issue that has more context.
