### ISSUE TITLE
Add `RedundantConstructorKeyword` rule

### ISSUE THREAD

**Issue by xouabita** [detekt/detekt#6637]
I could not find the rule in the open issues, but feel free to consolidate or close if it already exists.

### Non-Compliant code

```kt
data class Foo constructor(val foo: Int)
```

### Compliant code

```kt
data class Foo(val foo: Int)

data class Bar private constructor(val bar: String) {
    constructor(bar: Int): this("$foo")
}
```

## Context

This rule exists in IntelliJ and it would be nice to add it in detekt. See https://github.com/JetBrains/intellij-community/blob/9d88c1eb27825c9c6ca6b5541d88d9be2e5407bb/plugins/kotlin/code-insight/inspections-shared/src/org/jetbrains/kotlin/idea/codeInsight/inspections/shared/RedundantConstructorKeywordInspection.kt#L18

**Comment by xouabita** [comment]
I will try to contribute it 😄

**Comment by xouabita** [comment]
Hi @t-regbs, thanks for following up! Yes, my PR is now ready for review: https://github.com/detekt/detekt/pull/6660

**Comment by seelchen** [comment]
This issue seems to be resolved already, is there any reason to keep it open?

**Comment by BraisGabin** [comment]
Thanks to point that out. Closing :)
