### ISSUE TITLE
Fails to run with Kotlin 1.9.20 and Java 21

### ISSUE THREAD

**Issue by credmond-git** [detekt/detekt#6645]
## Expected Behavior
Should be able to run detekt with Kotlin 1.9.20 and Java 21.

## Observed Behavior
Receive an error 
* What went wrong:
Execution failed for task ':project:project-impl:detekt'.
> Invalid value (21) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

## Steps to Reproduce
When compiling with Kotlin 1.9.20 it works with JDK 17. But when i upgrade to JDK 21 it fails with the error:
Execution failed for task ':project:project-impl:detekt'.
> Invalid value (21) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

## Context
I am trying to upgrade our spring boot project to Java 21. To accomplish this i am upgrading: Spring boot to 3.2 with Kotlin to 1.9.20 and Java to 21. 

## Your Environment
* Version of detekt used: 1.23.3
* Version of Gradle used (if applicable): gradle-8.5-rc-3
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: Windows
* Link to your project (if it's a public repository): nope.

**Comment by credmond-git** [comment]
May be related to issue https://github.com/detekt/detekt/issues/6591

**Comment by 3flex** [comment]
This was fixed by https://github.com/detekt/detekt/pull/6572 and will be included in the next detekt release. You can try using a snapshot version of detekt in the meantime.
