### ISSUE TITLE
Add rule configuration for MagicNumber: ignoreTopLevelPropertyDeclaration

### ISSUE THREAD

**Issue by cowmanjoe** [detekt/detekt#6668]
## Expected Behavior of the rule
I think it would be nice to have a configuration setting for ignoring magic numbers in top level property declarations. This would be similar to `ignorePropertyDeclaration` configuration, except it would only apply to top level properties.

## Context
My problem is I work with `BigDecimal`s a lot in my work and we will sometimes want top-level `BigDecimal`s that act like constants. We can't use `const` modifier to obey the default MagicNumber rule's behaviour because they are not `String`s or primitives. With the MagicNumber rule, we have to do something like this:
```
private const val PRICE_OF_BREAD_DOUBLE = 15.12
private val PRICE_OF_BREAD = BigDecimal.valueOf(PRICE_OF_BREAD_DOUBLE)
```

**Comment by BraisGabin** [comment]
I would recommend you to use

```kotlin
private val PRICE_OF_BREAD = BigDecimal.valueOf("15.12")
```

Otherwise you are carry the precision problems of the double inside the bigdecimal

**Comment by BraisGabin** [comment]
Closing as there are not answer
