### ISSUE TITLE
Reduce JDK coverage on CI

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#6682]
## Expected Behavior

No unnecessary work is done when running the test suite on CI.

## Current Behavior

There are a total of 11 runs of the test suite in CI - one for each combination of LTS JDK and major OS (except JDK 8 on Windows).

## Context

With Java 21 adding another LTS version to test against we are likely wasting a lot of resources and time on redundant tests as pointed out by @BraisGabin.

Perhaps we can test only on the oldest and newest LTS JDK that detekt supports, or only on oldest + the current min JDK version supported by AGP, or some other defined strategy that reduces the size of the test matrix.

**Comment by 3flex** [comment]
CI primes the Gradle remote build cache - so whenever we drop JDK from CI it will lead to cache misses when contributors or maintainers run Gradle locally with one of those versions.

**Comment by BraisGabin** [comment]
What do you think about run this combinations?

- 8 Ubuntu
- 11 Ubuntu 
- 17 Ubuntu 
- 21 Ubuntu
- 21 Windows 
- 21 Mac OS

**Comment by 3flex** [comment]
Maybe mix the OS a little?

* 8 Ubuntu
* 11 Windows
* 17 macOS
* 21 on all

**Comment by BraisGabin** [comment]
My idea was that Ubuntu are the fastest by far. But you are right, probably two instances of windows will help to distinguish between flaky and actual problems. 

Both options work for me.

**Comment by cortinico** [comment]
> Maybe mix the OS a little?

I would instead not max as it introduces too much variaiblity and makes debugging harder (if a given build failes, you can't immediately tell if it's a OS or a JDK build)
