### ISSUE TITLE
detekt Gradle task is always created non-lazily

### ISSUE THREAD

**Issue by tasomaniac** [detekt/detekt#6691]
This issue is about lazy task configuration ([aka task configuration avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html)). It looks like the Android plugin tasks are lazy. Those work as expected. But the main `detekt` task and the tasks for jvm modules are not lazy.

## Expected Behavior

Ideally none of the Gradle tasks should be configured if they're not called/executed

## Observed Behavior

For Android modules - `detekt` task is created eagerly
For JVM modules - 3 tasks (as shown below) are created eagerly

Screenshots from Gradle build-scan.
<img width="717" alt="image" src="https://github.com/detekt/detekt/assets/763339/638251c0-f1dc-4b24-aa4d-3d9113d7d470">

<img width="816" alt="image" src="https://github.com/detekt/detekt/assets/763339/b27e9509-b94b-440f-b313-97c323a6305b">

## Steps to Reproduce

On any project, run `./gradlew help --scan`. Ideally the help task should not configure any of the tasks because they will not run.

## Your Environment

* Version of detekt used: 1.23.3
* Version of Gradle used (if applicable): 8.5
* Operating System and version: MacOS Ventura

**Comment by 3flex** [comment]
I cannot replicate when doing this on the detekt repo.

Do you have a reproducer please? Task configuration avoidance has been used in the plugin for a long time now so there might be something specific to your build that's causing an issue.

**Comment by tasomaniac** [comment]
I see what is the problem. One of the tutorials caused this issue. I will submit a fix to the tutorial to prevent this. Until then keeping it open.

**Comment by tasomaniac** [comment]
No actually not 🤦  Closing again.
