### ISSUE TITLE
Crash on weird comment (it seems)

### ISSUE THREAD

**Issue by cies** [detekt/detekt#6699]
New to Detekt, stumbled on a crash, want to help by submitting it. Feel free to close (I could easily fix the file to not let Detekt crash, so I'm not really impacted)

```kotlin
package some

import some.package.SomeEntity

class SomeException
/**
 * ...
 */(
  /**
   * ...
   */
  val some: SomeEntity
) : RuntimeException()
```

## Expected Behavior
Should not crash `detectMain`

## Observed Behavior

      Execution failed for task ':detektMain'.
      > Analyzing /home/cies/Repos/stager/app/models/ticketing/exceptions/MembershipInsufficientException.kt led to an exception.
        Location: org.jetbrains.kotlin.com.intellij.psi.impl.source.codeStyle.CodeEditUtil.saveWhitespacesInfo(CodeEditUtil.java:108)
        The original exception message was: Cannot invoke "org.jetbrains.kotlin.com.intellij.psi.impl.source.codeStyle.IndentHelper.getIndent(org.jetbrains.kotlin.com.intellij.psi.PsiFile, org.jetbrains.kotlin.com.intellij.lang.ASTNode)" because the return value of "org.jetbrains.kotlin.com.intellij.psi.impl.source.codeStyle.IndentHelper.getInstance()" is null
        Running detekt '1.23.4' on Java '18.0.2+9-FR' on OS 'Linux'
        If the exception message does not help, please feel free to create an issue on our GitHub page.

## Your Environment
* Version of detekt used: In the error
* Version of Gradle used (if applicable): 8.3
* Operating System and version: Linux, recent

**Comment by cies** [comment]
Another one:

```kotlin
package other

class OtherException : RuntimeException()
```

yielding:

        > Analyzing /home/cies/Repos/stager/app/models/ticketing/exceptions/NoTicketsAvailableException.kt led to an exception.
          Location: org.jetbrains.kotlin.com.intellij.psi.impl.source.codeStyle.CodeEditUtil.saveWhitespacesInfo(CodeEditUtil.java:108)
          The original exception message was: Cannot invoke "org.jetbrains.kotlin.com.intellij.psi.impl.source.codeStyle.IndentHelper.getIndent(org.jetbrains.kotlin.com.intellij.psi.PsiFile, org.jetbrains.kotlin.com.intellij.lang.ASTNode)" because the return value of "org.jetbrains.kotlin.com.intellij.psi.impl.source.codeStyle.IndentHelper.getInstance()" is null
          Running detekt '1.23.4' on Java '18.0.2+9-FR' on OS 'Linux'
          If the exception message does not help, please feel free to create an issue on our GitHub page.

Harder to fix...

**Comment by cies** [comment]
All of this started happening when I added `autoCorrect = true` to my Gradle config.

**Comment by 3flex** [comment]
Sorry for the late reply. This is most likely a ktlint issue. Can you please try using ktlint directly and check whether you see an error there too?

**Comment by tyler-berrett** [comment]
I'm also seeing this issue but only on linux
