### ISSUE TITLE
Shortening of the --classpath CLI-option

### ISSUE THREAD

**Issue by vatbub** [detekt/detekt#6703]
## Expected Behavior
A `--classpathFile` option exists in the CLI which points to a text file. Detekt then reads that text file and interprets the contents of the text file as if it was submitted to `--classpath`.

## Context
I am facing an issue where the classpath that I have to specify in the `--classpath` option is very long, in fact too long.  Because of that, Ant fails to launch detekt and the following exception is thrown:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (detekt) on project batch-job-executor.client: An Ant BuildException has occured: java.io.IOException: Cannot run program "C:\Program Files\Eclipse Adoptium\jdk-19.0.2.7-hotspot\bin\java.exe" (in directory "C:\Users\kammel\git\image-converter\batch-job-executor\client"): CreateProcess error=206, The file name or extension are too long
[ERROR] around Ant part ...<java fork="true" classname="io.gitlab.arturbosch.detekt.cli.Main" taskname="detekt" failonerror="true" dir="C:\Users\kammel\git\image-converter\batch-job-executor\client" classpathref="maven.plugin.classpath">... @ 9:219 in C:\Users\kammel\git\image-converter\batch-job-executor\client\target\antrun\build-detekt.xml
```

The relevant ant configuration is as follows:

```xml
<java taskname="detekt" dir="${basedir}"
      fork="true"
      failonerror="true"
      classname="io.gitlab.arturbosch.detekt.cli.Main"
      classpathref="maven.plugin.classpath">
    <arg value="--config"/>
    <arg value="${maven-parent.basedir}/detekt-config.yml"/>
    <arg value="--input"/>
    <arg value="${project.basedir}/src"/>
    <arg value="--report"/>
    <arg value="xml:${maven-parent.basedir}/target/reports/detekt.xml"/>
    <arg value="--report"/>
    <arg value="html:${maven-parent.basedir}/target/reports/detekt.html"/>
    <arg value="--report"/>
    <arg value="sarif:${maven-parent.basedir}/target/reports/detekt.sarif"/>
    <arg value="--base-path"/>
    <arg value="${maven-parent.basedir}"/>
    <arg value="--parallel"/>
    <arg value="--classpath"/>
    <arg value="${test_classpath}"/>
</java>
```

I have narrowed it down to the `--classpath` option as removing it fixes the problem (i.e. it is not `classpathref="maven.plugin.classpath"` that causes the issue).

One solution that I found [here](https://stackoverflow.com/questions/17749010/maven-and-ant-cant-run-java-createprocess-error-206-the-filename-or-extensio) is to generate a temporary jar file that only contains a manifest whose classpath references the actual classpath and point detekt to that classpath then. This, however does not seem to work (and I don't know why yet) and generating this jar also requires big changes to my build process. I would therefore prefer it if I could write the classpath to a text file and point detekt to that text-file, for instance using a `--classpathFile`  option.

**Comment by 3flex** [comment]
Please have a look and see if you can use an `@argfile`: https://docs.oracle.com/en/java/javase/21/docs/specs/man/java.html#java-command-line-argument-files

I don't think we need to do anything specifically in detekt to support this.

**Comment by vatbub** [comment]
But an @argfile is for the JVM right? I need this for detekt, not the JVM..

Matthew Haughton ***@***.***> schrieb am Di., 12. Dez. 2023,
05:53:

**Comment by 3flex** [comment]
Aren't you calling `java` from Maven? You should be able to pass the required arguments.

I'm not sure I can help further but I'll leave this open in case others can chip in.

**Comment by vatbub** [comment]
TIL (today I learned) that you can use @argfile for any arguments, not just JVM arguments. This, of course, makes this issue moot. Thanks for your help :)

For reference, this is my new Ant config:

```xml
<echo message="--config&#xD;&#xA;${project.basedir}/detekt-config.yml&#xD;&#xA;--input&#xD;&#xA;${project.basedir}/src&#xD;&#xA;--report&#xD;&#xA;xml:${project.build.directory}/reports/detekt.xml&#xD;&#xA;--report&#xD;&#xA;html:${project.build.directory}/reports/detekt.html&#xD;&#xA;--report&#xD;&#xA;sarif:${project.build.directory}/reports/detekt.sarif&#xD;&#xA;--base-path&#xD;&#xA;${project.basedir}&#xD;&#xA;--parallel&#xD;&#xA;--classpath&#xD;&#xA;${test_classpath}"
      file="${project.build.directory}/detektJvmArgs.txt" />
<java taskname="detekt" dir="${basedir}"
      fork="true"
      failonerror="true"
      classname="io.gitlab.arturbosch.detekt.cli.Main"
      classpathref="maven.plugin.classpath">
    <arg value="@${project.build.directory}/detektJvmArgs.txt"/>
</java>
```
