### ISSUE TITLE
Test failures caused by a changed wording of failure messages

### ISSUE THREAD

**Issue by vatbub** [detekt/detekt#6708]
## Expected Behavior
The build and tests succeed when checking out `origin/main`

## Observed Behavior
The build fails with the following message:

```
    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':detektMain'.
    > Analysis failed with 3 weighted issues.

    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.
    > Get more help at https://help.gradle.org.

    BUILD FAILED in 29s
    3 actionable tasks: 3 executed
    "
    to contain:
      "failed with 3 issues." 
        at io.gitlab.arturbosch.detekt.JvmSpec.Type resolution on JVM(JvmSpec.kt:17)
```

The full build log is attached here: [buildLog.txt](https://github.com/detekt/detekt/files/13635781/buildLog.txt)

Amongst others, it fails at `JvmSpec.kt` line 17 which states:

```kotlin
assertThat(result.output).contains("failed with 3 issues.")
```

The actual output, however, contains `"failed with 3 weighted issues."`, so, changing the above line to 

```kotlin
assertThat(result.output).contains("failed with 3 weighted issues.")
```

fixes the issue. I will shortly post a PR that contains all places where this is happening.

## Steps to Reproduce
1. Clone the repo
2. Checkout `origin/main`  (In particular, I ran this on `8e350ee7a895baacdbeb4480812cfb173ae750a8`)
3. Run `./gradlew build -x dokkaHtml`

## Context
N/A

## Your Environment
* Version of detekt used: N/A
* Commit affected: `8e350ee7a895baacdbeb4480812cfb173ae750a8`

* Version of Gradle used (if applicable): 8.5
* Gradle scan link (add `--scan` option when running the gradle task): https://gradle.com/s/bwo67jnwume24
* Operating System and version: Windows 10 Version 21H2
* Link to your project (if it's a public repository): N/A

**Comment by vatbub** [comment]
I can also reproduce this locally with `7bbdb026e320600c1e97eaf199a266681d83f5e9`. Funnily enough, the CI now fails on my PR _because_ of those changes.

**Comment by vatbub** [comment]
Hmm, even when I build detekt on our internal CI (which runs ubuntu), the same test failures happen and are fixed using my PR. It seems as if my CI and your CI use different versions of detekt, even though it is all built from the same commit...

**Comment by 3flex** [comment]
Run `./gradlew publishToMavenLocal` before the build. This is unfortunately a necessary step to make sure the functional tests are using artifacts produced by the build. Without that step the artifacts will be pulled from Maven Central and the behaviour won't always align, leading to these failures.

#6415 is stalled but should fix the build dependency issue which avoids this problem.

**Comment by vatbub** [comment]
In that case, Contributing.md should mention that. As a novice to the
project it's otherwise impossible to guess that 🙃

I can make a PR for that tomorrow if I feel motivated 🙈

Matthew Haughton ***@***.***> schrieb am Mo., 11. Dez. 2023,
22:12:

**Comment by 3flex** [comment]
Agreed, this should be covered in that doc. A PR is very welcome, thanks!
