### ISSUE TITLE
New Rule: No functions with less than X usages.

### ISSUE THREAD

**Issue by mgroth0** [detekt/detekt#6778]
## Expected Behavior of the rule

The core feature needed for this rule would be the ability to count the number of usages of a member. For a "prototype" of this rule, Detekt would need to scan the entire source set that the member belongs to. For a fully functional version of this rule, Detekt would also need to be able to scan across modules and count usages from other modules.

The user can simply configure a threshold X for the maximum(or minimum) number of usages per function (or class, val, var, etc.).

The user should also be able to configure whether or not to include test source sets in the usage counting.

## Context

Essentially, this is meant to provide a similar feature to the IDE highlighting of unused members. IntelliJ currently has [an issue](https://youtrack.jetbrains.com/issue/KTIJ-11832/Unused-symbol-Mark-a-function-only-used-by-tests-as-never-used) that causes test sources to be included in usage-counting for kotlin (in contrast to Java, which has the ability not to include test sources). Even if IntelliJ did not have this issue, a Detekt rule would still provide additional benefits beyond what IDE highlighting can provide, namely automatic checks and reports and better portability.

Unused members are code smell because they increase the size and complexity of a project without providing any features. At worst, an unused member is indicative of a bug. At best, it is an idea for something that may be used in the future or has some other practical reason for existing. But most often, it is just old code that can be considered clutter and should be deleted or refactored.

**Comment by cortinico** [comment]
This won't be easy to implement as detekt doesn't have the capability to scan the entire codebase and keep a context. Every rule are effectively an implementation of the visitor pattern implemented on the node of the AST.

We could extend detekt to start collecting those aggregated metrics (i.e. # of function usages vs definitions), but this is not in the roadmap

**Comment by cortinico** [comment]
I think the question is more for @detekt/maintainers if we ever want to implement such capability or not

**Comment by schalkms** [comment]
In my opinion, this feature might be better suited for a dedicated compiler plugin. 
Technically it's possible to implement this with detekt. However, it will require more effort than just implementing a new rule. One needs to gather the information from `BindingContext` or from some other Kotlin compiler APIs.

**Comment by TWiStErRob** [comment]
Agree, detekt doesn't have the capabilities. Even if we implemented all the tracking and collation necessary for this, we would be missing out on usages from Java (and Scala/Groovy/Clojure/etc.).

---

You can however, write an Android Lint check for this, and use it in non-Android projects too via `com.android.lint` standalone plugin (see [docs](https://googlesamples.github.io/android-custom-lint-rules/usage/agp-dsl.md.html)). That at least covers Java and .class-file usages. You can have a look at [UnusedIds](https://googlesamples.github.io/android-custom-lint-rules/checks/UnusedIds.md.html) and [UnusedResources](https://googlesamples.github.io/android-custom-lint-rules/checks/UnusedResources.md.html) for inspiration.

**Comment by schalkms** [comment]
Won’t implement for the reasons listed above
