### ISSUE TITLE
`:detekt-cli:test` fails on `main`

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#6780]
When I run `./gradlew :detekt-cli:test --rerun` on `main` some tests fail with this message:

```
MainSpec > Build runner > builds correct runner(String[], KClass) > [1] [--generate-config], class io.gitlab.arturbosch.detekt.cli.runners.ConfigExporter FAILED
    java.lang.IllegalStateException: detekt was compiled with Kotlin 1.9.21 but is currently running with 1.9.22.
    This is not supported. See https://detekt.dev/docs/gettingstarted/gradle#dependencies for more information.
        at app//io.gitlab.arturbosch.detekt.cli.Main.buildRunner(Main.kt:55)
        at app//io.gitlab.arturbosch.detekt.cli.MainSpec$Build runner.builds correct runner(MainSpec.kt:38)
```

Here the build scan:
https://ge.detekt.dev/s/o2rof3dplwj66/tests/task/:detekt-cli:test/details/io.gitlab.arturbosch.detekt.cli.MainSpec$Build%20runner?top-execution=1

I'm not sure why is this happening. On CI it seems to work. I executed `./gradlew publishToMavenLocal` but it didn't help (I think that it only helps for the gradle plugin test but I tried anyway)

**Comment by Goooler** [comment]
Seems this is happening after updating Kotlin 1.9.22 in my project, I'm currently on Detekt 1.23.4,see https://github.com/Goooler/DemoApp/actions/runs/7538078394/job/20518017833.

**Comment by BraisGabin** [comment]
I marked the PR to pick-request so the next release should contain the fix.

**Comment by 3flex** [comment]
That PR only changes tests though, not production code, so there's no point picking for 1.23.x. I've untagged it.

@Goooler please take a look at the most recent comments on https://github.com/detekt/detekt/issues/6198 as this might be your issue.
