### ISSUE TITLE
EmptyKtFile should be able to ignore package declaration

### ISSUE THREAD

**Issue by mgroth0** [detekt/detekt#6788]
Rule: EmptyKtFile

## Expected Behavior of the rule

There should be a way to exclude the package declaration. A package declaration says "where" a kotlin file is in the package hierarchy, and is generally not considered content of the file.

## Context

There are rules like MissingPackageDeclaration as well as IDE automations that may cause empty kotlin files to end up with a package delcaration. Without this feature, the `EmptyKtFile` is practically useless in many projects.

**Comment by BraisGabin** [comment]
This have sense. Do you want to give it a try and contribute with a PR?

**Comment by 3flex** [comment]
Should imports also be ignored? Or don't worry about it since we already have the unused imports rules?

**Comment by BraisGabin** [comment]
> Should imports also be ignored? Or don't worry about it since we already have the unused imports rules?

I thought the same. I think that both options are good. And, for now, I would vote to let unused imports rule do their job and keep this rule as simple as possible. But I wouldn't be against handle that too on this rule.
