### ISSUE TITLE
Gradle complains about a duplicated classpath.index

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#6815]
## Expected Behavior
Compilation always works

## Observed Behavior
Some times I get this error message while running `./gradlew test` (or similar tasks):

> Entry classpath.index is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.5/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

I have no idea what generates that error or how to reproduce consistently this issue.

## Steps to Reproduce
I don't know how to reproduce it. But when I run the task again with `--rerun-tasks` all "works" again.

## Context
Man, develocity is great. [Here we have all the build scans with this issue](https://ge.detekt.dev/scans/failures?failures.failureMessage=Execution%20failed%20for%20task%20%27:detekt-core:jar%27.%0A%3E%20Entry%20classpath.index%20is%20a%20duplicate%20but%20no%20duplicate%20handling%20strategy%20has%20been%20set.%20Please%20refer%20to%20https:%2F%2Fdocs.gradle.org%2F8.5%2Fdsl%2Forg.gradle.api.tasks.Copy.html%23org.gradle.api.tasks.Copy:duplicatesStrategy%20for%20details.&search.relativeStartTime=P90D&search.timeZoneId=Europe%2FMadrid#)

~Here a build scan: https://ge.detekt.dev/s/ohbvcth3vrkw6~

~Edit: Here another build scan: https://ge.detekt.dev/s/yjb2plhsdlbas~

This could be related with https://github.com/gradle/gradle/issues/27576. Gradle sports this issue depending on how the tasks are executed.

## Your Environment
* Version of detekt used: `main`

**Comment by 3flex** [comment]
This is an IntelliJ bug. Discussion here: https://github.com/detekt/detekt/discussions/6082

Consider giving the IntelliJ bug a thumbs up: https://youtrack.jetbrains.com/issue/IJPL-401/IDEA-should-generate-classpath.index-outside-user-files-or-even-dont-generate-this-index-at-all-when-UrlClassLoader-used-for

**Comment by 3flex** [comment]
I should also mention that just deleting the files is enough to fix the build and should save time over using `--rerun-tasks`
