### ISSUE TITLE
Split what a `Rule` reports and what a `Report` receives

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#6854]
Right now the class that the `Rule` reports is what the `Report` receives. That class is `Finding`. I think that we should change that. The reason behind this is that the `Rule` needs to receive a lot of information just for that. And the core knows all that information. My idea:

- The `Rule` reports a `CodeSmell`, this "just" contains critical things that only the `Rule` can knows. For example: The error message and the `Entity`.
- The core transformate that `CodeSmell` in a `Finding`. That Finding will include all the `CodeSmell` information but it will also include things like:
   - RuleId
   - "InstaceRuleId"
   - RuleSetId
   - If the Finding was suppressed and the reason (no yet on detekt but this is somethign that we want on 2.0)
   - ...

This will make `Rule` way simpler and move the logic to `detekt-core` the place where it belongs.

I would love to get some feedback about this idea.

**Comment by BraisGabin** [comment]
I created a fast draft to show how this change would be beneficial to detekt. This is just a Draft, the names are TERRIBLE and I didn't care about anything else than make the tests pass.

1. 17c5ef3320176247af8a4dc0b02d0d8b8d7512ae Not `CodeSmell` doesn't need to implement `Compactable`. That's not related with how we report findigns. They are just util functions for the reporting.
2. 1c0d1fb4bf4e7779e1840ce4609d1b8381d25267 We don't need to pass the `issue` isntance each time to the `CodeSmell`. Easier an less error prone API. Also this changes opens the door to remove the `issue` property from `Rule` directly. The rule just needs to provide it's description. We can construct the `Issue` at `detekt-core`.
3. 1398a71d542de5d6dbd466e77e9521a528e77b57 Remove all the code related with the `Severity` from `Rule` and move it to the core. The `Rule` doesn't care about the `Severity`. It reports the Finding, then is the core that reads the configuration and decides which is the `Severity` of that Finding. This reduces the code inside the api and also makes the code look better I think.

And, as I said, this is just a Draft. If you agree with this change we can move even more things.

To give context, this is related with the point 3 of #6738. It is difficult to add the new `id` to the `Rule` (ruleId vs ruleInstanceId). With this changes the `Rule` will not need to know those two ids. The `core` will handle them.

**Comment by marschwar** [comment]
I like the direction. Do you also mean to convert `CodeSmell` into a data class or poko not implementing the `Finding` interface? I think that would help a lot.

The only downside I see is, that it takes away the possibility to carry information from a 3rd party rule to a 3rd party reporter.

**Comment by BraisGabin** [comment]
> I like the direction. Do you also mean to convert `CodeSmell` into a data class or poko not implementing the `Finding` interface? I think that would help a lot.

Yes, that's the idea. 

> The only downside I see is, that it takes away the possibility to carry information from a 3rd party rule to a 3rd party reporter.

You are right about this. We could add a `Map<String, String>` so each rule could add whatever they want there and we pass it to the finding. That would work, right?

**Comment by marschwar** [comment]
Yes, I think that would work. But I am not sure we should do it from the start or rather wait for feedback from the users.

**Comment by BraisGabin** [comment]
I need help to name things.

To me a `Rule` creates and reports `Finding`s and then detekt provides a list of `Issue`s or `CodeSmell`s (I'm not sure which name I prefer).

My reason behind this is that the rules just find possible problems and flag them (`Finding`s). Then we process those `Finding`s adding contextual information and filtering them if needed and we end up with the `Issue`s or `CodeSmell`s that detekt found.

Be aware that we will be able to use `Issue` because the current `Issue` class will disappear because it will not be needed anymore.

Does this naming have sense for you?

**Comment by marschwar** [comment]
I prefer `Issue` for those that carry the severity. For the ones that are created by the rules I like `Finding` or `Violation`. I would also like `Detektion`, but that name we already use for the consolidated results.


I did a quick check what others are using:

* **issue**: sonar, nodejsscan, snyk, appscan
* **finding**: nodejsscan, veracode
* **bug**: spotbugs
* **violation**: pmd
* (lint) **error**: ktlint, checkstyle

**Comment by BraisGabin** [comment]
Ok, so for now (and as long as no one else say other thing) a `Rule` creates `Finding`s and detekt reports `Issue`s.
