### ISSUE TITLE
Gradle build-cache mess up with our tests on Widows

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#6869]
## Expected Behavior
When I execute the test in different OS the gradle task doesn't use the build-cache from other OS

## Observed Behavior
It does: https://ge.detekt.dev/s/rhgcpvrympk7w/timeline?name=:detekt-api:test

## Context
I started this reasearch after this comment: https://github.com/detekt/detekt/pull/6829#issuecomment-1890788295

The issue is that some PRs are failing on the Windows CI. It seems that #6829 introduced the problem. But, the CI on that PR is green and the CI once that PR was merged on `main` is green too (3c6eee5df6d7cea00055d3bf258393a0b2108812). And this second one doesn't use `PTS` so that's not the problem.

And if you check the build scans of the merge on main you can see that the 3 excutions on Windows have `detekt-cli:test FROM-CACHE`.

- https://ge.detekt.dev/s/rhgcpvrympk7w/timeline?name=:detekt-api:test
- https://ge.detekt.dev/s/5ubb3oyfqkdr6/timeline?name=:detekt-api:test
- https://ge.detekt.dev/s/3s5rpvi7gtb6g/timeline?name=:detekt-api:test

## Possible solution
I imagine that we should add an input for all the `test` tasks that defines the OS. This way gradle will not share the build-cache between them.

## Your Environment
* Version of detekt used: main

**Comment by 3flex** [comment]
An alternative would be to use something like [jimfs](https://github.com/google/jimfs) for the tests that deal with path handling, and have separate unit tests for Windows & *nix that will run on any OS.

If we do instead add the OS as a cache key as proposed I think that should be done alongside splitting test sources so the tests that are OS-dependent are in a separate source set from everything else. Unit tests shouldn't depend on the OS they run on.

**Comment by BraisGabin** [comment]
Here we have another instance of this issue: #7104 is failing for something that, I guess, was introduced at #7092

And I don't know how we could spot that this test was OS dependant.

**Comment by 3flex** [comment]
> I don't know how we could spot that this test was OS dependant.

The test deals with path input - that's the common issue. But I'm also not sure how best to spot this and make sure it's consistently identified and handled appropriately, other than just fixing it as it comes up. There's so much change at the moment that it's causing issues but it should settle once 2.0 is out the door.
