### ISSUE TITLE
Refactor how we handle `Baseline`

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#6882]
The code that handles the baseline feature is a bit messy. We have 3 different files that could be simplified in only one:

- `BaselineResultMapping`
- `BaselineFilteredResult`
- `BaselineFacade`

In all that code we are using the concept of `Detektion` that we don't need at all. My idea would be to merge all the logic in one single file `BaselineResultMapping` and rewrite the tests to check the cases. They aren't that much so we can take that as a single unit.

**Comment by MaximSysoev** [comment]
@BraisGabin Do we really need to rewrite tests? It seems that BaselineFacadeSpec and BaselineFilteredResultSpec just will be deleted. BaselineResultMapping will have the same set of public methods as earlier.

**Comment by BraisGabin** [comment]
Sure, with this refactor the tests should be rebased too. I imagine that we should merge them too.

**Comment by MaximSysoev** [comment]
@BraisGabin Please take a look at my PR.
