### ISSUE TITLE
Support Kotlin 1.9.22

### ISSUE THREAD

**Issue by sgyyz** [detekt/detekt#6898]
## Expected Behavior
The plugin can support Kotlin `1.9.22`.

## Current Behavior
The `detekt` plugin's latest version `1.23.4` only supports Kotlin `1.9.21`

## Context
```
Execution failed for task ':detekt'.
> detekt was compiled with Kotlin 1.9.21 but is currently running with 1.9.22.
  This is not supported. See https://detekt.dev/docs/gettingstarted/gradle#dependencies for more information.
```

Since the latest spring-boot stable version already upgraded the `jvm` plugin to `1.9.22`.

**Comment by Goooler** [comment]
Please take a look at the most recent comments on #6198 as this might be your issue.


Check https://detekt.dev/docs/gettingstarted/gradle#dependencies for more information

**Comment by 3flex** [comment]
Snapshots are also available which are currently compiled against 1.9.22.

**Comment by sgyyz** [comment]
@3flex any plan to release a patch version to upgrade it?

**Comment by 3flex** [comment]
I don't do the releases, but maybe, @cortinico?

In the meantime there's information about how to stop Spring from overriding the Kotlin version at the links provided above. You don't need a new detekt release to use detekt with Spring and different Kotlin versions.

**Comment by cortinico** [comment]
I can definitely do another release, but having to re-release detekt for every other minor of Kotlin is a major PITA

**Comment by sgyyz** [comment]
The `1.23.5` supports the Kotlin `1.9.22`, thanks @cortinico.
