### ISSUE TITLE
Allow enabling all rules in rule set

### ISSUE THREAD

**Issue by mgroth0** [detekt/detekt#6902]
## Expected Behavior

There should be a way either with the configuration file or the API to enable all rules in a rule set, rather than having to write each one in the yaml file.

## Current Behavior

My only options are:
1. Manually add all custom rules to both my RuleSetProvider and my yaml file.
2. Use the gradle property `allRules  = true`, which would enable tons of rules that I do not want.

## Context

I am creating a custom rule set. I have to add the list of rules to my custom RuleSetProvider as well as to my configuration file, which is redundant. There is a risk that I will add a rule to the RuleSetProvider, but forget to add it in the yaml file.

Is there a way to make all the rules for my custom RuleSetProvider enabled by default, either in the API or config? This would need to be on a per-ruleset basis and not affect other rulesets as `allRules=true` would.

**Comment by cortinico** [comment]
Nope there is no easy way for doing that.

> Manually add all custom rules to both my RuleSetProvider and my yaml file.

What's wrong with this approach?

**Comment by BraisGabin** [comment]
🤔 for custom rules you should provide your own default configuration. Here you have an example: https://github.com/BraisGabin/detekt-compiler-rules/blob/main/src/main/resources/config/config.yml

If you do that in the consumer side they should do nothing to enable the rules. The `detekt-generator` cli should help to automatically create this file. But I think that no too much people are using it right now so it can be a bit buggy for third parties. But we are willing to improve that tool. So any issue is more than welcome. We want to improve development experience for third party rule authors.
