### ISSUE TITLE
Function can be internal

### ISSUE THREAD

**Issue by DHosseiny** [detekt/detekt#6919]
Some Functions/Classes can have internal modifier when they are designed to be used inside of module.

Not adding internal modifier to them is not a good practice because it leads to misuse of the class/function out of module.

## Expected Behavior of the rule

Detekt can be check if the function/class usages are **just** inside the module and raise an error if internal modifier not added to it.

**Comment by DHosseiny** [comment]
But in my mind it can be a lint rule too.

**Comment by cortinico** [comment]
> are **just** inside the module

Sadly Detekt cant' do this as it doesn't have visibility among the module (which is a compilation concept)
