### ISSUE TITLE
New Rule Proposal: NoEmptyPackage

### ISSUE THREAD

**Issue by mgroth0** [detekt/detekt#6941]
## Expected Behavior of the rule

Fail if there is an empty package (a source folder with no files inside of it)

## Context

I know that the scope of a Detekt rule is usually the contents of a Kotlin file. But given the source file tree is already being walked, could this be possible?

**Comment by 3flex** [comment]
> new files inside of it

Did you mean "no" files inside of it?

If so, what's the need for this? Empty folders are ignored by git and the Kotlin compiler, so while they're a bit annoying, they don't cause any harm. And you're right that detekt operates on files so a rule like this would require special handling. I don't think it's a good fit.

**Comment by cortinico** [comment]
> If so, what's the need for this? Empty folders are ignored by git and the Kotlin compiler, so while they're a bit annoying, they don't cause any harm. And you're right that detekt operates on files so a rule like this would require special handling. I don't think it's a good fit.

Closing as we won't be able to implement this change in detekt + as @3flex mentioned, empty folders will be ignored by git/compiler. This is more something that a pre-commit hook or other tools could implement
