### ISSUE TITLE
Rule to verify calling super

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#6960]
## Expected Behavior of the rule
When `@javax.annotation.OverridingMethodsMustInvokeSuper` or `@androidx.annotation.CallSuper` is present on a method which is overridden, report that a call must be made. Very likely `@RequiresTypeResolution`.

## Context
Android Lint has a check for this, but when writing non-Android code, that is not usable.
Most projects likely have `com.google.code.findbugs:jsr305` which includes this annotation, but at present there's no Kotlin detector I could find other than Android Lint.

This gap could be very useful for rule authors and detekt contributors as well, since we continuously forget calling `super.visit()`.

## References
 * https://errorprone.info/bugpattern/MissingSuperCall
 * https://googlesamples.github.io/android-custom-lint-rules/checks/MissingSuperCall.md.html
 * oddly enough spotbugs (successor of maintainer (findbugs) of jsr305.jar) does not support it

**Comment by BraisGabin** [comment]
My only concern here is if we should add `javax.annotation.OverridingMethodsMustInvokeSuper` and `androidx.annotation.CallSuper` as default values on this rule. And if we don't add them: how many people will use these rule? Because it will be a rule that force you to configure it and to know how.
