### ISSUE TITLE
reportsDir property omission in Detekt task for android and jvm configurations

### ISSUE THREAD

**Issue by rwqwr** [detekt/detekt#6963]
## Expected Behavior
- The `reportDir` property in the Gradle task [Detekt](https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/Detekt.kt#L135) is equivalent to that set in the [DetektExtension](https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/extensions/DetektExtension.kt#L21).
- The `reportDir` property in the Gradle task [Detekt](https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/Detekt.kt#L135) is annotated with the `@OutputDirectory` annotation.

## Observed Behavior
- The `reportDir` property from DetektExtension is only used in DetektPlain configuration and is omitted in DetektAndroid and DetektJvm. Instead it is directly used to [set the outputLocation](https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektMultiplatform.kt#L143) for DetektReport. 
- Currently, the `reportDir` property in the Gradle task is marked with the `@Internal` annotation, preventing its use for task linking through inputs/outputs.

## Steps to Reproduce
```kotlin
//build.gradle.kts

abstract class CollectDetektReportsTask : DefaultTask() {

    @get:InputFiles
    abstract val reports: ConfigurableFileCollection
}

val collectReportTask = tasks.register("collectDetektReports", CollectDetektReportsTask::class)
subprojects {
    plugins.withType(DetektPlugin::class.java) {
        val detektTasks = tasks.withType(Detekt::class.java)
        collectReportTask.configure {
            reports.from(detektTasks.map { it.reportsDir })
        }
    }
}

//app/build.gradle.kts

plugins {
    ....
    id("io.gitlab.arturbosch.detekt")
}

detekt {
    reportsDir = project.layout.buildDirectory.dir("detektReport").get().asFile
}
```

Run:
```bash
./gradlew :collectDetektReports
```

Output:
```txt
Cannot query the value of task ':app:detektDebugUnitTest' property 'reportsDir' because it has no value available.
```

## Context
I want to collect all reports from Detekt tasks using the root collect task as [ReportMergeTask](https://detekt.dev/docs/introduction/reporting/#kotlin-dsl) does, but I need to use a custom report format (csv) and use task configuration avoidance and link tasks to each other by inputs/outputs as [Gradle recommends](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html). 
Currently this is not possible for Detekt, as the task outputs are not directly linked to the task itself as described at https://github.com/detekt/detekt/issues/4856. 
I noticed that the task also has a [reportDir](https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/Detekt.kt#L135) property, which is an output for the task and could be a solution to the problem, but it is marked as `@Internal`. I also noticed that the task property has no convention value from `DetektExtension` because it is omitted in the DetektAndroid and DetektKotlin classes, but is only set for DetektPlain . 

## Solution

To solve the problem with the reportDir property in Detekt tasks, I suggest setting a convention for the reportDir property within the task based on the value from the DetektExtension, as was done for [DetektPlain](https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektPlain.kt#L25).

## Inquiry

Is there a specific reason for marking the `reportDir` as `@Internal`? Could it be annotated with `@OutputDirectory` to resolve issue and improve Detekt's integration with Gradle's task configuration avoidance and output linking?

## Your Environment

* Version of detekt used: 1.23.5
* Version of Gradle used (if applicable): 8.6
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by 3flex** [comment]
Please review #6964 which should fix this. I haven't made the update you suggested, but the PR updates the report output locations so they're correctly annotated and linked to the task.
