### ISSUE TITLE
KtFile.virtualFilePath returning file name without full path

### ISSUE THREAD

**Issue by mgroth0** [detekt/detekt#6965]
In the latest release (1.23.5), `KtFile.virtualFilePath` returns the absolute file path.

In the current k2 branch (https://github.com/detekt/detekt/pull/6640) , `KtFile.virtualFilePath` returns just the file name, not the full path.

## Expected Behavior

We should be able to get the full path to the file in a custom rule.

## Observed Behavior

We now can only get the name, not the full path.

## Steps to Reproduce
1. Create a custom rule
2. in `visit` print the (`root.virtualFilePath`)

## Context

I have a couple of custom rules that validate the file name and package name based on the full file path. These rules now fail in the updated branch.

**Comment by 3flex** [comment]
That change was made in #6310

There's `PsiFile.absolutePath()` which should get you what you want.
