### ISSUE TITLE
RFC: KMP compilation analysis task names

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#7002]
## Expected Behavior

We have a consistent and unsurprising method for naming Gradle tasks registered by the Gradle plugin.

## Current Behavior

Current naming conventions are determined based on target type and whether it's MPP or not.

## Context

I would like to define rules for task naming so they're consistent and unsurprising.

Some possible options:
1. Use same naming rules for detekt compilation analysis tasks as the Kotlin plugin - replacing "compile" prefix with "detekt" prefix: `"detekt" + compilationName.takeIf { it != KotlinCompilation.MAIN_COMPILATION_NAME } + "Kotlin" + target.targetName`
2. As above, but leave `main` in the task name when it's the main compilation: `"detekt" + compilationName + "Kotlin" + target.targetName`
3. As above, but remove Kotlin: `"detekt" + compilationName + target.targetName`
4. Something else?

#### KMP Java
Given compilation tasks compileKotlinJvm and compileTestKotlinJvm:
1. detektKotlinJvm, detektTestKotlinJvm
2. detektMainKotlinJvm, detektTestKotlinJvm
3. detektMainJvm, detektTestJvm

#### Android
Given compilation tasks compileDebugKotlinAndroid, compileDebugAndroidTestKotlinAndroid, compileDebugUnitTestKotlinAndroid:
1. detektDebugKotlinAndroid, detektDebugAndroidTestKotlinAndroid, detektDebugUnitTestKotlinAndroid
2. Same as 1
3. detektDebugMainAndroid, detektDebugAndroidTestAndroid, detektDebugUnitTestAndroid

#### Native
I haven't checked real samples, but for an iosArm64 target, it should be similar to:
1. detektKotlinIosArm64, detektTestKotlinIosArm64
2. detektMainKotlinIosArm64, detektTestKotlinIosArm64
3. detektMainIosArm64, detektTestIosArm64

### Final thoughts
1. In MPP the task name seems to be treated as an implementation detail and the KGP naming convention is not documented. By simply creating corresponding tasks with `compile` replaced with `detekt` we can say that the compilation analysis will be performed on the same source & compilation setup as the originating task, and the names are almost identical. It also makes it easy to say that if the task names don't align, there's either a bug or some behaviour change in KGP that we need to look into.
2. With this option we have similar rationale but including `main` in the task name makes things a little clearer, so we can easily document that the task name format is `detekt<compilation name>Kotlin<target name>` and have a single, consistent naming rule.
3. As above but document as `detekt<compilation name><target name>`

In order of preference I would choose 1 or 3 in either order. 2 is at the bottom of the list. Would be good to get other thoughts.

**Comment by 3flex** [comment]
So your vote is for `"detekt" + compilationName + target.targetName`?

My thoughts on the alias is that we have a single lifecycle task `detekt` that we hook up to other task dependencies. But that would be the only one. It would depend on the "best" detekt analysis tasks, i.e. Using type resolution if available and only for the standard compilations (main and test on JVM for example).

That would be another PR.

I don't think we should spend any thought or effort on keeping other task names available. But we should offer ways to easily depend on sets of tasks that meet certain criteria. Again, separate piece of work.

> it would be great to align the tasks of pure jvm project with the ones of kmp.

Disagree as a specific goal for two reasons:
1. When not using KMP the target name is redundant. Adding `Jvm` suffix on every task name for a non-KMP project just adds noise.
2. Target name on KMP can be completely custom, you can declare a target like `jvm("strange")` and every Kotlin compilation task will end with "Strange", not "Jvm", so there's really no way to align. KMP and non-KMP works quite differently.

> the Native/3 options are not correct, right?

Whoops, fixed.

**Comment by BraisGabin** [comment]
> So your vote is for `"detekt" + compilationName + target.targetName`?

Yes! 

> Disagree as a specific goal for two reasons:
> 1. When not using KMP the target name is redundant. Adding `Jvm` suffix on every task name for a non-KMP project just adds noise.
> 2. Target name on KMP can be completely custom, you can declare a target like `jvm("strange")` and every Kotlin compilation task will end with "Strange", not "Jvm", so there's really no way to align. KMP and non-KMP works quite differently.

Have sense! Forget what I said.

**Comment by eygraber** [comment]
The new task names seem a little incongruous at first glance because KGP refers to things as `targetName + compilationName` (e.g. `commonMain`, `jvmMain`, jsTest`, etc...).

**Comment by 3flex** [comment]
Source sets and compilations have different naming conventions so they can't always align to each other when using KMP. `common` isn't a compilation target either.

The proposed task names for compilation analysis tasks align to the naming conventions for the Kotlin compilation tasks which I think best reflects their scope.

We're open to ideas here though, is there something else that would work better for you?

**Comment by eygraber** [comment]
My experience has been that most users are more familiar with source set names than they are with compilation names, and it would be easier to mirror what KGP does.

I'm working through some of this now [here](https://github.com/detekt/detekt/issues/6634#issuecomment-1996012038).

**Comment by 3flex** [comment]
> it would be easier to mirror what KGP does

This setup does mirror though - there needs to be a clear differentiation between source set tasks (fast, can't run all rules) and compilation tasks (slower, can run all rules). And the names of those tasks need to make sense.

Can we split the conversation please so each issue remains on topic - this issue is about task names, the issue you linked is about dependencies between tasks.

**Comment by eygraber** [comment]
> Can we split the conversation

I mentioned it because the code I wrote is kind of related, since it allows for type resolution to be used with source set tasks in some cases.
