### ISSUE TITLE
Release a version compiled with kotlin 1.9.23

### ISSUE THREAD

**Issue by Ihor-Hadzera-VGW** [detekt/detekt#7050]
Please add new release with support of Kotlin 1.9.23

**Comment by BraisGabin** [comment]
Detekt already supports kotlin 1.9.23. If you are getting any issue please open an issue explaining the problem (and check that it was not solved already). Probably this helps: https://detekt.dev/docs/gettingstarted/gradle#gradle-runtime-dependencies
