### ISSUE TITLE
detekt.dev is down

### ISSUE THREAD

**Issue by nvuillam** [detekt/detekt#7115]
There is several hours that detekt.dev is down, it makes MegaLinter internal CI crash ^^

![image](https://github.com/detekt/detekt/assets/17500430/18c7cfa2-54bf-41d5-abee-30e1f23c6d9c)

**Comment by mondaylord** [comment]
Same problem.

**Comment by 3flex** [comment]
@detekt/maintainers I'm not sure which of you can fix this, but whoever has access, can you please take a look?

**Comment by cortinico** [comment]
Now is back, there was a DNS misconfiguration on cloudflare + GitHub pages

> There is several hours that detekt.dev is down, it makes MegaLinter internal CI crash ^^

mmm not sure why MegaLinter CI should depend on our public website being up though 🤔

**Comment by nvuillam** [comment]
@cortinico we like to have a clean documentation so we check for dead links with [lychee](https://megalinter.io/beta/descriptors/spell_lychee/) ;)

**Comment by TWiStErRob** [comment]
@nvuillam was it actually crashing or just failing?

**Comment by nvuillam** [comment]
@TWiStErRob `failing` is a more appropriate word indeed :)
