### ISSUE TITLE
Link to default detekt config should be versioned

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#7133]
## Expected Behavior
Link to the default detekt config from the detekt.dev website should be versioned.

## Observed Behavior
It links to the generated file on main branch.

## Steps to Reproduce
Navigate to https://detekt.dev/docs/introduction/configurations, click link in this paragraph:

> See the [default-detekt-config.yml](https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml) file for all defined configuration options and their default values.

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by cortinico** [comment]
This is fairly easy to achieve as we already have support for templating the detekt version during the website generation 👍 

Happy to receive a PR or to help someone write this
