### ISSUE TITLE
Our CI reports the same issue more than once

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#7141]
## Expected Behavior
When I push a PR on the repo with one issue it is reported only once.

## Observed Behavior
Right now github is reporting it 3 times (see screenshot below):

<img width="753" alt="Captura de pantalla 2024-04-06 a las 23 32 15" src="https://github.com/detekt/detekt/assets/721244/1d749d1e-7930-44bf-ae7e-f624ffaf9e56">

## Steps to reproduce
Create a PR with an unused import.

## Context
This happened me multiple times already but you can check #7108 as an example

## Your Environment
* Version of detekt used: main

**Comment by 3flex** [comment]
Could be the updated merging of sarif reports?

**Comment by BraisGabin** [comment]
I think so

**Comment by BraisGabin** [comment]
I think that I fixed this already.
