### ISSUE TITLE
Baseline cleaning task

### ISSUE THREAD

**Issue by dzmpr** [detekt/detekt#7180]
Consider adding `detektCleanBaseline` task or a parameter for `detektBaseline` task which removes already fixed issues from baseline while not adding new. Now if you have `build.maxIssues > 0` new issues not fail detekt task, but `detektBaseline` task add them to baseline. It's only possible way to clean baseline: do it manually or set `maxIssues = 0` and set issues weight to 0, then run baseline.

## Context
I have an old project where some time ago detekt was added. It has a large baseline. During refactoring some issues were fixed but still present in baseline. And due to this it harder to plan work on tech debt using baseline.

**Comment by cortinico** [comment]
> It's only possible way to clean baseline: do it manually or set `maxIssues = 0` and set issues weight to 0, then run baseline.

In general for baseline, you want to just re-generate them. What's the point of adding yet another task for us to maintain when you can already achieve the same result?

**Comment by dzmpr** [comment]
> What's the point of adding yet another task for us to maintain when you can already achieve the same result?

If there are new issues that weight set 0 – they would appear in regenerated baseline.
As I said it might be just a flag, which excludes new issues from baseline, not a new task.

**Comment by 3flex** [comment]
This is too specific so I agree that we shouldn't add this feature.

The idea with the baseline is to generate then regenerate as issues are fixed - and that new issues are not introduced to the baseline once it's been established.

**Comment by BraisGabin** [comment]
I also agree that we don't want this by default.

Some extra thoughts:
- the weight concept is not going to exist on 2.0. We introduced the severity that should fulfill the same use cases.
- if you really want this feature you can implement it yourself. The Detekt api is extensible and this should be easily doable. Even the default baseline is implemented using this extensible api.
