### ISSUE TITLE
Question for new rule to check if test method is missing `@Test` annotation

### ISSUE THREAD

**Issue by trietbui85** [detekt/detekt#7207]
## Expected Behavior of the rule

It would check the Test File for any test method that doesn't have `@Test` annotation.

## Context

Sometimes devs forget to add the `@Test` annotation (yeah, really). So a Detekt rule would be helpful to avoid this situation.

**Comment by BraisGabin** [comment]
https://github.com/BraisGabin/detekt-junit-rules

That rule is implemented there. Detekt doesn't have rules related with frameworks. For that resin this is implemented in a third party plugin.

**Comment by trietbui85** [comment]
Thanks a lot. I even know there is such Detekt plugin.
