### ISSUE TITLE
Ignore / Suppress specific magic number warning in detekt baseline.xml for a Compose function

### ISSUE THREAD

**Issue by talhahasanzia** [detekt/detekt#7275]
### Discussed in https://github.com/detekt/detekt/discussions/7274

<div type='discussions-op-text'>

<sup>Originally posted by **talhahasanzia** May  8, 2024</sup>
To ignore magic number in a class, we can do this:
```
    <ID>MagicNumber:FeatureManager.kt$FeatureManager$30</ID>
```

Where, `FeatureManager` is class, and `30` is magic number.

What would happen if this is in compose lets say:

```
@Composable
fun CustomComposable(){
    LaunchedEffect(Unit) {
        delay(3000) // this needs to be added to baseline
        ...
    }
}
```

I have tried multiple approaches, but still I am unable to suppress this.

Referencing direct function from file reference:

```
    <ID>MagicNumber:CustomComposable.kt$CustomComposable$3000</ID>
```

Referencing direct magic number from file reference:
```
    <ID>MagicNumber:CustomComposable.kt$3000</ID>
```

Referencing direct magic number from element (function) reference:
```
    <ID>MagicNumber:CustomComposable$3000</ID>
```

This is hit and trial. I know that already, that this is not the way to do it (not mentioned in the docs what to do either)

Only reference to read for Baseline I found is this [detekt website](https://detekt.dev/docs/introduction/baseline/)</div>

**Comment by BraisGabin** [comment]
Answered on the Discussion
