### ISSUE TITLE
ignoreFailures doesn't work when using gradle workers 

### ISSUE THREAD

**Issue by AlexanderGH** [detekt/detekt#7280]
## Expected Behavior
Enabling gradle workers in the Detekt Gradle should be a functional no-op. `ignoreFailures = true` should result in no failures even when there are violations.

## Observed Behavior
All tasks with violations fail, even with ignoreFailures = true.

## Steps to Reproduce
Enable detekt.use.worker.api = true, parallel = true, ignoreFailures = true.
Add some violating code.
Run `./gradlew detektDebug`

## Your Environment
* Version of detekt used: 1.23.6 (latest)
* Version of Gradle used (if applicable): 8.7
* Gradle scan link (add `--scan` option when running the gradle task): Not Public
* Operating System and version: Mac OSX (Latest Stable)
* Link to your project (if it's a public repository): Not Public

**Comment by 3flex** [comment]
This should be fixed in main branch by #6964. Can you please try with a snapshot version of the Gradle plugin?

Until there's a new release you'll need to disable workers unfortunately.

**Comment by AlexanderGH** [comment]
Not sure I'll be able to get back to testing this in our repo any time soon so I'd just assume it's fixed, and if i ever get back to trying this again, I can re-open.
