### ISSUE TITLE
Multiline strings﻿ may occur parse error

### ISSUE THREAD

**Issue by baseballyama** [detekt/detekt#7284]
## Expected Behavior

Just finish detekt command

## Observed Behavior

Throw an error

```
> java.lang.IllegalStateException: Analyzing path/to/kotlin.kt led to an exception.
  Location: java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
  The original exception message was: java.lang.ArrayStoreException
  Running detekt '1.23.6' on Java '17.0.6+10-LTS' on OS 'Mac OS X'
  If the exception message does not help, please feel free to create an issue on our GitHub page.
```

## Steps to Reproduce

Run detekt with this code.

```kt
val foo = "foo"
val sql = """
foo: '$foo'""".trimMargin()
```

## Context

It is important to complete parsing without any errors.
A parsing error is inconvenient because it prevents all checks from being performed.

## Your Environment

* Version of detekt used: 1.23.6
* Version of Gradle used (if applicable): 8.7
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: Mac OS X 14.2.1
* Link to your project (if it's a public repository): N/A

**Comment by BraisGabin** [comment]
Could you share the full stack trace?

**Comment by baseballyama** [comment]
I run the command via `./gradlew` and I got only message what I shared.

And I'm not sure the reason but now I can not reproduce this issue.
Maybe there is some more special context for reproducing this, but anyway this issue is no longer reproduced at this time. (Possibly `./gradlew clean` solved this?🤔)

**Comment by BraisGabin** [comment]
Strange... If there is not way to reproduce it I'm going to close this. If you encountered it again please reopen. if you add `--stacktrace` on the `./gradlew` command you will get the full stacktrace.
