### ISSUE TITLE
Incorrect report of error - UnsafeOptInUsageError

### ISSUE THREAD

**Issue by Abhimanyu14** [detekt/detekt#7289]
## Expected Behavior
If `build.gradle` has `kotlinOptions.freeCompilerArgs` defined for opt-in experimental APIs, the `@androidx.compose.material3.ExperimentalMaterial3Api` is not required in the usage site in the code.  

But, detekt still shows lint error for them.

## Observed Behavior

Error  

>  /Users/abhimanyu/Documents/projects/finance-manager/codebase/android/core/ui/src/main/java/com/makeappssimple/abhimanyu/financemanager/android/core/ui/common/CommonScreenUIState.kt: Error: This declaration is opt-in and its usage should be marked with @androidx.compose.material3.ExperimentalMaterial3Api or @OptIn(markerClass = androidx.compose.material3.ExperimentalMaterial3Api.class) [UnsafeOptInUsageError from androidx.annotation.experimental]

## Steps to Reproduce

1. Can use any opt-in feature and use `kotlinOptions.freeCompilerArgs` in `build.gradle` instead of using annotation in the code.

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository): https://github.com/Abhimanyu14/finance-manager

**Comment by 3flex** [comment]
This is covered under https://github.com/detekt/detekt/issues/4465

**Comment by BraisGabin** [comment]
So, should we close this one as "dupe"?
