### ISSUE TITLE
The issue arises when I move the detekt-baseline.xml file from its default path (project/app/detekt-baseline.xml) to a new location (project/config/detekt/detekt-baseline.xml).

### ISSUE THREAD

**Issue by MudraPatel** [detekt/detekt#7293]
The issue arises when I move the detekt-baseline.xml file from its default path (project/app/detekt-baseline.xml) to a new location (project/config/detekt/detekt-baseline.xml). 
When I attempt to run gradle app:detekt, the Gradle tool in Android Studio fails to recognize the new path.
But when i run it from command line(./gradlew detekt) it work properly.

```
detekt {
    buildUponDefaultConfig = false 
    allRules = false 
    config.setFrom("$projectDir/config/detekt/detekt.yml") 
    baseline = file("$projectDir/config/detekt/detekt-baseline.xml") 
    disableDefaultRuleSets = false
    debug = false
    enableCompilerPlugin = true
}
```

_Originally posted by @MudraPatel in https://github.com/detekt/detekt/issues/4835#issuecomment-2109248448_

**Comment by BraisGabin** [comment]
Can you provide a reproducer? Which detekt version are you using? Which version of AS? How are you running the task from AS?

**Comment by 3flex** [comment]
Also in your description you mention two different commands: 
* gradle app:detekt (running in AS)
* ./gradlew detekt (running from CLI)

Please make sure you're using the same commands in CLI and AS.

You also seem to be using projectDir in your config, please make very sure that it's pointing to the right location after you move the file.

**Comment by MudraPatel** [comment]
Android studio version - Koala | 2024.1.1 Canary 5
detekt version - 1.23.3

I have resolved this issue - by adding the path on both the build.gradle file (root and app)

The following path has been included in the build.gradle file at the app level.
```
detekt {
    config.setFrom("../config/detekt/detekt.yml") // point to your custom config defining rules to run, overwriting default 
    baseline = file("../config/detekt/detekt-baseline.xml") // a way of suppressing issues before introducing detekt
}
```
The following path has been included in the build.gradle file at the project level.
```
detekt {
    config.setFrom("$projectDir/config/detekt/detekt.yml") // point to your custom config defining rules to run, overwriting 
    baseline = file("$projectDir/config/detekt/detekt-baseline.xml") // a way of suppressing issues before introducing detekt
}
```

Now both worked - From Android Studio gradle tool and command line.

Thanks!
