### ISSUE TITLE
JVM Target 22 is not supported by detekt

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#7382]
## Expected Behavior
Running detekt with a JVM target of 22 should work

## Observed Behavior
It fails

> Invalid value (22) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

## Steps to Reproduce
Run `./gradlew detekt on https://github.com/evant/kotlin-inject

## Context
I don't find that this happens with all of my projects.

## Your Environment
* Version of detekt used: 1.23.6
* Version of Gradle used (if applicable): 8.8
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/4ci4oxsd7cgzq
* Operating System and version: Ubuntu 24.04
* Link to your project (if it's a public repository): https://github.com/evant/kotlin-inject

**Comment by 3flex** [comment]
This is addressed by the upgrade to Kotlin 2.0.0 (#6640)
