### ISSUE TITLE
Gradle plugin is no longer compatible with Kotlin 2.0.0 and by Dependency Management Plugin

### ISSUE THREAD

**Issue by vcruzmj** [detekt/detekt#7384]
## Expected Behavior

The current approach for mismatching versions of your project and the embedded one in detekt (in the context of Gradle runtime dependencies) is described here:
https://detekt.dev/docs/gettingstarted/gradle/#dependencies.

This was working in all versions except 2.0.0
```kotlin
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.jetbrains.kotlin") {
            useVersion(io.gitlab.arturbosch.detekt.getSupportedKotlinVersion())
        }
    }
}
```
With this prior 2.0.0 you fix the message like when you build your project:

`detekt was compiled with Kotlin 1.8.0 but is currently running with 1.7.0`

## Observed Behavior

With the same approach in kotlin 2.0.0 with the configuration, the `:compileKotlin` task now fails with this message:

```sh
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Failed to transform kotlin-reflect-1.9.23.jar to match attributes {artifactType=classpath-entry-snapshot, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for BuildToolsApiClasspathEntrySnapshotTransform: /home/anonym/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.9.23/ab01e1cc8428c2140891318838ad7039f6fa389a/kotlin-reflect-1.9.23.jar.
         > Artifact org.jetbrains.kotlin:kotlin-build-tools-impl must have version aligned with the version of KGP when compilation via the Build Tools API is disabled.
```

## Steps to Reproduce

I create [this](https://github.com/vcruzmj/demo-detekt) repo with the `main` branch having the bug in `kotlin 2.0.0` and the `olderexample` branch with this working in `kotlin 1.9.4`, both with `detekt 1.23.6`

## Context
I'm trying to run detekt with Gradle in Kotlin 2.0.0 wit spring boot, but breaks the compilation of the project.
Can be related or duplicated from: https://github.com/detekt/detekt/issues/7304

## Your Environment

* Version of detekt used: 1.23.6
* Version of Gradle used (if applicable): 8.8
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: Ubuntu 22.04
* Link to your project (if it's a public repository): https://github.com/vcruzmj/demo-detekt

**Comment by 3flex** [comment]
We don't want or need the Kotlin version to be overridden on all configurations. We just need the `detekt` configuration to be left alone.

If you apply the config you've provided then you're overriding all configurations. That's having an impact on Kotlin itself which is what the warning is about.

There isn't much detekt can do about this directly. Your Gradle config needs to be fixed, or you need to find out which plugin is overriding the detekt configuration and stop it from doing that.

**Comment by vcruzmj** [comment]
> If you apply the config you've provided then you're overriding all configurations. That's having an impact on Kotlin itself which is what the warning is about.

But that is detekt official documentation https://detekt.dev/docs/gettingstarted/gradle/#dependencies, it's even in the logs of the warning.
 
> There isn't much detekt can do about this directly. Your Gradle config needs to be fixed, or you need to stop the dependency plugin overriding the configs.

But below Kotlin 2.0.0 this was working, so, was the official way to do it now? The only real change in my gradle configuration is kotlin from 1.9.4 to 2.0.0.

**Comment by vcruzmj** [comment]
reading #6198 more in detail, I tried this:

```kotlin
configurations.matching { it.name == "detekt" }.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.jetbrains.kotlin") {
            useVersion(io.gitlab.arturbosch.detekt.getSupportedKotlinVersion())
        }
    }
}
```

With that the project is fixed.

So instead of using `configurations.all {` I should use `configurations.matching { it.name == "detekt" }.all {`

I think (maybe it's just me) the documentation on https://detekt.dev/docs/gettingstarted/gradle/#dependencies should be updated to precise that configuration as an example, or I need to learn how to read better.

Thanks anyway for your help, and for this project.

**Comment by BraisGabin** [comment]
> I think (maybe it's just me) the documentation on https://detekt.dev/docs/gettingstarted/gradle/#dependencies should be updated to precise that configuration as an example, or I need to learn how to read better.

Can you provide a PR fixing the documentation?

**Comment by OksiBlack** [comment]
for me with spring boot project and build script plugins this

`
configurations.matching { it.name.contains("detekt") }.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.jetbrains.kotlin") {
            useVersion(io.gitlab.arturbosch.detekt.getSupportedKotlinVersion())
        }
    }
}
`

does not work.

Still detekt was compiled with Kotlin 1.9.23 but is currently running with 2.0.0.

**Comment by zaenk** [comment]
there's a note in the [gradle docs for ResolutionStrategy#eachDependency](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html#org.gradle.api.artifacts.ResolutionStrategy:eachDependency(org.gradle.api.Action))

> The rules are evaluated in order they are declared

with convetion plugins, `resolutionStrategy.eachDependency` was not working for me, because the detekt plugin was applied earlier then the spring dependency management - the latter was overriding the kotlin version.

one workaround I found was applying a custom plugin with the resolution startegy override in the module where spring dependency management is included

the custom plugin

```kotlin
package foo.bar

import io.gitlab.arturbosch.detekt.getSupportedKotlinVersion
import org.gradle.api.Plugin
import org.gradle.api.Project

class FixDetektKotlinResolution : Plugin<Project> {
    override fun apply(target: Project) {
        target.configurations.matching { it.name == "detekt" }.all {
            resolutionStrategy.eachDependency {
                if (requested.group == "org.jetbrains.kotlin") {
                    useVersion(getSupportedKotlinVersion())
                }
            }
        }
    }
}
```

and using it in another plugin

```kotlin
import foo.bar.FixDetektKotlinResolution

plugins {
    kotlin("jvm")
    id("io.spring.dependency-management")
    kotlin("plugin.spring")
}

dependencyManagement {
    imports {
        mavenBom(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
    }
}

apply<FixDetektKotlinResolution>()
```
