### ISSUE TITLE
Support State<Boolean> and Flow<Boolean> for NonBooleanPropertyPrefixedWithIs.

### ISSUE THREAD

**Issue by MaximSysoev** [detekt/detekt#7387]
## Expected Behavior of the rule
What do you think if `NonBooleanPropertyPrefixedWithIs` rule could be configured to ignore some types.
Now if we have something like `val isEnabled: State<Boolean>`, detekt marks such code as wrong. The same with `Flow<Boolean>`. 
It would be better to ignore `State<Boolean>` and `Flow<Boolean>` (or maybe support them right inside rule, but I'm not sure if it's good solution)
Or maybe it is possible to do now, but I don't know how?

## Context
In my team we accept that `val isEnabled: State<Boolean>` is ok and it is not necessary to name this value as `isEnabledState`. I suppose that there are many devs, who accept it.

**Comment by cortinico** [comment]
Effectively a duplicate of https://github.com/detekt/detekt/issues/5362
I believe we still don't want to implement this for the reasons mentioned in the linked issue

**Comment by MaximSysoev** [comment]
Ok, I see. Thank you for the answer. So I close the issue.
