### ISSUE TITLE
[Doc] In kts config, we should explicitly use `.set` convention as that supports all the Gradle versioin

### ISSUE THREAD

**Issue by atulgpt** [detekt/detekt#7434]
## Expected Behavior
At the doc https://detekt-git-main-detekt.vercel.app/docs/gettingstarted/gradle#kotlin-dsl-3
in the config, `basePath` we should be using `basePath.set(projectDir)` as operator overload is not present in the older Gradle plugin(it is introduced in Gradle 8.1 and will be stable from 8.4)

## Observed Behavior

At the doc https://detekt-git-main-detekt.vercel.app/docs/gettingstarted/gradle#kotlin-dsl-3
in the config, `basePath`, `basePath = projectDir.absolutePath` is used which is wrong as this config has been changed to `DirectoryProperty` from `String` at https://github.com/detekt/detekt/issues/6496

## Steps to Reproduce
Present in the latest doc at https://detekt-git-main-detekt.vercel.app/docs/gettingstarted/gradle#kotlin-dsl-3

## Your Environment

NA

**Comment by GrzegorzBobryk** [comment]
I wanted do fix that but I am a little bit confused. I am using detekt 1.23.6 and gradle 8.7. I see that still `basePath = projectDir.absolutePath` is correct in two approaches. 

First with detekt dsl:
![obraz](https://github.com/user-attachments/assets/3628ccdd-e2c7-47d5-8900-bae3cab22f5c)

Second with detekt plugin:
![obraz](https://github.com/user-attachments/assets/9e76c0f9-018d-453c-9936-7f08c9ddcc28)

Also `basePath` is still `String`:
![obraz](https://github.com/user-attachments/assets/ec91fb69-30c0-49c9-9185-d80b40ecb5b4)

Also I see big difference between compiled lib from maven, and code from main branch.
![obraz](https://github.com/user-attachments/assets/bd4f889c-808e-4b93-82c7-dd0b80d0109c)

Could you direct me on what should I look?

**Comment by atulgpt** [comment]
Hi, @GrzegorzBobryk I tested this in the [snapshot](https://detekt.dev/docs/introduction/snapshots/) version of Detekt. This changes have still not released yet and I think targeted to release in 2.0.0 version

**Comment by GrzegorzBobryk** [comment]
PR created. I am not sure how releases works here, but probably it would be better to wait with merge to time when guys release this new changes.

**Comment by cortinico** [comment]
> PR created. I am not sure how releases works here, but probably it would be better to wait with merge to time when guys release this new changes.

We can merge it now, and will appear in the `next` version on the website till we release a new stable.

**Comment by atulgpt** [comment]
Should we close this issue then?

**Comment by cortinico** [comment]
> Should we close this issue then?

Yup
