### ISSUE TITLE
Support Jvm 22

### ISSUE THREAD

**Issue by Nek-12** [detekt/detekt#7458]
## Expected Behavior

Detekt runs

## Observed Behavior

Detekt fails with

```
> Invalid value (JVM_22) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
```

## Steps to Reproduce

Pass 22 to gradle detekt task configuration

```kotlin
 withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
        jvmTarget = Configuration.jvmTarget.toString()
        parallel = true
        buildUponDefaultConfig = true
        autoCorrect = true
    }
```

## Context

We are not able to run detekt

## Your Environment

* Version of detekt used: 1.23.6
* Version of Gradle used (if applicable): 8.9
* Gradle scan link (add `--scan` option when running the gradle task): no thanks
* Operating System and version: MacOS Sonoma
* Link to your project (if it's a public repository): -

**Comment by cortinico** [comment]
I think we should do a point release (1.23.7) and add JDK 22 support (thoughts @3flex ?)

**Comment by 3flex** [comment]
Yes I think that's a good idea.

**Comment by 3flex** [comment]
This was already fixed by #6640, the only thing pending is a release. This could be closed on that basis.

**Comment by 3flex** [comment]
Closing - this is fixed in main/snapshots and will be also be available in the next release, whether that's another 1.23.x release or 2.0.0.

**Comment by sarah-jay-peper** [comment]
running into the same problem with JVMs 24 and 25 - when might the next release be due?

**Comment by Nek-12** [comment]
@sarah-jay-peper I suggest you open a new issue instead of necro-commenting on a closed one (as of more than a year)

**Comment by sarah-jay-peper** [comment]
right, sorry!
