### ISSUE TITLE
Rename @RequiresTypeResolution

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#7465]
## Expected Behavior
The annotation has a more descriptive name.

## Current Behavior
"Type resolution" is only part of the story. The analysis flag introduced by the fix for https://github.com/detekt/detekt/issues/7173 will have a certain naming convention e.g. "full" so this could be renamed to something like `@RequiresFullAnalysis` or similar.

## Context
Make things consistent for version 2.0.0.

**Comment by cortinico** [comment]
> so this could be renamed to something like `@RequiresFullAnalysis` or similar.

+1 to the name 👍 Full/Lite is something really relatable for users

**Comment by BraisGabin** [comment]
+1 to `@RequiresFullAnalysis`.

**Comment by 3flex** [comment]
This is up for grabs.
