### ISSUE TITLE
Running detekt with autoformat finds new issues (Formatting Rule Set)

### ISSUE THREAD

**Issue by vojtechpesek** [detekt/detekt#7484]
## Expected Behavior
1. Run `./gradlew detekt`.
2. Task passes, no issues are found.
3. Run `./gradlew detekt -Pformat`.
4. Task passes, no new issues are found and no formatting happens.

## Observed Behavior
1. Run `./gradlew detekt`.
2. Task passes, no issues are found.
3. Run `./gradlew detekt -Pformat`.
4. Task **fails**, new issues are reported and some are autoformatted.

## Steps to Reproduce
Replicable in the [public repository](https://github.com/vojtechpesek/detekt-repro-sample). See Section above for reproducer steps.

## Context
I expect that `detekt` task yields same results independently, whether autoformat is turned on or off. 
The use case is regular development. Before commiting, I run the detekt check manually to find any issues. I also want to use autocorrect as much as possible, but I am unable since running with autoformat formats additional files.

Additional detekt plugins included are:
- io.gitlab.arturbosch.detekt:detekt-formatting
- io.nlopez.compose.rules:detekt_compose

It might be issue of the detekt setup in project `build.gradle.kts` file. From my experimentation it looks like the issue is related to the [formatting rule set](https://detekt.dev/docs/rules/formatting/). I am currently unsure whether this problem is related to our gradle setup, or there is some bug (either in the rule set or in detekt itself).

## Your Environment
* Version of detekt used: 1.23.6
* Version of Gradle used (if applicable): 8.7
* Gradle scan link (add `--scan` option when running the gradle task): -
* Operating System and version: MacOS Sonoma 14.5
* Link to your project (if it's a public repository): https://github.com/vojtechpesek/detekt-repro-sample

**Comment by BraisGabin** [comment]
Works as expected. The autoformat issues are always fixed. It does not care about the baseline.

**Comment by vojtechpesek** [comment]
Thanks for the quick response. I'm sad to hear that. It means that autoformat is useless for projects that have baseline. Which in my opinion is not uncommon. Is there any specific reasoning why autoformat ignores the baseline @BraisGabin ?

**Comment by BraisGabin** [comment]
The reasoning a technical limitation. The issues are fixed before the baseline is checked.

It could be fixed but the main idea behind the baseline is to help projects to adopt detekt with issues. Even if they are hard to fix. The issues that are autofixable aren't hard to fix so those can be fixed directly.

My recommendation:
- autofix the issues and you will reduce your baseline size. 
- don't use the formatting rule set of detekt. It is just a wrapper over ktlint. You could use ktlint directly. They have baseline for the formatting rules.

**Comment by vojtechpesek** [comment]
Thanks for the explanation. We deciced to autofix the issues. Regarding the formatting rule set, i will pass the recommendation on to the team. Cheers.
