### ISSUE TITLE
Suppressing EnumEntryName on parent should suppress EnumNaming & EnumEntryNameCase

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#7491]
## Expected Behavior of the rule
Rule suppression on an enum class suppresses the reporting of EnumEntryName and EnumNaming.

## Context
Fixing violations using suppressions that stop the IDE reporting issues should also stop detekt from reporting those same issues.

**Comment by BraisGabin** [comment]
This should be easily fixable adding an alias to that rule.

**Comment by BraisGabin** [comment]
> This is enough to suppress in the IDE and should be enough for detekt too.

Agree.
