### ISSUE TITLE
Docs are not synced

### ISSUE THREAD

**Issue by GrzegorzBobryk** [detekt/detekt#7548]
## Expected Behavior

Docs are similar as project files.

## Observed Behavior

[Side](https://detekt.dev/docs/introduction/suppressing-rules) is different than [project files](https://github.com/detekt/detekt/blob/main/website/docs/introduction/suppressing-rules.md).

## Steps to Reproduce

1. Check side;
2. Check project files.

## Context

[My change](https://github.com/detekt/detekt/pull/6526/files) is present in files and is absent on website. My assumption is that it is the same with other changes in documentation.

## Your Environment

* Version of detekt used: N/A
* Version of Gradle used (if applicable): N/A
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): N/A

**Comment by BraisGabin** [comment]
Oh, I see what happend here. We didn't port this change to the 1.x branch and for that reason it is not updated. 🤔 I'm not sure how to proceed here... What do you think @cortinico?

**Comment by cortinico** [comment]
The problem is that your original PR hasn't updated all the versioned docs @GrzegorzBobryk 
Fix is here: https://github.com/detekt/detekt/pull/7579

**Comment by cortinico** [comment]
Oh I see what happened. Docs for the 1.23.x branches are generated from the `release/1.x` branch and your change is missing there. I've picked it on the release branch so this won't happen again
