### ISSUE TITLE
Latest json with declared rules is not available

### ISSUE THREAD

**Issue by GrzegorzBobryk** [detekt/detekt#7549]
## Expected Behavior

Latest json with declared rules is available.

## Observed Behavior

Only version [1.22.0](https://json.schemastore.org/detekt-1.22.0.json) is present.

![obraz](https://github.com/user-attachments/assets/2ef5583a-8094-4297-9d3e-b08fad219fff)
![obraz](https://github.com/user-attachments/assets/e266560b-780a-48b7-8274-0a395d2733ba)

## Steps to Reproduce

1. Use CTRL + B on `MaximumLineLength` in `detekt.yaml` to open json file and see rulset;
2. Use CTRL + B on `IfElseBracing` in `detekt.yaml` to see that this value is not present in json.

## Context

I want to have autocomplete while editing yaml file with detekt config. 

## Your Environment

* Version of detekt used: 1.23.6
* Version of Gradle used (if applicable):  8.7
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: Windows 10 and Windows 11
* Link to your project (if it's a public repository): N/A

**Comment by BraisGabin** [comment]
Those jsons are not maintained by detekt. They are generated by a third party (I have no idea who). We have #4162 to generate our own schemas but as far as I know no one started with it.
