### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.psi.KtExpression org.jetbrains.kotlin.resolve.calls.util.CallUtilKt.getCalleeExpressionIfAny(org.jetbrains.kotlin.psi.KtElement)'

### ISSUE THREAD

**Issue by Arsenii01** [detekt/detekt#7552]
## Expected Behavior

Successfull build
## Observed Behavior

Execution failed for task ':detekt'.
> Analyzing /xxx/xxx/xxx.kt led to an exception.
  Location: io.gitlab.arturbosch.detekt.rules.bugs.ImplicitDefaultLocale.checkStringFormatting(ImplicitDefaultLocale.kt:70)
  The original exception message was: 'org.jetbrains.kotlin.psi.KtExpression org.jetbrains.kotlin.resolve.calls.util.CallUtilKt.getCalleeExpressionIfAny(org.jetbrains.kotlin.psi.KtElement)'
  Running detekt '1.22.0' on Java '17.0.11+9' on OS 'Mac OS X'

## Steps to Reproduce

Kotlin version 1.8.10
detekt version 1.22.0
gradle version 7.5
Run task 'detekt'
## Context

I used compatibility table, with detekt version 1.23.0 I get this error: detekt was compiled with Kotlin 1.8.21 but is currently running with 1.8.10. 
With detekt version 1.22.0 I get exception described in 'Observed behavior', the same happens when using version 1.21.0
## Your Environment

* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): 7.5
* Operating System and version: Mac OS X Sonoma 14.5

**Comment by 3flex** [comment]
> with detekt version 1.23.0 I get this error: detekt was compiled with Kotlin 1.8.21 but is currently running with 1.8.10

When you get this message there should also be a link to documentation that explains what's happening and how to fix it, did you look at that?

**Comment by Arsenii01** [comment]
Yes, I saw docs at https://detekt.dev/docs/gettingstarted/gradle/#gradle-runtime-dependencies
but there is no buikd scripts which could override all dependency configurations

**Comment by 3flex** [comment]
Are you sure?

Are you using the spring dependencies plugin? If not another plugin might be interfering. Something, not detekt, is overriding up the dependency configurations.

Can you provide an isolated reproducer?

**Comment by Arsenii01** [comment]
I apologize, there is really a spring dependency plugin in the list. Thanks for your help
