### ISSUE TITLE
Was passed main parameter '--fail-fast' but no main parameter was defined in your arg class

### ISSUE THREAD

**Issue by vanniktech** [detekt/detekt#7570]
I've tried to update my Detekt version from 1.0.0 to 1.23.6 in my Gradle Plugin since 1.0.0 fails since one of the hopefully old dependencies can't be resolved anymore due to jcenter. Now I am getting:

```
Was passed main parameter '--fail-fast' but no main parameter was defined in your arg class
```

Has this parameter been removed? I don't understand the error message. Public reproducer: https://github.com/vanniktech/gradle-code-quality-tools-plugin/pull/325

**Comment by schalkms** [comment]
> Has this parameter been removed?

The --fail-fast CLI flag (and failFast Gradle property) has been removed. It was deprecated since 1.16.x - [#5290](https://github.com/detekt/detekt/pull/5290)

[changelog](https://detekt.dev/changelog#1220---2022-11-20)
