### ISSUE TITLE
Empty XML tags in baseline files

### ISSUE THREAD

**Issue by JordanLongstaff** [detekt/detekt#7622]
## Expected Behavior
An empty XML tag should be self-closing, e.g. `<ManuallySuppressedIssues />`.

## Observed Behavior
In the generated baseline XML files, an XML tag with no body is simply left empty, e.g. `<ManuallySuppressedIssues></ManuallySuppressedIssues>`.

## Steps to Reproduce

If you create any Kotlin module with a Detekt issue (e.g. a magic number) and run `./gradlew detektBaseline` on it, it'll generate the baseline file. You can see the empty-body `ManuallySuppressedIssues` tag for yourself. If there are no Detekt issues, the same will be true for the `CurrentIssues` tag.

Live examples in my repo: [One](https://github.com/JordanLongstaff/ArtemisAgent/blob/main/IAN/udp/detekt-baseline.xml) and [Two](https://github.com/JordanLongstaff/ArtemisAgent/blob/main/IAN/util/detekt-baseline.xml)

## Context

I am programming in Android Studio, which complains about the empty tags. These complaints show up as warnings in the Code Analysis view. If I replace the tags with self-closing tags, the warnings disappear; however, Detekt will still re-generate empty tags to replace them if the `detektBaseline` task is run again.

## Your Environment

* Version of detekt used: 1.23.7
* Version of Gradle used (if applicable): 8.6.0
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): [here](https://github.com/JordanLongstaff/ArtemisAgent)

**Comment by BraisGabin** [comment]
I looked at this time ago. We use a library here and it serialize the xml like that. So if someone wants to fix it can send a PR but it shouldn't over complicate the code.

**Comment by BraisGabin** [comment]
> But I always have to
> `./gradlew --stop
> `
> before
> `./gradlew :detekt-core:detekBaseline`
> otherwise it somehow remembers the previous tag names.
> 
> Probably something's wrong with my environment.

That's a known issue on our current gradle setup. The detekt tasks doesn't work without the --stop. That's o ly an issue for rule authors that want to test the rule on their own project.

About the issue there is already a PR that looks good :) thanks for the help!
