### ISSUE TITLE
Configure UtilityClassWithPublicConstructor with ignoreAnnotated

### ISSUE THREAD

**Issue by utzcoz** [detekt/detekt#7629]
## Expected Behavior of the rule

Hope `UtilityClassWithPublicConstructor` supports to configure to skip checking for classes annotated with specific annotation, like Robolectric's Implements.

## Context

I write some shadow classes in my repository, and it doesn't provide any constructor, and it only has companion object. The detekt reports `UtilityClassWithPublicConstructor` to me, and I want to keep the shadow class to current status instead of an object.

**Comment by BraisGabin** [comment]
You can add `ignoreAnnotated` to your configuration adding the annotation you want to suppress. It works for all the rules.
