### ISSUE TITLE
UnusedPrivateClass false positive with callable references

### ISSUE THREAD

**Issue by JordanLongstaff** [detekt/detekt#7660]
## Expected Behavior
I expect to see no `UnusedPrivateClass` warning because the private class is, in fact, used.

## Observed Behavior
The private class is marked by Detekt as an unused private class and the warning occurs.

## Steps to Reproduce
[This](https://github.com/JordanLongstaff/ArtemisAgent/security/code-scanning/286) is one of six private classes like this that are declared in my test suites. All of them are flagged as unused by Detekt, but none of them are actually unused, because there are callable references for all of them (namely, their primary constructors).

![Screen Shot 2024-09-21 at 2 22 09 PM](https://github.com/user-attachments/assets/804521d4-e4fa-4b60-b5fa-7e3cc6a03367)

## Context
These false positives are showing up as security alerts in my GitHub repo. I'm trying to clear some of them out today.

## Your Environment

* Version of detekt used: 1.23.7
* Version of Gradle used (if applicable): 8.10.1
* Operating System and version: macOS Monterey 12.7.6
* Link to your project (if it's a public repository): [ArtemisAgent](https://github.com/JordanLongstaff/ArtemisAgent)

**Comment by cortinico** [comment]
> [This](https://github.com/JordanLongstaff/ArtemisAgent/security/code-scanning/286) is one of six private classes

This link is broken.

Could you provide a snippet that would reproduce this detection instead?
