### ISSUE TITLE
Detekt website: Broken links to the Kotlin hidden costs benchmarking page

### ISSUE THREAD

**Issue by kyleojamf** [detekt/detekt#7696]
## Expected Behavior

Taken to the Kotlin's hidden costs - Benchmarks page.

## Observed Behavior

404 - The page you have entered does not exist

## Steps to Reproduce

If you go to the detekt website for the [performance rule set](https://detekt.dev/docs/rules/performance), **ForEachOnRange** and **SpreadOperator** both reference a benchmarking page. When you click on that link (https://sites.google.com/a/athaydes.com/renato-athaydes/posts/kotlinshiddencosts-benchmarks), you're greeted with a 404.

## Context

It's the source for why **ForEachOnRange** and the **SpreadOperator** are considered to have performance issues. Doing a search through the repo, I do see that in the documentation for the code, an archived version of that page is referenced:
https://web.archive.org/web/20230514162525/https://sites.google.com/a/athaydes.com/renato-athaydes/posts/kotlinshiddencosts-benchmarks
However, this is also an accessible version of that very page with different (unfortunately, inferior) formatting: https://sites.google.com/a/athaydes.com/renato-athaydes/posts/kotlins-hidden-costs-benchmarks
To me, I don't really care which page is referenced, as long as there's not broken links. Someone should decide that so we can at least be consistent.

**Comment by cortinico** [comment]
That's true. I think we can replace it with this blog series:

https://bladecoder.medium.com/exploring-kotlins-hidden-costs-part-1-fbb9935d9b62
https://bladecoder.medium.com/exploring-kotlins-hidden-costs-part-2-324a4a50b70
https://bladecoder.medium.com/exploring-kotlins-hidden-costs-part-3-3bf6e0dbf0a4

**Comment by markoeltiger** [comment]
Hello Team @3flex @BraisGabin @cortinico , I fixed this issue here https://github.com/detekt/detekt/pull/7713 , Kindly check it .
Thanks

**Comment by 3flex** [comment]
@markoeltiger thank you for your contribution. Just some feedback for the future, maintainers will check PRs when time allows, pinging everyone with an @ when you submit one is not necessary. Thanks!

**Comment by markoeltiger** [comment]
Thanks a lot @3flex For the feedback appreciated !
