### ISSUE TITLE
Documentation is not Updated with latest version 

### ISSUE THREAD

**Issue by markoeltiger** [detekt/detekt#7719]
## Expected Behavior
I should find the latest detekt version on the documentation website to use it 
## Observed Behavior
i find older version of detekt

## Steps to Reproduce
-Go for detekt.dev getting started for example go for  [Android -> Gradle ](https://detekt.dev/docs/gettingstarted/gradle) you will find the stated version in the documentation is 1.23.3 while the latest is 1.23.7
## Context
-Developers Doesnt use latest version

**Comment by BraisGabin** [comment]
Could add a link?

**Comment by markoeltiger** [comment]
I have updated the issue description

**Comment by BraisGabin** [comment]
Fixed with #7723
