### ISSUE TITLE
Suggest replacing measureTimeMillis with measureTime

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#7725]
## Expected Behavior of the rule
Flag calls to `kotlin.system.measureTimeMillis` and suggest replacement with `measureTime`.

## Context
It's deprecated on Native since 1.9 and [docs are updated in 2.1.0-beta2](https://github.com/JetBrains/kotlin/blob/2.1.0/libraries/stdlib/jvm/src/kotlin/system/Timing.kt#L15-L20) for JVM to say:

```
 * This function is obsolete, and it is recommended to use [measureTime] instead as
 * it does not suffer from [measureTimeMillis] downsides and provides human-readable output.
 *
 * [measureTimeMillis] uses `System.currentTimeMillis` which is not monotonic, is a subject
 * to a clock drift, and has an OS-dependent coarse-grained resolution.
 * [measureTimeMillis] can return a negative or zero value as a result.
 ```

Context: https://youtrack.jetbrains.com/issue/KT-68027

We have one usage in detekt itself which should be updated.

**Comment by markoeltiger** [comment]
Hello @3flex   , Can i take it ?

**Comment by 3flex** [comment]
@markoeltiger thanks for contributing. 

Are you planning to work on the rule as well? If not I'll unassign you.

**Comment by markoeltiger** [comment]
Hello @markoeltiger  , I would love to work on it but can you tell me which rule should I work on it , I am free to finish this issue.

**Comment by atulgpt** [comment]
Hi @3flex can we simply add this method to the list of forbidden methods(in the ForbiddenMethod rule) with the reason? Or do you want to add separate rule for this?

**Comment by 3flex** [comment]
> can we simply add this method to the list of forbidden methods

Yep I think that's the way to go.

**Comment by markoeltiger** [comment]
@3flex i am working on adding the method to ForbiddenMethod rule
