### ISSUE TITLE
Add config option to choose between absolute and relative paths when reporting

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#853]
## Expected Behavior
A finding should match into one console line.
For this, let the user choose if he want the findings to be reporting with relative or absolute paths.

## Current Behavior
When reporting the absolute path, findings are often broken into two lines and it looks awful.
This comes due to changes to the reporting api to have the paths clickable.

## Context
It is hard to read the findings now.

**Comment by RiccardoM** [comment]
Another use case for this would be allowing custom output reports to print either absolute or relative (to the project root folder) path. 

For example, if I want to integrate Detekt with [Gitlab code quality system](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html) I have to output the paths as relative to the project root folder. Currently I cannot do this becasue all the paths are printed as absolute paths.

**Comment by arturbosch** [comment]
It could be done by a postprocessor if we provide the `basePath` from the tooling api to the `SetupContext` in api ^^.
I think we should:
1. drop processor, report configurations from the config
2. Have a configuration option to include and exclude extensions
Similiar to https://github.com/detekt/detekt/blob/5a0fe624e571d20e1619b1e42360c2b1f513a2ce/detekt-tooling/src/main/kotlin/io/github/detekt/tooling/api/spec/ExtensionsSpec.kt#L22-L25
3. Support `deactivatedByDefault` behavior for extensions
4. Implement this as a deactivated extension lying around waiting for users to be used.

**Comment by chao2zhang** [comment]
We already have a draft #2492. But as mentioned in #3045, I will pick this up. Please update the status to in progress in Projects - Roadmap.

**Comment by BraisGabin** [comment]
@chao2zhang we could close this now, right?
