### ISSUE TITLE
Print filtered paths in debug mode

### ISSUE THREAD

**Issue by kenyee** [detekt/detekt#869]
## Expected Behavior
I didn't see this reported yet...when you run detektCheck, it just says "build successful" and reports no output

## Current Behavior
Should output a report to the shell when running from command line

## Steps to Reproduce (for bugs)
I did have to change the exclusions as mentioned here: https://github.com/arturbosch/detekt/issues/792
Before that, it was randomly showing 0 files analyzed.  After changing the exclusion it found the unit test files and flagged a few issues.  I reconfigured detekt.yml to work around those issues but then it reported nothing (doesn't say 0 files found either).

Top level build.gradle file config looks like:
detekt {
    version = "${detektVersion}"
    profile("main") {
        input = "$projectDir/app/src"
        config = "$projectDir/detekt.yml"
        filters = ".test.,.*/resources/.*,.*/tmp/.*"
    }
}
with this in the plugins list:
    id "io.gitlab.arturbosch.detekt" version "1.0.0.RC6-4"
detekt.yml file is just the one generated w/ "gradle detektGenerateConfig" and copied to detekt.yml at the project root.

## Context
Doesn't allow Detekt to run in our project.  Would like to use it in addition to ktlint.
There should be a debug flag in the detekt build.gradle config closure IMHO....

## Your Environment

* Version used: 1.0.0.RC6-4
* Operating System and version: OSX High Sierra
* Link to your project:

**Comment by arturbosch** [comment]
I assume this is solved as you mentioned it in #792? Feel free to reopen if you still have questions or problems.

**Comment by kenyee** [comment]
@arturbosch:
Thanks for making me run it clarify in #792.
The issue was the detekt.yml file was using the same test filter that is wrong (mentioned in 792).
And it's super weird that it's in the build.gradle config includes a list of excludes *and* it's also in the detekt.yml file.

And I still wish the build.gradle config for detekt had a debug mode.  The debug mode should show which files it auto filtered out IMHO.

**Comment by arturbosch** [comment]
Hm, good idea, I will reopen the issue with other name.
But the `test-pattern` just filters some of the rules which should not be run on test code but not all rules hmmm

**Comment by kenyee** [comment]
Apparently the test-pattern affects things like the exclude list in the config 😀 

If you add the exclusions that to that debug=true mode, that would help...and document that flag please 😃
