### ISSUE TITLE
UnnecessaryInnerClass Rule

### ISSUE THREAD

**Issue by vanniktech** [detekt/detekt#875]
Sometimes nested classes are declared as `inner` although they should not. In that case the fix is trivial - removing the `inner` keyword. It would be nice if there's a rule for this.

There's a high risk for false positives though so it should be tested thoroughly on sample projects.

**Comment by schalkms** [comment]
Good idea!

**Comment by BraisGabin** [comment]
This is already implmented in 1.20 🎉
