### ISSUE TITLE
The website needs a FAQ page

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#890]
List with frequently asked questions:
- 0 files analyzed (filters?)
- why does the gradle plugin print `--baseline` etc (using cli)
- ...

Happy to add more suggestions ^^

**Comment by Mauin** [comment]
If some of the arguments are points for frequently asked questions maybe that means the documentation for those arguments is too hard to find or not good enough?

**Comment by schalkms** [comment]
I would not call it FAQ, but rather **know limitations**.
I think detekt additionally needs a manual including the basic use cases.

**Comment by arturbosch** [comment]
I think having a FAQ does not mean the documentation is not good enough as the user has to search for the specific page when having a common problem. It is just a common place where to look after such easy pitfalls.

Known limitations is also a good point for symbol resolution etc

**Comment by schalkms** [comment]
This issue was created before we had the documentation available on the home page.
I suggest to close this for now.
